### ISSUE TITLE
R + Tmux + Quartz

### ISSUE THREAD

**Issue by GhostValk** [tmux/tmux#1008]
I have a very strange issue.. When i open an R prompt inside tmux, and call a plot, the quartz plot window works perfect, except it doesn't maximize to fullscreen.

Trying exactly the same with an R prompt from everywhere else works as expected, but not in tmux, any idea of what could it be?

Im using OSX 10.12

**Comment by krader1961** [comment]
The most common reason for programs to behave differently on macOS when launched from inside a tmux session is due to the macOS security model. The fix for this is to use a program named `reattach-to-user-namespace`. It's not part of macOS but if you use Homebrew just do `brew install reattach-to-user-namespace` or google it. Then put something like the following in your ~/.tmux.conf (this is from mine, I use the fish shell):

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
set-option -g default-command "exec reattach-to-user-namespace -l fish"
```

**Comment by GhostValk** [comment]
I already had that line in my conf file...

I think it must be a very specific problem in quartz, but can't manage to guess what it is; a very strange thing i noticed is that in the quartz window from the tmux R (the not working one), at the status bar in top of the screen, where the app name should be, there are 3 dots "..." and in a quartz window from any other source (the working ones) there is the cmd symbol "⌘".

So, they are somehow being opened with something different

**Comment by GhostValk** [comment]
[Image](https://ibb.co/cwS3aF)

There it is, left one is the "working one", right one is the not-enlarging window

**Comment by GhostValk** [comment]
Nvm, managed to fix it... reattach-to-user-namespace call must be put BEFORE calling a new session, otherwise is overwritten by default session settings. Thanks a lot!
