### ISSUE TITLE
Google phishing warning

### ISSUE THREAD

**Issue by cossio** [tmux/tmux#1017]
When I click the link:

https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz

I get a warning:

> Deceptive site ahead
> 
> Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers or credit cards).
> 

I am using Chrome.

**Comment by nicm** [comment]
Sounds like something you should take up with Google, Amazon or whoever
wrote your browser.


On 25 Jul 2017 11:35 am, "Jorge Fernández de Cossío Díaz" <
notifications@github.com> wrote:

When I click the link:

https://github.com/tmux/tmux/releases/download/2.5/tmux-2.5.tar.gz

I get a warning:

Deceptive site ahead

Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may
trick you into doing something dangerous like installing software or
revealing your personal information (for example, passwords, phone numbers
or credit cards).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1017>, or mute the thread

**Comment by maximbaz** [comment]
It is Github's issue, every repo is affected, not only tmux. I have reported it to Github support, you can close the issue here as there is nothing we can do.

**Comment by cossio** [comment]
@maximbaz Thanks. I just wanted you guys to be aware.

**Comment by maximbaz** [comment]
@cossio the issue is fixed, thanks for raising this!
