### ISSUE TITLE
Question / Feature Request: Ability to disable the dropping of output when there is a lot of output being outputted? 

### ISSUE THREAD

**Issue by heymoe** [tmux/tmux#1019]
I recently noticed that my ability to cat a somewhat large text file so I can cut-n-paste it elsewhere has stopped working. Basically if a text file contains say 1000 lines of text for example and I cat it and then scroll back in my terminal so I can select the output and then cut-n-paste it somewhere else, I end up with a lot few lines then the actual text file contained.

I'm currently running tmux v2.5 and noticed in the change log these 2 changes:

> * Handle slow terminals and fast output better: when the amount of data
>   outstanding gets too large, discard output until it is drained and we are
>   able to do a full redraw. Prevents tmux sitting on a huge buffer that the
>   terminal will take forever to consume.
> 
> * Do not redraw a client unless we realistically think it can accept the data -
>   defer redraws until the client has nothing else waiting to write.

To see if that is what broke my ability to cut-n-paste, I compiled tmux v2.4 and had to the same results. I didn't see anything in the change log for v2.4 that might be causing this except for maybe the general:

> * There have been substantial performance improvements.

Any ways, I then compiled v2.3 since I know I was able to do this at some point and it started working again.

Based on the v2.5 change log entries I noted above, I totally get why the dropping of output make sense. Trust me, there have been many times where I catted a file or ran some other command that had huge amounts of output and I just had to walk away until my Ctrl-C finally stopped it or the command finally finished. That being said, there are cases where you do want to do something that outputs a lot of data that you want to see completely like my cut-n-paste scenario. 

So my question is, is there a way to disable the  dropping of output that I can enable when needed or via the command line in versions greater than v2.3? I did look at the man pages and didn't see any command options jump out at me that would do this.

If not, may I submit a feature request where this feature can be turned off or maybe better be able to define how many lines of output can be fully displayed during a fast output scenario before the dropping starts.

Thanks for your time.

**Comment by nicm** [comment]
It is impossible for tmux to guarantee the consistency of the terminal scrollback and we are not going to try and do so with half measures.

**Comment by nicm** [comment]
The recommended way to copy and paste from tmux is to use copy mode and if it falls short it should be improved.

**Comment by heymoe** [comment]
As an added note, I'm not using a Linux shell or terminal. I'm running putty from windows and SSHing into a Linux box where I then use tmux to manage multiple shells instead of having to run multiple putty sessions. 

I did try using "copy mode" via this setup and it failed to populate my windows cut-n-paste buffer so that doesn't seem to be a solution.

I totally get that you / tmux can't guarantee the consistency of a terminal's (putty in this case) scrollback buffer. That's up the terminal itself. What you can guarantee is that whatever any output that is generated by a command executed inside of tmux is sent out which, as noted, is what tmux did in v2.3. If the terminal can't deal with it then so be it, that is not tmux's problem but in my experience with v2.3, I never had an issue of my terminal's scrollback buffer missing data I was expecting to be there.

I could argue that the decision to drop output starting in v2.4 (it seems) is a half measure to a problem that doesn't effect everyone and breaks the integrity of expected output of whatever command execute inside of tmux because tmux decided that by sending this line of output is going to cause an issue even though it might not actually be an issue to the user.

I mean this:

> if (x == true) {
>   save x;
>   del x;
> }

is a lot different than tmux deciding to drop one line output and ending up with this:

> if (x == true) {
>   del x;
> }

If someone didn't catch that mistake and cut-n-pasted that chuck of code elsewhere, they would be in for a surprise. Or if I tailed the last 300 lines of a log file and wanted to scroll back to to examine the output. I might miss what I'm looking for because tmux decided to drop the output I was looking for. Sure I could pipe the output though less or more but now I'm having to work around tmux breaking the integrity of the output to begin with.

Like I said in my first post, I totally get why this feature was added BUT it should not be the default behavior. If someone knows they are running on a slow terminal or knows they always runs some command that blasts a lot of output and locks up their terminal for a while by mistake, then give them the option to turn on output dropping instead of forcing the feature across the board.

**Comment by nicm** [comment]
No, tmux cannot guarantee what is in the terminal scrollback, the terminal features simply do that exist that allow it to do so, and any argument that it should try falls down when you have multiple windows or panes. 

The same applies to other full screen applications: if you run emacs and load a text file (or even run a command in ansi-term mode) you do not expect it to appear in the scrollback, you use emacs' own copy and paste.

tmux never guaranteed anything like this and the reason we provide copy mode is because it cannot.

**Comment by heymoe** [comment]
I think you're selective reading / didn't understand what I said.

I didn't say tmux should guarantee what's in the terminal's (putty) scrollback. I said tmux should guarantee that whatever output a command outputs, tmux should output it 1:1 and not drop output because it feels like. This is how tmux v2.3 worked.

If a terminal program, like putty, can't keep up and it doesn't keep a 1:1 copy in its scrollback buffer, that's its (putty's) fault and I don't blame tmux for that.

tmux is basically taking initiative by dropping output based on whatever algorithm you have implemented thus breaking the integrity of the output of whatever command was run inside of tmux. You should at least give the user the option to use or not use this feature instead of deciding for everyone that dropping output is a OK thing to do.

As I stated "copy mode" does not work from a windows machine using putty. Also how can I use putty's cut-n-paste feature, if you want to call putty a full screen application, if tmux doesn't output all the output 1:1 from the command I ran inside of tmux.

If I load a text file into emacs, I fully expect that emacs will load a 1:1 copy of that text file into its scrollback buffer or whatever. I don't expect it to leave out / drop lines of the text file because it decided I don't need to see it. That is basically what tmux is doing.

This shouldn't be hard to understand. You've change the behavior of tmux because you were trying to solve one problem but by doing so you've caused another. A simple command line option or some sort of toggle in tmux that tells it to drop output if need or don't drop output like it did in v2.3 is not a unreasonably request.  This gives the end user to ability to pick how tmux should treat the output of commands.

**Comment by nicm** [comment]
No, tmux never guaranteed this and has always used whatever method is best to draw the terminal. You can and always could get partial output to the terminal. For example with multiple panes, or if you switched between windows, or if tmux needed to, for example, draw the status line or resize during output.

If you load a text file into emacs, it will load a 1:1 copy of the file into its scrollback buffer _but not into the terminal scrollback_. tmux will do the same - if you use copy mode you will find the output is complete (up to history-limit). tmux cannot control the terminal scrollback.

There are mechanisms for tmux that can be used to set the system clipboard from copy mode (set-clipboard and copy-pipe), but I don't know if putty supports it.

**Comment by nicm** [comment]
I understand that you want it to work, but the fact is that trying to make the terminal scrollback remain coherent can only ever work in a very narrow range of cases.

If there is an easy way to do it, we could, but I am not going to remove or limit a feature that works really well and solves a genuine problem to achieve something that is essentially impossible to do properly.

Line wrapping is a similar problem, we make a basic effort but in the end it is pretty much impossible to keep consistent.

**Comment by heymoe** [comment]
If tmux never guaranteed it then why does tmux v2.3 work fine in putty while v2.4 and v2.5 doesn't?

I'm running tmux similar to how screen works. I do not carve out multiple panes within a single window. I also don't except my terminal's (putty) scrollback buffer to maintain consistency if I switch between tmux windows or resize the window. So yes this is likely one of those narrow use cases but it s use case none the less.

I do expect that if I cat a 1000 line text file from within a tmux window that tmux will output all 1000 lines so my terminal's can load all 1000 lines into it's scrollback buffer and as long as I don't resize my terminal or switch to a different tmux window, I should be able to view my terminal's scrollback buffer to see all 1000 lines. But starting in v2.4 if I cat a 1000 line text file, since cat is outputting all 1000 lines very quickly, your new tmux feature is dropping some of those lines so my terminal is only seeing a subset of those 1000 lines (maybe only 500 or less) to put into it's scrollback buffer thus breaking my ability to rely on the output I get from tmux.

You keep saying tmux never did this or that even though I'm telling you v2.3 works fine in the manner I've been using tmux up util v2.4.

I don't expect tmux to to try and maintain the scrollback buffer of my terminal. I just want it to not drop output. If I cat a 1000 line text file, I expect tmux to send me all 1000 lines of that text file.

**Comment by nicm** [comment]
I'm not saying 2.3 didn't work for you, I'm saying the fact that it worked for you doesn't mean it should still work. tmux has _always_ been able to draw the terminal differently from how the program inside draws it. Terminals have _never_ provided a way for tmux to keep the scrollback consistent.

We have changed something that was never expected to work in order to make something that was a long-term, consistent problem for many users considerably better.

Something like this will probably leave you with most of the output, but you will need to maintain it yourself:
~~~~
Index: screen-write.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/screen-write.c,v
retrieving revision 1.129
diff -u -p -r1.129 screen-write.c
--- screen-write.c	30 Jun 2017 22:24:08 -0000	1.129
+++ screen-write.c	26 Jul 2017 17:14:48 -0000
@@ -1027,6 +1027,8 @@ screen_write_linefeed(struct screen_writ
 		ctx->scrolled++;
 	} else if (s->cy < screen_size_y(s) - 1)
 		s->cy++;
+
+	screen_write_collect_flush(ctx, 0);
 }
 
 /* Scroll up. */
Index: tty.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tty.c,v
retrieving revision 1.292
diff -u -p -r1.292 tty.c
--- tty.c	21 Jul 2017 22:55:45 -0000	1.292
+++ tty.c	26 Jul 2017 17:14:49 -0000
@@ -197,6 +197,7 @@ tty_block_maybe(struct tty *tty)
 	size_t		 size = EVBUFFER_LENGTH(tty->out);
 	struct timeval	 tv = { .tv_usec = TTY_BLOCK_INTERVAL };
 
+	return (0);
 	if (size < TTY_BLOCK_START(tty))
 		return (0);

**Comment by nicm** [comment]
I don't really understand why you don't just use copy mode. Even if your terminal doesn't support set-clipboard, you can enter copy mode and scroll up using the mouse wheel just like you would outside, then in most terminals you can use Shift-Drag (or for some terminals Ctrl-Drag or Alt-Drag) to copy text into the system clipboard just as if you had scrolled the terminal scrollback instead.

**Comment by heymoe** [comment]
So you feel that silently dropping data is a OK thing to do? This seems crazy to me. If all it takes make tmux not drop data is 2 lines of code why not just make this a command line options that people can choose to run. --nodrop and then wrap those 2 line of code with a if statement.

> if (NODROP) {
>   diff code
> }
> 

Seems like a easy solution and gives users of tmux the option to decide if tmux should output 1:1 or drop data if its coming in too fast. Heck, make drop data the default behavior for all I care as long as I can run tux with --nodrop or whatever.

As for "copy mode", I've state that it does not work when running putty via a windows desktop. Sure I can entry copy mode and up arrow all the way back to the beginning of a 1000 line cat but space and enter to cut-n-paste inside of copy mode does not populate my windows cut-n-paste buffer.  And no, scroll wheel, Alt-Drap or Ctrl-Drag does not cause tmux to scroll up or down while in "copy mode" so I can't quickly scroll-up to the start, hold shift and start my cut-n-paste highlight, quickly scroll back to the bottom and select the ending part of my cut-n-paste and boom done in tmux like I can in my puttly session.

**Comment by heymoe** [comment]
I tested your diff code using v2.5 source and it does seem to make tmux not drop data now. I still think this would make a good command line option to give tmux users a choice.

**Comment by nicm** [comment]
But this is not a network connection, it is a terminal. tmux transforms
almost everything the application inside sends, sometimes for efficiency
and sometimes because the terminal outside requires different escape
sequences or has a different feature set from tmux itself. Dropping or
changing data is fine.

tmux has enough options already, I don't want to add another one for this
which is a niche case and one which we can't guarantee to get right anyway.
And there are a number of alternatives for most people.

Mouse wheel in copy mode definitely works, probably you need to turn on the
mouse option in tmux. I'm pretty sure there is a way to use terminal mouse
copy once you have scrolled in putty, in most terminals it is shift.

Anyway we have probably discussed this enough for now, if you come up with
a solution that allows your use case to work without breaking the reason we
did this in the first place then I will be happy to look at it.


On 26 Jul 2017 7:03 pm, "heymoe" <notifications@github.com> wrote:

So you feel that silently dropping data is a OK thing to do? This seems
crazy to me. If all it takes make tmux not drop data is 2 lines of code why
not just make this a command line options that people can choose to run.
--nodrop and then wrap those 2 line of code with a if statement.

if (NODROP) {
diff code
}

Seems like a easy solution and gives users of tmux the option to decide if
tmux should output 1:1 or drop data if its coming in too fast. Heck, make
drop data the default behavior for all I care as long as I can run tux with
--nodrop or whatever.

As for "copy mode", I've state that it does not work when running putty via
a windows desktop. Sure I can entry copy mode and up arrow all the way back
to the beginning of a 1000 line cat but space and enter to cut-n-paste
inside of copy mode does not populate my windows cut-n-paste buffer. And
no, scroll wheel, Alt-Drap or Ctrl-Drag does not cause tmux to scroll up or
down while in "copy mode" so I can't quickly scroll-up to the start, hold
shift and start my cut-n-paste highlight, quickly scroll back to the bottom
and select the ending part of my cut-n-paste and boom done in tmux like I
can in my puttly session.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1019#issuecomment-318135052>, or mute
the thread

**Comment by nicm** [comment]
Actually we potentially do not need a option - you must already be
disabling the smcup and rmcup terminal capabilities in order for scrollback
to work at all, so possibly we could just check that those have been
explicitly disabled.

**Comment by heymoe** [comment]
Maybe we have different use cases in mind when it comes to using tmux. 

Me personally, I use tmux to access multiple shells from a single terminal (putty) from my windows desktop. I use putty to ssh into a linux server where I have tmux running and from this single ssh connection I can launch multiple shell windows / "tabs" using tmux. Everything I'm doing is command line via a standard bash / tcsh shell. 

Sure tmux transforms / translates certain thing like the escape sequences that changes font colors or up and down arrow presses and I'm totally fine with that type of data manipulation and to a point it's expect that such things are manipulated for a better command line experience.

When I say dropping data I mean actual data that a command outputs. If I have a source code file (foo.c) that contains 500 lines of code and I run "cat foo.c" I expect that 500 lines of code will get displayed to my screen since that is the function of cat. To print the contents of a file to standard output for me to see. If the results of my cat command results in anything more or less than 500 lines of code from foo.c then there is something wrong. This is assuming foo.c contains just standard text and no escape sequences or binary data for some reason.

Running a bash shell inside of tmux v2.4+ results in tmux manipulating the data to the point that the expected results of running a command line command does not result in the actual expected data. It does this silently and without warning. I can't rely on any output from any command I run from the command line because if it outputs data too fast, tmux will just drop some of the data. This can happen when doing a really long directly listing (ls -alR /), catting a 500 text file (cat foo.txt), tailing the last 500 lines of a log files (tail -500 log.txt), etc.. etc.. If I run the same command multiple times on a static set of data, I expect the output to be the same every time but that's not possible now with tmux deciding to drop data from the output of said command. It does not count if tmux happens to drop the same lines each time.

Maybe you're only using tmux to run programs that don't output a lot of data quickly, top for example or running a program in a tmux window that only outputs a "I'm still alive" command ever 5 mins to monitor a process, etc.. where they don't hit this threshold that tmux is now applying to output data where it will start dropping data. So kudos to you, but that is not the case for everyone using tmux.  

My linux server is runing Arch linux. I have not made any system level changes to any terminfo files so unless smcup and rmcup are disabled by default in Arch, I'm going to assume they are enabled. I also don't have any reference to smcup or rmcup in my .tmux.conf file.

tmux is defined as a 'terminal multiplexer". A terminal being a interface to a computer where the results of commands executed via the terminal on said computer are outputted to the terminal. tmux is failing to do it's job by not displaying all the output of commands being run because it was decided that if the output is coming too fast that it's better to just drop some of the data.

**Comment by nicm** [comment]
You may expect tmux to pass everything to the terminal but this is not
how tmux works. tmux keeps its own history of output in every pane but
does not guarantee to pass it unaltered to the terminal outside.

**Comment by nicm** [comment]
tmux is not behaving incorrectly here, it is fine for it to drop data that will not affect the visible display - it always has done so one way or another and if you think it hasn't or shouldn't then you are under a misapprehension.

What is more questionable is whether your particular use case is worth adding some workaround so it at least partially works, like we have for line wrapping. There are several negatives here: without disabling the alternate screen (or, apparently, using putty), there is no scrollback anyway; most users can use copy mode which supports the mouse, multiple panes and on many terminals the system clipboard; and it can only ever work if you have one pane and keep the same current window.

I don't think you've really convinced me TBH but I'll think about what we could do. Maybe we could change what we do based on smcup/rmcup, since for most terminals you need to turn them off to have terminal scrollback work at all.

**Comment by heymoe** [comment]
I don't know why you keep saying what I'm doing never worked, partially worked or there is no scrollback in putty when using tmux. I've been using tmux for a while now doing exactly what I've described above without any issue with missing data until seemingly v2.4 rolled out.

I've confirmed that going back to v2.3 and compiling v2.5 with the changes you noted in an earlier comment fixes the miss data behavior I'm reporting. So, basically by implementing this flow control in the form of dropping data when too much output is coming in, you've change the behavior of tmux without providing a way to disable it for those users that don't need tmux to do flow control.

To show that I'm not trying to be a hard ass that's unwilling to learn something new, I've been searching to see if I can make "copy mode" work for me via putty over SSH.

So far I've added:

> set -g mouse on

to my .tmux.conf file and I can now us my mouse wheel to move up and down inside "copy mode". The arrow keys as well as page up and down on my keyboard also work when I'm in "copy mode", though being able to just drag putty's scroll bar like I normally do would be a lot quicker, BUT I can't seem to cut-n-paste more than whats on my screen by doing a shift-click and drag. That would be fine if all I wanted to cut-n-paste fit in the window but I cut-n-paste things that might be many windows worth of data, as in putty does not show me 500 lines of data within a single window without scrolling, so having to cut-n-paste 50 or so lines at a time would take forever.

I'm aware that I could use the ctrl-space to start my cut-n-paste and go to the end and pressing ctrl-w is how you normally would do it and that does indeed work as long as I'm pasting back into something in tmux. It does not populate the system / Windows cut-n-paste buffer so I can paste that data into say notepad++.

If you know how I can shift-drag multiple pages of data while in "copy mode", I'm all ears.

**Comment by krader1961** [comment]
It only works if you have a single pane with a single window per session. As soon as you split the display into multiple panes or switch windows the terminal scroll back stops working. The terminal scrollback also doesn't work if you attach to an existing session from a different terminal. For example, several times a day I'm likely to attach to my sessions from either my main desktop machine or my laptop. Those terminals won't have any of the output written to those sessions so the native terminal scrollback is useless to me.

**Comment by krader1961** [comment]
@nicm, FWIW, I'm inclined to agree with you. Even when I'm using tmux with a single pane and have just connected to a session and run a command that produces a huge amount of output. Which seems to be the use case that @heymoe cares about. Having said that I wonder if it might be better to disable the output optimization if there is a single pane. That behavior has its own problems but might better fit most users mental model. Obviously it does not, cannot, and should not attempt to sync the terminal scroll back with tmux output history. So this doesn't do anything for the case where you attach to a session after having run `cat` that writes a large number of lines to the session/terminal. But it does mean that if the user does the hypothetical `cat` after connecting to the session they should be able to use their terminal's native scrollback capability.

**Comment by nicm** [comment]
@heymoe I'm not saying 2.3 didn't work for you, I'm saying it was not _meant_ to work. This was never a feature, and there _are_ mechanisms in 2.3 that will leave gaps in the scrollback, it just happens your terminal has the right features or your use case is limited enough that you have never hit them.

@krader1961 with a single pane is one of the times this improvement is most needed because we are scrolling the most data. Most users will never see this because tmux issues smcup which disables the scrollback entirely.

**Comment by krader1961** [comment]
> with a single pane is one of the times this improvement is most needed because we are scrolling the most data. Most users will never see this because tmux issues smcup which disables the scrollback entirely.

Okay, I'll take your word for that. Although my experience begs to differ. I never use more than one pane and have smcup in both my tmux and native terminal terminfo definitions. Yet I've never noticed missing data when using iTerm2's native scrollback after large amounts of data has been streamed to the display. Which suggests that my typical use of tmux does not trigger the heuristic that causes output to be elided before sent to the  terminal. Unlike the situation for @heymoe.

**Comment by nicm** [comment]
It is more common if you have a slow terminal or network connection because then the terminal can't keep up with the volume of data.

**Comment by nicm** [comment]
I just tried putty and it does correctly turn off the scrollback when in the alternate screen; however, there is an option "Disable switching to alternate screen" which @heymoe must have selected.

**Comment by krader1961** [comment]
> It is more common if you have a slow....

That makes sense. I seldom connect to my tmux sessions via slow connections. And when I do so (such as from an open WiFi connection at a coffee shop) the bandwidth and latency is typically so bad that I am unlikely to even check that the terminal scrollback buffer is accurate. In which case the tmux optimization that @heymoe is complaining about is actually a net benefit by reducing how much data streams to my laptop. Something that [mosh](https://mosh.org/) (the mobile secure shell ) also does.

**Comment by nicm** [comment]
@krader1961 there are a couple of mechanisms and I'm surprised you are not hitting one of them:

1) If you have a high volume of data, then tmux will work out that the terminal can't keep up and switch from updating every line when it comes in to redrawing the entire terminal as often as it can - this is most often triggered when the terminal or network connection is slow.

2) If the application inside tmux sends a lot of lines very fast (for example "jot 10000"), tmux will probably see more lines in one block of data from read() than can possibly fit on the screen - for example, if your terminal is 50 lines high and a read() contains 200 lines, tmux will discard the first 150 and only draw the last 50. There are also other similar improvements: for example, if tmux knows that there is a "1" at 0,0 on the terminal and a naive interpretation would mean drawing another "1" at the same position, tmux could omit that. Mostly it is biased around improving the most common cases - if you have a non-default foreground or background colour or attributes, or are using UTF-8 characters, or anything else less common, tmux is more likely to draw even if it is unnecessary. And there are some things we just can't do because terminals work in different ways so we need to be sure that we leave them in a known (to tmux) state.

You will probably not hit (1) but you should be able to hit (2) fairly easily.

**Comment by nicm** [comment]
(1) is actually quite hard to hit now both because of (2) and also because we have improved how we clear the screen (a common source of high data volume was needing to clear entire regions using spaces, but now we do that using the insert character sequence when possible). Also xterm is one of the slower terminals, but it also has features like left-right margins that let us reduce the data volume for panes further.

**Comment by nicm** [comment]
For (2) you are on OS X and IIRC the maximum read() size on OS X is quite small (maybe 128 bytes?) compared with other platforms, so the opportunities for this optimization are more limited. Anyway, if you aren't seeing any problems then you have no problems :-).

**Comment by heymoe** [comment]
Indeed I'm using tmux in a single window mode as in I'm not breaking up the terminal screen into multiple boxes / panes each with a different shell running in it. One shell, full screen, basically like using screen instead of tmux.

I totally understand that if I did break my screen into multiple panes in single window that the scroll back buffer of my terminal (putty) will not work. I also understand that my terminal's scroll back buffer will not work right if I change to a different tmux window or did a resize of the terminal and I don't expect tmux to try and re-populate my terminal's scroll back buffer with the data from the new window. Nor do I expect tmux to try to re-populate my terminal's scroll back buffer when I re-attach to tmux.

When I need to do a large cut-n-paste, I run the command and then do my cut-n-paste right after without doing any of the noted things above or anything else that would obviously break the integrity of my terminal's scroll back buffer.  

Indeed since I'm running tmux from a remote ssh session I understand that a the mass output of a command being run will not keep up in real time over the network like it likely would if I was running said command locally on the server but I'm not doing this work over a dial up network but typically over a local gig lan network which is more than fast enough to not need tmux to decide that it needs to drop data from my command output. I mean catting a 1000+ line text file over a gig lan is plenty fast to have all 1000+ lines show up in my opinion. 

As I said I can definitely see the cases where this data dropping feature can come in handy but when you need to see all the data like in my use cases, this really throws a monkey wrench into the works. And sure v2.3 might have had the drop data feature in it but it seem that how tmux decides when to start dropping data has been cranked to 11 / became super aggressive starting in v2.4+ for my use cases. I could cat files containing over 8,000 lines if not up to my max scroll back buffer without any problems in v2.3. I don't do that that often but when I needed to before, it worked fine.

I haven't look at the code deeply enough to know exactly how tmux decides when to drop data but it seems that it does something like: if X number of line comes in within a set period of time then start dropping data while not taking into account how fast the terminal is actually able to absorb the flood of data / network speed. If the connection if fast enough then why not let all the data though when in single window mode?

**Comment by antcodd** [comment]
@heymoe There are two sensible ways of working around this that I have no clue why they haven't been mentioned. If anything they should work better than your previous workflow as they work natively in copy mode. Took me a while to find having just started using tmux again.

1. If your putty is capable of supporting the xterm clipboard escape sequences  you can use set -g set-clipboard on. I believe this is on by default in most cases (not sure why since the most common libvte terminal emulators like gnome-terminal don't support it which cause console spam when copying).
2. You can set up portable system clipboard copying using the [tmux-yank plugin](https://github.com/tmux-plugins/tmux-yank). Unfortunately it doesn't look like putty is supported. Alternatively, if you look at for example https://unix.stackexchange.com/questions/348913/copy-selection-to-a-clipboard-in-tmux and change the xclip commands to the putty command used in tmux-yank scripts/helpers.sh you can make it fairly seamless. If you used a different terminal like Mobixterm or set up X forwarding over putty you could use xclip/xsel itself.

There is enough infrastructure in tmux 2.3 to make selection and clipboard copy and paste behaviour behave pretty much exactly like gnome-terminal and friends (2.6 if you want selection active specific commands). For some reason it is scattered across the internet rather than integrated in tmux-yank as options. I might look at adding them or creating a 'sensible' clipboard plugin once 2.6 is out.

**Comment by nicm** [comment]
I'm going to leave this as it is for the moment, thanks.

**Comment by moll** [comment]
I'm going to have to support @heymoe's use case here. I was wtfing for quite some time the other day puzzled what is losing half of my `cat file-with-200-lines` output. Worked on my Mac, didn't on my Linux. Turned out one was running Tmux v2.1, the other v2.6, which seems to match the issue talked about here.

I too use `xterm*:smcup@:rmcup@` because I find the terminal emulator scrollback to be far more user friendly than Tmux's was last I tried. Terminal.app or iTerm2.app seem smoother, have inertia scrolling and have a scrollbar I can grab onto. I appreciate the optimizations for those that have this setting off and are on bad connections, but for me on perfect connections, I'd like my 2K bytes of output as-is. :)
