### ISSUE TITLE
[feature request] escape should bail out of ex commands/search

### ISSUE THREAD

**Issue by Grazfather** [tmux/tmux#1020]
I don't know how many times I've been stuck in the prompt to search up/down without knowing it. 

It would be nice if escape simply bailed out of any prompt and returned to normal mode.

I can't even think of a downside to this.

**Comment by jungle-boogie** [comment]
When this usually happens to me, I press enter and I'm out of search mode.

What's wrong with enter?

**Comment by Grazfather** [comment]
It 'commits' whatever you've entered while you were jamming the keys trying to figure out wtf is happening. That'll cause a scroll back, for example, if it finds a match and you were in search back.

**Comment by nicm** [comment]
Works for me.

**Comment by nicm** [comment]
Escape should already closesthe prompt in emacs mode and it can't in vi mode for an obvious reason. C-c will also work and it is recommended because you won't need to wait for escape-time before it happens.

**Comment by Grazfather** [comment]
What is the obvious reason? In vim escape will bail out of both search and Ex mode.

C-c could kill whatever process is in the pane if it turns out I'm not actually in a tmux command mode, so it's less safe. Escape is best because it's universal and won't really kill anything.

**Comment by nicm** [comment]
Escape is needed to switch mode.

**Comment by Grazfather** [comment]
Ah, I never noticed that vim keys were used while in Ex/search mode (e.g. while typing, not navigating).

That's actually not how it works in vim.

You have to hit `q:` to go into the command window if you want to edit a command or search. For that reason I'd suggest you dump that feature and just keep the vim keys for _after_ a search has been made, or a selection. Otherwise you've basically made a third type that's neither vim nor emacs.

**Comment by nicm** [comment]
I think people will complain if we disable line editing at the command prompt with vi keys.

**Comment by Grazfather** [comment]
I doubt it, but this is getting to be where it's more work than I'd hope for to implement, but vim editing mode (like the bash/readline option) would be best separated from vim navigation, but that's a lot of work. Thanks for considering.

**Comment by nicm** [comment]
Personally I think we should only support one key set for line editing but people would definitely complain if the command prompt stopped working like vi mode does in the shell, I don't know where you get the idea it is different.

**Comment by nicm** [comment]
Try ksh or bash vi line editing...

**Comment by Grazfather** [comment]
Right, so that's something else. I did misread your last comment (my bad).

I'd guess +95% of people who use vim mode in tmux use it for select navigation, not for line editing. I don't know anyone who uses vi mode line editing, even the die-hard vim users. Of course, not super easy just removing that and counting the complaints..

**Comment by nicm** [comment]
Yes I think it is stupid too but it is there now and if we are keeping vi
keys for copy mode we might as well keep them for the command prompt too.


On 31 Jul 2017 6:03 pm, "Grazfather" <notifications@github.com> wrote:

Right, so that's something else. I did misread your last comment (my bad).

I'd guess +95% of people who use vim mode in tmux use it for select
navigation, not for line editing. I don't know anyone who uses vi mode line
editing, even the die-hard vim users. Of course, not super easy just
removing that and counting the complaints..

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1020#issuecomment-319131987>, or mute
the thread
