### ISSUE TITLE
Escape key conflicts with vim

### ISSUE THREAD

**Issue by ovu** [tmux/tmux#1026]
Hi all, I am using tmux 2.5 with vim 8.0.648. 
By default tmux uses the Escape Key to enter in the copy mode. However, im Vim Escape is used to change from insert mode into command mode. Vim is not going to command mode after pressing Escape.

Is there a way to configure tmux to allow vim change mode when pressing the Escape key?

**Comment by nicm** [comment]
tmux does not use Escape by default.

**Comment by ovu** [comment]
Removing the following lines from my config fixed the issue:

unbind [
bind-key -n C-[ copy mode

It was working before in tmux 1.9.

**Comment by nicm** [comment]
C-[ and Escape are the same key so it probably worked only by fluke


On 28 Jul 2017 8:37 pm, "ovu" <notifications@github.com> wrote:

Removing the following lines from my config fixed the issue:

unbind [
bind-key -n C-[ copy mode

It was working before in tmux 1.9.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1026#issuecomment-318743904>, or mute
the thread

**Comment by ovu** [comment]
Since it was clarified. Let's close the issue. Thanks for your help.
