### ISSUE TITLE
Unbinding shift+backspace and ctrl+backspace

### ISSUE THREAD

**Issue by jamesla** [tmux/tmux#1031]
I want to unbind shift+backspace and ctrl+backspace to stop them from switching panes.

I have tried all sorts of variants of

```
unbind c-^backspace
unbind shift-^backspace
```

But cannot figure out how to unbind these key bindings. Does anybody know how I can do this?

**Comment by krader1961** [comment]
You first have to figure out what those key combinations send. Historically, back in the days of DEC VT100s, ctrl-backspace and shift-backspace didn't make any sense and the modifier keys were just ignored. That's because [backspace] normally sends a control character. Specifically, [ctrl-H]. So applying the control modifier key wouldn't normally do anything. Modern software terminals allow you to customize what such key combinations send. But there is no standard for what is sent.

If you have the fish shell available you can use its handy `fish_key_reader` program to answer this question. If you don't have that try running `od -tx1z` or `xxd` then press those keys followed by [enter] then [ctrl-D].

**Comment by jamesla** [comment]
Thanks that was really helpful. I ran and it turned out both ctrl + backspace and shift + backspace are sending the same key press which is  
```
hex:    8  char: \cH  (or \b)
```
Knowing that I have tried:
```
unbind C-H
```
To no effect. Any ideas from here?

**Comment by nicm** [comment]
tmux does not have a default binding for C-h or for BSpace.

**Comment by nicm** [comment]
I am not going to play guessing games about your config. Please read the [CONTRIBUTING](https://raw.githubusercontent.com/tmux/tmux/master/CONTRIBUTING) file.

**Comment by grivet** [comment]
I have the exact same issue. I have no custom binding that changes the pane. This is a tmux issue, and Ctrl-Backspace is definitely a problem.
