### ISSUE TITLE
xclip not working with run-shell

### ISSUE THREAD

**Issue by CeleritasCelery** [tmux/tmux#1035]
I am using tmux 2.3 and want to define a command to send the paste-buffer to system clipboard. I have tried using the command below and every variant I can think of, but when I try to run it, I get a message saying it returns with exit code 1. When the run the command in sh it works fine and when I remove the xclip part it doesn't throw an error. How can I debug what is causing the error?

```bash
bind-key b run-shell "tmux show-buffer | xclip -in -sel clip > /dev/null"
```

**Comment by nicm** [comment]
Is xclip in the PATH used by /bin/sh? What if you use its full path?

**Comment by CeleritasCelery** [comment]
Thank you for your reply. It is on `PATH`. and I get the same error even if I use the full path like so 
```
bind-key b run-shell "tmux show-buffer | /usr/bin/xclip -in -sel clip > /dev/null"
```

**Comment by nicm** [comment]
What about full path to tmux?

**Comment by CeleritasCelery** [comment]
Same error.
```
bind-key b run-shell "/usr/bin/tmux show-buffer | /usr/bin/xclip -in -sel clip > /dev/null"
```

**Comment by CeleritasCelery** [comment]
So after looking into this some more I am only seeing this behavior when I log in via SSH. when I am logged into the machine normally it works fine.

**Comment by nicm** [comment]
Are you using ssh -X or -Y?

**Comment by CeleritasCelery** [comment]
I am not

**Comment by nicm** [comment]
Which X server are you trying to get xclip to talk to?

**Comment by CeleritasCelery** [comment]
X11. I have remote machine where I run emacs in a VNC and am trying to use my shell through SSH and tmux. I want to be able to send stuff copied from tmux to the clipboard to be pasted into Emacs.

If I have both tmux and Emacs running in my VNC everything works fine. It's just when I split off tmux to run through SSH that I am running into xclip problems.

**Comment by nicm** [comment]
Which X server, the one on the machine running ssh or the one on the
machine running tmux?


On 16 Aug 2017 5:54 pm, "CeleritasCelery" <notifications@github.com> wrote:

X11. I have remote machine where I run emacs in a VNC and am trying to use
my shell through SSH and tmux. I want to be able to send stuff copied from
tmux to the clipboard to be pasted into Emacs.

If I have both tmux and Emacs running in my VNC everything works fine. It's
just when I split off tmux to run through SSH that I am running into xclip
problems.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1035#issuecomment-322833767>, or mute
the thread

**Comment by CeleritasCelery** [comment]
the one on the machine running tmux.

**Comment by nicm** [comment]
I assume you want to set the clipboard on your local machine. You will need
to forward X to the machine using ssh -X or ssh -Y so that xclip can talk
to your local X server. You can see if this is working by checking DISPLAY
after ssh (but before running tmux), it should show localhost:0 or
something similar. Then you need to make sure that DISPLAY is set for
xclip: tmux will update it in the global environment by default, but I'm
not sure if 2.3 will pass that to run-shell. If it doesn't you will need to
upgrade tmux.

Alternatively you can use a terminal which supports the OSC 52 clipboard
sequence (ie, xterm) and use the tmux set-clipboard option.

**Comment by nicm** [comment]
Oh the one on the machine running tmux is easier: just make sure DISPLAY is
set. It is probably being removed after ssh. So set it again when running
xclip: something like DISPLAY=:0.0 xclip ...

**Comment by CeleritasCelery** [comment]
Thank you. That helped
