### ISSUE TITLE
Tmux does not show anything

### ISSUE THREAD

**Issue by grapeli23** [tmux/tmux#1044]
on Fabrice Bellard riscv32 console
https://bellard.org/jslinux/vm.html?cpu=riscv32&url=https://bellard.org/jslinux/buildroot-riscv32.cfg

tmux-1.7 (Why start the old version, because it is very fast.)
https://drive.google.com/open?id=0BwO8xuhb9OwrR0Y3MnROQi1ERXc
In the xterm terminal, works fine.

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by grapeli23** [comment]
> Does this still happen with master?

Tmux version 2.5 displays this message.
`tmux: need UTF-8 locale (LC_CTYPE) but have ANSI_X3.4-1968`

**Comment by nicm** [comment]
You need to install a UTF-8 locale (it will try en_US.UTF_8, C.UTF-8 and $LANG/$LC_ALL).

**Comment by grapeli23** [comment]
Hmm! But how?
On a system running in the emulator in javascript (with speed 30-100MIPS), UTF-8 is a superfluous ballast.
Pre-installed GNU Screen works fine.

**Comment by nicm** [comment]
tmux requires a UTF-8 locale.



On 20 Aug 2017 11:04 pm, "grapeli23" <notifications@github.com> wrote:

Hmm! But how?
On a system running in the emulator in javascript (with speed 30-100MIPS),
UTF-8 is a superfluous ballast.
Pre-installed GNU Screen works fine.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1044#issuecomment-323615010>, or mute
the thread
