### ISSUE TITLE
Control separators in the lists

### ISSUE THREAD

**Issue by lasers** [tmux/tmux#1053]
Greeting. I am wondering if we can clean up the lists to make it easy for others to parse by printing the lists with control separators between fields.

Reason... I'm working on tmux script that will use this data so I'd like to see if something can be done about this as there are lot of "hacks" to split all of them up... and I notice that between commands, the size `[123x46]` would be in different columns.

Optionally, it would be nice to have labels on top.... there so we know what they're for... Really, I don't care. I just want to know what the percent in `tmux list-panes -a` is for... and having same labels in mostly same columns would be nice. This probably would break somebody else's tmux parsing... so optional it is. What are your thoughts on this? Ty.

**Comment by nicm** [comment]
Use -F

On 1 Sep 2017 6:28 am, "lasers" <notifications@github.com> wrote:

Greeting. I am wondering if we can clean up the lists to make it easy for
others to parse by printing the lists with control separators between
fields.

Reason... I'm working on tmux script that will use this data so I'd like to
see if something can be done about this as there are lot of "hacks" to
split all of them up... and I notice that between commands, the size
[123x46] would be in different columns.

Optionally, it would be nice to have labels on top.... there so we know
what they're for... Really, I don't care. I just want to know what the
percent in tmux list-panes -a is for... and having same labels in mostly
same columns would be nice. This probably would break somebody else's tmux
parsing... so optional it is. What are your thoughts on this? Ty.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1053>, or mute the thread

**Comment by lasers** [comment]
Huh. This is better... More variables... More insanity... I promise I will try and add them all... It'll take me some time. I'm closing this and will message here if I have more questions in the future. For now...
* Is it possible to simply print everything related to that `list` rather than inputting all variables?
* I was going to about missing titles in `list-panes -a`. `-F` got that one covered too. 👍 

P.S.  Now I know it's `#{pane_id}` I was asking about... Many thanks for a quick response.

**Comment by nicm** [comment]
I don't see why anyone would want all the possible formats, just use the
ones you want to see.

**Comment by lasers** [comment]
I was going to expose them as placeholders so the users can view `session_name`, `pane_title`, etc... on their `py3status` with i3wm. If I can't get them all, then I will try for dynamic placeholders where the users can add the placeholders directly from `tmux`'s `FORMATS` section. I will try and make that soon enough. Cheers. 👍

**Comment by lasers** [comment]
Started working on this... Barely scratched the `tmux` surface.

For `tmux list-buffers`...
I added `index` and `number`. I wanted to know if you're interested in implementing them in `tmux` too... to make tmux more useful and/or interesting... or something else. I dunno.

`index` prints `1` up to `N` (top to bottom)...
`number` prints `buffer_name` without `buffer` + then leftstrip all `zeroes`.

That's all for now. Thx.
