### ISSUE TITLE
resizing panes screws up selection cursor position

### ISSUE THREAD

**Issue by d-e-s-o** [tmux/tmux#1074]
I have two panes next to each other. In the left one I start selecting text (copy-mode + begin-selection) and keep the selection active. I switch to the right pane. Now I increase the size of this pane (resize-pane -H 1), effectively shrinking the size of the left pane. Upon reentering the left pane and starting over to select a new area (begin-selection) the cursor is totally off. That is, the selection begins at a different location than where the cursor is. If I exit copy mode and reenter it things are back to normal.

![output](https://user-images.githubusercontent.com/6610056/30359626-ea603a12-9800-11e7-9670-7ae3a7cd03aa.gif)
[commands.txt](https://github.com/tmux/tmux/files/1298129/commands.txt)
[tmux.conf.txt](https://github.com/tmux/tmux/files/1298130/tmux.conf.txt)
[tmux-server-24507.txt](https://github.com/tmux/tmux/files/1298131/tmux-server-24507.txt)

**Comment by nicm** [comment]
Does this still happen with master?

On 13 Sep 2017 5:29 am, "Daniel Mueller" <notifications@github.com> wrote:

I have two panes next to each other. In the left one I start selecting text
(copy-mode + begin-selection) and keep the selection active. I switch to
the right pane. Now I increase the size of this pane (resize-pane -H 1),
effectively shrinking the size of the left pane. Upon reentering the left
pane and starting over to select a new area (begin-selection) the cursor is
totally off. That is, the selection begins at a different location than
where the cursor is. If I exit copy mode and reenter it things are back to
normal.

[image: output]
<https://user-images.githubusercontent.com/6610056/30359626-ea603a12-9800-11e7-9670-7ae3a7cd03aa.gif>
commands.txt <https://github.com/tmux/tmux/files/1298129/commands.txt>
tmux.conf.txt <https://github.com/tmux/tmux/files/1298130/tmux.conf.txt>
tmux-server-24507.txt
<https://github.com/tmux/tmux/files/1298131/tmux-server-24507.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1074>, or mute the thread

**Comment by d-e-s-o** [comment]
Good point. I checked and at ae5a62a514f56e202db885caaa59b32f5ea2f5d0 it works as expected. I guess I can close the issue then. Thanks.

**Comment by d-e-s-o** [comment]
For the record, 1883d299bf853dac75cd67c012b9f074b0a4dbef is the fix.
