### ISSUE TITLE
choose-tree mode tagging behavior unclear

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1076]
in choose-tree mode, it is possible to tag sessions, windows, or panes. 
It is not clear what happens if the items tagged have different types.
Also, when you attempt to tag a subitem for an item that is already tagged, the parent becomes untagged.  
It is not clear why that happens. 

It would be helpful if the man page explained those cases better.

**Comment by nicm** [comment]
When you run a command that operates on the tagged items (whether a builtin key like pressing 'D' with choose-client, or from the command prompt with ':'), it runs the command on each tagged item in turn.

The reason that it untags the session when you tag a window is because it doesn't make sense to target both. If you target a session, it will include the window; so if you want to target an individual window, there is no point in having the session as well.

Personally I think this is easy enough to figure out but if you want to suggest some man page changes I'll take a look.
