### ISSUE TITLE
choose-buffer mode: Add ability to run command for all tagged choose-buffer buffers

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1077]
A feature request to allow choose-buffer mode to have ':' command like choose-tree mode.
This feature would make it possible to select multiple buffers and run the same command on each.

It would make it easier to build a command line from multiple buffers.

**Comment by nicm** [comment]
Please give me examples of some commands you want to run on multiple buffers.

**Comment by frosencrantz** [comment]
paste-buffer is the one I was thinking of.  I would like to be able to select multiple separate items in copy mode , and then be able to paste them in bulk. This would be useful for building a long command line with multiple arguments from different parts of a pane.

**Comment by nicm** [comment]
A key to paste all tagged would be better for this.

**Comment by nicm** [comment]
But you have no way to express the order they are pasted so both seem of limited use to me.

**Comment by frosencrantz** [comment]
Typically in such a case I would pick a bunch of similar items like filenames, and pasting them all on the command line in any order is fine.

**Comment by nicm** [comment]
Try this please: [tmux-paste.diff.txt](https://github.com/tmux/tmux/files/1394194/tmux-paste.diff.txt)

Adds P key to paste tagged buffers. Its a bigger diff than might appear to be needed because I added an argument to one of the functions and also removed some code that I think is now unnecessary (commands would previously have executed immediately so we needed to copy stuff and cancel the mode first, now commands are executed back at the event loop we can cancel afterwards).

**Comment by nicm** [comment]
I have applied this now.
