### ISSUE TITLE
Large delay for prompt echoing after command completion on xfce4-terminal

### ISSUE THREAD

**Issue by vt220** [tmux/tmux#1089]
Scenario:
------------
1. Start tmux from an xfce4-terminal (version used: 0.8.6, on Linux)
2. Run some short-running cli command which returns to the shell after a completion (for example, run compilation on a small source file, in the reproduction below a small C++ file was compiled with g++).

Expected results:
---------------------
After the command completes and returns to the shell, a prompt should be printed. 

Actual results:
-----------------
The command itself completes after a couple of seconds (when timed outside tmux, the command takes 3-4 seconds to complete), but a prompt is not printed, making it seem as though the command is still running. If left alone, the prompt is eventually printed after a delay of 30-60 seconds. Alternatively, if any key is pressed (after waiting 3-4 seconds for the command to complete), the prompt is printed.

The problem happens only when tmux is started from xfce4-terminal. The problem doesn't happen when tmux is started from xterm or konsole, and it doesn't happen in xfce4-terminal when tmux is not used.
In addition, the problem occurs only on a x86 machine (on an Eee PC 1000HE with an Atom N280 CPU) and does not reproduce on a x64 machine.

Tmux version: 2.5
TERM outside: xterm-256color (the same TERM was used in all tested terminal emulators)
TERM inside: tmux-256color

Attached are the relevant log files and (just in case) a C++ file used for a compilation (I had to append .txt extension in order to be able to upload it to the github).

The delay can be seen in server's log at 1506355999.797109 (for about ~40s).

[tmux-server-14344.log](https://github.com/tmux/tmux/files/1330567/tmux-server-14344.log)
[tmux-client-14342.log](https://github.com/tmux/tmux/files/1330568/tmux-client-14342.log)
[tmux-out-14344.log](https://github.com/tmux/tmux/files/1330566/tmux-out-14344.log)
[a.cc.txt](https://github.com/tmux/tmux/files/1330571/a.cc.txt)

**Comment by nicm** [comment]
tmux seems to be working as expected. What libevent version are you using? Does it work if you do this before starting tmux (make sure you kill tmux entirely)?
~~~~
export EVENT_NOPOLL=1

**Comment by nicm** [comment]
You can see the time gaps are not unexpected:
~~~~
1506355996.613070 /dev/pts/5: keys are 1 (\r)
1506355999.795514 input_parse: %0 ground, 17 bytes: [vt220@eee test]$
1506355999.795548 screen_write_collect_end: 17 [vt220@eee test]$  (at 0,1)
1506355999.795617 /dev/pts/5: [vt220@eee test]$
1506355999.796448 /dev/pts/5: wrote 17 bytes (of 17)

**Comment by vt220** [comment]
Seems that libevent 2.1.8-stable is used. When 'select' is used instead of a 'poll' (with EVENT_NOPOLL=1), the results are identical.

I suppose that small gaps (a couple of seconds) are to be expected, but more than 30 seconds seems a way too much. And if the problem is somehow is related to libevent, why it doesn't happen on other terminals?

**Comment by nicm** [comment]
Yes it seems more likely to be an xfce4-terminal problem. But there is
nothing funny about the output (it is just plain characters, no escape
sequence) so hard to guess what. What do they say about it?

**Comment by vt220** [comment]
I can try to ask on xfce mailing lists if you think it is worth a try, but since the problem doesn't happen in xfce4-terminal by itself I am afraid that the problem will be referred back to tmux. Especially since the problem is not easily reproducible (I don't think many people have old x86 machines laying around).

**Comment by nicm** [comment]
Run tmux in strace with -f -ttt -ostrace.out and show me the file

**Comment by vt220** [comment]
Please see attached. The problem seem to be in 1506372260.410032 (in strace's log), with select talking 40 seconds to complete. 

[tmux-server-15615.log](https://github.com/tmux/tmux/files/1330786/tmux-server-15615.log)
[strace.out.log](https://github.com/tmux/tmux/files/1330788/strace.out.log)

**Comment by nicm** [comment]
No, that is not the case. That select is after the write(), tmux writes the prompt here after fd 6 is returned from this earlier select():
~~~~
15615 1506372260.408697 _newselect(11, [3 6 8 9 10], [6], NULL, {tv_sec=50, tv_usec=569986}) = 1 (out [6], left {tv_sec=50, tv_usec=569965})
15615 1506372260.408915 writev(6, [{iov_base="[dima@eee test]$ ", iov_len=17}], 1) = 17
15615 1506372260.409247 write(5, "1506372260.409214 /dev/pts/5: wr"..., 53) = 53
~~~~
fd 5 is the log, so this matches this log line:
~~~~
1506372260.409214 /dev/pts/5: wrote 17 bytes (of 17)
~~~~
And fd 6 is the terminal pty slave side. It is not /proc/15615/fd (that is fd 6, but only temporarily - you missed a close(6) a few lines down). It is actually received from the client here, note the cmsg_data=[6]:
~~~~
15615 1506372250.475674 recvmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="d\0\0\0\24\0\0\0\10\0\0\0\377\377\377\377\0\0\1\0e\0\0\0\37\0\0\0\10\0\0\0"..., iov_len=65535}], msg_iovlen=1, msg_control=[{cmsg_len=16, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[6]}], msg_controllen=16, msg_flags=0}, 0) = 128
~~~~
The 40-second select() that you mentioned might appear suspicious, but the reason it is 40 seconds is just because that is how long tmux has to wait before you press another key (that is, tmux is idle until whatever is causing the delay shows you the prompt).

So it appears as if tmux is writing the prompt pretty much as soon as it receives it. I think this is either a bug in xfce4-terminal or a kernel bug.

**Comment by nicm** [comment]
Do you also have this problem in gnome-terminal? It is also VTE-based.

**Comment by nicm** [comment]
This is where tmux reads the prompt from pty connected to the the shell inside, so it is about 5 milliseconds between tmux getting it and it sending it to the terminal:
~~~~
15615 1506372255.558811 _newselect(11, [3 6 8 9 10], [], NULL, {tv_sec=55, tv_usec=419993} <unfinished ...>
15615 1506372260.404108 <... _newselect resumed> ) = 1 (in [10], left {tv_sec=50, tv_usec=574827})
15615 1506372260.404241 ioctl(10, FIONREAD <unfinished ...>
15615 1506372260.404342 <... ioctl resumed> , [17]) = 0
15615 1506372260.404470 readv(10, [{iov_base="[dima@eee test]$ ", iov_len=17}], 1) = 17

**Comment by vt220** [comment]
gnome-terminal works fine. I will try to ask on xfce mailing lists, will report back (probably in a couple of days).

**Comment by nicm** [comment]
Closing but please comment again if you get this resolved.

**Comment by Zunino** [comment]
> gnome-terminal works fine. I will try to ask on xfce mailing lists, will report back (probably in a couple of days).

I'm seeing the same behavior in my XFCE environment (no tmux though). Did you ever find the actual cause of the problem? Thank you.
