### ISSUE TITLE
What's the best practices for Debugging TMux ?

### ISSUE THREAD

**Issue by accesio** [tmux/tmux#1099]
Hi,

I've been slowly working on a feature for tmux because debugging it has gotten in the way.

I've done curses debugging before where I can connect to a different screen (pty ) and have the debugger step through the UI rendering functions and it makes it pretty easy to debug these drawing features.  However, I have problems getting this to work on tmux ( probably bc its way more advnaced than my simple curses programs )...for instance, I had a problem getting tmux to continue running correctly (?). It was probably my not being sophisticated setting up gdb correctly.

Is there a best practices guide for how to debug tmux while developing a feature using a GDB or something similar ? 

It could help those debug some of the issues / features that people want to add.

Just a thought,

**Comment by accesio** [comment]
By "tmux to continue running correctly" meant , after a breakpoint and typing continue...tmux was left in a foobar state.

**Comment by nicm** [comment]
I just attach gdb to the tmux server process and it works fine. If the
screen gets corrupted you can make tmux redraw it with C-b r.



On 6 Oct 2017 7:26 pm, "Jimi Damon" <notifications@github.com> wrote:

By "tmux to continue running correctly" meant , after a breakpoint and
typing continue...tmux was left in a foobar state.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1099#issuecomment-334834148>, or mute
the thread
