### ISSUE TITLE
How can I emulate v2.5 choose-window behavior using v2.6 choose-tree?

### ISSUE THREAD

**Issue by ntwk** [tmux/tmux#1115]
As of version 2.6 choose-window is aliased to `choose-tree`.  I am trying to come up with a `choose-tree` command which will give me the exact look and feel of the older choose-window command.

So far, I have come up with the following:

`choose-tree -N -w`

The `-N` disables the new "preview" window and `-w` displays all windows collapsed and also ensures that the current window is highlighted.

However, the above command isn't quite the full solution.  I typically have multiple sessions running and the `choose-tree` lists windows in **all** of my sessions.  The old `choose-window` only listed windows in the **current** session.

My understanding is that I can use the `choose-tree` `-f` filter option to filter out windows using a format string.  I'd like to filter out all windows in sessions other than the current one.  So far I have:

`choose-tree -N -w -f #{==:#{session_name},????}`

I'm not sure what to replace `????` with.  Basically, I'd like the format string to test that the `session_name` of a given list item matches the `session_name` of the window from which the `choose-tree` command was invoked.

Can anyone help me out?

My environment is as follows:

- Platform: Linux 4.13.5
- Tmux version: 2.6
- TERM inside tmux: screen-256color
- TERM outside tmux: rxvt-unicode-256color

**Comment by nicm** [comment]
Try eg

run 'tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"'

**Comment by ntwk** [comment]
I tried running `tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"` from a shell prompt and it doesn't appear to filter list items.

It produces the exact same list as `tmux choose-tre -Nw`.

**Comment by nicm** [comment]
tmux run "tmux choose-tree ..."

**Comment by ntwk** [comment]
Now I see what you were doing there.  I missed the preceeding `run` command in your first reply.

`tmux run 'tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"'` gets me very close to a full solution but there remains one small detail.  Do you know how I can also filter the line at the top of the list which corresponds to the session as a whole?

**Comment by nicm** [comment]
No the tree always has at least one session.

**Comment by andykais** [comment]
hi, no luck with the above command, also trying to recreate the old tmux choose window 

`choose-tree -Nwf"##{==:##{session_name},#{session_name}}"`

I tried running the command with both named and unnamed sessions and in both cases two sessions were still shown instead of one. Is there a way to show the output of `#{session_name}` to debug?

**Comment by ntwk** [comment]
> hi, no luck with the above command, also trying to recreate the old tmux choose window
>
> `choose-tree -Nwf"##{==:##{session_name},#{session_name}}"`

Because you need to perform variable substution in two passes, use the `run-shell` command like so:

`run-shell 'tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"'`

**Comment by jonlee836** [comment]
@ntwk 

works great!

btw is there a way to highlight the session name?

**Comment by ntwk** [comment]
I'm not sure if there is a way to highlight the session name.  If you are curious enough, try creating a new issue on the topic.

**Comment by axelson** [comment]
Thanks for this! I really wanted the old behavior too so that I can easily switch between windows of the current session. I have sessions that have about 12 windows, and I often have 8 sessions running at once so by default `choose-tree` will not allow me to choose the all the windows of the current session).

To contribute to the discussion here is a snippet to bind `w` to replicate the previous behavior:

    bind-key w run-shell 'tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"'

It seems like it should be possible to call choose-tree directly without going through run-shell but I'm not sure how to accomplish that.

**Comment by stephen-smith** [comment]
> > Do you know how I can also filter the line at the top of the list which corresponds to the session as a whole?

> No the tree always has at least one session.

Okay, well, until we can get back all of the old behavior, I'd like choose-window back please.  Choose tree is unfriendly to my workflow.  I don't ever want to select (or even see) multiple windows merged and I definitely don't want to switch sessions.
