### ISSUE TITLE
Poor usability with new choose-tree shortcuts

### ISSUE THREAD

**Issue by jdigory** [tmux/tmux#1132]
With:

```
Linux unknown
tmux 2.6
screen
```

The new `choose-tree` shortcut key change was made here:
https://github.com/tmux/tmux/commit/aad4e4ddb194cba9c01b0ddd696fb7b214e1a7eb
and described as:
> - shortcut keys change from 0-9, a-z, A-Z which was always a bit weird with keys used for other uses to 0-9, M-a to M-z.

The issue I'm having is that the change results in poor usability, requiring remapping of "muscle memory" for keystrokes, but also changes the default position for each window by shifting down one.

Here is a snippet of windows on version 2.6:

```
(9)   ├─> 8: foo (1 panes) "foo.com: [tmux]"
(M-a) ├─> 9: bar (1 panes) "blah"
(M-b) └─> 10: baz- (1 panes) "baz.com: bash"
```

compared to prior versions:

```
(8)   8: bash  [134x109] (1 panes) "foo.com"
(9)   9: bash  [134x109] (1 panes) "foo.com"
(a)  10: bash* [134x109] (1 panes) "foo.com"
(b)  11: bash- [134x109] (1 panes) "foo.com"
```

The `a-z` keys are really pretty nice, especially as they require only a single keystroke. I'd like to see a configuration option to restore this behavior (at this point, restoring the original behavior globally without a configuration change would likely only cause more confusion).

Additionally, note that window 9 in the prior versions is easily accessed as "9", whereas in 2.6, it is now "meta-a". This is very confusing, and seems like a regression; one that should be corrected for all users.

This "shift down" seems to be caused by the 0th-position window being some sort of master window:

```
(0)   - 0: 11 windows (attached)
(1)   ├─> 0: pl* (1 panes) "blah"
```

This makes window 0 only accessible by shortcut "1", and the same for windows 0-9...

**Comment by nicm** [comment]
0-9a-z is too many keys to use up for shortcuts not to mention the
difficulty and annoyance of skipping letters that are used for other things.


On 24 Oct 2017 12:48 am, "Josh Lavin" <notifications@github.com> wrote:

With:

Linux unknown
tmux 2.6
screen

The new choose-tree shortcut key change was made here:
aad4e4d
<https://github.com/tmux/tmux/commit/aad4e4ddb194cba9c01b0ddd696fb7b214e1a7eb>
and described as:


   - shortcut keys change from 0-9, a-z, A-Z which was always a bit weird
   with keys used for other uses to 0-9, M-a to M-z.

The issue I'm having is that the change results in poor usability,
requiring remapping of "muscle memory" for keystrokes, but also changes the
default position for each window by shifting down one.

Here is a snippet of windows on version 2.6:

(9)   ├─> 8: foo (1 panes) "foo.com: [tmux]"
(M-a) ├─> 9: bar (1 panes) "blah"
(M-b) └─> 10: baz- (1 panes) "baz.com: bash"

compared to prior versions:

(8)   8: bash  [134x109] (1 panes) "foo.com"
(9)   9: bash  [134x109] (1 panes) "foo.com"
(a)  10: bash* [134x109] (1 panes) "foo.com"
(b)  11: bash- [134x109] (1 panes) "foo.com"

The a-z keys are really pretty nice, especially as they require only a
single keystroke. I'd like to see a configuration option to restore this
behavior (at this point, restoring the original behavior would likely only
cause more confusion).

Additionally, note that window 9 in the prior versions is easily accessed
as "9", whereas in 2.6, it is now "meta-a". This is very confusing, and
seems like a regression; one that should be corrected for all users.

This "shift down" seems to be caused by the 0th-position window being some
sort of master window:

(0)   - 0: 11 windows (attached)
(1)   ├─> 0: pl* (1 panes) "blah"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1132>, or mute the thread

**Comment by jdigory** [comment]
What about the "shift-down" problem, making window 0 accessible at "1", etc?

**Comment by nicm** [comment]
The keys are for the lines, line 0 is the session. Same if you expand the windows the keys will change so 2 will be the first pane in the first window. So you can quickly choose any line.

choose-tree is designed for when you need more information to decide which session, window or pane you want - if you already know the index, use one of the bindings to select-window (C-b 0 to 9, C-b ').

If you want keys that let you reach higher indexes directly, you could add some additional bindings, for example something like:
~~~~
bind w switch-client -Twindows
bind -Twindows 0 select-window -t:=0
bind -Twindows 1 select-window -t:=1
...
bind -Twindows a select-window -t:=10
bind -Twindows b select-window -t:=11
...
~~~~
Which will make eg "C-b w a" go directly to window 10 without needing choose-tree at all.

**Comment by jdigory** [comment]
Ok, thanks.
