### ISSUE TITLE
"has-session" does prefix matching

### ISSUE THREAD

**Issue by anbn** [tmux/tmux#1143]
If a session "test" does exist, `tmux has-session -t` will also match sessions t, te and tes.

    % tmux -V
    tmux 2.6
    % tmux new-session -t test -d
    % tmux has-session -t t 
    % tmux has-session -t te
    % tmux has-session -t tes
    % tmux has-session -t test
    % tmux has-session -t teste
    can't find session teste

It would be more convenient if the exact session name was matched. If prefix matching is intended, this should be documented and mentioned in the man page. Currently, the man page entry says 

> Report an error and exit with 1 if the specified session does not exist.  If it does exist, exit with 0."
 
Linux x86_64
tmux 2.6
screen-256color

**Comment by nicm** [comment]
This is documented, look for the first time target-session is mentioned in
the manual.


On 30 Oct 2017 7:31 am, "Anselm Brachmann" <notifications@github.com> wrote:

If a session "test" does exist, tmux has-session -t will also match
sessions t, te and tes.

% tmux -V
tmux 2.6
% tmux new-session -t test -d
% tmux has-session -t t
% tmux has-session -t te
% tmux has-session -t tes
% tmux has-session -t test
% tmux has-session -t teste
can't find session teste

It would be more convenient if the exact session name was matched. If
prefix matching is intended, this should be documented and mentioned in the
man page. Currently, the man page entry says

Report an error and exit with 1 if the specified session does not exist. If
it does exist, exit with 0."

Linux x86_64
tmux 2.6
screen-256color

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1143>, or mute the thread

**Comment by anbn** [comment]
Thank you, I didn't see that. Exact name matching with =session works well, closed.
