### ISSUE TITLE
libc dll hell

### ISSUE THREAD

**Issue by dbabits** [tmux/tmux#1155]
@nicm, and all,
Below is the output on the host where I want to run tmux that I successfully built elsewhere.

1. Question: since it shows that there are later versions of glibc, can dependency on glibc 2.14 and 2.17 be removed from the build?
2. Alternatively, I would need to link glibc statically, but that didn't work for a different reason(i looked at 
similar issue #395, but that didn't help). I'm getting error: No rule to make target `compat/forkpty-linux.c, needed by compat/forkpty-linux.o' - This only happens when adding -static to LDFLAGS of tmux's make.

3. Any other suggestions?

The script I use for building tmux is this: https://github.com/dbabits/tmux_local_install/blob/master/tmux_local_install.sh

```
> ldd -v ./tmux.2.6
./tmux.2.6: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./tmux.2.6)
./tmux.2.6: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./tmux.2.6)
        linux-vdso.so.1 =>  (0x00007fff471b0000)
        libutil.so.1 => /lib64/libutil.so.1 (0x000000331ea00000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x000000331ee00000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x0000003310200000)
        libc.so.6 => /lib64/libc.so.6 (0x000000330ea00000)
        /lib64/ld-linux-x86-64.so.2 (0x000000330e200000)

        Version information:
        ./tmux.2.6:
                libutil.so.1 (GLIBC_2.2.5) => /lib64/libutil.so.1
                libresolv.so.2 (GLIBC_2.2.5) => /lib64/libresolv.so.2
                libc.so.6 (GLIBC_2.7) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.9) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.14) => not found
                libc.so.6 (GLIBC_2.8) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.10) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.17) => not found
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
        /lib64/libutil.so.1:
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libtinfo.so.5:
                libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libresolv.so.2:
                libc.so.6 (GLIBC_2.4) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
```

Appreciate your help.

**Comment by nicm** [comment]
I don't want to debug your scripts, why don't you just configure with
--enable-static?

$ ./configure --enable-static >/dev/null
$ make >/dev/null
$ ldd ./tmux
        not a dynamic executable
$

**Comment by dbabits** [comment]
Because this gives me: No rule to make target `compat/forkpty-linux.c, needed by compat/forkpty-linux.o'

**Comment by nicm** [comment]
What tmux version? Show me config.log and full make output.

**Comment by nicm** [comment]
There is no forkpty-linux.c because on Linux forkpty is on libutil, so I am guessing that on your platform libutil is not able to be linked statically, or there is a flaw in the configure test.

**Comment by nicm** [comment]
I only need config.log actually, don't worry about make output.

**Comment by dbabits** [comment]
The platform is Amazon Linux 4.9.32-15.41.amzn1.x86_64 SMP Thu Jun 22 06:20:54 UTC 2017.

I'm not able to attach the files at the moment, because my proxy doesn't let me, will do later from home.
Could you look perhaps at the link I provided at the top ? - it just has a few configure and make commands and shows versions, there's nothing to debug.

thanks for your help.

**Comment by nicm** [comment]
If you want to build tmux by putting -static in LDFLAGS you will need to do it on your own, I am only going to support building static builds with --enable-static, sorry.

**Comment by nicm** [comment]
Show me the config.log when you can get it and I will take a look, or look for the lines where it looks for forkpty, for example, I have this:
~~~~
configure:6851: checking for library containing forkpty
configure:6882: ccache gcc -o conftest  -D_GNU_SOURCE -D_DEFAULT_SOURCE     -static   conftest.c  -ltinfo -levent  -lresolv >&5
/tmp/ccbbJzBO.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `forkpty'
collect2: error: ld returned 1 exit status
configure:6882: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "tmux"
| #define PACKAGE_TARNAME "tmux"
| #define PACKAGE_VERSION "master"
| #define PACKAGE_STRING "tmux master"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "tmux"
| #define VERSION "master"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define HAVE_DIRENT_H 1
| #define HAVE_FCNTL_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_PATHS_H 1
| #define HAVE_PTY_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_SYS_DIR_H 1
| #define HAVE_DIRFD 1
| #define HAVE_FLOCK 1
| #define HAVE_PRCTL 1
| #define HAVE_SYSCONF 1
| #define HAVE_ASPRINTF 1
| #define HAVE_CFMAKERAW 1
| #define HAVE_MEMMEM 1
| #define HAVE_SETENV 1
| #define HAVE_STRCASESTR 1
| #define HAVE_STRNDUP 1
| #define HAVE_STRSEP 1
| #define HAVE_NCURSES_H 1
| #define HAVE_B64_NTOP 1
| #define HAVE_DAEMON 1
| /* end confdefs.h.  */
|
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char forkpty ();
| int
| main ()
| {
| return forkpty ();
|   ;
|   return 0;
| }
configure:6882: ccache gcc -o conftest  -D_GNU_SOURCE -D_DEFAULT_SOURCE     -static   conftest.c -lutil -ltinfo -levent  -lresolv >&5
configure:6882: $? = 0
configure:6899: result: -lutil
~~~~

**Comment by dbabits** [comment]
Nicholas,

- Here's [config.log](https://github.com/dbabits/tmux_local_install/blob/master/config.log)
- Configure and make [flags](https://github.com/dbabits/tmux_local_install/blob/master/tmux_local_install.sh)

I have to admit, I do not know the difference between --enable-static and -static in LDFLAGS, but I made sure to use --enable-static. 
Same result though.

**Comment by nicm** [comment]
OK it looks like your problem is nothing to do with forkpty. Almost all the configure tests are failing because they are trying to link with libtinfo and failing:
~~~~
configure:6122: gcc -std=gnu99 -o conftest       -I/home/ec2-user/local/include -I/home/ec2-user/local/include/ncurses  -static  -L/home/ec2-user/local/lib -L/home/ec2-user/local/include/ncurses -L/home/ec2-user/local/include conftest.c  -ltinfo   -levent    >&5
/usr/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
~~~~
This is despite the fact that PKG_CONFIG says that libtinfo exists.

It looks like you are pointing configure to a locally built ncurses, but leaving it to use the system pkg-config (I suspect you probably don't need to use a local ncurses at all but it won't do any harm).

Try doing "PKG_CONFIG=/bin/false ./configure ..." to disable pkg-config and make configure look for the libraries directly.

**Comment by nicm** [comment]
The other option would be to use the pkg-config variables (LIBEVENT_CFLAGS etc, look at "configure --help") but YMMV, probably better just to turn off pkg-config and stick with the way you do it now.

**Comment by dbabits** [comment]
Ok, good news: PKG_CONFIG=/bin/false worked - thanks for that, and the explanation
Bad news: i now get on the other host where I'm trying to run it.
```
FATAL: kernel too old
Segmentation fault 
```
It's RHEL.
```
uname -a 
Linux 2.6.32-431.66.1.el6.x86_64
```

Anything can be done about that?

**Comment by dbabits** [comment]
```
execve("./tmux.2.6.static", ["./tmux.2.6.static", "-V"], [/* 50 vars */]) = 0
uname({sys="Linux", node="xyz", ...}) = 0
open("/dev/tty", O_RDWR|O_NOCTTY|O_NONBLOCK) = 3
FATAL: kernel too old
writev(3, [{"FATAL: kernel too old\n", 22}], 1) = 22
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5f8e434000
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
```

**Comment by dbabits** [comment]
My analysis:
> file tmux.2.6.static
tmux.2.6.static: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux **2.6.35**, not stripped

I believe 2.6.35 indicates  the minimum kernel version

uname shows my Linux as  2.6.32 

My guess, it's the version of glibc that got linked in that doesn't support older kernel.
Is this correct?

**Comment by nicm** [comment]
Yes seems most likely. You will need to find an older Linux box to build on. Or you can try this  [tmux.gz](https://github.com/tmux/tmux/files/1462862/tmux.gz) from CentOS 6.5 but it is dynamically linked so you will need libevent and ncurses packages installed.

**Comment by dbabits** [comment]
is there a way to install a specific version of glibc side-by-side, and indicate it at configure time ?

**Comment by nicm** [comment]
You will need to try it, or ask the glibc or RHEL developers.

**Comment by carlwgeorge** [comment]
The [IUS](https://ius.io) project ships tmux2u packages for RHEL 6/7 that follow the latest 2.x version of tmux.
