### ISSUE TITLE
Is there a way to prevent pane switching from overflowing past left and right boundaries?

### ISSUE THREAD

**Issue by gilgameshskytrooper** [tmux/tmux#1158]
![illustration](https://78.media.tumblr.com/58cbeec41acbbab89fd820f261c53fd1/tumblr_ozf21xbUFo1s5a4bko1_1280.jpg)

I have been digging around the good ole' world wide web for answers, but I have not been able to find any articles that do a good job detailing how I can prevent tmux from going past the physical borders when doing directional pane switching.

Let me explain more in detail what I mean by this: Let's say I have 2 vertically split panes, one right and one left. When on pane right is active, I want to prevent tmux from switching the active pane to  pane left when I do `prefix-left-arrow` (same concept with horizontal split panes: If I am at the bottom-most pane, I want to prevent tmux from going to top pane when I do `prefix-down-arrow`.

The reason for this is because I am currently using a program called BetterTouchTools to send the `prefix-arrow` commands to my terminal (so I can trigger them using swipe gestures). This works 99.9% of the time, but since swipe gestures can be ambiguous and inaccurate at times, I want to enforce hard borders on tmux that prevent pane switching from crossing the edges of the window.

Please let me know if this functionality already exists, or if not, please add to a future version.

Thank you!

**Comment by nicm** [comment]
You can script this by using #{pane_at_top}, #{pane_at_left} formats, for example something like:
~~~~
if -F '#{pane_at_top}' '' 'selectp -U'

**Comment by gilgameshskytrooper** [comment]
Is this done in `~/.tmux.conf`?

**Comment by gilgameshskytrooper** [comment]
Also, are these the actual commands I need to implement?

```
if -F '#{pane_at_top}' '' 'selectp -U'
if -F '#{pane_at_bottom}' '' 'selectp -D'
if -F '#{pane_at_left}' '' 'selectp -L'
if -F '#{pane_at_right}' '' 'selectp -R'
```

**Comment by gilgameshskytrooper** [comment]
@nicm, your specific command did not work

**Comment by nicm** [comment]
Works for me.

**Comment by gilgameshskytrooper** [comment]
Here is a demo of me trying to use these settings:

[https://youtu.be/uRoqXGemiN8](https://youtu.be/uRoqXGemiN8)

**Comment by gilgameshskytrooper** [comment]
It's still allowing `prefix-up` to go from the top pane to the bottom pane

**Comment by nicm** [comment]
tmux version?

**Comment by gilgameshskytrooper** [comment]
```
$tmux -V
2.6
```

Also found this question [here](https://unix.stackexchange.com/questions/215688/tmux-select-pane-ldur-command-disable-auto-cycling-behavior), with no answers:

**Comment by nicm** [comment]
What exactly did you put in .tmux.conf?

**Comment by gilgameshskytrooper** [comment]
My environment:
macOS: 10.13.1
Terminal: iTerm2 (Not using native tmux capabilities)
tmux: 2.6 (installed via homebrew)

```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-ressurect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# set -g default-terminal 'tmux-256color'
set -g default-terminal 'screen-256color'
set -ga terminal-overrides 'screen-256color:Tc'
set-option -g default-command 'reattach-to-user-namespace -l fish'
set -g mouse on
# bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
# bind -n WheelDownPane select-pane -t= \; send-keys -M
# bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set-option -sg escape-time 10
set -g history-limit 20000
set -g @continuum-restore 'on'
# set -g @continuum-boot 'on'


set-window-option -g mode-keys vi

# bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
# bind-key Escape copy-mode
# bind-key -t vi-copy Escape cancel
# bind-key p paste-buffer
# bind-key -t vi-copy v begin-selection
# bind-key -t vi-copy V select-line
# bind-key -t vi-copy r rectangle-toggle
# bind -t vi-copy y copy-pipe "pbcopy"


if -F '#{pane_at_top}' '' 'selectp -U'
if -F '#{pane_at_bottom}' '' 'selectp -D'
if -F '#{pane_at_left}' '' 'selectp -L'
if -F '#{pane_at_right}' '' 'selectp -R'

run '~/.tmux/plugins/tpm/tpm'
```

**Comment by nicm** [comment]
You need to bind the commands to the keys you want to use to move between
panes.

On 14 Nov 2017 6:15 pm, "Andrew Lee" <notifications@github.com> wrote:

My environment:
macOS: 10.13.1
Terminal: iTerm2 (Not using native tmux capabilities)
tmux: 2.6 (installed via homebrew)

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-ressurect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# set -g default-terminal 'tmux-256color'
set -g default-terminal 'screen-256color'
set -ga terminal-overrides 'screen-256color:Tc'
set-option -g default-command 'reattach-to-user-namespace -l fish'
set -g mouse on
# bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys
-M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=;
copy-mode -e; send-keys -M'"
# bind -n WheelDownPane select-pane -t= \; send-keys -M
# bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set-option -sg escape-time 10
set -g history-limit 20000
set -g @continuum-restore 'on'
# set -g @continuum-boot 'on'


set-window-option -g mode-keys vi

# bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
# bind-key Escape copy-mode
# bind-key -t vi-copy Escape cancel
# bind-key p paste-buffer
# bind-key -t vi-copy v begin-selection
# bind-key -t vi-copy V select-line
# bind-key -t vi-copy r rectangle-toggle
# bind -t vi-copy y copy-pipe "pbcopy"


if -F '#{pane_at_top}' '' 'selectp -U'
if -F '#{pane_at_bottom}' '' 'selectp -D'
if -F '#{pane_at_left}' '' 'selectp -L'
if -F '#{pane_at_right}' '' 'selectp -R'

run '~/.tmux/plugins/tpm/tpm'

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1158#issuecomment-344348694>, or mute
the thread

**Comment by gilgameshskytrooper** [comment]
I'm not particularly great at reading the tmux man docs, but I found a working solution using shell commands.

Thanks for your help @nicm 

For anyone interested in a working solution, Just add this to your `~/.tmux.conf`.

```
unbind Up     
unbind Down   
unbind Right   
unbind Left  
bind Up run-shell "if [ ! $(tmux display-message -p '#{pane_at_top}') == 1 ]; then tmux select-pane -U; fi"
bind Down run-shell "if [ ! $(tmux display-message -p '#{pane_at_bottom}') == 1 ] ; then tmux select-pane -D; fi"
bind Right run-shell "if [ ! $(tmux display-message -p '#{pane_at_right}') == 1 ]; then tmux select-pane -R; fi"
bind Left run-shell "if [ ! $(tmux display-message -p '#{pane_at_left}') ]; then tmux select-pane -L; fi"
```

**Comment by rofrol** [comment]
@gilgameshskytrooper default-shell does not set it for run-shell. You need to run like this:

`run-shell 'bash "some command"'`
