### ISSUE TITLE
When a tmux process dies via signal, close/detach hooks don't run

### ISSUE THREAD

**Issue by lharding** [tmux/tmux#1174]
### A brief description of the problem with steps to reproduce
1. Set a session-close hook: `set-hook -g client-detached run-shell "touch /tmp/it-got-closed"`
2. Start a `tmux` session.
3. Kill the session by sending that `tmux` process `SIGHUP`/`SIGTERM`/etc
4. Hooks don't run.

Killing via `tmux kill-session ...` or exiting the wrapped shell runs the hooks correctly.

### Your terminal, and $TERM inside and outside of tmux
Terminal is `rxvt-unicode` from the Arch linux package. `TERM=rxvt-unicode-256color`

### Output of `uname -sp && tmux -V && echo $TERM`

```
Linux unknown
tmux 2.6
screen
```

Thanks!

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1730903/x.diff.txt)

**Comment by systemmonkey42** [comment]
Any change on this?
client-detached hooks are not running if the terminal window is closed while a session is attached.

Note that 'tmux list-sessions' clearly shows the session goes from attached to unattached, but the hook is not triggerred.
(In my case, the hook runs a shell script, which is simply not called when connection is lost, or the window is closed instead of manually detaching)
