### ISSUE TITLE
S-Down binding not working.

### ISSUE THREAD

**Issue by codybuell** [tmux/tmux#1175]
Shift-Down binding does not work or runs the binding for Shift-Up.

Platform: OSX
Terminal: iTerm2 build 3.1.5
TMUX: 2.6 installed via homebrew
TERM: xterm-256color / screen (outside and in tmux respectively)

Steps to reproduce:

  1. run `tmux -Ltest -f/dev/null -vvv new`
  2. create several new windows
  3. create mapping `bind-key -n S-Down previous-window`
  4. S-Down mapping does not work.
  5. create mapping `bind-key -n S-Up next-window`
  6. S-Up mapping works as expected, S-Down mapping now runs S-Up mapping (next-window)

Outside of tmux output from `cat` for S-Down:

`^[[1;2B`

Outside of tmux output from `cat` for S-Up:

`^[[1;2A`

Inside of tmux output from `cat` for S-Down:

`^[[1;2A`

Inside of tmux output from `cat` for S-Up:

`^[[1;2A`

Quick fix of `set -as terminal-overrides ',st*:kind@:kri@'` as mentioned in #1105 not working.

[tmux-server-38187.log](https://github.com/tmux/tmux/files/1515719/tmux-server-38187.log)

**Comment by codybuell** [comment]
Building from latest in Github resolves the issue.

**Comment by ivladak** [comment]
2.6 is still the latest release (and thus has this bug). Looks like  db44151a3747ac66a45b2f730b0f9919172e2a75 is the commit that fixes it. 

I was going to suggest backporting it to the release branch, but then I learned that there's no such thing.

This bug is not that big a deal, but I thought I'd let you know that people are still hitting it. And probably more will be hitting it over time as distributions adopt newer releases (the bug was introduced shortly before 2.6). 

I started binding things to S-up and S-down after reading this post: http://stahlke.org/dan/tmux-nested/ so it might be somewhat popular.
