### ISSUE TITLE
Feature request: Option to automatically change to window with bell or activity marker

### ISSUE THREAD

**Issue by SpikePy** [tmux/tmux#1199]
There is a shortcut for

> Move to the next window with a bell or activity marker.  M-n

But there doesn't seem to be a command for executing the same action.

Also it would be awsome to have an option that enables automatical switching to the window/pane that triggered the bell or activity. This would be realy helpful for tailing multiple logs.

**Comment by nicm** [comment]
There is no way to have a key binding without a command, look at list-keys.


On 18 Dec 2017 1:25 pm, "SpikePy" <notifications@github.com> wrote:

There is a shortcut for

Move to the next window with a bell or activity marker. M-n

But there doesn't seem to be a command for executing the same action.

Also it would be awsome to have an option that enables automatical
switching to the window/pane that triggered the bell or activity. This
would be realy helpful for tailing multiple logs.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1199>, or mute the thread

**Comment by SpikePy** [comment]
Thanks for the advice. The command is nowhere documented but thanks to you I found out it's

`:next-window -a`

Maybe it should be added to the man-pages?

**Comment by nicm** [comment]
next-window was replaced by select-window IIRC.

**Comment by SpikePy** [comment]
I found a solution for my request by binding a hook to a key 

`# follow activity`
`bind f set-hook alert-activity 'next-window -a'`
`# unfollow`
`bind F set-hook -u alert-activity`

But wouldn't it be nice to have such functionality out of the box via a option in .tmux.conf?!

**Comment by nicm** [comment]
No I don't think this is something where we need two ways to do it.
