### ISSUE TITLE
Pane Titles

### ISSUE THREAD

**Issue by 2E0PGS** [tmux/tmux#1227]
We really need a way to set a pane title just like a window title.

Allow the user to hit a key combo to enable pane titles and then another combo to trigger input for setting a title for that selected pane.

Terminator has this function and its useful if I am running many `tail -f logfile` or other bash commands that don't set a title. This also allows for easier viewing at a glance.

This is the main reason I cannot switch from Terminator to Tmux fully. There is just no proper pane titles yet! Yes I have tried using and setting current_pane_command but that is no good. I must be able to assign a name manually for this to be useful.

**Comment by 2E0PGS** [comment]
Terminator example:
![image](https://user-images.githubusercontent.com/15659301/34695329-57c0ba8c-f4c2-11e7-8b80-f58a28ab8ef7.png)

**Comment by nicm** [comment]
select-pane -T

**Comment by 2E0PGS** [comment]
@nicm That does not help. So your suggesting I have to switch around to each pane every time to see it say "bash" in the bottom left or see it say "tail". This does not provide a easy to see overview of whats running at a glance. Also if I am running many tail commands I cannot see which tail is following which logfile since it just shows "tail" in the bottom left not tail -f /var/log...

Also I want the option to name the pane what I want. I can assign more info than just a running programs name without flags. Maybe I have a pane specifically for running general commands so a program name as the pane title is no good if it need to know which one I use as the hotdesk so to speak.

Hopefully this clears things up? Look at my terminator screenshot. It shows a nice overview of whats running and I can name the pane whatever I want. I don't think it would take much to implement this in tmux. It has a way to set a pane title in the border in newer versions but not a way to set that manually.

**Comment by nicm** [comment]
You set it manually with select-pane -T.


On 11 Jan 2018 10:04 am, "Peter Stevenson" <notifications@github.com> wrote:

@nicm <https://github.com/nicm> That does not help. So your suggesting I
have to switch around to each pane every time to see it say "bash" in the
bottom left or see it say "tail". This does not provide a easy to see
overview of whats running at a glance. Also if I am running many tail
commands I cannot see which tail is following which logfile since it just
shows "tail" in the bottom left not tail -f /var/log...

Also I want the option to name the pane what I want. I can assign more info
than just a running programs name without flags. Maybe I have a pane
specifically for running general commands so a program name as the pane
title is no good if it need to know which one I use as the hotdesk so to
speak.

Hopefully this clears things up? Look at my terminator screenshot. It shows
a nice overview of whats running and I can name the pane whatever I want. I
don't think it would take much to implement this in tmux. It has a way to
set a pane title in the border in newer versions but not a way to set that
manually.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1227#issuecomment-356886295>, or mute
the thread

**Comment by nicm** [comment]
Or change pane-border-format if you want to show something different.

**Comment by 2E0PGS** [comment]
![image](https://user-images.githubusercontent.com/15659301/34820498-9d058f6c-f6b8-11e7-8614-0ff732d383c8.png)
What version of tmux are you using?

**Comment by 2E0PGS** [comment]
Brilliant that's working now. Had 2.3 not 2.6. I tried on 2.6 before submitting this but didn't see anything anywhere in the code for rename pane. Perhaps a shortcut key should be set by default for this.
Also it requires disabling `set -g pane-border-format "#P: #{pane_current_command` in config if present.

Cheers!

**Comment by 2E0PGS** [comment]
Is it possible to add a keybind for this manually? I tried adding one but don't know the way to trigger user input for the title. I can set a keybind for a static title name but need to know the way to grab user input. 
Something like `bind-key t select-pane -T ${user_input}`.

UPDATE just found a way to do this by modifying this users post: https://unix.stackexchange.com/a/269542
`bind-key t command-prompt "select-pane -T '%%'"`

**Comment by 2E0PGS** [comment]
So I now have all the functionally I needed ref pane titles. Thanks!
