### ISSUE TITLE
terminfo tmux-256color missing some tmux supported entries

### ISSUE THREAD

**Issue by piec** [tmux/tmux#1236]
Hi,

While investigating True Color support on my platform I noticed that some escape sequences supported by tmux aren't present in ncurses' terminfo section for tmux-256color.
I made a tiny script to extract supported entries from tmux's source and check the existence in terminfo (using tput): https://gist.github.com/piec/90394e21886fee701aadbf235c5df09e

Some may be useful to add:
* E3: clear scrollback - CSI Ps J, Ps = 3 (ED)
* hpa: Cursor Character Absolute - CSI Ps G (CHA)
* vpa: Cursor Backward Ps Times - CSI Ps d (VPA) ~~CSI Ps D (CUB)~~
* indn: Scroll up Ps lines. CSI Ps S (SU)
* invis: invisible character attribute - CSI Pm m, Ps = 8 (SGR)
* XT boolean?
* Tc - but apparently Thomas Dickey has plans to integrate it already

How should we proceed? should we submit a patch to ncurses?

Cheers

---
**Platform**
Arch Linux up to date
tmux 2.6 / tmux git master 06684c93de3e5fbc01bf6749c62defffaa07c52c
terminfo 2017-11-18

**Comment by nicm** [comment]
vpa is not CUB it is VPA which is CSI d.

XT is "XTerm Title" which means it supports the xterm title setting sequences, tmux has support in as much as it can usefully support them.

I suggest you don't mention Tc because it is an extension and RGB colour has already been discussed to death.

I personally don't think any of the others are useful enough to change but if you want to you need to make a patch against the latest terminfo.src and send it to Thomas or to ncurses-dev.

The tmux entry is based on screen, so if screen supports them too (probably true for vpa/hpa, maybe invis and XT, probably not for indn, E3) it would be better to change the screen entry and tmux will inherit it. Otherwise it will need to go into the tmux entry.

**Comment by piec** [comment]
Oops yes I got confused with CSI Ps d / CSI Ps D

Thanks for your feedback, I think I'll submit a patch to ncurses with updated screen (for those supported) and tmux entries

**Comment by nicm** [comment]
OK great.
