### ISSUE TITLE
Questiong: About status bar

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#1258]
Hi, 

This is more of a question and if this is possible to be done at all.

If I have ```#I:#W``` in the status-current-format , if by any chance current window name changes , would it be possible to only display output of ```#W``` in the status bar ? and not to display current window index  as well as ```#W```. 

e.g: This is how it looks normally [0:] with out any window name changes, now lets say I ssh to my host  my status bar will change to [0:hostname], but what I want if possible to be [hostanme] with out 0: . Once I exit the remote host it should go back to [0:]. 

I hope that makes sense.
Thanks.

**Comment by ThomasAdam** [comment]
I'd suggest you get your shell to change/clear the window title.

**Comment by nicm** [comment]
You can do this with something like (not tested):

#{?window_name,#{window_index}:#{window_name},#{window_index}}





On 14 Feb 2018 4:19 am, "lanox" <notifications@github.com> wrote:

Hi,

This is more of a question and if this is possible to be done at all.

If I have #I:#W in the status-current-format , if by any chance current
window name changes , would it be possible to only display output of #W in
the status bar ? and not to display current window index as well as #W.

e.g: This is how it looks normally [0:] with out any window name changes,
now lets say I ssh to my host my status bar will change to [0:hostname],
but what I want if possible to be [hostanme] with out 0: . Once I exit the
remote host it should go back to [0:].

I hope that makes sense.
Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1258>, or mute the thread

**Comment by nicm** [comment]
Great.

**Comment by lanox** [comment]
@ncim sorry to bother you with another silly question, is it possible to add a blank line above tmux status bar. 
e.g
```
bash>$ (cursor)

1: bash*  2: bash-  3: vim-
```
instead of 
```
bash>$ (cursor)
1: bash*  2: bash-  3: vim-
```

**Comment by nicm** [comment]
No it is not possible.

**Comment by lanox** [comment]
@nicm thanks ... 

would it be possible to request as feature ?

**Comment by nicm** [comment]
Well, I'm not going to write it. We are working towards allowing status lines with multiple lines, so you might be able to do it once that is finished, but it won't be soon.

**Comment by lanox** [comment]
fair enough. @nicm thanks for the quick responds.
