### ISSUE TITLE
Feature request: argument to default to vi for all settings otherwise set to emacs

### ISSUE THREAD

**Issue by AquaL1te** [tmux/tmux#1280]
When I'm on a different system and install tmux to do some stuff quicker, I always get confronted with the default emacs behavior which is quite different. Which means either rsync a config that changes the behavior to vi or manually set status-keys and mode-keys to vi.

It would be awesome to have a quick fix for this, like having a command line switch to switch to vi instead of emacs behavior. For example, starting tmux like this `tmux --vi`, which then would switch emacs defaults to vi.

**Comment by nicm** [comment]
VISUAL=vi tmux

On 6 Mar 2018 8:07 am, "Kees de Jong" <notifications@github.com> wrote:

When I'm on a different system and install tmux to do some stuff quicker, I
always get confronted with the default emacs behavior which is quite
different. Which means either rsync a config that changes the behavior to
vi or manually set status-keys and mode-keys to vi.

It would be awesome to have a quick fix for this, like having a command
line switch to switch to vi instead of emacs behavior. For example,
starting tmux like this tmux --vi, which then would switch emacs defaults
to vi.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/1280>, or mute the thread

**Comment by AquaL1te** [comment]
Perfect! Missed that one in the manual page.
