### ISSUE TITLE
Display invalid UTF8 characters as �

### ISSUE THREAD

**Issue by tardypad** [tmux/tmux#1286]
```
ArchLinux
tmux 2.6
termite as terminal
TERM=xterm-256color outside tmux
TERM=tmux-256color inside tmux
LANG=en_US.UTF-8
```
Trying to display the following non UTF-8 text file
[non_utf8.txt](https://github.com/tmux/tmux/files/1819323/non_utf8.txt)�

Directly in termite, the non UTF-8 character is displayed as �
```
$ cat non_utf8.txt 
CAF� LATTE
```
If I do the same in tmux within termite, it is just ignored
```
$ cat non_utf8.txt 
CAFLATTE
```

Here is the log file from `tmux -vv -Ltest -f/dev/null new`
[tmux-server-18204.log](https://github.com/tmux/tmux/files/1819349/tmux-server-18204.log)

I am not sure what is responsible for rendering that character is such a way.
So I don't know if this is a bug or a current limitation in tmux.
In any case, would it be possible for tmux to have that same display of �?

This would be really useful to spot encoding issues
(for an example of why I would have wanted this today)

**Comment by nicm** [comment]
tmux only supports UTF-8, non-UTF-8 characters are discarded.

**Comment by tardypad** [comment]
For the record, my colleague has the same behavior on MacOS, tmux 2.6, Terminal
but there instead of '�' it shows a '?' (might be font thing)

**Comment by tardypad** [comment]
My question is then: Is it possible to display them as � or such, instead of discarding them?

**Comment by nicm** [comment]
No it is not.

**Comment by tardypad** [comment]
For more background, here is the problem that happened to me today
I was logging some JSON data and displaying it the terminal
such kind of non UTF8 characters were thus discarded in the display (which I didn't know and it's not obvious that this is the behavior)
as a result I failed to spot the encoding issue in the data

Sure we manage to spot it with further investigation and tools
but such display would have been helping

**Comment by tardypad** [comment]
OK if it's not possible I understand

Is it possible at least to document this somewhere in the manual
I couldn't find any explanation of this behavior anywhere
I indeed read that tmux only supports UTF8 now but that wasn't obvious to me that other characters would be simpley discarded from the display

**Comment by nicm** [comment]
You can't dump just anything to the terminal and expect it to behave in a particular way or for two different terminals to behave in the same way. It is not a sensible way of trying to detect encoding problems.

If you had sent your file to rxvt-unicode or xterm instead of tmux it may well have displayed fine and you wouldn't have spotted it wasn't UTF-8 there either.

tmux has always dropped anything it doesn't understand, which is how invalid escape sequences have always been handled. I don't have particularly strong feelings about whether we should also drop invalid UTF-8 or substitute the replacement character. They are both wrong so it seems that it hardly matters, and I don't know if we particularly want to change.

**Comment by nicm** [comment]
I think I might change it as part of another change I have had around for a bit, but I need to think about it.

**Comment by tardypad** [comment]
OK I understand
Thanks so far for the explanations and the quick responses
