### ISSUE TITLE
SSH ControlPersist not keeping connections open when launched with 'new-window'

### ISSUE THREAD

**Issue by ElijahLynn** [tmux/tmux#1300]
I am actually using Tmux Cluster and moving this issue here, https://github.com/davidscholberg/tmux-cluster/issues/17. 

Tmux 2.6
Given the following ~/.ssh/config:
```
ControlMaster                  auto                  
ControlPath                    /tmp/ssh_mux_%h_%p_%r 
ControlPersist                 4h   
```
Within a tmux session, run the tmux command `new-window "ssh <server>"`. Then after the connection is established, close the pane or window or type `exit`. The window closes. The connection stored in /tmp/ssh_mux_* is also deleted. It should not be deleted. I think that SSH isn't exiting properly in this case. It may not be a tmux issue per say but this is where I am at right now.

**Comment by nicm** [comment]
This seems unlikely to be a tmux issue so I don't know why you are reporting it here instead of to ssh.

But I think you may just be misunderstanding how ssh works. It is up to you to keep the first ssh process which manages the control socket running; if it exits, the socket will be removed. It is not a daemon. It all seems to work correctly for me:

If I run one ssh to a host and then type exit in the first, ssh will exit and remove the control socket.

If I run two ssh to the same host and then type exit in the first, the first ssh will remain running until the second ssh is also exited, then it will remove the socket.

If I run two ssh to the same host and then force the first ssh to exit by killing the tmux pane (or by sending it a signal or whatever), the second ssh will also exit saying "Shared connection closed".
