### ISSUE TITLE
tmux breaks ghci line editing

### ISSUE THREAD

**Issue by sjfloat** [tmux/tmux#131]
I use vi mode in ghci

    $ cat ~/.haskeline 
    editMode: Vi

Normally, the 'k' key moves up in the command line history, as expected.

But when running ghci in tmux, entering the 'k' key moves up one time, after which it breaks out of command mode and emits the 'k' key in edit mode. In the example below, ':q' is the previous command in the history:

    Prelude> kkkkkkk:q

As you can see, the first 'k' produces ':q' as it should, but subsequent 'k' keys are not interpretted as the command to 'move up one line'.

Note that ghci uses libedit for command line editing (vs readline, for example).

**Comment by sjfloat** [comment]
Note that, extremely infrequently, this works correctly.

**Comment by sjfloat** [comment]
I managed to capture logs from a time that worked (only once so far) and from a time it didn't.

I tried to attach logs here, but got

    Something went really wrong, and we can’t process that file. 

But I noticed that the time it worked correctly, it treated the escape key and the 'k' keys as different keys instead of as one as it usually does.

**Comment by sjfloat** [comment]
I have found what may be a workaround for this problem. Reducing the 'escape-time' setting seems to help with this:

    set escape-time 100

**Comment by nicm** [comment]
Are you sure you are exactly describing what you are doing? escape-time only affects the Escape key and there is no mention of it in your description.

Are you JUST pressing k, or are you pressing Escape then k?

**Comment by sjfloat** [comment]
Yes, I hit escape to break out of command mode, then I hit 'k'. The odd thing is that, when it fails, it works exactly once and then kicks me back into edit mode. I can confirm that reducing 'escape-time'  improves matters, as I tested it on a number of different and disparate systems. I did some more testing and I find that if I pause for an impractically long time after hitting escape, it seems to work OK too.

**Comment by nicm** [comment]
If you press Escape (\033) then k within tmux escape-time, tmux will send them both together as M-k (\033k). Presumably, libedit is then seeing that as M-k rather than Escape then k. You need to wait long enough after pressing Escape and before pressing k for both escape-time to expire and tmux send the Escape and for libedit to recognise that they are separate keys.

If you set escape-time to 0 tmux will send Escape immediately and you will only be subject to whatever delay libedit uses to detect M-k, but you may find tmux itself will no longer recognise keys pressed with Meta (usually it is fine on a local machine or a fast network though).

**Comment by sjfloat** [comment]
Yes, that's what seems to be happening. 100ms seems workable.

While you may not want to change code or config defaults, it might be good if this could be documented somehow to save someone some frustration and lost time.

**Comment by nicm** [comment]
This is how every program works. But I don't mind adding an FAQ entry if you want to write one.

**Comment by sjfloat** [comment]
Yeah, I'll probably do that. Let me think on it a little; my particular
scenario is probably a little too specific to be very useful.

On Tue, Oct 6, 2015 at 9:43 AM, Nicholas Marriott <notifications@github.com>
wrote:

> This is how every program works. But I don't mind adding an FAQ entry if
> you want to write one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmux/tmux/issues/131#issuecomment-145860111>.
>



-- 
"I have delusions of grandeur. I believe myself to be Steve Jones"

**Comment by sdeleon28** [comment]
I've added `set escape-time 0` to `.tmux.conf` and it still has a very noticeable lag. I find this problem particularly annoying because my muscle memory starts typing normal mode commands immediately after hitting `<Esc>`. I've only been using Vim for a couple of months, I can only imagine how much of a turn off this must be for someone who's been using Vim for 20 years. Is there really no way to eliminate the lag entirely? This doesn't happen with vanilla Vim + tmux.

**Comment by jamen** [comment]
@sdeleon28 It wasn't resetting for me either, but after some digging I realized tmux is tricky to actually restart:

```sh
tmux source-file ~/.tmux.conf
```

This did the trick for me.  [Here is a reddit post](https://www.reddit.com/r/vim/comments/40257u/delay_on_esc_with_tmux_and_vim/) that has various methods and may help.
