### ISSUE TITLE
tmux changes session name from /etc/bashrc from remote host

### ISSUE THREAD

**Issue by lanox** [tmux/tmux#132]
Hi i came across where tmux changes session name automatically from /etc/bashrc from remote host.

Basically whenever  i ssh to virtualbox CentOS 7 my tmux session name will inherit the PS1 from /etc/bashrc.  
I have tested this by removing everything from /etc/bashrc, then ssh to remote host again and session name will remain the same.

I did notice that /etc/bashrc sets PS1 for various things including screen*, which i am sure that is the PS1 that my tmux inherits.

 If i make any changes to  PROMPT line below and ssh to remote host my tmux session name will change depending on what i change to PROMPT line i made .

```
screen*)
      if [ -e /etc/sysconfig/bash-prompt-screen ]; then
          PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
      else
          PROMPT_COMMAND='printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'
      fi
      ;;
    *)
      [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
      ;;
    esac
  fi
```
Another thing i have find out is if i am running tmux but my TERM is set to xterm-256color instead of screen-256color it will not use PS1 from /etc/bashrc/ which kind of makes sense as /etc/bashrc/ doesn't containing anything for xterm-256color.

I am using mac os x El Capitan wiht Iterm2 nightly build.

Hope there is enough information there.

**Comment by nicm** [comment]
If you don't want your profiles to rename tmux windows I suggest you either remove that bit from your PS1 or turn off allow-rename in .tmux.conf.

**Comment by lanox** [comment]
hi @nicm well removing PS1 from every remote host is kind of not practice at all ?.

Also if i turn of allow-rename it means i cant set any other name to tmux session, is there anything else we can do ?

**Comment by nicm** [comment]
allow-rename only stops programs inside tmux setting the name.

**Comment by lanox** [comment]
@nicm which means that my tmux session name will never change even if i am telling my session name to change with hostname of remote host ?

I am little confused as to why is tmux inheriting the PS from /etc/bshrc from remote host ? isn't that also security issue ?

**Comment by lanox** [comment]
@nicm basically this is what i have set in my .zshrc is the code below, where it changes the session name to hostname. 
```ssh() { for arg; do; if [[ "$arg" != -* ]]; then print -n "\ek${(V)${arg/#*@/}}\e\\" ; break; fi; done; command ssh "$@ ";print -n "\ekzsh\e\\" }```

However as i said above /etc/bashrc from remote host overwrites my definition of session name with its own.

**Comment by nicm** [comment]
tmux can't tell that you want it to work sometimes and sometimes not work. There is bound to be a way to stop CentOS doing this.

-------- Original message --------

**Comment by nicm** [comment]
PS1 and shell profiles are not much to do with tmux but with your shells

**Comment by lanox** [comment]
@ncm I dunno, test it your self and you will see I am pretty sure I am doing everything correct.

My shell Is  zsh my term outside tmux is xterm-256color. When I am in tmux term is screen-256color. Logging to remote host and you will see that s tmux session name becomes as follow.

Username@hostname

Then if you cd in to dirs it also changes to

Username@hostname:/tmp/test/test1

So as you can see session name can become very long.

**Comment by nicm** [comment]
You are confusing session name and window name. And I think you have a fundamental misunderstanding of how ssh and shells work.

There is an escape sequence to change the window name (actually there are several, but you are using \033k).

You have this escape sequence in your prompt on both the Mac and the remote host, but they rename the windows to different things. When you ssh into the remote host, of course it loads the profile on the remote host and that has a different prompt with a different \033k. It is no longer running the same shell as your local host, it is a new shell running on the remote host, with a new profile, and with new stuff in its prompt which sends something completely different to tmux.

There is *no way* for tmux to tell that your want it to to listen to \033k on the local host and not on the remote host. They look the same to tmux, all it sees is \033ksomething, it doesn't know you have run ssh or there is a new shell.

You can do one of these:

- Turn off allow-rename, to stop the remote host renaming the window. This will also turn off the local host renaming it, so you will have to rename them in a different way there perhaps by putting $(tmux renamew whatever) in your PS1 instead of using \033k.

- FIx or remove your shell profiles on the remote hosts to not do this.

- Put up with it.

**Comment by lanox** [comment]
@nicm Thanks so much for clearing few a few things up. You are most likely right in saying that my understanding is somewhat limited.

Last question (i hope),  lets say if i don't have any manual configuration for tmux or any shell,
is it normal for tmux to append everything in session name (like in screenshot)?
<img width="851" alt="screen shot 2015-10-07 at 9 40 16 pm" src="https://cloud.githubusercontent.com/assets/7599183/10335396/1d5dd1fa-6d3c-11e5-8336-4189d16e9892.png">

If that is a default behaviour i kind of think that is wrong, reason i say this is purely on the bases that the session name will take most of the tmux status bar. 

(NOTE: In screenshot above I have removed the ssh script I had.)

Sorry for taking up to much of your time just tying to understand it.

Also, do you mind if I ask if you could point me in a direction where I can work it out how to set tmux to rename ssh session name automatically when I ssh to remote host.

Thank you very much.

**Comment by nicm** [comment]
No, tmux is not doing this, your shell is doing it. If you turn allow-rename off it will not be able to.

**Comment by lanox** [comment]
Cheers I get what you are saying, I read you reply few times and it make sense what you are saying...

**Comment by komodin** [comment]
@lanox hi, have you solved this? how? thanks

**Comment by lanox** [comment]
@komodin  pretty much what nicm, said and wrote a wrapper around ssh to disaplay server name wehn sshing to remote host.

**Comment by faicker** [comment]
In the remote ssh host, as the /etc/bashrc notices, you can touch a file /etc/sysconfig/bash-prompt-screen and chmod +x to replace PROMPT_COMMAND var.
