### ISSUE TITLE
Tmux text highlighting for special keywords like error, warning, etc

### ISSUE THREAD

**Issue by rmacknojia** [tmux/tmux#1363]
I found some patch on the following link to enable it.
https://gist.github.com/pxsta/5f86092eec0d611c2770

It is something already available? This could be a nice feature.

**Comment by c02y** [comment]
This feature is really useful, if the patch is not suitable for tmux, any plan in tmux?

**Comment by nicm** [comment]
Don't have any at the moment. Would like to see regex search/highlight in copy mode rather than this TBH.

**Comment by c02y** [comment]
It is not that convenient.

BTW, why  "This code is not suitable to go in as it is."? I know the patch is old, after some migration I believe it should be working.

**Comment by krader1961** [comment]
It's not suitable because a) the feature does not belong in tmux and b) it isn't sufficiently general. Also, consider how this feature (tmux modifying the display of random text) will interact with IDEs, editors, and tools like `less` which will also be trying to control the display of the text. Which one takes precedence? You might counter that if the text has any attributes at all (e.g., a color change) then tmux should leave it as is and only apply its coloring if the text has no attributes. Same problem. How does tmux know the app did not intend to present the text with the default attributes?

@c02y I see you're still making similarly ill-considered comments in the [fish shell](https://github.com/fish-shell/fish-shell/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3Ac02y+) project.

**Comment by krader1961** [comment]
I especially love this most recent [fish shell question](https://github.com/fish-shell/fish-shell/issues/5774) by @c02y. In my four decades of programming I can't recall ever wanting to know if the CLI args contained zero, one, or more options/flags (e.g., `-h`) independent of other CLI arguments. There may be a situation where knowing that would be useful but it is so rare that it isn't worth special-casing in a command like the fish `argparse` command that I implemented.

**Comment by krader1961** [comment]
@nicm Consider this fish shell [issue](https://github.com/fish-shell/fish-shell/issues/5682) opened by @c02y. This person made me do a head-desk more than once when I was actively contributing to the fish shell project. I see they are still an idiot. Any issue or comment from @c02y should prima facie be assumed to be incorrect or ill-advised.

**Comment by devenv** [comment]
@krader1961 How all of this is relevant to this issue? You are pulling a classic ad hominem...
"the feature does not belong in tmux " - why not?
Current solutions are tools like grc and similar but that's really inconvenient, highlighting something by a key-bind sounds very tmuxy IMO...
Regarding the color overrides - for my needs I need tmux to override everything else, not sure why anyone would want it otherwise but it can be configurable I guess?

**Comment by krader1961** [comment]
@devenv You apparently did not actually read, for comprehension, my first comment. I explained why this feature does not belong in tmux outside of special modes such as "copy" mode. It should never be enabled for the presentation of output in the normal view.

Also, I did not employ an ad hominem attack. I cited several examples where the person I was criticizing exhibited poor knowledge or aesthetics related to computer interfaces. That is relevant to their comment in this issue. An ad hominem attack is where someone argues "person x should be ignored on subject y because they did unacceptable thing z." Substitute random nouns for `x`, `y`, and `z`.

**Comment by devenv** [comment]
"I see they are still an idiot. Any issue or comment from @c02y should prima facie be assumed to be incorrect or ill-advised." based on his past actions - is not ad hominem? ok...
I don't see any issue with what he wrote in this thread, and I couldn't care less about what he wrote in others...
This feature is legit IMO, I explained why.

**Comment by krader1961** [comment]
@devenv Just to be clear... An example of an ad hominem response is something like "@c02y should be ignored about tmux coloring random text because they beat their dog." Notice the final clause. It has nothing to do with this issue. Even if it was true that would not invalidate their comments on this issue which should be evaluated on their own merits. I did that. I pointed out their stupidity in other, related, projects because that is relevant.

**Comment by krader1961** [comment]
@devenv  You say

> This feature is legit IMO, I explained why.

But you wrote

> Why is it closed? It's a killer feature, can we reopen please? :)

Sorry, but I don't consider that to be an explanation why you this feature should be implemented.

**Comment by devenv** [comment]
Again, you are making another fallacy, you quoted two of my unrelated (to each other) comments, implying that that was my explanation for legitimacy. While obviously, I meant my other comment.
I don't have time for bickering on Github, it's just not my cup of tea.

@nicm this issue should be open at least for conversation IMO...

**Comment by nicm** [comment]
The code doesn't have any license and copyright text so I can't take it, and the author did not submit it themselves so I can ask them for it or for any other changes (for a start it needs to more closely match tmux's code style, and I think it should be an array option now not a new option type).

**Comment by nicm** [comment]
I also don't like the way this applies to text on input and doesn't reevaluate if you change the highlight options.

I'd rather see regex searching in copy mode if someone wanted to do something like this.

**Comment by devenv** [comment]
My problem with copy mode in this context is that it's paused, this won't solve my needs... e.g. nested tmuxes with running logs...
I'll try to make a PR if anyone else (more familiar with tmux code base and C in general :) ) won't take it...
If you agree that it's something that we want in tmux...

**Comment by nicm** [comment]
If you want this to move forward, either write new code yourself or contact the original author for permission, tidy up this diff and open a PR. I think it should use an array option (it can parse it into regexs when it is changed) so that will also at least need to change. And I would like it if it reapplies the highlights when they are changed, that would be complicated however. Also I would like regex searching in copy mode so I can jump between highlights with a single key, by for example binding a key to "copy-mode \; send -X search-backward #{highlights[0]}".

**Comment by c02y** [comment]
@devenv  As for "ad hominem attack" from @krader1961 , I really do not think he is employing any ad hominem attack, maybe he is just a perfectionist, he was even criticizing me for typos or grammar mistakes in my comments/posts. But I'm totally OK with his criticisms, those criticisms only make me better.

@krader1961 Since you got experience of four decades of programming, you must have a lot of "knowledge or aesthetics related to computer interfaces", but it is unfair to wish others to do things with your mind. Since you are over 40, you must meet a lot people in your life or on the Internet, you should already know how to handle those people who are "idiot" to you. And doing a head-desk because of the things/people you don't like is not good for your health, next time you encounter that I make any "incorrect or ill-advised" comment/post, please just ignore me, of cause, criticisms are always welcome.

Anyway, now I know the reason why this feature is not implement, thanks  for all.

And it got two solutions if anyone like this feature:
1. get the permission of the patch(or write it on your own) and write a PR
2. bind a key in tmux to search the keywords manually

**Comment by devenv** [comment]
License added :)
https://gist.github.com/pxsta/5f86092eec0d611c2770

**Comment by pxsta** [comment]
Thank you for your discuss.

I know it's better to implement this feature in a terminal such as putty, rather than in the tmux.
However I have meny machines(at home, workplace, temporary office, etc.) which can connect to my server and it's too much bother to install my modified putty on all machines.
So I implemented the feature in the tmux running on the server for my own use four years ago.

I'm sorry but I don't have enough time to write a PR.
Additionally, I'm not sure this is the best way to highlight the text.

I added the license and please feel free to use it.
thanks.
