### ISSUE TITLE
source-file not working in linux

### ISSUE THREAD

**Issue by karakays** [tmux/tmux#1413]
I am using tmux for both in Ubuntu 18.04 (tmux v2.6) and OSX High Sierra (tmux v2.7). Both environments share the same base tmux.conf file. OS-specific configuration is kept in separate files and loaded as shown.

```
# tmux.conf file
if-shell "echo $OSTYPE | grep darwin" "source-file ~/.tmux/.tmux.conf.osx"
if-shell "echo $OSTYPE | grep linux" "source-file ~/.tmux/.tmux.conf.linux"
```
Although source-file is loaded osx configuration, the same is not working in linux. I can confirm base conf file is loaded but tmux.conf.linux is not.

Running if-shell command from terminal loads the config file properly, but it still does not work when invoked from the config file itself.
```
$ tmux if-shell "echo $OSTYPE | grep linux" "source-file ~/.tmux/.tmux.conf.linux"
```

**Comment by krader1961** [comment]
How is `OSTYPE` set? That's not a typical env var. Have you confirmed it is set to the expected value on Linux? What does `:display-message -p $OSTYPE` show?

Also, FWIW, that's a rather expensive way to do that test as it involves two commands and a pipeline. If nothing else you should do `grep -q` since you don't need or really want the output of grep just its exit status. But it would be more efficient to do something like `if-shell 'test "$OSTYPE" = linux' ...`

**Comment by karakays** [comment]
```
~ $ echo $OSTYPE 
linux-gnu
~ $ echo $OSTYPE | grep linux
linux-gnu
~ $ tmux if-shell "echo $OSTYPE | grep darwin" "run-shell \"echo darwin\""
~ $ 
~ $ tmux if-shell "echo $OSTYPE | grep linux" "run-shell \"echo linux\""
linux
```
According to the output above, if-shell works.
I tried grep -q as suggested, but it did not help.

I just realized that running it from terminal loads the config file properly, but it still does not work when invoked from the config file itself.
```
$ tmux if-shell "echo $OSTYPE | grep linux" "source-file ~/.tmux/.tmux.conf.linux"
```

**Comment by nicm** [comment]
OSTYPE is probably set in some shell profile that if-shell does not load. Why not use uname -s?

**Comment by nicm** [comment]
~~~~
if-shell 'test "`uname -s`" = "Linux"' "blah blah"

**Comment by nicm** [comment]
Looks like OSTYPE is a bashism:
~~~~

**Comment by krader1961** [comment]
@karakays Your mental model of how UNIX env vars work in general appears to be wrong. Too, how they interact with tmux is incorrect. Within a tmux session you should do what I suggested. Get a tmux prompt by typing [ctrl-a]: (or whatever your prefix char is) then type `display-message -p $OSTYPE`. Consider what happens when you did this:

```
tmux if-shell "echo $OSTYPE | grep linux" "run-shell \"echo linux\""
```

Due to the use of double-quotes your current shell will replace `$OSTYPE` with the value it currently has in that shell. Which is not necessarily the same value the tmux server has for that var and which will be included in the environment of any subshells the tmux server runs.

Here is an experiment which might help you understand how this all ties together. Start with no tmux server running: `tmux kill-server`. Open two terminals. In both windows type `echo $OSTYPE` to make sure it is set to the same value.

In the first window start a tmux session with a different value for `OSTYPE`:

```
env OSTYPE=wtf tmux
```

In the tmux session in terminal 1 type `echo $OSTYPE` it should say `wtf`. Now type [ctrl-a]: then `display-msg -p $LOGNAME` . That should say `wtf`. That's because the tmux server got the value from the `env ...` environment and passed it to the interactive shell it spawned. Because it was already set that bash subshell did not initialize it to the value you expect.

Now switch to terminal 2 and run the following commands (obviously replace `darwin` with whatever makes sense for your system):

```
tmux if-shell "echo $OSTYPE | grep darwin" 'run-shell "echo $OSTYPE"'
tmux if-shell 'echo $OSTYPE | grep darwin' 'run-shell "echo $OSTYPE"'
tmux if-shell "echo $OSTYPE | grep darwin" "run-shell 'echo $OSTYPE'"
tmux if-shell "echo $OSTYPE | grep darwin" 'display-message -p $OSTYPE'
tmux if-shell 'echo $OSTYPE | grep wtf' 'run-shell "echo $OSTYPE"'
tmux if-shell "echo $OSTYPE | grep wtf" 'display-message -p $OSTYPE'
```

Then ponder how the difference between single and double quotes affects the behavior.

**Comment by karakays** [comment]
thank you for your great explanation, @krader1961 - it was a very sneaky issue for me due to my lack of knowledge here.
