### ISSUE TITLE
tmux scripting no longer works as expected

### ISSUE THREAD

**Issue by ToadJamb** [tmux/tmux#1442]
The following script has very different behavior in version 2.1 (on ubuntu 16.04) than it does in 2.6 (on ubuntu 18.04):

```bash
tmux new -s setup -d
tmux send-keys 'rvm current' C-m
tmux split-window -h -p 66
tmux send-keys 'rvm current' C-m
tmux select-pane -t 1
tmux send-keys 'ruby ~/.vim/bundle/vim_test_runner/test_runner' C-m
tmux split-window -v -p 25
tmux send-keys 'rvm current' C-m
tmux select-pane -t 3
tmux send-keys 'vi main.sh' C-m
```

In 2.4, this results in output that you would expect if the operations were processed synchronously (more or less). For instance, the last `send-keys` call results in `main.sh` being opened in vim inside the 3rd pane (I have tmux configured to use a 1-based index).

In 2.6, this script results in the correct number of panes, but they are not sized correctly and ALL `send-keys` commands run in the first pane.

I have tried a number of ways to work around this, but have had little luck. What is the correct way to make scripts of this nature work using 2.6?

**Comment by nicm** [comment]
The way tmux guesses the current session and what pane you want it to use when there is no target did change around a bit in the last few releases.

Your script may work again in 2.7, but I'm not certain because you are creating a new session and if you run this script inside tmux it may guess that the session you want for the subsequent commands is the one with the pane where you are running the script rather than the one you just created.

Anyway, I don't recommend writing scripts like this. You could probably get away with just specifying the session you want on the other commands (tmux send-keys -tsetup: ...), or the best way is to explicitly specify the targets you want using -P and -t:
~~~~
S=$(tmux new -s setup -dP)
tmux send -t$T foo
P=$(tmux splitw -t$S -hP -p66)
tmux send -t$P bar
...
~~~~

**Comment by ToadJamb** [comment]
I think I finally found a solution that does what I'm looking for. I use tmux to script out my dev environment as I work with a lot of different projects with various dependencies. By doing this, I can have my dev environment up and running in a flash with all of the services, ssh sessions, etc. It seems like this is a reasonable use of tmux,

Here is my solution:
```
tmux new -s setup -d
tmux send-keys 'tmux split-window -h -p 66' C-m
tmux send-keys 'tmux select-pane -t 1' C-m
tmux send-keys 'tmux split-window -v -p 25' C-m
tmux send-keys 'tmux send-keys -t 3 "vi main.sh" C-m' C-m
tmux send-keys 'tmux select-pane -t 3' C-m
tmux attach -t setup
```

This does not seem ideal, as I'm using `send-keys` to execute tmux commands, some of which are also `send-keys`, but it does what I'm looking for and appears to work on both 2.1 and 2.6. If this makes sense to you in the context of 2.6 and there's a better way to accomplish it, let me know.

**Comment by chrahunt** [comment]
@ToadJamb, have you seen [tmuxinator](https://github.com/tmuxinator/tmuxinator)?

**Comment by ToadJamb** [comment]
Yes, of course. I had heard about it when I wrote the gem that is actually executing these commands. I created this project years ago and actually explained why it exists in addition to tmuxinator. My explanation is at the very bottom of the [readme](https://bitbucket.org/ToadJamb/gems_mucks/src/default/README.md).

The changes I outlined in my 'solution' are definitely sub-optimal, as different pieces of my layouts now have to know far more than I'd like them to about what the layout looks like (it appears that my nested `send-keys` calls need a target to be specified), but I have sorted most of it out.
