### ISSUE TITLE
Physical escape key and Meta keys seem to conflict

### ISSUE THREAD

**Issue by aep2** [tmux/tmux#1447]
Behavior observed in tmux versions - 2.4, 2.5, 2.6. I did not try 2.7 but would expect . Tried with 3 different keyboards on 3 separate systems (either Ubuntu 16.04)

Steps to reproduce

- apt-get install tmux on Ubuntu 18.04
- create ~/.tmux.conf
- put **bind-key -n M-h         resize-pane -L** (Idea to is to use Meta key (ALT) + hjkl to resize pane.
- launch using tmux
- Ctrl + B (prefix) + % to create a vertical pane
- Switch to the right most pane
- Hit "Escape" Key + H.
- The right most pane will be resized and increase in width to the left

It seems that the "Escape" key + "h" performs a similar function as Alt + "h" except that pressing and holding alt and pressing h can move the pane left multiple times whereas "Escape" key + "h only moves it once. Unsure whether this is expected behavior.
 
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.6
xterm-256color

**Comment by krader1961** [comment]
Expected behavior. Terminal based apps can't actually detect the use of the "meta" key in the way that GUI apps can. That is a limitation of communicating everything as a byte stream over the tty interface. That is, as if you had typed the literal characters. Terminals work around that limitation by mapping [alt-h], for example, to sending [esc] then `h`. Thus simulating a char sequence a user might type.

P.S., Even that isn't guaranteed since some terminal apps require you to explicitly enable mapping [alt-x] to [esc] + `x`.

**Comment by nicm** [comment]
It is good that you went to the effort of testing multiple tmux versions, keyboards etc. Unfortunately, this is just how terminals work. Escape is \033 so there is no difference between Escape+x and M-x, they are both \033x.

As you noticed, the system treats Meta as a modifier so holding it down will generate a stream of \033x\033x\033x..., but holding down Escape will only generate one \033xxxxxx..., although there is no way for tmux to tell this.

On modern terminals there are a few keys where we can be sure an Escape is an Escape. For example in xterm the M-Up sequence is \033[5;3~ which has the modifier built into it, so if we see Escape+M-Up \033\033[5;3~ then we know for sure that the first \033 is an Escape key not the Meta modifier. But there are only a few special keys like this.

This all wouldn't really be too much trouble except that Escape except the original vi(1) authors chose to use it for mode switching. Still we are now stuck with it.
