### ISSUE TITLE
something wrong with config 'set -g default-terminal "xterm-256color"'

### ISSUE THREAD

**Issue by colben** [tmux/tmux#1485]
- OS
    archlinux lastest
- TMUX
    version 2.7-1 and set -g default-terminal "xterm-256color"
- START TMUX COMMAND
    tmux [-2]
- ISSUE
    Sometimes the terminal cursor does not appear after bash prompt properly.
- REAPPEAR
    Start tmux and split the first pane into two small panes vertically, then switch cursor in the two small panes some times, and we can found this issue.

**Comment by nicm** [comment]
tmux is not xterm, default-terminal should not be set to xterm*.

**Comment by TheRojam** [comment]
May this Problem is not a Problem with ArchLinux. Could you upload a screenshot please? May I have the same Problem with tmux on two different devices with two different OS.

**Comment by TheRojam** [comment]
May this Problem is not a Problem with ArchLinux. Could you upload a screenshot please? May I have the same Problem with tmux on two different devices with two different OS.
See the following Screenshots from my macOS computer.
![screenshot 2018-09-26 at 13 25 27](https://user-images.githubusercontent.com/1362428/46078071-6d208080-c193-11e8-8eec-e00ac5d87e70.png)
![screenshot 2018-09-26 at 13 25 28](https://user-images.githubusercontent.com/1362428/46078073-6d208080-c193-11e8-8d5d-cf821b893088.png)

**Comment by dylnmc** [comment]
@colben use `set -g default-terminal "*-256color"`

**Comment by dylnmc** [comment]
I use

```
set -g  default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
```
to enable true color and set default terminal to tmux-256color

this doesn't work in ssh for some reason
