### ISSUE TITLE
Feature Request Add multi-column panes like tcvt

### ISSUE THREAD

**Issue by frosencrantz** [tmux/tmux#1503]
The tool tcvt (http://subdivi.de/~helmut/tcvt/ or https://github.com/spork87/tcvt)  is an ANSI terminal emulator, that turns a $COLUMNS x $LINES terminal into a $COLUMNS/n x $LINES*n terminal of n columns.  Allowing you to convert a portrait terminal layout to landscape layout.

tcvt works well within a pane of tmux.   However this tool is not longer actively developed and is buggy.  It lacks full support for utf8, mouse mode, various keys,  etc.

The request here is to add this ability to tmux panes,  Maybe even windows.  The builtin tmux support would be more robust than tcvt.

**Comment by nicm** [comment]
This is quite a nice idea but I'm not planning to work on it. I would recommend just doing it within one pane (having some way to say "make this pane 2 columns") because otherwise it is likely to be very complicated. I'm not really sure how it would look in the code so I don't really know how much work it would be - a lot of the likely problems (eg wrapping and scrolling), there is already code to deal with for panes. But there is more to it than just taking a pane XxY but telling the program it is (X/2)x(Y*2).

I'll add it to the TODO file but I wouldn't hold your breath or anything.

**Comment by frosencrantz** [comment]
Also, I was going to add this is most useful in zoom mode, where you want to see as much as you can of a file or output.
