### ISSUE TITLE
can I map <F9> to  <c-b>o to switch among panes within a window

### ISSUE THREAD

**Issue by losemyheaven** [tmux/tmux#1525]
Hi,
Is there any way to map function key to <c-b>o?
That will make switching pane more easy for me.

This is my environment.
Linux x86_64
tmux 2.7
xterm-256color

Thanks

**Comment by krader1961** [comment]
According to the documentation (I haven't tried this) you should be able to do something like this:

```
bind-key F9 select-pane -n
```

**Comment by losemyheaven** [comment]
@krader1961 
Thanks for your help.
I tried this. But it seems that select-pane needs a target pane, I would like to just switch to next pane.

**Comment by krader1961** [comment]
I misread the man page. It suggested to me it would recognize the `-n` flag. Does `bind-key F9 select-pane -t {next}` work?  FWIW, I'm flailing a bit since I don't use tmux panes and am basing my answers on what I see in the man page. I use tmux almost exclusively for persistent sessions I can access from more than one machine.

**Comment by losemyheaven** [comment]
Still does not work. But really thanks for your help.

**Comment by nicm** [comment]
Yes you can bind F9 to the same as o, look at bind-key and list-keys.

**Comment by losemyheaven** [comment]
hahahaha
I made it.
bind-key -n F9 select-pane -t{next}

Thanks for your help.
