### ISSUE TITLE
printing file to terminal causes kills the server

### ISSUE THREAD

**Issue by rmzg** [tmux/tmux#1534]
Version: 849d06c0dfadfa5d4a194fd7ce660ac8a5d9e9e7
Uname: Linux hs 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux
term: xterm-256color

If you print the contents of this file: http://rt.rmz.gs/crash to the screen at some point you get Server Lost and no more tmux server.  

And yes, the file is 100MB and most of it is needed to cause the server death but I don't have time to isolate the exact combination that does it.

**Comment by krader1961** [comment]
I'll start by saying that I downloaded your file. Then started a new tmux session using the tmux version you say you're using. Then cat'ed that file. I had no problem other than some unexpected CLI input to my shell as a result of some of the escape sequences causing my terminal (iTerm on macOS) to inject data into stdin of the terminal.

You're cat'ing a non-text [Matroska](https://en.wikipedia.org/wiki/Matroska) (i.e., MKV) file to your terminal and are surprised when your computer halts and catches fire? :smile: Just kidding. Obviously this shouldn't cause tmux to die. Nonetheless it's not surprising that doing so causes problems. At least 90% of all security problems are because some program (e.g., Adobe Flash) assumes its input is not malformed. The problem is how to identify the specific section of that file which is causing the failure.

@rmzg Are you familiar with the concept of "binary search"? Could you take some time to divide the file in half and see which half causes the failure? Then take that half and repeat the process? Since the specific sequence that causes the failure may cross a binary search boundary this is going to require more manual intervention that is typical for this type of problem isolation. But since, as you say, the problem doesn't manifest when running tmux with maximal logging I don't know what else to suggest.

**Comment by rmzg** [comment]
I can take another crack at downsizing the file, although I'll note that it was originally 15GB...

I noticed when I looked at the log file, when it failed to crash with tmux -vv, that there was a million (roughly) lines of tmux commands output. send-keys change-window, a bunch of C-x stuff. Is that something that should be possible to happen? I'm not 100% sure how terminal/tmux stdin works but is it possible to tell the difference between a catted file and keyboard input?

My theory right now with the `tmux -vv` thing is that it's a speed issue: if the input happens fast enough it explodes but when you add `-vv` writing to the file slows it down just enough to survive.

**Comment by krader1961** [comment]
>  is it possible to tell the difference between a catted file and keyboard input?

Yes and no. Yes, tmux can differentiate between what you type and the output of "cat". No, because the problem is the distinction is irrelevant. That is because the problem is not with what you type. It is due to the output that is a consequence of what you type. Consider that any program you ran, not necessarily `cat`, will take what you type and output a considerably more complex sequence of bytes in order to affect where the cursor goes, the color of the text, etcetera. Running `cat a_file` simply makes the process of converting what you type to the output that tmux has to translate more deterministic.

> My theory right now with the tmux -vv thing is that it's a speed issue:....

That is unlikely. What is more likely is that enabling debug logging affects something such as the location of a data structure in memory. And thus affects a memory access that would otherwise be invalid.

What happens if, before you run tmux, you type `ulimit -c unlimited` to enable core dumps. Then run `tmux` and cat the problematic file in that session. Do you get a process core dump? The location of the core dump is system dependent. It might be in your PWD or some location like */cores/*.

**Comment by rmzg** [comment]
Good idea:

[core.zip](https://github.com/tmux/tmux/files/2569076/core.zip)

**Comment by krader1961** [comment]
@rmzg Unfortunately, core dumps are system specific. Only someone using your exact combination of OS and tmux binary will be able to use that core dump. Since you're on Linux you're probably using gcc to build tmux. What do you see if you run `gdb -c /path/to/the/core/file /path/to/tmux` then type `bt`?

**Comment by krader1961** [comment]
Also, what does `locale` output? These types of problems are often due to not using a Unicode compatible locale.
