### ISSUE TITLE
 In cygwin, once open seven sessions, the eighth session can't be opened. 

### ISSUE THREAD

**Issue by fengyichui** [tmux/tmux#1535]
`uname -sp`: CYGWIN_NT-10.0 unknown
`tmux -V`: tmux 2.8
`echo $TERM`: screen-256color
`.tmux.conf`: none

**Issue**: In cygwin, once open seven sessions, the eighth session can't be opened. I use zsh.

**Steps to reproduce**:

>1. Add `tmux -vv -Ltest -f/dev/null new` to .zshrc
>2. Open seven zsh (tmux sessions)
>3. When open eighth zsh, the tmux session can't be created and this terminal looks like dead.

**Log**：[tmux-server-5516.log](https://github.com/tmux/tmux/files/2570761/tmux-server-5516.log)

**Screenshots**：

![1](https://user-images.githubusercontent.com/17896291/48330567-e57dcb00-e687-11e8-805b-cc00f602ee96.jpg)

**Comment by nicm** [comment]
What is in the client log for the 8th client?

**Comment by fengyichui** [comment]
I regained all the logs: [tmux-log-1535.zip](https://github.com/tmux/tmux/files/2574242/tmux-log-1535.zip)

**Comment by nicm** [comment]
This doesn't show anything useful. Can you try strace on client and server and show the output?

**Comment by fengyichui** [comment]
I put the following code to .zshrc to trace client log:

```sh
if [[ ! -f "/tmp/strace-tmux.tmp" ]]; then
    echo '1' >/tmp/strace-tmux.tmp
fi
i=$(cat /tmp/strace-tmux.tmp)
echo $((i+1)) >/tmp/strace-tmux.tmp
strace -f -o strace-tmux-client-$i.log tmux -Ltest -f/dev/null new
```

Use `strace -f -o strace-tmux-server.log -p 9824` to trace server log

log: [strace-tmux-1535.zip](https://github.com/tmux/tmux/files/2578980/strace-tmux-1535.zip)

When use strace, 9th session can't be opened (not 8th). The server log grow especially fast once the 9th terminal is opened.

I feel this issue may be a problem with the cygwin platform.
Currently, I workaround this issue as follow (put into .zshrc and limited to 6 clients):

```sh
tmux_ls=$(tmux ls 2>/dev/null)
# Workaround tmux client limited in cygwin
if [[ "$tmux_ls" && "$OSTYPE" =~ "cygwin" && "$(echo $tmux_ls | wc -l)" == "6" ]]; then
    echo "Warning: tmux can only open up to 6 sessions in cygwin"
else
    # try to reattach sessions
    (echo -n $tmux_ls | grep -vq attached) && exec tmux attach-session -d || exec tmux
fi
```

**Comment by nicm** [comment]
It is definitely a Cygwin problem. There is not much obvious in the logs or strace, at least to me, but I don't know much about Cygwin. I think you will need to ask the Cgywin developers.

**Comment by nicm** [comment]
I wondered if it was hitting FD_SETSIZE but it looks like that is 64 on Cygwin and from the strace it seems like tmux only has 32.

**Comment by nicm** [comment]
It looks like the last client never sends its last message:
~~~~
$ grep sendmsg strace-tmux-client-8.log
  105   82518 [main] tmux 12632 cygwin_sendmsg: 124 = sendmsg(5, 0xFFFF56D0, 0x0)
  118   84067 [main] tmux 12632 cygwin_sendmsg: 7081 = sendmsg(5, 0xFFFF56D0, 0x0)
  142  176104 [main] tmux 12632 cygwin_sendmsg: 16 = sendmsg(5, 0xFFFF56D0, 0x0)
$ grep sendmsg strace-tmux-client-9.log
  128   88541 [main] tmux 12956 cygwin_sendmsg: 124 = sendmsg(5, 0xFFFF56D0, 0x0)
  105   89601 [main] tmux 12956 cygwin_sendmsg: 7081 = sendmsg(5, 0xFFFF56D0, 0x0)
$
~~~~
Which could be because the server isn't reading the previous data, or some other reason. The strace output on Cygwin is fairly useless for someone not familiar with the Cygwin code.

**Comment by krader1961** [comment]
All I can offer is anecdotal data. I use Cygwin on Windows 10 solely to build and test the fish and ksh shells. I regularly find the build/test cycle being unable to spawn new processes. Usually because a prior unit test left some orphaned processes running. And I'm talking about a handful of rogue processes, not hundreds or thousands. Manually killing them "fixes" the problem. My Cygwin environment seems to have a very low limit on one or more resources.

**Comment by nicm** [comment]
I'm not going to look into this any further so I'm going to close this but if you have any further questions feel free to ask.
