### ISSUE TITLE
When default shell does not exist, tmux crashes without any usable feedback

### ISSUE THREAD

**Issue by axelson** [tmux/tmux#1538]
Tmux 2.8
Arch Linux
TERM=xterm-256color

Minimal config:
```
set-option -g default-shell /bad/path
```

This is what happens when I run tmux:
```
jason@jdesktop ~/config> tmux
[exited]
jason@jdesktop ~/config> [?65;1;9c
```

Instead I would expect to get an error like `Tmux was unable to run your current shell`

**Comment by nicm** [comment]
This is not a crash, it exits normally as it would when the server has no sessions. It would be complicated for tmux to tell if a command run in a pane has started successfully, and also to pass that result back to the parent process. I don't think it is worth it.

You could possible add a simple sanity check for default-shell with access() but I'm not really sure it is worth the bother, because the same issue exists if you put nonsense in default-command, or pass an invalid command directly to new-session.
