### ISSUE TITLE
switch -Tprefix doens't work anymore

### ISSUE THREAD

**Issue by purpleP** [tmux/tmux#1559]
You once suggested that I can do this to show display panes when pressing prefix. Since 2.8 this doesn't work. It shows pane numbers, but does not triggers prefix.
```
set -g prefix none
bind -n C-Space display-panes "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix
```

**Comment by nicm** [comment]
display-panes blocks until the command finishes now, it will need a -b flag
to be added to the code like run-shell for the old behaviour.

**Comment by purpleP** [comment]
@nicm Do you mean something like `bind -n C-space display-panes 'run-shell -b "tmux switchc -Troot; select-pane -t '%%''` or what? Where do I need to put this `-b` flag?

**Comment by nicm** [comment]
No I mean display-panes needs a -b flag added, but it doesn't currently
support one. I'll look when I get home in a week.

**Comment by nicm** [comment]
Try this please, you will need to add -b to your display-panes command: [x.diff.txt](https://github.com/tmux/tmux/files/2673260/x.diff.txt)

**Comment by purpleP** [comment]
> Try this please, you will need to add -b to your display-panes command: [x.diff.txt](https://github.com/tmux/tmux/files/2673260/x.diff.txt)

In latest master I can split panes vertically with your patch but not horizontally . In fact I don't think I can use any other command 4ab3b18b36ddd361e0e0030d9d3a2c98b754e88c

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by purpleP** [comment]
Thanks to you for making usefull software!

**Comment by purpleP** [comment]
`bind -n C-Space display-panes -b "select-pane -t '%%'; switchc -Troot"\; switchc -Tprefix`

Is broken again. I think it works if I build 2.9 tag.

**Comment by nicm** [comment]
This is because any key is now passed into the overlay function rather than just 0-9. Try this please [x.diff.txt](https://github.com/tmux/tmux/files/3329730/x.diff.txt)
~~~~
Index: cmd-display-panes.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-display-panes.c,v
retrieving revision 1.28
diff -u -p -r1.28 cmd-display-panes.c
--- cmd-display-panes.c	18 Jun 2019 11:08:42 -0000	1.28
+++ cmd-display-panes.c	26 Jun 2019 11:21:37 -0000
@@ -204,7 +204,7 @@ cmd_display_panes_key(struct client *c, 
 	struct cmd_parse_result		*pr;
 
 	if (event->key < '0' || event->key > '9')
-		return (1);
+		return (-1);
 
 	wp = window_pane_at_index(w, event->key - '0');
 	if (wp == NULL)
Index: server-client.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/server-client.c,v
retrieving revision 1.289
diff -u -p -r1.289 server-client.c
--- server-client.c	20 Jun 2019 19:29:38 -0000	1.289
+++ server-client.c	26 Jun 2019 11:21:37 -0000
@@ -1220,9 +1220,13 @@ server_client_handle_key(struct client *
 	 * blocked so they need to be processed immediately rather than queued.
 	 */
 	if ((~c->flags & CLIENT_READONLY) && c->overlay_key != NULL) {
-		if (c->overlay_key(c, event) != 0)
+		switch (c->overlay_key(c, event)) {
+		case 0:
+			return (0);
+		case 1:
 			server_client_clear_overlay(c);
-		return (0);
+			return (0);
+		}
 	}
 
 	/*

**Comment by purpleP** [comment]
@nicm It works, thanks!

**Comment by nicm** [comment]
Great, thanks!
