### ISSUE TITLE
tmux start-server without forking

### ISSUE THREAD

**Issue by LaraCraft93** [tmux/tmux#16]
I want to be able to start the tmux server without forking the process, but I found no way on last tmux release.

I found this commit on cvs-archived repository:

https://github.com/ThomasAdam/tmux-cvs-archived/commit/4ae54388081f3802700eae2ebcd876efcb2714f5

why it's not in the main tree?

**Comment by nicm** [comment]
I don't like it :-).

**Comment by zxcvbn97** [comment]
Without forking the process can be useful for debugging purpose. Why not?

**Comment by nicm** [comment]
It doesn't make it appreciably easier and tmux doesn't log anything to stdout.

**Comment by LaraCraft93** [comment]
I need it because I want to start a default tmux session on my system and restart the session if it don't exist anymore. For do this with a forking process I need a infinite loop,  and it is ugly.

It's a functional implementation, not only for debugging.

**Comment by ntnn** [comment]
@LaraCraft93 You can define the socket-path, tmux doesn't start a second server on the same socket.

**Comment by ThomasAdam** [comment]
It was useful once or twice when I was debugging tmux server code for something, but it's generally not a problem now to just either use abort() (in rare cases), or shove some log_debug() calls in, etc., etc.

**Comment by devurandom** [comment]
I would also like to see this feature in order to make tmux interact more nicely with a service supervisor like systemd or s6.

**Comment by mmonaco** [comment]
+1 to this. I think it would be useful for learning and debugging if there was an option to `start-server`to not fork which also implies or could be used in conjunction with an option to log to `stdout` / `stderr`, and also to imply `set-option -s exit-empty off`.

This isn't only about systemd, I'd be interested in this for running manually too. However, for those interested my current user-unit workaround is:

```
[Service]
Type=forking
GuessMainPID=true
ExecStart=/usr/bin/tmux set-option -g exit-empty off \; start-server
ExecStop=-/usr/bin/tmux kill-server
```

but this doesn't solve the logging problem.

I also like to keep the server running in order to keep startup latency to a minimum.
