### ISSUE TITLE
Right arrow symbol (→) not showing up

### ISSUE THREAD

**Issue by maksimf** [tmux/tmux#1602]
tmux 2.8
MacOS 10.14.3
iTerm2 3.2.7

I'm using oh-my-zsh with the default theme it looks like this, when running just iTerm2, with no tmux:

<img width="79" alt="screenshot 2019-02-12 at 23 35 23" src="https://user-images.githubusercontent.com/860283/52666271-e7715780-2f1e-11e9-8068-94a77eb01caa.png">

But in tmux right arrow disappears:

<img width="73" alt="screenshot 2019-02-12 at 23 35 30" src="https://user-images.githubusercontent.com/860283/52666300-f8ba6400-2f1e-11e9-8147-aca1aaf5959c.png">

Tried to change font, no effect. It still works outside of tmux and not inside.

My .tmux.conf:

```
set-window-option -g mode-keys vi
bind c new-window -c "#{pane_current_path}"
```

**Comment by nicm** [comment]
Sounds like you don't have UTF-8 configured properly, try running tmux with -u.

**Comment by maksimf** [comment]
Works like a charm. How do I configure UTF-8?

**Comment by nicm** [comment]
Using -u is fine if you want, or set LANG,LC_ALL or LC_CTYPE to a UTF-8 locale.

**Comment by krader1961** [comment]
I use tmux on macOS and don't have any such problem. The character in the subject line is code point U+2192. I can't tell what the character is in your terminal because you used PNG images. If you copy those chars to your clipboard then do `echo -n [command-V] | od -tx1` (where [command-V] means paste the clipboard) what is output? You should see this which is the UTF-8 encoding of that code point:

```
0000000    e2  86  92
0000003
```

Also, what does `locale` output inside and outside tmux? If it isn't a UTF-8 locale that will cause problems.

**Comment by maksimf** [comment]
`locale` inside/outside tmux is the same

```
LANG=
LC_COLLATE="en_US"
LC_CTYPE="en_US"
LC_MESSAGES="en_US"
LC_MONETARY="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_ALL="en_US"
```

```
$ echo -n → | od -tx1

0000000    e2  86  92
0000003
```

**Comment by krader1961** [comment]
> LC_ALL="en_US"

There's your problem :smile: Change that to `en_US.UTF-8` and you'll have fewer problems.

**Comment by maksimf** [comment]
Thank you!
