### ISSUE TITLE
use combined emoji on tmux, pein border was shift

### ISSUE THREAD

**Issue by 2357gi** [tmux/tmux#1605]
watch this screenshot
![](https://i.imgur.com/idMNA2k.png)

Details:
- macOS 10.14.3 (18D109)
- tmux version 2.8
- terminal2.9.1 (421.1)

Steps to reproduce:
- print emoji that combined using a zero width joiner between each character and display as a single emoji( e.g. 🧞‍♂️ , 👨‍💻, 👨‍👨‍👧...)

Expected results:
- border does not shift.

Actual results:
-The border shifts by the amount of combined emojis.

**Comment by nicm** [comment]
Logs?

**Comment by 2357gi** [comment]
Is this OK with this tmux-out-*.log?
[tmux-out-3699.log - Pastebin.com](https://pastebin.com/JZPZuyit)

**Comment by nicm** [comment]
No I need the tmux-server*.log. Do this:
~~~
tmux -Ltest -f/dev/null -vvv new
~~~
Then print one of the problem characters.
Then do "exit" and send me the tmux-server*.log file.

**Comment by 2357gi** [comment]
oh, ok
[tmux-server-3947.log - Pastebin.com](https://pastebin.com/C4b0xJ7P)

and Is there any other missing information?

**Comment by nicm** [comment]
Your platform does not have a correct width for U+200d ZERO WIDTH JOINER, from the log:
~~~~
1550243418.834949 Unicode 200d, wcwidth() -1
~~~~
So tmux will assume it is width 1. You could try building tmux with utf8proc and see if it has a correct width instead.

**Comment by nicm** [comment]
Actually, even if your platform had the correct width, tmux does not support this feature of Unicode.

**Comment by nicm** [comment]
I don't have any terminals that support this so I think it is premature to try and support it in tmux, sorry. I expect you will find lots of other applications have problems with these sequences.

**Comment by MartyLake** [comment]
Hey @nicm would you be able to open the issue again ? On windows I use Fluent Terminal that displays emoji correctly, but I reproduce this error.

**Comment by nicm** [comment]
I have this on the todo list but no plans to work on this in the near future, if you want to work on it feel free to ask questions or open a PR.

**Comment by MartyLake** [comment]
I have no experience of tmux code, but I am willing to try :) Do you have any guide or suggestions about where to start ?

**Comment by nicm** [comment]
I would suggest first looking at how tmux handles Unicode and particularly zero width characters at the moment.

The way Unicode characters that are made up of multiple codepoints (that is, a visible codepoint and one or more combining zero-width codepoints) is that all the UTF-8 data for the codepoints that make up one visible character are collected together into a single struct utf8_data which then goes into a single extended grid cell.

Individual codepoints are handled from the terminal in input.c:input_top_bit_set - at this point, each comes in separately from the terminal so the visible and zero-width codepoints will be separate utf8_data structs.

They are each in turn (as they arrive) fed into screen-write.c:screen_write_cell where the first visible codepoint will be written into a grid cell directly, then the second will end up in screen_write_combine which will append it onto the previous codepoint in the same cell.

For the zero width joiner character, we will need to follow the same process - so that all three codepoints, the first visible character, the zero width joiner, and the third character that is being joined all end up together in the utf8_data for the same cell. If you do this and the cell has the correct width, the rest of the code (that is, drawing the UTF-8 later) should just work.

At the moment tmux can tell when to combine the characters because it knows the current character is zero-width, the trick with the zero width joiner will be knowing that the next character (when it arrives) will need to be joined because that will not be evident from the character itself, you will need to add a flag that is set when the zero width joiner is processed. I'm not sure where the best place for a flag is - probably in the input_ctx and then passed into screen_write_cell probably as an argument or in the screen_write_ctx. Then it can use that flag to enter screen_write_combine for the third combining character rather than putting it in a new cell.

I am assuming the width of the first character determines the width of the entire combined character, if it doesn't then things get more complicated, because if a cell expands from width 1 to width 2 after it is inserted then you will need to add padding. But I would just ignore this possibility for now and see if it is needed later.

This should actually be less complicated than I thought it would be :-).

**Comment by nicm** [comment]
It actually looks like the zero width joiner can in some cases appear after the combining character rather than before. I don't think this is needed for emoji however, so you could probably just ignore that case for the moment.

**Comment by MartyLake** [comment]
Well, I *lied*, my bug is related to emoji, but different. Will go to bed, sleep, and hopefuly open a better more accurate ticket :'(

**Comment by MartyLake** [comment]
Sorry for making you think and write this very long explanation. Hopefully when someone encounters this issue again, this person can just pick it up there :)

**Comment by nicm** [comment]
I have done a bit of work on this  but I don't have any terminals that support it so I am going to wait until they appear (diff against master): [tmux-zwj.diff.txt](https://github.com/tmux/tmux/files/4628226/tmux-zwj.diff.txt)

I thought Terminal.app supported it but it doesn't actually adjust the cursor position correctly so I can't tell if this tmux change actually works, and it doesn't cope with sequences where the width changes after the ZWJ but I don't know how common they are. Of course it will need application support to be much use anyway and AFAIK few support it.
