### ISSUE TITLE
Error in `tmux': corrupted double-linked list: 0x0000000000ff1dc0

### ISSUE THREAD

**Issue by fengzhao** [tmux/tmux#1616]
tmux 2.8   
when i use  the command to install tmux , and to start a new session , but it crashed!

```shell
$ cd /tmp
$ sudo yum install ncurses-devel  automake
$ 
$ wget https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz
$ tar -zxvf libevent-2.1.8-stable.tar.gz 
$ cd libevent-2.1.8-stable
$ ./configure
$ make && make install
$ ln -s /usr/local/lib/libevent-2.1.so.6 /usr/lib64/libevent-2.1.so.6

$ git clone https://github.com/tmux/tmux.git
$ cd tmux
$ sh autogen.sh
$ ./configure && make
$ make install 
```

![image](https://user-images.githubusercontent.com/6206340/53404805-61124680-39f1-11e9-8143-81d6cb57d711.png)

**Comment by nicm** [comment]
How did you make sure tmux built with the right libevent headers?

**Comment by fengzhao** [comment]
@nicm  what doex it mean ?

**Comment by nicm** [comment]
You have installed your libevent to /usr/local, how do you know tmux is finding the headers in /usr/local/include not using a different version from /usr/include?

**Comment by fengzhao** [comment]
@nicm  OK, so how do i do to solve the problem ?

**Comment by krader1961** [comment]
Add a `#error "correct header found"`  to the top of the libevent headers you installed in */usr/local/...*. If the build fails with that error message then you know your build is including those headers. Also, run `ldd` against your tmux binary to confirm it is loading the libevent lib in */usr/local/...* rather than some other library of that name.
