### ISSUE TITLE
adding -a flag to set-hook command

### ISSUE THREAD

**Issue by sudobash1** [tmux/tmux#1619]
It would be nice to be able to give multiple commands to the same hook across multiple `set-hook` commands. The reasons I see for this are:

1. Organization & readability: I sometimes want two unrelated actions for the same hook. I can put them on the same hook command with a `;` but this means they have to be in the same line in the same `.tmux` file
2. Plugins: If two plugins want to bind an action to the same hook (eg `window-pane-changed`) one will end up overriding the other. They would need to do manual parsing of `tmux show-hooks` to determine if there is already a hook and to get the old value to append to.

I think that a clean solution would be to add the `-a` flag to `set-hook` which would behave similarly to the `-a` flag in `set-option`. That way multiple commands could be added easily to the hook without checking for special cases.

The only gotcha would be if someone tried something like `tmux set-hook -a window-pane-changed ' ; command'` to a hook that was not already set. Having a hook be prefixed by `;` causes a `no command` error. Perhaps the `-a` flag could automatically add a `;` if appending to a hook which already had a command.

**Comment by nicm** [comment]
I'd quite like hooks to be multiple lines, a bit like array options.

**Comment by ThomasAdam** [comment]
Something for the weekend, I'll take a look.

**Comment by nicm** [comment]
I wonder if hooks could just be array options (maybe user options, although they can't be arrays at the moment).

**Comment by nicm** [comment]
I am actually thinking now that we know all the hook names, so why not just make them fixed options?

Initially perhaps they could jut be stored as options and we could looks the hooks tree and set-hook and show-hooks could remain and just call options_* to set them.

Then eventually we could make a couple of other useful changes (allow wildcards to show-options and aliases to expand arguments) and add set-hook and show-hooks as aliases, something like:

show-hooks="show-options hook-*"
set-hook="set-option hook-%0 %1"

set-hook -R would be a problem in this case but perhaps it could be moved to another command.

In the short term if you want to write set-hook -a now then go for it, since any other changes would want it anyway.

**Comment by ThomasAdam** [comment]
Cool, I'll pick this up!

**Comment by nicm** [comment]
[tmux-hook-options.diff.txt](https://github.com/tmux/tmux/files/3118815/tmux-hook-options.diff.txt)

This makes hooks array options, so you can now set them with set-option -a:

~~~~
$ tmux show-hooks -g pane-mode-changed
pane-mode-changed[0] set-option -Fg status-left-style "bg=#{?#{==:#{pane_mode},copy-mode},colour5,colour8}"
$ tmux set-option -ga pane-mode-changed lsk
$ tmux show-hooks -g pane-mode-changed
pane-mode-changed[0] set-option -Fg status-left-style "bg=#{?#{==:#{pane_mode},copy-mode},colour5,colour8}"
pane-mode-changed[1] list-keys
$
~~~~

I should probably add -a to set-hook as well.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later.

**Comment by sudobash1** [comment]
@nicm Thanks for making this happen!
