### ISSUE TITLE
brew and autojump not work. 

### ISSUE THREAD

**Issue by XueqiLi** [tmux/tmux#1623]
Inside of tmex, whenever I tried to use autojump, I get an error `autojump_chpwd:4: command not found: autojump`; whenever I tried to use brew, I get an error `zsh: command not found: brew
`. Both of them works fine outside of tmux. This happened even if I don't use any `.tmux.conf` file. Tmux is install with brew.

Environment:
* tmux 2.8
* macOS 10.14.3
* oh-my-zsh
* autojump 22.5.1
* brew 2.0.3-41
* iTerm2 3.2.7
* `$TERM`: `xterm-256color` outside. I tried to set it as `xterm-256color`, `screen-256color`, `screen` inside of term, none of them works.

```
# el at MacBook-Pro-13.local in ~ [12:05:08]
→ brew --version
zsh: command not found: brew

# el at MacBook-Pro-13.local in ~ [12:05:12]
→ autojump --help
zsh: command not found: autojump

# el at MacBook-Pro-13.local in ~ [12:05:18]
→ uname -sp && tmux -V && echo $TERM
Darwin i386
zsh: command not found: tmux
```

log:
[tmux-server-12579.log](https://github.com/tmux/tmux/files/2953078/tmux-server-12579.log)

**Comment by nicm** [comment]
Sounds like a problem with your shell profiles to me.

**Comment by nicm** [comment]
Are you sure you aren't setting a different PATH inside and outside tmux? Remember tmux creates login shells by default.

**Comment by XueqiLi** [comment]
> Are you sure you aren't setting a different PATH inside and outside tmux? Remember tmux creates login shells by default.

I did not, and I have checked, they are the same. What problem you think might be on shell profiles?

**Comment by nicm** [comment]
tmux has nothing to do with finding these programs, it is entirely up to your shell, so there must be some configuration difference between inside and outside tmux.

**Comment by XueqiLi** [comment]
But so far everything I can think of is the same. Any suggestion?

**Comment by krader1961** [comment]
@XueqiLi Nicm is correct. The problem is with your shell config. That your shell can't find `tmux` or `brew` when run inside a tmux session implies your `$PATH` var does not contain */usr/local/bin* since that is where they would typically be found. What do you see if you run `type brew` in a shell not in a tmux session. And I hate to doubt you but I think you need to show us the output of `echo $PATH` from a shell running outside of, and inside, a tmux session.

P.S., Probably unrelated to your problem but the macOS permission model means that for some things to work correctly (e.g., `ssh-add`) you need to add something like the following (from my *~/.tmux.conf*) to your tmux config:

```
# The reattach-to-user-namespace is necessary to be able to contact ssh-agent
# via the SSH_AUTH_SOCK env var. This is also necessary to make pasteboard
# (clipboard) interaction work for programs run within the tmux server.
#
# Note that we don't use the `-l` flag to invoke fish as a login shell. That's
# because we've already done whatever special things we want done the first
# time we log in if we're creating a tmux session. So there is no point doing
# that work (which can be quite expensive) a n'th time.
set-option -g default-command "exec reattach-to-user-namespace /usr/local/bin/fish"
```

**Comment by XueqiLi** [comment]
Sorry, you are right. It do miss `/usr/local/bin`. I miss it from a bunch of different `bin` directory. But I don't know what changed it. Should I just add a line in `$PATH` to change `$PATH` every time?

Thank you

**Comment by nicm** [comment]
reattach-to-user-namespace should not be necessary since tmux 2.6, assuming Apple have not broken it again.

Are you sure you don't want to source your .zshrc or similar from .zsh_profile or similar? You will need to check in the zsh docs what these files are called.

**Comment by XueqiLi** [comment]
I just find in the `man` page of zsh says before it read `.zshrc` file in `$HOME` it reads a file in `/etc`, : interactive shell reads `/etc/zshrc`, login shell reads `/etc/zprofile`. In the `\etc\zprofile` it has
```if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi```
which set up the `$PATH`. And in `/etc/zshrc` there is nothing to do with `$PATH`.

But shouldn't tmux create login shell by default?

**Comment by krader1961** [comment]
> But shouldn't tmux create login shell by default?

Tmux does create a login shell by default in each window. Your problem isn't due to anything tmux is doing. Unfortunately, due to the nearly infinite number of ways people can shoot themselves in the foot when configuring their shell, it isn't possible for us to know what mistake you have made in configuring your shell.

**Comment by nicm** [comment]
I think you will need to ask the zsh community or developers for help with this.
