### ISSUE TITLE
Tmux remote sessions and tmux socket tunneling

### ISSUE THREAD

**Issue by izemmouri** [tmux/tmux#1643]
Hi,

I don't like nested tmux sessions, however if you want to attach to a tmux session on a remote server while already in a local tmux session, you have pretty much no choice.

My question is: would it be possible to have transparent remote tmux sessions, i.e. remote tmux sessions that appear as local by tunneling the remote tmux socket with the ssh (or other) connection. As I have tried to do that and failed, I am guessing it might not be possible. By googling this a bit, one learns about eventual limitations due to the tunneling not actually forwarding all possible functions. I'm not sure to understand and you probably will explain this even better, but in any case, could this be a future functionnality to tmux, because it'd be damn nice.

**Comment by nicm** [comment]
You can't forward tmux's socket because it needs to pass the file
descriptors. This has come up before and the way I would like to see this
done is by making the tmux server able to talk to another using control
mode, it could be at session, window or pane level, I'm not sure which
would work best. That way, because control mode is a text protocol, it can
be tunnelled with ssh and tmux doesn't have to worry about networking or
encryption. Iterm2 has already shown that control mode is sufficient to
make a new UI for tmux, but so far nobody has done the work on something
like this. It would be a good bit of work but not an enormous project.

**Comment by akorchemniy** [comment]
Similar to this question: https://www.reddit.com/r/tmux/comments/d22l3x/single_client_multiple_tmux_servers/
