### ISSUE TITLE
How to investigate 127 errors best?

### ISSUE THREAD

**Issue by binarykitchen** [tmux/tmux#1679]
When I run `tmux source ~/.tmux.conf` and it returns the notorious 127 error code, what't the best way to examine this?

No error messages, no stack trace, nothing, makes it very hard to examine where the heck the problem comes from. Is there some kind of debug mode?

In my case it returns with
'powerline-config tmux setup' returned 127

Already googled before but nah, no hits. Thanks for any hints how to examine this best.

**Comment by krader1961** [comment]
Exit status 127 typically means the command was not found when it is the status from a POSIX shell script. Which may or may not be relevant to your situation but I'm betting it is relevant. Is `powerline-config` in your `$PATH`? And there is no `setup` tmux command so `tmux setup` makes no sense.

**Comment by binarykitchen** [comment]
Yes `powerline-config` is in my path under `/home/michael-heuberger/.pyenv/shims`. Although I am on ZSH and this path is being set in `.zshrc`. Not sure if `mux source ~/.tmux.conf` really parses .zshrc?

 >> And there is no setup tmux command so tmux setup makes no sense.
Well it's `powerline-config tmux setup`, not `tmux setup`.

**Comment by krader1961** [comment]
Start tmux with the `-vvv` flag and upload the server log. You need to ensure tmux is not already running.

**Comment by binarykitchen** [comment]
Ummm, not sure how to do this. I'm on the remote server and each time I kill tmux, SSH connection is aborted. And then when I log in again, tmux starts again.

**Comment by krader1961** [comment]
> And then when I log in again, tmux starts again.

That implies you are starting tmux from your *~/.profile*, *~/.bashrc*, or similar shell config file. There is no way for anyone else to know what you've done in that regard since the possibilities are infinite. That is something you'll need to figure out as it has nothing to do with tmux per se. But all this begs the question: Why are you running `tmux source ~/.tmux.conf`? If you are starting a tmux server in the normal fashion the sourcing of *~/.tmux.conf* will automatically happen.

**Comment by binarykitchen** [comment]
Yeah I am running `tmux source ~/.tmux.conf` to test the config file in a remote tmux session. If there is a better way to test, then I won't do that again.

Anyway, inspiration of my tmux config comes from 
https://github.com/kairichard/dotfiles/blob/master/tmux.conf

where `powerline-config tmux setup` is run and there it gets stuck.

**Comment by krader1961** [comment]
> Yeah I am running tmux source ~/.tmux.conf to test the config file in a remote tmux session.

I can't make any sense of that sentence. Starting tmux in that remote tmux session should automatically be sourcing *~/.tmux.conf*. What you seem to be saying is that you are changing the contents of that file after the tmux server has already been started and want to tell the already running tmux server to use your updated config. Yes? No? Something else?

Thanks for the link to that tmux.conf as it provides much needed context for your issue. You really should have mentioned that in your original problem statement. The error appears to be from this line in the tmux.conf on which you are basing your config:

```
if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'
```

Note that the `'env "$POWERLINE_CONFIG_COMMAND" tmux setup'` portion of that tmux statement literally runs `tmux setup` via the `env` command with the environment vars updated to include whatever `$POWERLINE_CONFIG_COMMAND` is defined to be. Which, AFAICT, makes no sense.

**Comment by krader1961** [comment]
Also, I wouldn't trust the author of the tmux.conf you seem to be using given that it contains

```
# Use whatever shell we launched from 
set -g default-shell $SHELL
```

Which is pointless since that is already the default shell value unless you are changing it after the tmux server has already been started. Which suggests that everything else in that person's tmux.conf is suspect.

**Comment by nicm** [comment]
run-shell uses /bin/sh, if you are running an executable outside your default PATH in .tmux.conf you will need to use its full path.

**Comment by krader1961** [comment]
Note that `env "$POWERLINE_CONFIG_COMMAND" tmux setup` will always fail since `tmux setup` is invalid. Which cause the `run-shell ...` portion of that statement to always be run. I have no idea what the person who wrote that tmux config file was trying to do but I would advise you to ignore their advice.

**Comment by nicm** [comment]
I think "tmux setup" is arguments to powerline-config.

**Comment by krader1961** [comment]
> I think "tmux setup" is arguments to powerline-config

Yes, but in the `if-shell` command it is the command that is run by `env`. Consider running `env X=y tmux setup`. Does that make any sense? It always fails which means the `powerline-config tmux setup` alternative is always run. Which is probably also nonsense but since I have no idea how `powerline-config` interprets its arguments I can't be certain of that. However, since the condition which predicates running that command is nonsense I am comfortable concluding running the latter command is nonsense.

**Comment by nicm** [comment]
env only sets variables if the argument has an = in it, this is more like
running "env X tmux setup".

The idea is to run "$POWERLINE_CONFIG tmux setup" and if it fails try
"powerline-config tmux setup" instead. This is not how I would do it but it
should work.

**Comment by binarykitchen** [comment]
thanks for the dicussion guys. can follow you till here but now what? what should i test to find out what's wrong? and what changes do you suggest?

**Comment by nicm** [comment]
Try pointing POWERLINE_CONFIG to wherever your powerline-config binary is.

**Comment by binarykitchen** [comment]
hardcoding a path is never good

**Comment by nicm** [comment]
Right well I don't really have much interest in debugging a random config you copied off the internet. Why don't you ask whoever wrote it? Or start with an empty config and add bits that you understand?

**Comment by binarykitchen** [comment]
Agree. Will do.
