### ISSUE TITLE
About version numbering scheme

### ISSUE THREAD

**Issue by drmad** [tmux/tmux#1712]
I'm sorry if this question is misplaced. It's not a issue report, just a general question:

What's the tmux version numbering scheme, if any? What will be the next version after 2.9? 2.99? 2.10? 3.0? 

I'm the main developer of [https://github.com/drmad/tmux-git/](https://github.com/drmad/tmux-git/), and one of my contributors, @ryw89, noticed that you're now using letters in the version number (as in 2.9a), and we need to check the tmux version for the *-attr to *-style change in 2.9, so we need to know the version scheme for comparing.

Thanks!

**Comment by nicm** [comment]
You could have just looked to see what the number was after 1.9...

After 2.9 will be 3.0. Letters are for bug fix releases and are rare, you
can ignore them.

-attr was changed to -style in tmux 1.9 so unless you want to support tmux
1.8 you may not need to check for it.

**Comment by gnachman** [comment]
I've run into a few problems with tmux versions. I need to parse them to support new features and sometimes to work around bugs. The rules as I've discovered them so far are:

* There may be a prefix of `next-` to signify an unreleased version.
* There may be a suffix of `-rc` to signify a release candidate.
* After stripping those, there may be a single letter suffix to denote a bugfix version (e.g., 2.9a).
* After stripping that, there are two decimal numbers separated by a period.

Since I need to write a function that can properly parse version numbers from future releases of tmux, I'd like to know if I'm missing anything to avoid breaking in the future.

**Comment by ThomasAdam** [comment]
You're not missing anything.
