### ISSUE TITLE
Support comparisons  <, <=, >, >=   %if #{comparison,a,b}

### ISSUE THREAD

**Issue by HaleTom** [tmux/tmux#1747]
`man tmux` says:

> Comparisons may be expressed by prefixing two comma-separated alternatives by ‘==’ or ‘!=’ and a colon.

To support backward compatibility, I compare the tmux version with `bc` and the `<` and `>=` operators as shown [here](https://github.com/tmux/tmux/issues/1732).

It would be great to not need to rely on a subshell and `bc` for this.

**Comment by nicm** [comment]
This has been on the TODO list for a while and it isn't a big job. I expect a simple strcmp would work fine for the version number.

You could also use matching so for example #{||:#{m:[01].*,#{version}},#{m:2.[0123],#{version}}}.

**Comment by nicm** [comment]
Try this please: [tmux-format-ltgt.diff.txt](https://github.com/tmux/tmux/files/3212560/tmux-format-ltgt.diff.txt)

**Comment by codisms** [comment]
Using `strcmp()` won't handle semver should the minor version hit double digits.  `2.9` would be considered greater than `2.10`.

**Comment by nicm** [comment]
This will never happen.

**Comment by lacygoill** [comment]
> Try this please: [tmux-format-ltgt.diff.txt](https://github.com/tmux/tmux/files/3212560/tmux-format-ltgt.diff.txt)

FWIW, I've been able to apply the patch and compiled tmux, and in my limited testing the code seems to work for the `<` and `>` operators but not for `<=` and `>=`.

That is, if I write this in `/tmp/tmux.conf`:

    %if #{<=:#{version},9.9}
    set -g status-style bg=red
    %else
    set -g status-style bg=green
    %endif

Then start tmux with:

    $ tmux -Ltest -f/tmp/tmux.conf

I would expect the status line to be colored in red, since I compiled tmux with the version `2.9`:

    $ sed -i "/AC_INIT/s/\S\+)/2.9)/" configure.ac

And tmux expands the replacement variable `#{version}` with 2.9:

    $ tmux display -p '#{version}'
    2.9

And 2.9 is lower than 9.9.

Maybe I misunderstood how to use the operator though.

Here are the logs:
[tmux-client-11431.log](https://github.com/tmux/tmux/files/3219427/tmux-client-11431.log)
[tmux-out-11433.log](https://github.com/tmux/tmux/files/3219428/tmux-out-11433.log)
[tmux-server-11433.log](https://github.com/tmux/tmux/files/3219429/tmux-server-11433.log)

**Comment by nicm** [comment]
Yes thanks this line in format_build_modifiers is wrong:

+ memcmp("<", cp, 2) == 0 ||


Change it to "<=" not "<".

**Comment by lacygoill** [comment]
I can confirm that changing:

    memcmp("<", cp, 2) == 0 ||

with:

    memcmp("<=", cp, 2) == 0 ||

fixes the issue. Now all 4 operators seem to work as expected. Thank you very much for the patch.

**Comment by nicm** [comment]
Great, applied now, thanks!
