### ISSUE TITLE
Italics broken in tmux 2.1

### ISSUE THREAD

**Issue by bentomas** [tmux/tmux#175]
It happened in this commit, which specifically mentions breaking italics: 7382ba82c5b366be84ca55c7842426bcf3d1f521

Seems crazy to me, that if a terminal reports it _supports_ italics, tmux _ignores_ this and only shows italics based on the the terminal name.  I mean, at that point, why do we even bother looking at what the terminal says it can do at all? Let's just make loads of assumptions about what a terminal can do based purely off of a very short name and hope for the best.

That commit did a lot of stuff (like change default-terminal to be a server option instead of a session option) which gives me hope that we can get sane handling of italics put back in, and that this break was only included because it was the other changes that were wanted.

**Comment by bentomas** [comment]
I don't understand why this was closed?

**Comment by nicm** [comment]
The rationale and the solution is right there in the commit message, you are just complaining.

**Comment by bentomas** [comment]
I'm not complaining, I'm suggesting that this change was a bad one and should be reversed or trying to understand why it isn't a bad change.

There is no discussion of this change here in issues, in the mailing list or online that I can find.  So, like you said, all I have to go on is the commit message.  

The commit message does not explain **why** this behavior was chosen. Had it done so, I wouldn't have created an issue.

It only explains why the previous behavior was chosen. It says, `This was acceptably until recently because xterm's terminfo entry lacked sitm, so most users got smso.`, but doesn't say what changed recently and why that was no longer acceptable.

Yes, it says it is emulating historical behavior, but does not say why.  The only note about the historical behavior is that it is _incorrect_.  I think asking why incorrect behavior is chosen is a reasonable question.  

But not only that, the commit message says the behavior it is emulating for screen is `send smso`, which _isn't actually what this code does_. If you [look at the code in question in master](https://github.com/tmux/tmux/blob/master/tty.c#L461-L464), if the terminal is screen, it sends `sitm` and not `smso`

And finally, the main point of my original issue isn't _at all_ addressed in the commit message. Why are the terminal capabilities as specified by the host being ignored/overwritten by tmux?  This just doesn't make any sense. Like I said above, why bother checking to see if the terminal can support `sitm` if it is going to be ignored anyway?

**Comment by nicm** [comment]
If you were asking for an explanation perhaps you should have phrased
your issue as a question. I mean, you don't understand what the issue
is, or the background, or the commit message, or the code, so why are
you telling me it is crazy and being sarcastic? I don't have any
obligation to do things the way you think they should be done.

Anyway, I'll tell you:

When screen gets the SGR 3 escape sequence (\E[3m) inside, it asks for
standout from the terminal outside by looking at the terminfo entry set
outside ("xterm", say) and sending smso. This is wrong, because SGR 3 is
meant to be italics. I don't know why they chose to do this, possibly it
was before italics was available, or they had some other motivation,
possibly it was sensible at the time.

The "screen" terminfo entry has smso=\E[3m, because when an application
inside screen wants standout, it will look in the "screen" terminfo for
smso and send what it finds (SGR 3), and SGR 3 is standout in screen.

So that's all good for screen which has no support for italics.

But for tmux we want to support italics. Previously, we would look at
whether the terminal outside had sitm and send it when we got SGR 3 from
the application inside (this is what we're meant to do, because SGR 3 is
supposed to be italics). If the terminal didn't have sitm, we would send
smso.

This meant that because we use the "screen" terminfo entry inside tmux,
an application asking for standout would send SGR 3, and if the terminfo
entry outside had smso tmux would behave like screen and give it
standout (meaning show any subsequent text using standout), and if it
had sitm tmux would give it italics.

This was acceptable, because the "xterm" terminfo entry didn't have
sitm: most people use "xterm" and most people don't care about italics,
and it allowed the few who do care to enable it with terminal-overrides
and a custom terminfo entry.

But now the "xterm" terminfo entry has changed so it does have sitm, so
suddenly everyone is getting italics when their applications in tmux ask
for standout. This is clearly wrong and everyone will complain about it.

So what do we do?

The right solution is for everyone to stop using the "screen" terminfo
entry in tmux and use the new "tmux" terminfo entry instead. The "tmux"
terminfo entry has sitm=\E[3m and smso=\E[7m and everything is grand.

But adding a new terminfo entry isn't that simple. It is easy enough to
actually add a "tmux" one, but terminfo doesn't propagate very fast, and
there will be a lot of old hosts without it for a very long time.

(Also you should understand that terminfo is not always complete, is
sometimes a moving target, is often out of date and is occasionally
wrong. tmux does the best it can to stick to it, but it is not always
possible.)

And now we have "tmux" terminfo entry, applications inside tmux with TERM
set to "screen" will send SGR 3 expecting standout (because that is
smso), but with TERM set to "tmux" they will send SGR 3 expecting
italics (because that is - rightly - sitm).

So we need to support both. And the best solution is to just check what
terminfo entry applications are likely to be using, which is in
default-terminal.

This means that by default, users get the "screen" terminfo (almost
certain to be available on their box), and it shows standout when
requested.

And people who want italics can just set default-terminal to "tmux", and
use the "tmux" terminfo entry. If they don't have the "tmux" terminfo
entry yet, they can upgrade their terminfo, or build their own like in
the FAQ, or copy the screen one and rename it. These people get the
short end of the stick, but they are the minority and are more likely to
be power users who are always tweaking their configs anyway.

In any case, the code is right, this change is sensible and it is not
going to be reverted.

**Comment by bentomas** [comment]
Thank you for the detailed explanation.  

You're right, my initial issue wasn't very helpful. I'd been looking for an explanation of why my terminal-overrides weren't working for literally 4 hours at that point, and was tearing my hair out. I found the issue that broke things, and was hoping there was some sort of mistake.  My issue was left in frustration and it shows.  Though I did genuinely want to understand, so again thanks.

As to how I missed the explanation in the FAQ about italics, that's fairly embarrassing, especially in light of my snarky issue here. I guess I was concentrating more on the terminal-overrides aspect of the whole ordeal and less on the italics side of things.

I think you can at least appreciate the fact that no where in all the tmux docs or the commit is this change/solution explained like what you just did.

**Comment by LandonSchropp** [comment]
@nicm I'm following [these instructions](https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/) for getting italics set up in my terminal. Could you please elaborate a little more how to set up the change to enable italics? I'm not quite sure I understand from reading the commit. Should I add a `default-terminal` type to the terminal database? Should I be using different escape sequences?

**Comment by LandonSchropp** [comment]
Never mind. I found it in the [FAQ](https://github.com/ThomasAdam/tmux/blob/master/FAQ).
