### ISSUE TITLE
"tmux choose-buffer -O time" selects oldest item at first.

### ISSUE THREAD

**Issue by koie** [tmux/tmux#1759]
### Issue description

"tmux choose-buffer -O time" sets currnent to a last item (*1)
I suppose this behavior is inconvenient, and a first item should be selected.

example: 

- tmux set-buffer 111
- tmux set-buffer 222
- tmux set-buffer 333
- tmux choose-buffer -O time
```
 ____________________________________________________________________________
|(0)  buffer2: 3 bytes (Sun May 26 23:57:17 2019)
|(1)  buffer1: 3 bytes (Sun May 26 23:57:17 2019)
|(2)  buffer0: 3 bytes (Sun May 26 23:57:17 2019)  <- THIS LINE IS SELECTED(*1)
|
```
- tmux choose-buffer -O name
```
 ____________________________________________________________________________
|(0)  buffer0: 3 bytes (Sun May 26 23:57:17 2019)  <- THIS LINE IS SELECTED
|(1)  buffer1: 3 bytes (Sun May 26 23:57:17 2019)
|(2)  buffer2: 3 bytes (Sun May 26 23:57:17 2019)
|
```
- tmux delete-buffer -b buffer0
- tmux choose-buffer -O time
```
 ____________________________________________________________________________
|(0)  buffer2: 3 bytes (Sun May 26 23:57:17 2019)  <- THIS LINE IS SELECTED
|(1)  buffer1: 3 bytes (Sun May 26 23:57:17 2019)
|
```

### Bug?

In window_buffer_init -> mode_tree_build -> mode_tree_set_current(mtd, tag),
tag is 0 since mtd->line_list is NULL.
mode_tree_set_current(mtd, tag=0) sets current to item->order==0 which is oldest item.
I want newest item is selected.

### My hack 1

In window_buffer_build(),  `*tag = data->item_list[0]->order;` before return.

### My hack 2

`static u_int   paste_next_order = 1;` in paste.c.

**Comment by nicm** [comment]
Your first hack is no good because we don't want the current item to be reset to 0 every time it rebuilds (for example of resize). The second one fixes this but not the same for clients.

I think this is a better fix, explicitly choose the first item after calling the build callback if the callback didn't set one: [x.diff.txt](https://github.com/tmux/tmux/files/3220950/x.diff.txt)
~~~~
Index: mode-tree.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/mode-tree.c,v
retrieving revision 1.31
diff -u -p -r1.31 mode-tree.c
--- mode-tree.c	26 May 2019 17:34:45 -0000	1.31
+++ mode-tree.c	26 May 2019 17:57:05 -0000
@@ -384,7 +384,7 @@ mode_tree_build(struct mode_tree_data *m
 	if (mtd->line_list != NULL)
 		tag = mtd->line_list[mtd->current].item->tag;
 	else
-		tag = 0;
+		tag = UINT64_MAX;
 
 	TAILQ_CONCAT(&mtd->saved, &mtd->children, entry);
 	TAILQ_INIT(&mtd->children);
@@ -400,7 +400,10 @@ mode_tree_build(struct mode_tree_data *m
 	mode_tree_clear_lines(mtd);
 	mode_tree_build_lines(mtd, &mtd->children, 0);
 
-	mode_tree_set_current(mtd, tag);
+	if (tag != UINT64_MAX)
+		mode_tree_set_current(mtd, tag);
+	else
+		mode_tree_set_current(mtd, UINT64_MAX);
 
 	mtd->width = screen_size_x(s);
 	if (mtd->preview) {

**Comment by nicm** [comment]
Note I edited my comment, first diff was wrong.

**Comment by koie** [comment]
Thank you.  This patch works fine!

**Comment by nicm** [comment]
Applied now, thanks!
