### ISSUE TITLE
[Feature Request] Optionally enable borders on all sides of all panes

### ISSUE THREAD

**Issue by aste4** [tmux/tmux#1786]
Optionally enable borders on all sides so that it is easier to see which pane is active - motivation: https://superuser.com/questions/547883/tmux-current-pane-border-not-obvious. This coupled with `pane-active-border-fg`

When starting tmux and performing the first vertical split yields:
```
X       (title)
          |
          |
          |
status_bar
```
Requested:
```
X       (title)
+----------+---------+
|          |         |
|          |         |
|          |         |
+----------+---------+
status_bar
```

It would use up 2 rows and 2 columns which leaves less space for code/characters. It might not even look pretty, but I would like to see whether its even practical. I've been looking more at `screen-redraw.c` but couldn't quite figure it out yet. Is it easily feasible?

**Comment by nicm** [comment]
You can get a top or bottom line - turn on pane status lines and make it empty. I don't see a need for empty borders, it's a bit of a waste of screen space.

Not sure how hard it would be to implement, you'd need to change code outside of screen-redraw.c (probably tty.c and screen-write.c and layout*.c as well) in order to handle the extra borders.

**Comment by mk-pmb** [comment]
>  it's a bit of a waste of screen space.

Counter-example: When you use a graphics card not fully compatible with your display, you can have a console with black background, surrounded by black emptiness due to projection settings. (Either because your display limits your options, or because stretch-to-fill would make your font look ugly.) In that case it can be helpful to sacrifice the outer rows/columns for easier visual distance guessing.
