### ISSUE TITLE
tmux start-server doesn't start the server in HEAD

### ISSUE THREAD

**Issue by paulhybryant** [tmux/tmux#182]
Installed tmux through brew install --HEAD
tmux -V shows 2.2

tmux start-server finished with exit code 0
tmux show-options -g failed with no server running on  /tmp/tmux-...

It works in my previously installed version (2.1 I think).

**Comment by ThomasAdam** [comment]
No, see:

`tmux -Lx start \; show -g`

**Comment by paulhybryant** [comment]
Thanks for the reply. It is still not clear to me why the following command returns error?

tmux start-server
tmux list-sessions
no server running on /private/tmp/tmux-180029/default

The only thing in ~/.tmux.conf is 
set-option -sg exit-unattached off

**Comment by ThomasAdam** [comment]
For that reason alone---start-server doesn't create any sessions.

**Comment by paulhybryant** [comment]
And thus the server exits? If so is there a flag / option that prevent the server from exiting in this case? I didn't find such a flag / option in the manual. Thanks you.

**Comment by nicm** [comment]
A tmux server will exit without a session. Create a session and it will
not exit.

**Comment by kchr** [comment]
Sorry for reviving an old thread, but what is the purpose of `start-server` if you can't use it to start a server?

**Comment by kjell** [comment]
I agree this feels bogus. I got around it in my setup script by spawning a ghost window with `sleep 1` to keep the server alive while I spawn a few other sessions. When the `sleep`ing session ends it exits and the other sessions keep the server running.

```
tmux has || tmux start \; new-session -d 'sleep 1'
<spawn your tmux sessions here>
```

And a bit easier way to do this is just starting the desired sessions within the same set of instructions as `start`:

```
tmux start \; new-session -d -s session1 \; new-session -d -s session2
```

**Comment by nicm** [comment]
You do not need to use tmux start if you are using tmux new. new also
starts the server.



On 20 Feb 2017 10:17 pm, "Kjell Olsen" <notifications@github.com> wrote:

I agree this feels bogus. I got around it in my setup script by spawning a
ghost window with sleep 1 to keep the server alive while I spawn a few
other sessions. When the sleeping session ends it exits and the other
sessions keep the server running.

tmux has || tmux start \; new-session -d 'sleep 1'
<spawn your tmux sessions here>

And a bit easier way to do this is just starting the desired sessions
within the same set of instructions as start:

tmux start \; new-session -d -s session1 \; new-session -d -s session2

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/182#issuecomment-281194823>, or mute
the thread

**Comment by vaygr** [comment]
I believe what initially wanted (or might be useful) use case is this:

1. let tmux read default `.tmux.conf`
2. define X number of different sessions
3. start them via `tmux source-file ~/.tmux/session` regardless of tmux server availability

so even when you have `new` in you session files, `tmux source-file` wouldn't work because it expects the server already running.

let's say you want to *declare* sessions without actually starting them in default tmux run (and without using key bindings), how would you do that if not `tmux start \; new [-d]`?

**Comment by cdown** [comment]
In my case, I'd like the server to be able to run without a session so I can have a deterministic systemd unit that controls the tmux server and its children. This seems like a legitimate use case for having the server running with no sessions. Right now I have to create a noop session.

**Comment by danijar** [comment]
Same problem here. I'd like to have a tmux server running without any sessions, so that I later can connect to it when I SSH into my machine. Starting tmux from the SSH client means it gets killed once the SSH session ends. I'm currently using a systemd user service for this which requires creating a dummy session:

```
# ~/.config/systemd/user/tmux.service

[Service]
Type=forking
ExecStart=tmux new -s dummy -d
ExecStop=-tmux kill-server
Restart=on-success

[Install]
WantedBy=default.target
```

**Comment by jackwasey** [comment]
This could be in the man page, which (as of 2.7, on ubuntu disco) still just says:

> start-server Start the tmux server, if not already running, without creating any sessions.

Which resulted in me ending up here.
