### ISSUE TITLE
tmux 3.0: bindkey c-\

### ISSUE THREAD

**Issue by wookayin** [tmux/tmux#1827]
As per in [tmux 3.0 CHANGELOG](https://raw.githubusercontent.com/tmux/tmux/3.0/CHANGES):

> * INCOMPATIBLE: tmux's configuration parsing has changed to use yacc(1). There
  is one incompatible change: a \ on its own must be escaped or quoted as
  either \\ or '\' (the latter works on older tmux versions).

The behavior of parsing `\` is breaking. Well, I understand breaking changes are sometimes necessary -- but then how to bind <kbd>C-\\</kbd> ?

The following is a configuration line that is working well on tmux <= 2.9:
```tmux
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
```

In 3.0, it fails to parse near `\`:
```
.tmux.conf:250: unknown key: C- if-shell
```

I would like to have a configuration file that is compatible with **both 2.x and 3.0** (because `if-else` is not possible in 2.x). I have tried the following but neither one works:

```
bind -n 'C-\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind -n C-'\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
```

Thanks!

**Comment by lacygoill** [comment]
Try this:

    bind -n 'C-\' if-shell "$is_vim" "send-keys 'C-\\'" "select-pane -l"

**Comment by wookayin** [comment]
@lacygoill Brilliant, that works perfectly for both versions. Thank you!

**Comment by nicm** [comment]
It says exactly this in the text you copied.

**Comment by lacygoill** [comment]
The main issue was in the rhs of the key binding, because it contains `if-shell` which I think adds a parsing step (I could be wrong though).

And `if-shell` removes one level of backslashes in the string.
The OP tried to quote the backslash in the lhs:

    bind -n 'C-\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
            ^   ^

    bind -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
              ^^

But in both cases, they forgot, or didn't know, that `if-shell` introduced an additional parsing step, and so they thought they could use the same amount of backslashes in the argument passed to `send-keys`:

    bind -n 'C-\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
                                                  ^^

While in fact, they needed to double the backslashes.
So either of these should work:

    bind -n C-\\ if-shell "$is_vim" "send-keys C-\\\\" "select-pane -l"
              ^^                                 ^^^^

    bind -n 'C-\' if-shell "$is_vim" "send-keys 'C-\\'" "select-pane -l"
               ^                                   ^^

But in both cases, the amount of backslashes in the rhs is doubled compared to the lhs.

Although, now that I think about it, I would not use either of these versions; I would use single quotes around `send-keys`:

    bind -n 'C-\' if-shell "$is_vim" 'send-keys C-\\' 'select-pane -l'
                                     ^              ^

So that tmux doubles the backslashes when it normalizes the key binding in its table:

    $ tmux lsk | grep -i 'c-\\'
    bind-key -T root C-\\ if-shell "send-keys C-\\\\" "select-pane -l"
                                                ^^^^

I've made so many mistakes in the past, in Vim, because of double quotes, that I never use them unless they're really needed.
In tmux, you need double quotes when you refer to an environment variable which must be expanded, or an escape sequence which must be translated.

For example, this would not work, because the single quotes prevent the expansion of `$EDITOR`:

    bind C-g display '$EDITOR'
                     ^       ^

But this would work:

    bind C-g display "$EDITOR"
                     ^       ^

**Comment by lacygoill** [comment]
In any case, in the lhs, either of these should work:

    'C-\'
    C-\\

And in the rhs, either of these should work:

    "send-keys 'C-\\'"
    "send-keys C-\\\\"
    'send-keys C-\\'
