### ISSUE TITLE
[RFE] Add support to serial console

### ISSUE THREAD

**Issue by mperezco** [tmux/tmux#1862]
### Request for Enhancement - Add support to serial console

Being **tmux** the most widely used **screen** replacement it would be nice to have a feature used to manage some serial port attached devices, which is, being able to access and manage it the same way screen does.

```
screen /dev/ttyS0 <speed>
```

Could this be, please considered?

**Comment by nicm** [comment]
No this should not be part of tmux, use a dedicated serial program like cu or minicom.

**Comment by nicm** [comment]
No this should not be part of tmux, use a dedicated serial program like cu or minicom.

**Comment by ThomasAdam** [comment]
Plus, unlike twenty years ago, it's a lot easier to install software now.

**Comment by mperezco** [comment]
Tmux could become the default if it can fully replace screen. 
There proposals are workarounds, they do not solve the problem: replacing screen

**Comment by ThomasAdam** [comment]
Replacing screen isn't the goal for tmux

**Comment by anselal** [comment]
Why did you close this issue? This a feature request, it is not an invalid issue...

**Comment by krader1961** [comment]
It was closed because the feature will not, and should not, be implemented. It is orthogonal to the purpose of the program. It is a feature that should never have been implemented in `screen`. There are many programs dedicated to serial communication and related transfer protocols like zmodem: cu, minicom, kermit, etc. If you need that capability just run one of those programs inside (or outside) a tmux session.

**Comment by anselal** [comment]
Oh k
