### ISSUE TITLE
Text Colors not working at command line

### ISSUE THREAD

**Issue by irrationalnumbers** [tmux/tmux#1908]
I've gone through multiple threads here on the same issue, but I cannot seem to get colors to work for the command line inside of TMUX.  Syntax highlighting works perfectly well in VIM without an issue.  If I use `screen`, command line text colors work without a problem.  I'm running ubuntu 16.04 64bit.

Please see the details below.

Please provide the following information:
* tmux version (`tmux -V`): tmux next-3.1
* Platform (`uname -sp`): Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`): outside(xterm-256color), inside(screen-256color)

Terminal the issue was tested on: terminator, xterm, gnome-terminal
Versions tested: 2.2, 2.9a, 3.0-rc, next-3.1 (logs are from next-3.1)
[tmux-client-25986.log](https://github.com/tmux/tmux/files/3610012/tmux-client-25986.log)
[tmux-out-25988.log](https://github.com/tmux/tmux/files/3610013/tmux-out-25988.log)
[tmux-server-25988.log](https://github.com/tmux/tmux/files/3610014/tmux-server-25988.log)
[tmux.conf.txt](https://github.com/tmux/tmux/files/3610016/tmux.conf.txt)

logs from running clean config as requested (same issue exists):
[tmux-client-25986.log](https://github.com/tmux/tmux/files/3610039/tmux-client-25986.log)
[tmux-out-25988.log](https://github.com/tmux/tmux/files/3610040/tmux-out-25988.log)
[tmux-server-25988.log](https://github.com/tmux/tmux/files/3610041/tmux-server-25988.log)

Thank you

update:
The following screenshot shows what I'm referring to by command prompt or bash colors inside tmux (left) and outside of tmux (right).
![Screenshot from 2019-09-14 02-06-18](https://user-images.githubusercontent.com/41571724/64900904-781a3c80-d694-11e9-82f1-19459638bfd6.png)

**Comment by nicm** [comment]
This doesn't mean anything to me, what command line? What colours?

**Comment by irrationalnumbers** [comment]
updated post with screenshot

**Comment by krader1961** [comment]
Run this from your bash prompt: `echo -e "\e[32mhello\e[0m"`. Is the word "hello" green or orange? If it's green then tmux is correctly handling color sequences and the problem lies elsewhere; e.g., your shell config. If it's orange then something is going wrong when tmux maps its colors to the correct sequence for your terminal.

**Comment by irrationalnumbers** [comment]
Hi Kurtis,
This was in fact green.  Thanks for the troubleshooting support as I was having a hard time narrowing down where to look.  I will look elsewhere to find the underlying cause since it's not related to tmux.

**Comment by krader1961** [comment]
@irrationalnumbers The problem could still, theoretically, be a problem with tmux but that is extremely unlikely. Start by verifying that `$TERM` is actually set correctly by doing `echo $TERM` in both environments. Then compare the output of `env` in the tmux and non-tmux environments. Then compare the output of commands like `set -o`. The likely explanation is that your bash config files (e.g., *~/.bashrc*), or a related script, is incorrectly overriding `$TERM` or otherwise misinterpreting its `screen-256color` value.

**Comment by irrationalnumbers** [comment]
@krader1961 
After your comment I did some digging and it turns out that tmux doesn't appear to be importing alias' that I have in my .bashrc file.  I'm not sure if this is normal, but I tested that my environment variables and other custom awk commands function fine in tmux, but, for instance:

alias ls='ls --color=auto'

is ignored/not applied.  This is my .bashrc at the moment:
BRIGHTNESS=0.8
export TERM=xterm-256color
export TERMINFO=/lib/terminfo
alias ls='ls --color=auto'
pdfmerge() { gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -sOutputFile=$@ ; }

**Comment by krader1961** [comment]
You should never, even if not using tmux, unconditionally do `export TERM=xterm-256color`. You should only export TERM if it is not already set. And if it isn't set that indicates a problem elsewhere.

Your *~/.bashrc* should be read by an interactive shell. However, if `$BASH_ENV` is set then the file it names will be read instead of *~/.bashrc*.

**Comment by psxvoid** [comment]
Hi,

I have a similar issue with tmux 2.6 inside WSL on windows 10 running Ubuntu 18.04.

`echo $TERM` shows `xterm-256color` (without tmux) and says `screen` (with tmux). However, tmux has a green status bar and some commands are highlighted (but not in the same way as without tmux). NeoVim is also outputting perfect colors.

`~/.bashrc` only has this containing $TERM:
````sh
# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac
````

Is there anything I can do to fix it? Is it an issue with tmux?
