### ISSUE TITLE
pasting text on vim with shortcut Command + v.

### ISSUE THREAD

**Issue by carlosjcc** [tmux/tmux#1940]
### Issue description

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

**setting**: vim on tmux
**how to reproduce the issue**: in vim, in `normal` mode, copy text, try to paste it while **still** in "normal" mode with Command + v.
**issue**: the first character of the pasted text (using Command + v) is missing, sometimes more. And vim changes to `insert` mode.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 2.9a
* Platform (`uname -sp`): Darwin i386
* $TERM inside of tmux: screen
* $TERM outside of tmux: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new

vim version: 8.1
[tmux_logs.tar.gz](https://github.com/tmux/tmux/files/3732219/tmux_logs.tar.gz)

**Comment by nicm** [comment]
This log looks fine, assuming you are pasting "abc". This sounds like a vim problem.

**Comment by delphinus** [comment]
It seems your ⌘V did `a` (Append text) and input `bc`. It is not a bug.

**Comment by carlosjcc** [comment]
> This log looks fine, assuming you are pasting "abc". This sounds like a vim problem.

It's not a vim problem cuz it works on vim on terminal (not running on tmux)

> It seems your ⌘V did `a` (Append text) and input `bc`. It is not a bug.
this seems to be the issue, which is not correct, since it works on vim on a terminal

**Comment by krader1961** [comment]
FWIW, I can reproduce this using tmux built from tmux git master branch. I've confirmed that the problem is Vim is not enabling bracketed-paste mode inside tmux.  You can see this by starting vim and typing `:set t_BE?` then press [enter]. If bracketed-paste is enabled you'll see `t_BE=^[[?2004h`. If it isn't you'll see `t_BE=`.  Whether or not it is enabled seems to depend on this symbol in *src/term.h* not evaluating to an empty string:

```
#define T_BE       (TERM_STR(KS_CBE))      /* enable bracketed paste mode */
```

That essentially does a indexed lookup into the `term_strings[]` array which is populated by the `parse_builtin_tcap()` function in *src/term.c*. I've never looked at the vim source before so I gave up at that point. Running `:help bracketed-paste` provides a workaround:

```
If your terminal supports bracketed paste, but the options are not set
automatically, you can try using something like this:

        if &term =~ "screen"
          let &t_BE = "\e[?2004h"
          let &t_BD = "\e[?2004l"
          exec "set t_PS=\e[200~"
          exec "set t_PE=\e[201~"
        endif
```

I recommend taking this up with the Vim project.
