### ISSUE TITLE
How to source an rc or any dotfile across all sessions

### ISSUE THREAD

**Issue by mbkupfer** [tmux/tmux#1965]
### Issue description

How do I source an rc file across all panes (and sessions.) I've tried running `source-file` in tmux but that apparently only works with tmux command syntax since I got an error with the `export` command. 

I understand if this isn't a tmux related issue, but since tmux promotes long running sessions I always run into a situation where I have to make an update one of my dotfiles and have to either source in all other panes or kill the server and restart a session.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
**tmux next-3.1**

* Platform (`uname -sp`).
**Darwin i386**

* $TERM inside and outside of tmux (`echo $TERM`).
 **TERM is set to `xterm-256color`, but I also have the following environment variable from a zsh plugin: `ZSH_TMUX_TERM=screen-256color`. Not entirely sure how that syncs up with tmux nor how it even relates to this issue, but I'm sure that clears up the difference in $TERM**

* Logs from tmux (`tmux kill-server; tmux -vv new`).
**Is this necessary to kill the server given my issue? I would prefer if I didn't have to.**

**Comment by nicm** [comment]
tmux has no control over what shells or any other program inside does or what their environment looks like after they are started.

**Comment by mbkupfer** [comment]
@nicm that is what I figured, but I also can't imagine I'm the only one with this use case. Maybe a better question would be, is there a way to write a script that sources a file in all tmux sessions?

**Comment by krader1961** [comment]
@mbkupfer Sure, that's trivial. Below is an example. The list of windows of tmux windows is hardcoded but that's just because it's from a script I use to execute a suite of unit tests on several VMs. Generalizing it to ask tmux for the list of windows is trivial. Also, note that because you're synthesizing keystrokes this is fragile. If the window doesn't contain a shell waiting for a command random bad things can happen.

```
windows=(macpro osuse freebsd ubuntu fedora mac1012 obsd cygwin wsl)
for window in ${windows[*]}
do
    # Sync the latest source and build it.
    tmux send-keys -t "Project Build:$window" 'ast-sync' C-m
    tmux send-keys -t "Project Build:$window" 'cd ~/projects/3rd-party/ast' C-m
    tmux send-keys -t "Project Build:$window" 'git clean -dfx' C-m
    tmux send-keys -t "Project Build:$window" 'mkdir build' C-m
    tmux send-keys -t "Project Build:$window" 'cd build' C-m
done
```

**Comment by mbkupfer** [comment]
@krader1961 That is very helpful. I think I can take it from here.

As for, 
> If the window doesn't contain a shell waiting for a command random bad things can happen.

Would I be able to programmatically check for this?

**Comment by krader1961** [comment]
> Would I be able to programmatically check for this?

In theory, yes. Use `tmux capture-pane -p -t "Project Build:$window"` to capture the contents of the window. Then parse it to determine if the last thing written is your shell prompt. The problem is how to do so robustly since the prompt won't necessarily be the last line in the window and you might even be doing something like editing a file where the last line in the edit window looks like a shell prompt. I didn't bother to implement that for my use case because the tmux windows I'm sending those synthetic keystrokes to should always be at a shell prompt waiting for input.

And in case it's not obvious what I mean by "random bad things" consider if you're running emacs or vim (or some other editor) in the window and you send a sequence of keystrokes like `source ~/.bashrc`. What will the editor do?
