### ISSUE TITLE
Can many versions installed on one compute ? 

### ISSUE THREAD

**Issue by ShnDanYao** [tmux/tmux#2024]
Can many versions installed on one compute ? 
 if can, how can i manage them?
Since I have no root to the sever compute, I want to install a latest version for my own besides the version already installed.Can I?

**Comment by krader1961** [comment]
> Can many versions installed on one compute ?

Yes, you can install multiple versions of most programs, including tmux. The specifics of how to do so depends on the program.

> if can, how can i manage them?

Using whatever tools are available in your environment. This doesn't have much of anything to do with tmux.

> Since I have no root to the sever compute, I want to install a latest version for my own besides the version already installed.Can I?

Yes, if you can install the tmux source and its dependencies (e.g., a C compiler) and otherwise arrange to run arbitrary commands during the setup of your "sever compute"; by which I think you mean a virtual machine such as a AWS compute node.

**Comment by ShnDanYao** [comment]
thanks very much ~
