### ISSUE TITLE
[Feature Request] Swap pane tree

### ISSUE THREAD

**Issue by cIvanrc** [tmux/tmux#2029]
Hi,
Sadly, I'm not an expert with tmux, so I don't know if my question is stupid.
My question is about if is possible to navigate (to swap) between panes by a tree?

In this way, swap the pane for the selected pane.

*like the image of the bottom.
*the tree in the image is `choose-tree`

**If this behavior doesn't exist, I would like to propose it**

Like the `choose-tree` command, that shows a directory in a pane (and not in the whole window)
it would be like a browser to exchange panes

This will be a big help to swap secondaries panes quickly (logs, console, etc) without leaving the window or the main pane

![image](https://user-images.githubusercontent.com/29314633/71387041-69a6bf80-25b7-11ea-9cf6-c2b9be087bd9.png)

**Comment by nicm** [comment]
This came up recently and I worked on it a bit but it is not easy to do well because of how the tree code works and there are questions about what happens if you move the pane that is currently in tree mode into a different session.

Here is a diff that lets you tag a window and then use 's' to swap it with the currently selected window - but it only works for windows, not panes: [x.diff.txt](https://github.com/tmux/tmux/files/3997944/x.diff.txt)

**Comment by nicm** [comment]
This is already in the TODO file so I will revisit it at some point.
