### ISSUE TITLE
Tmux error reporting changed, not backward compatible for control mode

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#2048]
### Issue description

I built tmux at commit 6b0091e1850d25ccd47143c9df18e1dddef2f4d4.

When I issue a command like `display-message -t '%9' -p '#{pane_current_path}'` in control mode and there is no pane 9, the output is:

```
%begin 1578121968 723 1
%error 1578121968 723 1
can't find pane: %9
```

In tmux 3.0a, the output is correct:

```
%begin 1578121997 262 1
can't find pane: %9
%error 1578121997 262 1
```

The documentation states that the output of a command in control mode is terminated by either `%end` or `%error`.

The consequence is that iTerm2 drops the connection in tmux integration mode during certain race conditions, such as when a pane is closing, and a command referencing a bad number is already in flight.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux next-3.1

* Platform (`uname -sp`).
Darwin i386

* $TERM inside and outside of tmux (`echo $TERM`).
xterm-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-client-98035.log](https://github.com/tmux/tmux/files/4021633/tmux-client-98035.log)
[tmux-server-98037.log](https://github.com/tmux/tmux/files/4021634/tmux-server-98037.log)

**Comment by nicm** [comment]
This is because errors go to stderr but %error goes to stdout. That was always the case but now they can be reordered. I think the best thing to do is just to send everything to stdout in control mode:
~~~~
Index: cmd-queue.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cmd-queue.c,v
retrieving revision 1.78
diff -u -p -r1.78 cmd-queue.c
--- cmd-queue.c	19 Dec 2019 09:22:33 -0000	1.78
+++ cmd-queue.c	4 Jan 2020 18:03:36 -0000
@@ -551,7 +551,10 @@ cmdq_error(struct cmdq_item *item, const
 			msg = utf8_sanitize(tmp);
 			free(tmp);
 		}
-		file_error(c, "%s\n", msg);
+		if (c->flags & CLIENT_CONTROL)
+			file_print(c, "%s\n", msg);
+		else
+			file_error(c, "%s\n", msg);
 		c->retval = 1;
 	} else {
 		*msg = toupper((u_char) *msg);

**Comment by gnachman** [comment]
I can confirm that fixes the issue.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
