### ISSUE TITLE
Vim rendering issue

### ISSUE THREAD

**Issue by Shamaoke** [tmux/tmux#2064]
I observe a rendering issue in Vim when running it as a part of multi-window tmux session, by sending keys to the multiplexer.

Here's an animated image, which demonstrates the issue.

![vim-rendering-issue-in-tmux](https://user-images.githubusercontent.com/625266/73121579-83f40480-3f8c-11ea-9ec1-e46f7137c5c0.png)

On the image I start a tmux session through the following start-up script, which creates two windows and send keys to run Vim in the first one. After I switch to it and move cursor downward the rendering defects start to appear in the Vim window.

```zsh
#! /usr/bin/env zsh

tmux start-server

tmux new-session -d -s sample -n one

tmux send-keys -t sample:1 'ls -1 /usr/bin | vim -' C-m

tmux new-window -t sample:2 -n two

tmux attach-session -t sample
```

Here's the list of the key points.

• The session should contain more then one window;

• The editor should be run by sending keys to the multiplexer (not from the command line);

• The keys shouldn't be sent from the window where the editor is supposed to reside;

• The issue is present when running Vim without configuration (`vim -u /dev/null`);

• The issue is present when running a tmux session without configuration (`tmux -f /dev/null`);

• The issue is present when running tmux inside different terminal emulators (I tried urxvt and [Kitty](https://github.com/kovidgoyal/kitty)).

The issue happens regularly in the aforementioned circumstances. This makes impossible creating custom window layouts which contain Vim as their part.

Linux (Arch); tmux 3.0; Vim 8.2; rxvt-unicode 9.22; Kitty 0.15.1

**Comment by nicm** [comment]
TERM inside tmux? tmux logs?

**Comment by Shamaoke** [comment]
`tmux-256color`

```
1579971229.819196 client started (130160): version 3.0a, socket /tmp/tmux-1000/default, protocol 8
1579971229.819230 on Linux 5.4.14-arch1-1 #1 SMP PREEMPT Thu, 23 Jan 2020 10:07:05 +0000; libevent 2.1.11-stable (poll)
1579971229.819245 socket is /tmp/tmux-1000/default
1579971229.819263 trying connect
1579971229.819326 add peer 0x55e8db315df0: 6 ((nil))
1579971229.819387 sending message 100 to peer 0x55e8db315df0 (4 bytes)
1579971229.819396 sending message 101 to peer 0x55e8db315df0 (22 bytes)
1579971229.819401 sending message 102 to peer 0x55e8db315df0 (12 bytes)
1579971229.819407 sending message 108 to peer 0x55e8db315df0 (11 bytes)
1579971229.819415 sending message 104 to peer 0x55e8db315df0 (0 bytes)
1579971229.819421 sending message 107 to peer 0x55e8db315df0 (4 bytes)
1579971229.819427 sending message 105 to peer 0x55e8db315df0 (15 bytes)
1579971229.819432 sending message 105 to peer 0x55e8db315df0 (38 bytes)
1579971229.819438 sending message 105 to peer 0x55e8db315df0 (19 bytes)
1579971229.819443 sending message 105 to peer 0x55e8db315df0 (942 bytes)
1579971229.819456 sending message 105 to peer 0x55e8db315df0 (20 bytes)
1579971229.819461 sending message 105 to peer 0x55e8db315df0 (11 bytes)
1579971229.819466 sending message 105 to peer 0x55e8db315df0 (15 bytes)
1579971229.819471 sending message 105 to peer 0x55e8db315df0 (15 bytes)
1579971229.819476 sending message 105 to peer 0x55e8db315df0 (13 bytes)
1579971229.819480 sending message 105 to peer 0x55e8db315df0 (21 bytes)
1579971229.819485 sending message 105 to peer 0x55e8db315df0 (34 bytes)
1579971229.819490 sending message 105 to peer 0x55e8db315df0 (13 bytes)
1579971229.819495 sending message 105 to peer 0x55e8db315df0 (16 bytes)
1579971229.819499 sending message 105 to peer 0x55e8db315df0 (17 bytes)
1579971229.819504 sending message 105 to peer 0x55e8db315df0 (47 bytes)
1579971229.819509 sending message 105 to peer 0x55e8db315df0 (23 bytes)
1579971229.819516 sending message 105 to peer 0x55e8db315df0 (36 bytes)
1579971229.819521 sending message 105 to peer 0x55e8db315df0 (23 bytes)
1579971229.819526 sending message 105 to peer 0x55e8db315df0 (27 bytes)
1579971229.819531 sending message 105 to peer 0x55e8db315df0 (10 bytes)
1579971229.819535 sending message 105 to peer 0x55e8db315df0 (52 bytes)
1579971229.819540 sending message 105 to peer 0x55e8db315df0 (11 bytes)
1579971229.819545 sending message 105 to peer 0x55e8db315df0 (8 bytes)
1579971229.819550 sending message 105 to peer 0x55e8db315df0 (18 bytes)
1579971229.819555 sending message 105 to peer 0x55e8db315df0 (11 bytes)
1579971229.819559 sending message 105 to peer 0x55e8db315df0 (17 bytes)
1579971229.819564 sending message 105 to peer 0x55e8db315df0 (41 bytes)
1579971229.819569 sending message 105 to peer 0x55e8db315df0 (31 bytes)
1579971229.819573 sending message 105 to peer 0x55e8db315df0 (12 bytes)
1579971229.819578 sending message 105 to peer 0x55e8db315df0 (23 bytes)
1579971229.819583 sending message 105 to peer 0x55e8db315df0 (267 bytes)
1579971229.819588 sending message 105 to peer 0x55e8db315df0 (54 bytes)
1579971229.819599 sending message 105 to peer 0x55e8db315df0 (26 bytes)
1579971229.819604 sending message 105 to peer 0x55e8db315df0 (18 bytes)
1579971229.819609 sending message 105 to peer 0x55e8db315df0 (16 bytes)
1579971229.819614 sending message 105 to peer 0x55e8db315df0 (17 bytes)
1579971229.819620 sending message 105 to peer 0x55e8db315df0 (19 bytes)
1579971229.819624 sending message 105 to peer 0x55e8db315df0 (15 bytes)
1579971229.819629 sending message 105 to peer 0x55e8db315df0 (15 bytes)
1579971229.819634 sending message 106 to peer 0x55e8db315df0 (0 bytes)
1579971229.819640 cmd_pack_argv: argv[0]=new-session
1579971229.819644 cmd_pack_argv: argv[1]=-d
1579971229.819648 cmd_pack_argv: argv[2]=-s
1579971229.819652 cmd_pack_argv: argv[3]=sample
1579971229.819656 cmd_pack_argv: argv[4]=-n
1579971229.819660 cmd_pack_argv: argv[5]=one
1579971229.819664 sending message 200 to peer 0x55e8db315df0 (36 bytes)
1579971229.819669 client loop enter
1579971229.822926 peer 0x55e8db315df0 message 203
1579971229.822965 client loop exit
```

**Comment by nicm** [comment]
This is the client log, I need the server log, look at https://raw.githubusercontent.com/tmux/tmux/master/.github/CONTRIBUTING.md

**Comment by Shamaoke** [comment]
```
#! /usr/bin/env zsh

tmux -vv start-server

tmux -vv -f /dev/null new-session -d -s sample -n one

tmux send-keys -t sample:0 'ls -1 /usr/bin | vim -' C-m

tmux new-window -t sample:1 -n two

tmux attach-session -t sample
```
By running this script I get the following 6 log files.

[tmux-client-133048.log](https://gist.github.com/Shamaoke/32e5c0bdaff2521ef3ce60840d63efd2)

[tmux-client-133051.log](https://gist.github.com/Shamaoke/eb72794d83030cbb6cdd7a521e2e6762)

tmux-out-133050.log (empty)

[tmux-out-133053.log](https://gist.github.com/Shamaoke/becce470bc21d22c6b7d37ebae7fa033)

[tmux-server-133050.log](https://gist.github.com/Shamaoke/7427e4b7dc40005978ea016734f69ac1)

[tmux-server-133053.log](https://gist.github.com/Shamaoke/dd1f8efbf752465879cd53dea38467b1)

**Comment by nicm** [comment]
I can't reproduce this.

You do not need `tmux start-server` in your script, this is why you have two server logs. You can just remove that line entirely.

Does this still happen if you try with `vim -uNONE`?

If so, does it still happen if you do `pkill -WINCH vim` after attaching tmux but before scrolling vim?

**Comment by Shamaoke** [comment]
I tested the start-up script again, but for this time I removed `tmux start-server` line and instead of Vim, I run another console application — [ncdu](https://en.wikipedia.org/wiki/Ncdu).  The issue is also present there.

```
#! /usr/bin/env zsh

tmux -L sample -vv -f /dev/null new-session -d -s sample -n one

tmux -L sample send-keys -t sample:0 ncdu C-m

tmux -L sample new-window -t sample:1 -n two

tmux -L sample attach-session -t sample
```

Here's an animated image which demonstrates the issue.

[ncdu rendering issue in tmux](https://live.staticflickr.com/65535/49468720547_4fab1b8578_o.png)

Here's a brief description about what is going on. All of the following effects are not normal.

I start a tmux session through a start-up script, which creates two windows and send keys to the first one to run ncdu. When I switch to the first window, which displays a list of directories and files along with their sizes, you already can see the rendering defect ­— it's an empty line between the `/.gem` and `/.texlive` lines.

When I start moving the cursor line, you can see, that the second line (`/.data-lower`) isn't updated — it still displays the highlighted cursor line. Other lines begin to be updated only when I move the cursor line over them. So, `/.downloads` is updated to `/.virtualbox`, `/.cache` to `/.downloads` and so on.

When I move the cursor line to the `/.gem` directory and continue to move downwards, the title bar of the program (the part, where the current working directory, `/home/user`, is displayed) is moving upwards and become hidden behind window borders (normally, the title is fixed and should always be displayed).

After the title has been hidden, the two top lines (`/.data-lower`) stay still and stop to move up and down with the whole window.

Here's the log files, which was compiled, when I recorded the animation.

[tmux-client-71969.log](https://gist.github.com/Shamaoke/93aa9b13baee107236d25942acecac32)

[tmux-out-71971.log](https://gist.github.com/Shamaoke/531db44f4ad5f3c1beb36108fe892a50)

[tmux-server-71971.log](https://gist.github.com/Shamaoke/59d073034ef953882497992741bdd4cc)

I also tested the script once again with Vim running without configuration.

Here's the script.

```
#! /usr/bin/env zsh

tmux -L sample -vv -f /dev/null new-session -d -s sample -n one

tmux -L sample send-keys -t sample:0 'ls -1 /usr/bin | vim -u NONE -' C-m

tmux -L sample new-window -t sample:1 -n two

tmux -L sample attach-session -t sample
```

Here's the resulted animation.

[vim rendering issue in tmux](https://user-images.githubusercontent.com/625266/73547668-79d07b00-4450-11ea-87e1-cc5af75ce2f8.png)

On the animation, I start Vim, which displays a list of files in the `/usr/bin` directory, which was piped to the editor by the `ls` utility. When I switch to the window where Vim resides, you already can see the rendering defect — not all files are displayed, some files at the beginning of the list are skipped, there's an empty space at the bottom part of the window. The editor window begins to be updated only when I start moving the cursor.

Here's the log files, which was compiled, when I recorded the animation.

[tmux-client-71469.log](https://gist.github.com/Shamaoke/ff77d7170d452ca9e23e0579a0837c9a)

[tmux-out-71471.log](https://gist.github.com/Shamaoke/a7e1ef9586ad5e03822f12e6afcd4058)

[tmux-server-71471.log](https://gist.github.com/Shamaoke/e1dd84913756c6eb3520c0ff3129371b)

I want to note, that the programs are started with the default or without any configuration. The script was tested in urxvt and Kitty terminal emulators, and also in the raw Linux console (TTY). The observing effects in these environments are _exactly_ the same as on the animation. These effects don't differ when running the script multiple times, they are exactly the same every time.

Also, these issues appear only when running console programs through the `send-keys` tmux command, from a script or directly from the tmux command line inside an already started tmux session.

Here's a list of tmux, its dependencies and their versions.

_tmux 3.0_

_ncurses 6.1_

_libevent 2.1.11_

_libutempter 1.1.6_

**Comment by nicm** [comment]
Does this still happen with tmux built from master? Does it fix it if you do `pkill -WINCH vim` after attaching tmux? What terminal are you using?

**Comment by nicm** [comment]
Wait, I think I have reproduced it now. I'll get back to you.

**Comment by nicm** [comment]
I am a bit suspicious this is the same as https://github.com/tmux/tmux/issues/2063.

It seems like vim is ending up with the wrong terminal size.

However although I can reproduce, I can't see how it is a problem with tmux - it is definitely setting the size correctly and a test program always shows the size is updated properly and SIGWINCH is received.

Also I can't reproduce with plain `vim` rather than `ls|vim -`, and I can't reproduce if I put a sleep between the send-keys and the attach-session.

So it seems like vim is losing the SIGWINCH when it is started up reading from stdin.

**Comment by nicm** [comment]
I can't reproduce this with neovim so I would suggest you try it instead of vim.

There are a number of issues about problems with both vim and neovim and SIGWINCH, for example:
~~~~
https://github.com/vim/vim/issues/424
https://github.com/neovim/neovim/issues/11066
https://github.com/neovim/neovim/issues/11330

**Comment by Shamaoke** [comment]
@nicm Yes, it seems that Vim (and some other programs) incorrectly determine/don't have enough time to determine the size of the terminal window when starting, so the rendering defects appear. Setting a timeout before attaching a session allows to bypass the issue.

But the thing is, that the code sample, which I gave at the title message is an excerpt from the script generated by [tmuxinator](https://github.com/tmuxinator/tmuxinator), a tmux session manager. Because I use it, I have no control over how a session is started and so have no means to avoid the issue.

The generated script also cannot be generally changed, since the issue affects small subset of software, and the timeout for the most cases is undesirable.

It needs to contact with tmuxinator developers. Perhaps, they can help to develop the solution.

As to NeoVim, I sure can migrate to it, but again this won't solve the problem in general, since some another soft is also affected by this issue.

Thanks for taking the time to this issue. I think, it can be closed. I'll message here if I'll have any progress about the case.

**Comment by nicm** [comment]
It is a bug in Vim, because there is no reason they should not be able to work out the right size, although it takes some care to get it right. I think you need to talk to the Vim developers.

**Comment by jonhoo** [comment]
For what it's worth, I also semi-regularly observe this same issue, and I am using neovim. The issue seems to require (at least in my case) that neovim is launched from a TUI program. I can reliably reproduce it when launching neovim from inside `mutt` _right_ after I start a new `tmux` window with `mutt` in it (subsequent opens of `neovim` from inside the same `mutt` tmux session does not trigger the issue), and it very occasionally triggers if I switch buffers inside of neovim.

Since I can relatively reliably reproduce the issue, how can I help debug it?

**Comment by nicm** [comment]
What do the neovim developers say?

**Comment by jonhoo** [comment]
I haven't filed it as a neovim bug, because it does not happen when `tmux` is not used. Also, as @Shamaoke observed above, it also happens with vim, which makes me think this is likely a tmux issue.

**Comment by nicm** [comment]
Your problem sounds like it is with mutt actually rather than vim, it is mutt that is responsible for resizing the pty running vim, not tmux. Does mutt itself resize properly?

**Comment by jonhoo** [comment]
This also happens outside of mutt, such as occasionally when switching buffers inside of neovim. But again, only inside tmux. And yes, I have never had an issue with the mutt UI itself.

**Comment by nicm** [comment]
Wait, it happens when you don't resize?

**Comment by jonhoo** [comment]
Yes, there is no resizing going on here.

**Comment by nicm** [comment]
Then it is not the same problem, please open a new issue with logs. Don't use mutt, just tmux and neovim.

**Comment by jonhoo** [comment]
There is no resize in the description of this issue either as far as I can tell? But maybe I missed it somehow?

The issue is _much_ harder to reproduce with just tmux and neovim, and I cannot do so reliably. Through mutt I have a particular reproducing sequence that works every time.

**Comment by nicm** [comment]
Read the rest of the comments. This problem is because when you create a detached tmux session with vim and then immediately attach it, the initial size is 80x24 and then it is resized very quickly afterwards. vim is not correctly picking up the resize. If you are not resizing vim or causing it to be resized and if tmux is attached when the problem happens, it is not the same.

**Comment by jonhoo** [comment]
All right, I've been digging some more, and think you may be right that the issue is somehow related to resizing, specifically because it is related to opening a _new_ window. Some more detail on exactly the flow that causes the odd behavior might be useful:

 - I'm running xmonad, and have no other windows open.
 - I have a hotkey that runs
   ```
   alacritty -e tmux new-session -A -s mail /bin/bash -ic mutt
   ```
 - When I start mutt this way, it first displays a message saying that it is connecting to the IMAP server. This message usually appears alone on the _bottom_ of the terminal with nothing else drawn on the screen. But _sometimes_ it instead appears in the _middle_ of the terminal. This suggests that it is indeed somehow getting the wrong window dimensions.
 - The mutt TUI then opens, listing all the messages. That TUI looks fine regardless of where the "connecting" message appeared, and correctly fills the whole terminal.
 - I then press a key to reply to an e-mail, which runs neovim in the same terminal window. **If** the mutt "connecting" message appeared in the middle of the screen, neovim also appears to think the window is half as tall as it really is, which causes some really weird artifacts.

Interestingly enough, switching to a different virtual desktop and back makes neovim then render correctly. As does, for some reason, quitting neovim, which brings back the mutt TUI, and then opening neovim again.

Unfortunately, for whatever reason, I cannot reproduce the issue with `tmux -vv` (though I _can_ reproduce with `-Ltest -f/dev/null`), presumably because there's a race here, and `-vv` slows tmux starting process enough to make the race not happen.

As for my very occasional issues with neovim in isolation, they are rare enough that it _could_ be they only arise after I open/close another xmonad tile, and I just haven't noticed that that was the case. I'm not sure. I will pay more attention the next time it happens.

**Comment by nicm** [comment]
The mutt message appearing in the middle of the screen is not a problem, mutt presumably does not care about the terminal size changing while it is connecting to the IMAP server, or at least does not care enough to move the message. It only matters if the size is still wrong when mutt redraws (eg if it only takes up half the terminal, or puts the bottom status line in the wrong place).

Does this happen if you are creating a new session or only if you are attaching an existing one that previously had a different size?

If mutt draws correctly with the full size of the terminal, then it knows the right size at that point.

If it then starts vim, vim should be able to get the right size from the terminal - if mutt could, then vim could do.

If you run `env -i vim` instead of just `vim`, does the problem go away?

If not, then please try this program: [test-winch.c.txt](https://github.com/tmux/tmux/files/4319152/test-winch.c.txt)

Compile it:

~~~~
mv test-winch.c.txt test-winch.c
make test-winch
~~~~

Then run it exactly as you would vim.

If you can run it and the last line of output does not show the correct terminal size, they this may be a problem with tmux or mutt. If it always shows the correct terminal size, then it is a problem with vim.

**Comment by jonhoo** [comment]
Yeah, you're probably right about mutt not caring, but I figured it might be relevant that neovim renders weirdly if _and only if_ the mutt connecting line appears in the middle.

As an aside, the neovim rendering issue _also_ just occured, and it happened immediate after I had closed an xmonad window in the same virtual desktop, which suggests it is also a resize issue.

I tried test-winch, and _sometimes_ see:
```
start: 51 213
```
and other times see
```
start: 29 88
signal: 51 213
```
Which I suppose then suggests that tmux always eventually sets the right size, and that the issue is with neovim (and vim from the sound of the previous discussion in this issue) not responding to `SIGWINCH` correctly?

**Comment by jonhoo** [comment]
My guess is that this is then related to https://github.com/neovim/neovim/issues/11330.

Thanks for sticking with me in debugging this!

**Comment by nicm** [comment]
Yes in those two cases either:

1) the terminal has the new size already, so no problem;

2) the terminal has the old size when the program starts, but SIGWINCH is later received and after that the size is the new size.

It is almost certainly the second case where vim is not working, it is probably reading the terminal size at startup and then not installing a SIGWINCH handler until afterwards, so there is a race during which size changes can be lost.

**Comment by nicm** [comment]
That's just a guess however, it could be something else.
