### ISSUE TITLE
(issue) image position and scaling on multi-panes

### ISSUE THREAD

**Issue by al-hub** [tmux/tmux#2076]
uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux next-3.2
rxvt-unicode-256color

I've used ranger and w3m in tmux.
It works well on single pane but issued on multi-panes case for image as below,

multi-panes ( ranger, w3m )
![ranger_on_multi_panes_50](https://user-images.githubusercontent.com/56526241/73904850-c13b8900-48e0-11ea-8280-98da1522b0bb.jpg)
![w3m_on_multi_panes_50](https://user-images.githubusercontent.com/56526241/73904874-d0223b80-48e0-11ea-9919-8a0d2798440b.jpg)

single pane
![ranger_on_single_panes_50](https://user-images.githubusercontent.com/56526241/73904896-e03a1b00-48e0-11ea-84d5-c8130c320ff5.jpg)
![w3m_on_single_panes_50](https://user-images.githubusercontent.com/56526241/73904912-e8925600-48e0-11ea-933e-3a5aa0a2e669.jpg)

And I found the similar issues,

Previewed image scaling issue with ranger and tmux panes.
https://github.com/ranger/ranger/issues/480

w3mimgpreview and tmux
https://lists.gnu.org/archive/html/ranger-users/2013-05/msg00001.html

Any advice and suggestions will be greatly appreciated.

**Comment by krader1961** [comment]
This type of issue is why I was skeptical about adding SIXEL support to tmux. See issue #1613. In particular comments such as [this one](https://github.com/tmux/tmux/issues/1613#issuecomment-559070798) by @nicm. Which is not to say it shouldn't be done but clearly doing so in a robust, bug free, manner is going to be extremely difficult and will probably require at least two or three years of work to be reasonably robust. So, @al-hub, while your issue is certainly legitimate given that tmux now attempts to support the SIXEL protocol you need to understand that at this point in time rendering bugs are expected and it may be another year or two before your situation works correctly.

**Comment by nicm** [comment]
The biggest problem with SIXEL is that it is just too slow. The plan was to
convert them to an ASCII representation as soon as they needed to be
redrawn, someone was working on a way to do that but they have not been in
touch for a while.

**Comment by nicm** [comment]
tmux does not support SIXEL at the moment anyway so this is expected.

**Comment by krader1961** [comment]
> tmux does not support SIXEL at the moment anyway so this is expected.

My apologies for implying otherwise. I thought I saw a recent issue/pull-request that implied otherwise. That tmux does not support SIXEL also explains the behavior observed by @al-hub. I was mislead by one of the images that, sort of, implied tmux was relocating a SIXEL image to a particular pane.
