### ISSUE TITLE
Don't monitor activity for one session in a group

### ISSUE THREAD

**Issue by ddickstein** [tmux/tmux#2090]
Say I've created a group with 2 sessions (the session share the same set of windows) and each session is currently viewing a different window (e.g. session A is viewing window 1 and session B is viewing window 2). I have `activity-action other` as a global setting (I think this is the default because I don't touch this setting in my tmux config). If I am working in session A, window 1 and I produce some activity, the window 1 tab of session B lights up, presumably because of my `activity-action other` setting. I do want the `activity-action other` behavior normally, but this notification is spurious. So I'd like to be able to say that for session A activity-action should be other but for session B activity-action should be none. I see ways to set certain options per-window and globally but I don't see (/ haven't figured out) how to set the option for one session and not the other.

**Comment by nicm** [comment]
activity-action is a session option so set it differently on each session?

**Comment by ddickstein** [comment]
Maybe the setting isn't doing what I would expect it to do then. If I set activity-action to none (and also bell-action for good measure) in session B and then in A:1 I press the down arrow on the command line, B:1 still gets highlighted.

**Comment by nicm** [comment]
*-action only affect the actual alert, that is whether there is a bell or a message or both depending on visual-*. The status line changes based on the window flags which are set whatever the options values are.

**Comment by nicm** [comment]
It is difficult to make tmux do what you want automatically because 1) although tmux knows you typed in a pane, it doesn't know whether the activity is a result of that 2) tmux doesn't know which clients you are looking at, so it can't know whether you want to see the activity or not.

It is fairly easy to only show reverse when you want in `window-status-format`, if you can decide how tmux should decide when to ignore the activity flag.

**Comment by ddickstein** [comment]
I don't need tmux to figure out what session I'm looking at - I want to communicate to it that for session B I don't want to see activity notifications.

It sounds like the action settings affect whether a notification is triggered at the source, and as long as it is then it will appear in all sessions. Is that correct? I'm still confused if that's the case though, because if I try setting activity and bell actions to none in both A and B I *still* get a notification in B when I press down in A:1.

**Comment by nicm** [comment]
Each window has a set of alert flags (bell, active, silence). When one is set on a window, tmux triggers a bell, a message or both in every session where this window is linked, including session groups. Exactly what and when happens for each session is controlled by bell-action, activity-action, silence-action and visual-bell, visual-activity, visual-silence.

Separately, when the status line is drawn, the reverse attribute of windows with an alert flag is set in the status line format and style options - by default window-status-activity-style. These are window options so you can't set them per session.

The only thing you can do is turn window-status-activity-style to default and instaed apply the reverse flag in window-status-format for only the sessions you want. For example, you could do something like this and then set the @ignore_alert_flags user option to 1 in the sessions where you don't want them shown:
~~~~
set -g window-status-activity-style default
set -gF @saved_format '#{window-status-format}'
set -g window-status-format '#{?#{&&:#{window_activity_flag},#{?#{@ignore_alert_flags},0,1}},#[reverse],}#{T:@saved_format}'
~~~~

**Comment by ddickstein** [comment]
Can you elaborate on "exactly what happens and when"? Clearly there's some mismatch here between what I expect these settings to affect and what they actually affect. I'd prefer to actually suppress the notification than to hide it with styling.

**Comment by nicm** [comment]
You are confusing the alert action (which is a message or a bell or both) with the style of the window in the status line, they are entirely separate.

**Comment by ddickstein** [comment]
What does setting `activity-action none` mean if not to prevent the flag from being set when there is activity?

**Comment by nicm** [comment]
I already explained this, activity-action controls whether the configured action takes place in each session when activity happens. The nature of the action (bell or message or both) is configured with visual-activity. activity-action none means tmux will not send a bell or a message to any clients attached to that session. This is separate from the formatting of the status line which shows whether the activity flag is set when the status line is drawn, not what action was taken to notify the user when the alert happened.

**Comment by ddickstein** [comment]
I'm really not asking about formatting and the status line. I'm asking about why setting activity-action to none doesn't appear to stop the action (and thus, the notification) from being triggered. I don't see the difference between "prevent[ing] the flag from being set on the window when there is activity," which you said I can't do in your previous comment, and "control[ing] whether the configured action takes place," which is what you said activity-action controls. Is the configured action taking place not the same as setting the flag?

**Comment by nicm** [comment]
You said:

> If I am working in session A, window 1 and I produce some activity, the window 1 tab of session B lights up

This is **not** a message (visual bell) or a bell. And it is not a notification, which is something completely different. **This is the style used for windows that have the activity flag set, it is separate from activity-action.**

> I'm really not asking about formatting and the status line.

You **are** asking about formatting and the status line, because **you cannot control this with activity-action because activity-action controls whether there is a message or a bell in the session, *not* the style of the window in the status line.**

It seems like you are imagining some way you think it should work rather than reading the way I am telling you it actually works.

You have the same window linked into several sessions. When the activity flag is set, the window is shown as reverse in any sessions where it is not the current window. This is *as well as* a bell or message action being taken.

**The cannot control the style of the windows in the status line with activity-action.**

**activity-action controls when tmux sends a message, or a bell - *not* whether the window appears in reverse in any status lines.**

If you want windows with activity not to be shown in reverse, you need to change window-status-activity-style and window-status-format. I have already given you an example of how you can configure this for each session separately.
