### ISSUE TITLE
the command bar should support 'quit' or 'exit'

### ISSUE THREAD

**Issue by the1mills** [tmux/tmux#2105]
Using <kbd>ctrl</kbd>-<kbd>c</kbd> is sometimes dangerous or inconvenient when the window context switches by the OS.  I am looking for `:q` or `:quit` or `:exit` to work to get me out of the menu.

---------------------

![Screenshot from 2020-03-09 11-20-45](https://user-images.githubusercontent.com/2148448/76245402-0eb95780-61f9-11ea-9a1b-77f5449cee17.png)

![Screenshot from 2020-03-09 11-20-32](https://user-images.githubusercontent.com/2148448/76245403-0f51ee00-61f9-11ea-94b4-91d09a452647.png)

**Comment by nicm** [comment]
No I don't like this idea. You can use C-g or Escape if you don't like C-c.

**Comment by the1mills** [comment]
don't be stubborn - please listen to your users.  escape and ctrl-g do not work on my machine. I am running ubuntu with jetbrains terminal emulator.  I am not sure why escape or ctrl-g don't work, but they don't. it is safe to use quit or exit.

**Comment by krader1961** [comment]
Wow! First, `exit` and `quit` are confusing in the command prompt context. Why don't they mean "exit the current session"? Second, if you can use [ctrl-C] you should be able to use [ctrl-G]. Have you confirmed that typing [ctrl-G] doesn't send the ASCII BEL character? If it doesn't, yet [ctrl-C] sends SIGINT, then your terminal environment is seriously FUBAR. Third, it is hard to believe pressing the [esc] key on your keyboard doesn't send an escape character.

Finally, if the problem is that the "window context switches by the OS" then typing anything, including `exit` or `quit`, will cause problems. Consider if the current window is changed to one that is at a shell prompt waiting for you to type a command. Typing "exit" and pressing [enter] will probably cause that shell to exit.

**Comment by the1mills** [comment]
how are they confusing in that context? is `kill-session` confusing in that context? if `quit` or `exit` is confusing in that context, is `exit` confusing in the bash shell context? no it's not anymore confusing than literally anything else.

i don't want to use ctrl-c if I don't have to. unfortunately, for reasons unknown, ctrl-g and escape do not work to get me out of the command prompt in tmux.

**Comment by krader1961** [comment]
You didn't address my final, most important, point. If the window with the keyboard focus is randomly changing then anything you type is likely to cause problems. You need to fix that. But it is also useful to figure out if your terminal is simply incapable of generating [ctrl-G] or [esc], which is very unlikely, or there is a problem with your tmux installation.

Open a new terminal. Do not start tmux or attach to a tmux session. Type `od -tx1` and press [enter]. Now press [ctrl-G] followed by [esc], [enter], [ctrl-D]. You should see something like this:

```
krader@ubuntu1604-32:~$ od -tx1
^G^[
0000000 07 1b 0a
0000003
```

Now do the same thing from a shell prompt inside a tmux session. You should see the same output.

**Comment by krader1961** [comment]
> is exit confusing in the bash shell context?

No, but it means exit the current shell. In the context of a tmux command prompt that could reasonably be interpreted to mean exit the current session; not exit the command prompt.

**Comment by krader1961** [comment]
@the1mills I'm betting you are using vi mode and that `tmux -S show-options -g | grep status-key` returns `status-keys vi`. 

@nicm I can confirm that in vi mode neither [ctrl-G] or [esc] work to cancel the command prompt. In emacs mode both work. This is with tmux built from commit 67d240827 on Dec 24. Too, the man page doesn't mention [ctrl-G]:

```
             The following keys have a special meaning in the command prompt, depending on
             the value of the status-keys option:

                   Function                             vi        emacs
                   Cancel command prompt                Escape    Escape
                   Delete from cursor to start of word            C-w
                   Delete entire command                d         C-u
                   Delete from cursor to end            D         C-k
                   Execute command                      Enter     Enter
                   Get next command from history                  Down
                   Get previous command from history              Up
                   Insert top paste buffer              p         C-y
                   Look for completions                 Tab       Tab
                   Move cursor left                     h         Left
                   Move cursor right                    l         Right
                   Move cursor to end                   $         C-e
                   Move cursor to next word             w         M-f
                   Move cursor to previous word         b         M-b
                   Move cursor to start                 0         C-a
                   Transpose characters                           C-t
```

**Comment by krader1961** [comment]
@nicm I built from the current git  `master` branch, commit 39dc809, and confirmed that in vi mode [esc] and [ctrl-G] still cancel the command prompt with `set-option -g status-keys emacs` but not `vi`.

@the1mills This illustrates why it is important to understand the problem before proposing a solution. If vi status-mode is fixed is there any reason @nicm's answer isn't satisfactory?

**Comment by krader1961** [comment]
It looks like the bug is in `status_prompt_key()`, or possibly `status_prompt_translate_key()`, since the former only calls the latter when in vi mode:

https://github.com/tmux/tmux/blob/39dc80975144692e0fbbc562ac3b0dff7a7f8271/status.c#L942-L952

It's not at all obvious from a casual review of the code why those translations are needed or correct. In fact, instrumenting the code shows that at least for the [esc] key the problem is here:

https://github.com/tmux/tmux/blob/39dc80975144692e0fbbc562ac3b0dff7a7f8271/status.c#L752-L755

That block of code results in the [esc] keypress being ignored while in status-mode == vi.

**Comment by nicm** [comment]
We should map q to C-g with vi keys really.

**Comment by nicm** [comment]
We can't add Escape for vi keys of course because that switches mode. I don't see any other obvious analogue in vi or ksh.

I don't think there is any harm in adding `C-g` for vi keys, it seems to do something in vi ("show status"?) but nothing tmux is likely to care about.

We can add `q` in command mode which looks like it is unbound in vi by default and matches copy mode anyway.

Of course you can always do `Enter` with an empty prompt without entering anything and the command prompt will close.

Try this please:
~~~~
+++ status.c    12 Mar 2020 06:32:20 -0000
@@ -733,6 +733,7 @@ status_prompt_translate_key(struct clien
        if (c->prompt_mode == PROMPT_ENTRY) {
                switch (key) {
                case '\003': /* C-c */
+               case '\007': /* C-g */
                case '\010': /* C-h */
                case '\011': /* Tab */
                case '\025': /* C-u */
@@ -812,6 +813,9 @@ status_prompt_translate_key(struct clien
                return (1);
        case 'p':
                *new_key = '\031'; /* C-y */
+               return (1);
+       case 'q':
+               *new_key = '\003'; /* C-c */
                return (1);
        case 's':
        case KEYC_DC:

**Comment by nicm** [comment]
I have applied this now.

**Comment by the1mills** [comment]
@krader1961 unimaginative - when I type :quit  it could be in the wrong window, but it be much more obvious -  the letters "q u i t" would literally appear or not appear in the right window. with ctrl-c it is not a visible character, so it's not possible to verify that I am typing in the correct context/window. come on man.
