### ISSUE TITLE
getting tmux to use existing domain socket without changing permissions

### ISSUE THREAD

**Issue by godmar** [tmux/tmux#2110]
First, my apologies for what is likely a "how do I?" question rather than a bug.

I'm using tmux 1.8 (on CentOS 7, a machine I do not manage).

I am creating a Unix socket, change its permissions to 0700, then run tmux.
The permissions are reset to 0770, making the session available to anyone in my group.

```
mksock() { 
    SOCK="$1" python -c "import os, socket as s; s.socket(s.AF_UNIX).bind(os.environ['SOCK'])"; 
}

SOCKNAME="/tmp/tmux-socket"

mksock ${SOCKNAME}
chmod 0700 ${SOCKNAME}

tmux -S ${SOCKNAME} new -s shared
rm ${SOCKNAME}
```

When I run this script, however, I end up in a tmux session and:

```
$ ls -l /tmp/tmux-socket 
srwxrwx--- 1 me mygroup 0 Mar 11 23:28 /tmp/tmux-socket
```

This means that everyone in 'mygroup' is able to `tmux -S /tmp/tmux-socket attach -t shared`, which is somewhat unexpected. For instance, on a shared server, the user may be in a group "Majors" along with hundreds of other users.

Looking at the code, I see an [unlink() call](https://github.com/tmux/tmux/blob/03945276f7010a69969714f8b581d68ee9ff92ba/server.c#L114).

The reason I came across this is because I would like to create a bash script that starts a tmux session in a way that a specified user or group of users is allowed to share the session by giving them access to the domain socket via setfacl.  This works once the session is in progress, that is, I can do:

```
chmod g-rwx /tmp/tmux-socket
setfacl -m u:blabla:rw /tmp/tmux-socket
```

My question is: how do I set this up before starting the session and get tmux to respect the permissions? Thank you.

**Comment by krader1961** [comment]
> how do I set this up before starting the session and get tmux to respect the permissions?

The behavior you're seeing is due to `server_update_socket()` in file *server.c*:

https://github.com/tmux/tmux/blob/39dc80975144692e0fbbc562ac3b0dff7a7f8271/server.c#L289-L323

This isn't a bug in the usual sense; i.e., behavior that doesn't match the documentation. It might be considered a design deficiency that tmux doesn't allow the user to control the permissions of the tmux socket. It's not clear why that function forces the group permissions to mirror the user permissions. Presumably @nicm found a situation where not mutating the permissions in that manner caused problems. Most likely because someone had done `umask 0077` before starting the tmux server which caused their coworkers to be unable to attach to their tmux server.

**Comment by nicm** [comment]
Shared primary groups are poor practice.

Kurtis you are not reading the code correctly, the function you show is only setting g+x if g+r is already set.

The reason the group permission is returned is because when tmux binds to the new socket In `server_create_socket` it does:
~~~~
mask = umask(S_IXUSR|S_IXGRP|S_IRWXO);
~~~~
If you remove this line, tmux will use your existing umask and you will be able to control the socket permissions with umask like other new files. Since you have a shared primary group I assume you have umask 077.

Alternatively you can chmod the socket after it has been created, although obviously that leaves a small period when it is open.

The reason we include g+w is so people can share sockets however I'm not actually convinced it is a good idea now, it was changed a long time ago. I'm not sure it is a good idea not to set umask either...

**Comment by nicm** [comment]
We you will need to remove that line and the later one that does `umask(mask)`.

**Comment by nicm** [comment]
OK, I have remembered how this works.

The reason we do this is that people can share sockets, yes. And it is safe by default because the socket is created inside a directory which is created with 0700 permissions:
~~~~
        if (mkdir(resolved, S_IRWXU) != 0 && errno != EEXIST)
                goto fail;
~~~~
So unless you change permissions on the directory, other users cannot connect to your socket.

I think perhaps we should not change umask for new sockets if the user gives `-S` since in that case they are creating the socket outside of the directory and probably want their own umask. Or it would be safer to give a 077 umask in that case and require the user to chmod the socket themselves if they want it more open.

However, since you are using tmux 1.8 you wouldn't see any benefit from this change even if we made it. The easiest thing for you to do is to use `-L` instead of `-S` for your new socket (something like `-Lpython` instead of `-L/tmp/tmux-socket`) which will create a second socket inside the directory in /tmp so it will be protected by the directory permissions.

**Comment by nicm** [comment]
Try this please against master to create sockets started with `-S` with umask 077: [x.diff.txt](https://github.com/tmux/tmux/files/4322691/x.diff.txt)

**Comment by nicm** [comment]
Oh if you don't want to use `-L` you could use `-S` but create the socket inside a directory with the permissions you want, the same as tmux does.

**Comment by nicm** [comment]
I have applied this change to OpenBSD now, it will be GitHub later. So in summary with 1.8 you have the following options:

- Wait until the change reaches GitHub then build tmux from master where sockets given by `-S` are created with umask 177 rather than 117.

- Use `-S` but put the socket in a directory with safe permissions like tmux does.

- Use `-L` instead of `-S` so the socket goes into tmux's directory in /tmp.

I'm closing this issue now but do reply if you have further questions.
