### ISSUE TITLE
Mouse movement tracking not disabled on exit

### ISSUE THREAD

**Issue by andygoth** [tmux/tmux#2116]
When exiting tmux after having opened the right-click menu at least once, mouse tracking stays enabled. This results in garbage being "typed" into the terminal when the mouse is moved or clicked.

The problem does not occur when exiting tmux without ever having used the right-click menu. Rather, tmux successfully clears mouse tracking before termination. Thus, the easiest way to reproduce the problem is to start tmux then use the right-click menu to kill the one and only pane.

Recovery methods: run "`reset`" or "`echo -en '\e[?1003l'`", or restart tmux then exit without right-clicking, or restart the xterm.

```
$ uname -sp && tmux -V && echo $TERM
Linux Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
tmux 3.0a
tmux-256color
```

I doubt it matters, but I'm testing with LXTerminal 0.3.2.

I used the "`script`" program to log the terminal output of tmux. This showed **CSI**`?1003h` is sent when the menu is posted, so that mouse dragging and movement may be tracked, but **CSI**`?1003l` is not sent when the menu is closed, nor at any time afterward. It is, however, sent during tmux startup.

**Comment by nicm** [comment]
This seems like a problem in the terminal, tmux assumes that mouse modes are exclusive (apart from SGR mouse mode). If you turn on mouse mode 1003 and then turn on 1000, 1003 will be turned off and replaced with 1000. So when you close the menu, since you are going from mouse 1003 to mouse 1000, tmux will only enable 1000 rather than clearing 1003 and then enabling 1000.

This is how xterm works and it doesn't make sense to me that a terminal would work otherwise, so I think the terminal is at fault here.

We should probably clear 1003 on exit however, because it may still be the only bit set. Although in the case of menus it should have been disabled already when the menu was closed.

**Comment by nicm** [comment]
I have changed tmux to turn off 1003 as well when the client exits, which will fix your problem. You will still be getting a lot of spurious mouse events (which tmux will hide from you) because it assumes that only one mouse mode can be active at a time.

We could change to turn off each mode individually and TBH it wouldn't really hurt anything, although it would be nice to hear from the terminal developers if there is a reason why they do it this way. I think LXTerminal is VTE... @egmontkob?

**Comment by egmontkob** [comment]
We indeed do it differently in VTE than xterm does. I had the impression that 1002 / 1003 were extensions on top of 1000; apparently it's not the case, it seems now that 1000, 1002 and 1003 are three exclusive modes in xterm.

With the `h` and `l` ("high" and "low") trailing letters, combined with possibly also supporting `s` and `r` ("save" and "restore") this radiobutton approach is a bit weird to me, also it's not fully clear how saving/restoring is exactly supposed to work. With an interface like this (high/low/save/restore) it would be much clearer to me to have independent switches, and the current behavior be derived from these booleans. This is I think what VTE does, but not what xterm.

The details aren't clearly documented in xterm; and I think we never cared to study the exact behavior (or the source) – and I'd bet other terminals don't exactly copy xterm either.

It's unclear to me what the "correct" solution would be. I don't know who invented these 1000, 1002, 1003 modes; was it xterm? Probably it was. I find the arguments "terminals should copy xterm" and "apps should switch off everything that they switched on" about equally strong.

(LXTerminal is VTE, but depending on a compile option, it can be the ancient unsupported GTK2-based version, or the new GTK3-based one.)

**Comment by nicm** [comment]
I think they were invented by xterm.

All the terminals I have here behave like xterm, but treating them individually like VTE is a natural enough assumption if you don't check, so you are probably not alone.

TBH I don't think it really matters. If many other programs apart from tmux cared you would probably have heard about it by now. I'll just change tmux to turn them off individually and not assume they are exclusive.

**Comment by nicm** [comment]
I have changed this now, it will be in GitHub in a few hours when it syncs. Please let me know if you continue to see problems.

@egmontkob my feeling is that it would be sensible for you to follow xterm on this, particularly since you reuse TERM=xterm - there is not really any reason to diverge on this. But if it was going to be a big problem you would have heard of it by now so it probably doesn't matter that much.

**Comment by houglum** [comment]
Thanks for fixing this in https://github.com/tmux/tmux/commit/7cae4e8e89a98329843e3df8b3644f501288256b!

For anyone else also running into this and waiting on the 3.1 release, a workaround is use the `reset` command in your terminal.
