### ISSUE TITLE
Scrolling in default mode

### ISSUE THREAD

**Issue by toddyamakawa** [tmux/tmux#2134]
### Feature request

It would be useful to have the ability to scroll in default mode. I see two ways this could be accomplished:

1. `tmux scroll-up` would be available in default mode 
1. Creating a new `tmux set-scroll-position` function. It could accept relative or absolute positions.

One common use case is if I run a command like `ls` and then I want to `cat 14599.log 9731.log 4359.log` but I accidentally cleared the screen. Now I either have to run `ls` again to find the filenames or scroll up. If I were outside of tmux, I could just scroll up in the terminal window, but in tmux I'm stuck in copy mode. I can't type while I'm in copy mode.

(Note: `ls` is just a basic example. Imagine if it were a long running command, or if it were a command that I ran again it might have different results like `ps -ef`)

**Comment by nicm** [comment]
I don't understand what you mean. You want to be able to scroll up and then type stuff in without seeing what you are typing? How is that any more convenient than just scrolling up, copying what you want and then pasting it?

**Comment by toddyamakawa** [comment]
> I don't understand what you mean. You want to be able to scroll up and then type stuff in without seeing what you are typing?

I didn't think about the use case of typing without seeing stuff, but that probably doesn't make sense. Imagine if you run `clear` in your terminal emulator. You can then scroll up to and type without resetting your scroll position.

> How is that any more convenient than just scrolling up, copying what you want and then pasting it?

To be honest, I rarely use copy-mode. I use a plugin very similar to [tmux-fingers](https://github.com/Morantron/tmux-fingers). The main problem is what if I `clear` my screen and need to copy multiple things? Do I enter copy-mode and paste each one one thing at a time? Do I copy each thing into the buffer and then paste each buffer one at a time? What if copy/paste isn't good enough? What if I need to open files in multiple directories but the relative path is different than what I copy? At that point it's easier to type everything out with tab completion or fzf.

The problem is in order to know what I need to open, I need to enter copy mode to find what I'm looking for, quit copy mode, type what I was looking for, and repeat for each item. It would be a lot easier if I could just scroll up.

I realize that clearing the screen might not be common for a lot of people, but I do it a lot. I have the `<Enter>` key mapped to clear my screen if I don't specify a command. My workflow involves constantly resizing panes, so if I resize a pane down to a height of 1 and back to full height, then it effectively clears the screen.

Does that make sense? I definitely want to see what I'm typing, so it makes sense if the relative scroll position can't exceed the height of the pane.

**Comment by nicm** [comment]
I don't have any terminal emulators here where I can scroll up once I have cleared and still type without the scroll position going back to the bottom, that seems like very unusual behaviour.

I wouldn't object to having a way to trim empty lines from the bottom of the terminal, so you can recover up to the visible height of the terminal from the history. But it seems a bit obscure, I'm not sure many people will use it, especially since you won't be able to restore more than the visible height of the terminal. It seems like it would be better not to clear everything in the first place.

I'm not interested in doing too much to duplicate things you can already do with copy mode however.

Resizing a pane to 1 line in height in tmux and then making it bigger again does not clear it, I don't know why that is happening for you.

The problem of copying multiple items from copy mode is an interesting one. I can think of some ideas there:

- It would be nice to be able to remember the position in copy mode and go back to the same place when entering it again, although there questions about it would work with scrolling.

- It would be nice to be able to enter copy mode on pane X in pane Y or a new (perhaps empty) pane, so you could eg use pane 2 to copy from pane 1 while still being able to see pane 1.

- It would be nice to be able to build a paste buffer in copy mode by  doing multiple copies. I don't think this would be too hard to implement TBH.

I don't know what other terminals do here.

**Comment by nicm** [comment]
You can try this which adds `resizep -T` to trim lines below the cursor and pull lines down from the history which will let you "undo" a clear: [x.diff.txt](https://github.com/tmux/tmux/files/4403529/x.diff.txt)

**Comment by toddyamakawa** [comment]
> It seems like it would be better not to clear everything in the first place.

Yeah. At the moment resizing my panes down to a height of 1 works really well in my workflow except for the fact that it effectively clears the screen. I can't think of an easier/better way to do this at the moment.

> Resizing a pane to 1 line in height in tmux and then making it bigger again does not clear it, I don't know why that is happening for you.

I'm able to consistently reproduce this behavior. I'm definitely doing some things I haven't seen in other people tmux.conf files though:
https://github.com/toddyamakawa/tmux-prefixless/blob/master/scripts/key-bindings.bash#L65

> It would be nice to be able to remember the position in copy mode and go back to the same place when entering it again, although there questions about it would work with scrolling.

It sounds like for this to work, there would have to be a new command or flag to jump the cursor back to that position in copy mode.

> It would be nice to be able to enter copy mode on pane X in pane Y or a new (perhaps empty) pane, so you could eg use pane 2 to copy from pane 1 while still being able to see pane 1.

True, this is basically possible already. I can copy things from one pane to another, and then copy it back to the original once I leave copy mode.

> It would be nice to be able to build a paste buffer in copy mode by doing multiple copies. I don't think this would be too hard to implement TBH.

Would this be like adding an `append-buffer` command? That sounds pretty useful to me.

> I don't know what other terminals do here, if anything.

I guess with other terminals I would just highlight what I want to copy with the mouse and middle click to paste, and I can repeat that as many times as I want.

> You can try this which adds resizep -T to trim lines below the cursor and pull lines down from the history which will let you "undo" a clear: x.diff.txt

This works perfectly! 👍

**Comment by toddyamakawa** [comment]
> Resizing a pane to 1 line in height in tmux and then making it bigger again does not clear it, I don't know why that is happening for you.

I did a couple more tests in commit `58886515` with the patch you sent me and I notice something. Firstly note that I run the following:
```
tmux \
	bind-key -n M-k 'resize-pane -y 1 ; select-pane -U ; resize-pane -y 999' \; \
	bind-key -n M-j 'resize-pane -y 1 ; select-pane -D ; resize-pane -y 999'
```
Basically every time I leave a pane, I resize it down to height 1, and then I maximize the size of the pane I enter.

If I have two panes open:
```
1
----
2
```
If I start in pane 1, and then go down then down again to end up back in pane 1, the first time it doesn't clear the screen. But the second time I go down-down it does. I also notice if I switch really quickly down-up then it doesn't clear the screen, but if I switch down-pause-up it does.

**Comment by nicm** [comment]
Does it still clear if you run cat in the pane instead of leaving it at
your shell prompt?

**Comment by toddyamakawa** [comment]
> Does it still clear if you run cat in the pane instead of leaving it at
> your shell prompt?

Good point. I should mention that while commands are running, I don't think I've ever experienced the pane getting cleared. I just tested it with `cat` and the pane does not get cleared. The same is true for other long running commands or things like `tail -f`.

**Comment by nicm** [comment]
OK then it seems like the clearing on resize is a problem with your shell rather than with tmux.

**Comment by nicm** [comment]
It seems like you would be better to zoom the pane rather than resize the other to size 1.

**Comment by nicm** [comment]
I have applied this -T diff now to OpenBSD, it will be in GitHub later on. I have added the other three things to the todo list. Some replies:

 >> It would be nice to be able to remember the position in copy mode and go back to the same place when entering it again, although there questions about it would work with scrolling.

>It sounds like for this to work, there would have to be a new command or flag to jump the cursor back to that position in copy mode.

Yes a command or a flag to copy-mode. The biggest difficulty is what happens if the pane scrolls while outside copy mode, but I think we'd have to see how it works in practice to decide what to do there.

>>It would be nice to be able to enter copy mode on pane X in pane Y or a new (perhaps empty) pane, so you could eg use pane 2 to copy from pane 1 while still being able to see pane 1.

> True, this is basically possible already. I can copy things from one pane to another, and then copy it back to the original once I leave copy mode.

Yes, it would be simpler if you could just do eg `splitw -h '' ; copy-mode -t{up} -Xyz` or whatever and it would open a new temporary pane with your current pane's history. I think this will happen if we get copy mode able to take a snapshot of the history when it is entered.

>> It would be nice to be able to build a paste buffer in copy mode by doing multiple copies. I don't think this would be too hard to implement TBH.

> Would this be like adding an append-buffer command? That sounds pretty useful to me.

`append-selection` and `append-selection-and-cancel` already exist, I was thinking of something more sophisticated but probably not going to happen in the short term anyway.

>>I don't know what other terminals do here, if anything.

> I guess with other terminals I would just highlight what I want to copy with the mouse and middle click to paste, and I can repeat that as many times as I want.

Right, you can do the same with tmux too. But both tmux and all the other terminals I'm aware off will scroll back to the bottom when you paste (middle click or otherwise) so you can't do multiple copies like this without scrolling back to find what you want to copy again.

**Comment by nicm** [comment]
If you now build tmux from master, you can do something like this:
~~~~
bind C {
        splitw -f ''
        set-hook -p pane-mode-changed 'if -F "#{!=:#{pane_mode},copy-mode}" "kill-pane"'
        copy-mode -s'{last}'
}
~~~~
Which will make `C-b C` (`C-b S-c`) open a new pane with the history from the current pane, so you can copy from that while still typing and pasting into the original pane.
