### ISSUE TITLE
Unicode codepoints greater than or equal to U+10000 mangled on input on Cygwin

### ISSUE THREAD

**Issue by lalbornoz** [tmux/tmux#2153]
### Issue description

Unicode codepoints greater than or equal to U+10000, such as the majority of Emojis, are mangled on input on Cygwin. This invariably occurs on account of Cygwin's 16-bit wide wchar_t[1], resulting in silent truncation of the upper 16 bits of such codepoints as encoded in UTF-16, regardless of locale and/or command-line arguments such as ``-u``, i.e. w/ "😀" (U+1F600:)

![tmux_cygwin_wchar_screenshot](https://user-images.githubusercontent.com/17064903/78504442-98633300-776d-11ea-8ecd-da73926de9f3.png)

This [patch](https://github.com/tmux/tmux/files/4434327/tmux-3.1-rc3%2Bcygwin_wchar_t.patch.txt) fixes this by using ``uint32_t`` instead of ``wchar_t`` on Cygwin wherever required.

### Required information

* tmux version: tmux 3.1-rc3
* Platform: CYGWIN_NT-6.3 unknown
* $TERM inside and outside of tmux, resp.: screen, xterm
* Logs from tmux, generated w/ ``tmux kill-server; tmux -vv new``:
[tmux-client-25086.log.txt](https://github.com/tmux/tmux/files/4434337/tmux-client-25086.log.txt)
[tmux-out-25088.log.txt](https://github.com/tmux/tmux/files/4434338/tmux-out-25088.log.txt)
[tmux-server-25088.log.txt](https://github.com/tmux/tmux/files/4434339/tmux-server-25088.log.txt)

## References
[1] <https://lists.gnu.org/archive/html/bug-coreutils/2011-01/msg00090.html>

**Comment by nicm** [comment]
I'm not going to scatter ifdefs all over the place because Cygwin can't implement wchar_t properly.

But I think we could probably convert wchar_t to uint32_t or wrap it in a unicode_char typedef or something for all platforms, since we only support Unicode and UTF-8.

However, Cgywin's mbtowc is broken (it returns the result in two pieces) so first we need a compat/cygwin_mbtowc.c with a wrapper than handles that. So I suggest looking at that first :-).

**Comment by lalbornoz** [comment]
1) tmux support for >=U+10000 code points on Cygwin
2) No tmux support for >=U+10000 code points on Cygwin

Pick one. I don't work for free.
