### ISSUE TITLE
Making tmux sessions after 3.1 upgrade results in permissions errors on Mac

### ISSUE THREAD

**Issue by geowa4** [tmux/tmux#2184]
### Issue description

After running `brew upgrade tmux` this morning, I could no longer create tmux sessions. I have a simple workaround so this is more of an informational message to others in the same situation I was this morning. Feel free to close unless you think there's something worth fixing.

This is the error I was seeing.

```bash
tmux new
error creating /private/tmp/tmux-503 (Permission denied)
```

The workaround was pretty straightforward once I saw in the changelog that some things changed with socket management.

```bash
sudo rm -rf /private/tmp/tmux*
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
tmux 3.1

* Platform (`uname -sp`).
Darwin i386

* $TERM inside and outside of tmux (`echo $TERM`).
xterm-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).
error creating /private/tmp/tmux-503 (Permission denied)
error creating /private/tmp/tmux-503 (Permission denied)

**Comment by nicm** [comment]
Nothing changed with sockets between 3.0a and 3.1 and even the change in master only affects `-S`.

**Comment by Dovermore** [comment]
This fixed the immediate exit issue for me. Though I didn't upgrade my tmux to head.

Somehow one of my `dylib` went not found when I run tmux. (I forgot which one..)
After running `brew doctor` and manually linking some libraries, my tmux starts to exit immediately upon launching. (log file has no obvious error)
Upgrading to `HEAD` does not help to resolve this issue (I then reversed back to 2.9)
The command `sudo rm -rf /private/tmp/tmux*` successfully cleared the problem.

This is probably an issue caused by some updates in other programs. The only notable update I had recently was java. Do tmux depend on java?

**Comment by nicm** [comment]
> Also when using HEAD build, upon successful login there will be a 6c in my command line input. This is probably something todo with .tmux config I am using.

Open another issue with logs please.
