### ISSUE TITLE
Searching a pane's content (search-backward command) can hang tmux completely

### ISSUE THREAD

**Issue by ddelnano** [tmux/tmux#2203]
### Issue description

When searching backward in a pane a user can lock tmux up completely by searching for `()`. The tmux server will consume a large amount of CPU and it seems to never recover from this. I had to `kill -9 PID` and start a fresh tmux server.

### Reproducing
1. Start tmux
2. Type the following commands `Prefix-[ + ?` (search-backward)
3. Type `()` in the `(search up)` line
4. Press Enter
5. Notice that tmux server consumes lots of CPU and remains blocked indefinitely.

### Required information

Please provide the following information:

* tmux version (`tmux -V`) -- **3.1b**
* Platform (`uname -sp`). -- **Linux unknown**
* $TERM inside and outside of tmux (`echo $TERM`)
** inside -- **screen-256color**
** outside -- **xterm-kitty**
* Logs from tmux (`tmux kill-server; tmux -vv new`) -- I did not collect logs but I did recompile tmux with debug symbols and recorded a flamegraph to hopefully spot what function was hung. However, I didn't have much luck interpreting it.

[tmux-server-flamegraph-svg.zip](https://github.com/tmux/tmux/files/4601656/tmux-server-flamegraph-svg.zip)

**Comment by nicm** [comment]
Yes, nice one. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/4603004/x.diff.txt)

**Comment by ddelnano** [comment]
@nicm thanks for the quick fix! I have verified that the patch works :ok_hand:

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by balta2ar** [comment]
I'm still experiencing significant performance regressions with search and navigation. I've just checkouted e71c5efd and recompiled.

My current tmux window shows the following when I enter scroll mode: (229 results) [4515/45261]
Two scenarios:
1. I search for something forward or backward direction and then I just press and hold `n` key without releasing. tmux instantly becomes irresponsive. When I release the key it takes several seconds for tmux to become responsive again. For comparison, I saved that buffer with 45261 lines into a file and tried searching in neovim -- it's always responsive and fast.
2. After I searched for something, I scroll the screen using arrows (up and down). Until the cursor is within the screen, performance of navigation is fine, but once the screen needs a redrawal, it gets suddenly worse. Just press and hold Up arrow, for example. It's important that you're in search mode -- otherwise scrolling is fast.

**Comment by balta2ar** [comment]
I used default search settings, which I believe use regexp engine now. I tried binding `?` and `/` to `-text` and `-incremental` but all of them are noticably slow:
```
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-text \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-text \"%%%\""
```

**Comment by balta2ar** [comment]
Gentle ping @nicm.

**Comment by nicm** [comment]
Open a new issue please.
