### ISSUE TITLE
'%' for previous matching bracket with vi mode-keys does not work

### ISSUE THREAD

**Issue by chrisbarber** [tmux/tmux#2204]
### Repro

```
setw -g mode-keys vi
```
Go into copy mode, move cursor to `x` or `)` on a line like:
```
....(....x.....)....
```
and press `%`. Expected: cursor should jump back to `(`. Actual: none.

### More info

So it looks like a simple matter of the condition here https://github.com/tmux/tmux/blob/5e97d79eb1337db2dd5969fb2c339d14427f545b/window-copy.c#L1368-L1370 getting reversed as you were cleaning up #1666.

I pulled master and tested with the following variations but I honestly have no clue which is correct since I only understand the last part of the condition:
* Invert the whole condition
```C
				if (!(gc.data.size != 1 ||
				    (gc.flags & GRID_FLAG_PADDING) ||
				    strchr(close, *gc.data.data) == NULL))
```
* Invert just the last one
```C
				if (gc.data.size != 1 ||
				    (gc.flags & GRID_FLAG_PADDING) ||
				    strchr(close, *gc.data.data) != NULL)
```
Both work to fix my simple repro example above, so hopefully what is correct regarding the other conditions will be obvious to you.

Maybe I should have added another comment somewhere in there when originally looking at this in #1666, besides the one comment [here](https://github.com/tmux/tmux/blob/5e97d79eb1337db2dd5969fb2c339d14427f545b/window-copy.c#L1353-L1355). But basically the situation is like the cursor is on `x`
```
......x.......)....
```
The outer for-loop has advanced us to `)`. Then we do `window_copy_cmd_previous_matching_bracket`. But here that will *fail*, and we will still be sitting on `)`. In that case `strchr(close, *gc.data.data) != NULL` and we restore the cursor back to original position `x`. It would also work to test `strchr(open, *gc.data.data) == NULL`, but I'm not sure if it's any clearer.

### Required information

Please provide the following information:

* tmux version: 3.1b or master

**Comment by nicm** [comment]
The first two parts of the condition make sure that it is sensible to look at *gc.data.data: if size != 1 then doing the strchr with just the first byte would be wrong; and if it is a padding cell (GRID_FLAG_PADDING) is set, then the data is meaningless.

**Comment by nicm** [comment]
So at the moment the condition is saying "this is not a closing bracket".

**Comment by nicm** [comment]
I think you are saying that the condition should be "if this IS a closing bracket (ie, the call to `window_copy_cmd_previous_matching_bracket` didn't work), then move back".

So we need to invert the entire condition because we need to say "it's width 1, and it isn't padding, and it is a closing character", so we need to do this, which is in effect the same as your fix putting a `!` around the whole thing:
~~~~
--- a/window-copy.c
+++ b/window-copy.c
@@ -1365,9 +1365,9 @@ window_copy_cmd_next_matching_bracket(struct window_copy_cmd_state *cs)
                                px = data->cx;
                                py = screen_hsize(s) + data->cy - data->oy;
                                grid_get_cell(s->grid, px, py, &gc);
-                               if (gc.data.size != 1 ||
-                                   (gc.flags & GRID_FLAG_PADDING) ||
-                                   strchr(close, *gc.data.data) == NULL)
+                               if (gc.data.size == 1 &&
+                                   (~gc.flags & GRID_FLAG_PADDING) &&
+                                   strchr(close, *gc.data.data) != NULL)
                                        window_copy_scroll_to(wme, sx, sy);
                                break;
                        }

**Comment by nicm** [comment]
This seems to fix it for me but please test anyway.

I always forget what the key bindings are for this or I would use it more, and the emacs key bindings for it are stupid anyway, I hate having to use two modifiers at the same time.

**Comment by chrisbarber** [comment]
Yes looks good and checks out when I test your patch.

I am not sure if `window_copy_cmd_previous_matching_bracket` could actually leave the cursor on a place where it would produce size != 1 or a padding cell, or how to test that. But the logic makes sense the way it is now for sure, and the "normal" case works properly. And it makes sense to protect the condition against doing the `strchr` in an invalid case even if it is unreachable.

**Comment by nicm** [comment]
Good stuff, applied now, thanks.

Yes, if `window_copy_cmd_previous_matching_bracket` can only leave us on either an opening bracket or where we were (a closing bracket), it would be OK without it, but it does no harm to check.
