### ISSUE TITLE
capture-pane -pJ in control mode doesn't always put %end on its own line

### ISSUE THREAD

**Issue by tbodt** [tmux/tmux#2215]
I've been seeing some nasal-demons-type issues with control mode in iTerm2, and tracked them down to this. Apparently it is possible for the output of `capture-pane -pJ` to not end with a newline, so I get something like this when I run capture-pane manually with `tmux -C` (scroll horizontally for the punch line):

```
capture-pane -pJ -t %8
%begin 1589586446 77638 1
[redacted command output]
tbodt@tbodt.~ [1]>                                                                                                                                                                  0.006s%end 1589586446 77638 1
```

That last line is my shell prompt, with the time taken by the last command on the right. iTerm2 is missing the %end because it doesn't start a line, and gets pretty confused from then on.

I don't have a consistent way to reproduce this, will be sure to post if I find one. I'm also on tmux 3.0a, I will check to see if this has been fixed since.

**Comment by nicm** [comment]
`capture-pane` with `-J` is not guaranteed to end in a newline, although I can't come up with a test where it doesn't. What is iTerm2 using this for?

We could possibly force it to end in a newline like we do for `-P`, or provide an alternative output form.

**Comment by tbodt** [comment]
iTerm2 assumes that a %end can only appear at the beginning of the line, which in this case it isn't. Is this an iTerm bug then?

**Comment by nicm** [comment]
Well, it isn't really a bug, it is just unexpected.

`%end` should always be at the start of the line - otherwise there is no way for iTerm2 to tell if it is a real `%end` or if there is `%end` in the window outout.

But from what I can see this is not currently guarantee from `capture-pane`, so this might mean sending data from `capture-pane` that didn't actually exist (an extra newline).

I don't really want to do anything until there is a test case that shows this happening though.

If I'm right and this is actually possible from `capture-pane`, there are a few choices here:

1) Force a newline at the end of `capture-pane` if one wasn't present, maybe by default or with an extra flag to `capture-pane`. Would anyone really care if this was done by default? Perhaps not.

2) Do (1) but also include the output size in the `%end`, so the reading program can tell what size was data and what was the extra newline.

3) Extend the `-P` form of output to normal output (so `\n` would be replaced by `\012`).

The easiest would be (1) which means only tmux would need to change.

Or (3) since the `-P` form already used by both tmux and iTerm2.

But neither would fix any other commands which do not have a terminating newline, although the only one I am aware of is `save-buffer` and it isn't supported in control mode at the moment anyway.

@gnachman?

**Comment by nicm** [comment]
What do you have in your prompt? I can't make this happen with the likes of:
~~~~
tmux -Ltest new -x10 -y2 -d 'printf "0123456789\naaa\033[8Gbbb"; sleep 3' \; run -d 1 \; capturep -eqpJ
~~~~
Unless this is something that was already fixed that I have forgotten...

**Comment by tbodt** [comment]
I'm using fish with something in the right side of the prompt, but that alone doesn't seem to cause the problem, and I dunno what does.

**Comment by nicm** [comment]
Kill tmux then run it with `-vv` then reproduce and show me the server log please.

**Comment by gnachman** [comment]
It's possible it doesn't matter. Would be good to have a repro case before I weigh in.

**Comment by tbodt** [comment]
In my opinion the %begin line should have a byte count and there should be no %end line

**Comment by gnachman** [comment]
Byte counts over a tty are fraught with peril. Line drivers like to insert and delete CR and LF in unpredictable ways.

**Comment by tbodt** [comment]
I wouldn't be able to upload a tmux -vv log; there'd be too much confidential stuff in there. The best I could do is look at it myself and figure out the entire problem.

From looking at the code, it seems like this happens when the last line of the grid has GRID_LINE_WRAPPED set. Can you think of anything that might cause that to happen?

**Comment by tbodt** [comment]
Actually I found a way to repro:
- Attach to a tmux session in iTerm while in full screen
- Start the fish shell and set a right prompt, by running `function fish_right_prompt; echo hi; end`
- Run commands to fill up the grid to the bottom of the screen, so the prompt is on the last line
- Exit fullscreen in iTerm, then enter again
- Detach and reattach

If %end and %begin lines appear on the pane, that reproduced the bug.

**Comment by tbodt** [comment]
Bisected to 9ee1a8f7

**Comment by nicm** [comment]
Hmm, does this fix it: [x.diff.txt](https://github.com/tmux/tmux/files/4661395/x.diff.txt)

**Comment by nicm** [comment]
...

**Comment by tbodt** [comment]
I'll check that today, it's been a long weekend

**Comment by tbodt** [comment]
I applied that patch and couldn't repro anymore, and haven't had any issues for a week, so that seems to be working.

**Comment by nicm** [comment]
OK great, applied now. Although it is a little academic now because the code now forces it to end with a newline anyway for other reasons...

Thanks!
