### ISSUE TITLE
Upgrading from 2.9 to 3.0: binding "{" appears to not work anymore.

### ISSUE THREAD

**Issue by dmonopoly** [tmux/tmux#2240]
$ tmux -V
tmux 3.0a

My old version was tmux 2.9. These commands no longer work:
```
# Rotate panes. These no longer work in tmux 3.0.
unbind-key {
bind-key { swap-pane -D
unbind-key }
bind-key } swap-pane -U
```

Can we have a better migration/upgrade process for tmux? This is the third time I've had an update issue with tmux. Backwards compatibility may be an answer, or link to a common set of "before and after" configs, crowd-sourced. 

Thanks for all the great work.

**Comment by nicm** [comment]
This is mentioned in the change log.

**Comment by andb0t** [comment]
> This is mentioned in the change log.

This is not the case. Please indicate where in https://raw.githubusercontent.com/tmux/tmux/3.1b/CHANGES this is listed. I've been banging my head at the config file migration from versions 2.x to 3.x for quite a while now.

**Comment by nicm** [comment]
~~~~
* INCOMPATIBLE: Add a new {} syntax to the configuration file. This is a string
  similar to single quotes but also includes newlines and allows commands that
  take other commands as string arguments to be expressed more clearly and
  without additional escaping.

  A literal { and } or a string containing { or } must now be escaped or
  quoted, for example '{' and '}' instead of { or }, or 'X#{foo}' instead of
  X#{foo}.
~~~~

**Comment by andb0t** [comment]
Gotcha, thanks for the quick answer. Found out, that this also extends to constructions like
```
> git diff
-bind S-Left swap-pane -s {left-of}
+bind S-Left swap-pane -s '{'left-of'}'
```

**Comment by andb0t** [comment]
I added a suggestion for a wiki entry: https://github.com/tmux/tmux/issues/2163#issuecomment-713529262
