### ISSUE TITLE
[Feature request] New control mode notifications

### ISSUE THREAD

**Issue by gnachman** [tmux/tmux#2242]
When using control mode and depending on the configuration, iTerm2 may poll regularly for:

* `#{pane_current_path}`
* `#{T:status-left}`
* `#{T:status-right}`
* `#{pane_title}`

This has grown over the years as new features have become available. A general mechanism for subscribing to changes to formatted strings would reduce network usage and improve response time when one of them does change.

The ideal system would let me give tmux a list of display formats and then tmux would notify me when any of them changes. Something like:

```
> set-opt -g subscribed-formats "#{T:status-left} #{T:status-right}"
< %update-subscription %<wp> <index of subscription that changed> <new value>
```

**Comment by nicm** [comment]
Yes we can do this, although using a `subscribed-formats` option won't work because options are not per client. It will need to be a separate list and a flag to another command (`refresh-client` has largely become the control mode command so perhaps there, or maybe `display-message` which is used for formats).

It could be expensive for tmux to expand the formats to test them so I would probably check them at most once a second and only when tmux has already been woken up for some other event.

**Comment by nicm** [comment]
I think I would make it so you give an ID for the subscription so you do something like:
~~~~
refresh-client -U 'myformat:#{status-left}'
~~~~
Then tmux will report:
~~~~
%format-changed myformat value
~~~~
But this means they are not per-pane or per-window - although there is no need for stuff like `status-left` to be per pane, what formats are you using that do need to be per pane?

**Comment by gnachman** [comment]
Yeah, of course `set-opt` wouldn't make sense. `refresh-client` would be fine for me.

Ideally, tmux would compute the dependencies of each subscription and then expand the formats only when one of them changes. So if I subscribe to `#{T:status-left}` then the dependency graph would include `status-left` plus whatever the dependencies of the evaluated `status-left` expression are. I do something similar for interpolated strings in iTerm2 now, and it works well.

But that's complicated, and once a second would be an improvement over polling since you could squelch the notification if the value hasn't changed since the last time it was reported.

> I think I would make it so you give an ID for the subscription so you do something like:

That'd be nice. If the status bar goes away then I could cancel that subscription.

**Comment by nicm** [comment]
Try this please: [tmux-control-sub.diff.txt](https://github.com/tmux/tmux/files/4817980/tmux-control-sub.diff.txt)

The command is `refresh-client -B` since most of the other obvious flags are already used. The argument can either be `name:format` to add a subscription or `name` to remove. Adding a duplicate name will silently update the existing subscription and removing a nonexistent name will be silently ignored.

I chose to include a `:` separator to `%subscription-changed` to separate the value from the previous arguments, so (like `%extended-output`) you should ignore any extra arguments between the name and the `:` so we can add them in future.

~~~~
$ ./tmux -Lx -C a
%begin 1592899807 270 0
%end 1592899807 270 0
%session-changed $0 0
refresh-client -B 'foo:#{window_name}'
%begin 1592899819 274 1
%end 1592899819 274 1
%subscription-changed foo : ksh
renamew test
%begin 1592899824 275 1
%end 1592899824 275 1
%window-renamed @0 test
%subscription-changed foo : test
refresh-client -B 'foo'
%begin 1592899832 277 1
%end 1592899832 277 1

**Comment by nicm** [comment]
I would avoid 1) using spaces in the name and 2) subscribing to frequently updated format variables.

How many subscriptions will you need to make? If it is 10-20 then this will be fine as it is, but if you want to make 1000 then we may need to only check 100 a second or something.

**Comment by gnachman** [comment]
I can't imagine why it would ever be much more than 10 distinct paths.

How would this work for something like `#{pane_current_path}`? I would love to get subscribed to it for all panes (including future ones) automatically.

**Comment by nicm** [comment]
As it is now it will only give you the active pane. Perhaps could make "per pane" or "all pane" subscriptions, so you give like `-B name:pane:format` where pane is empty for no pane (like now), a pane ID for that single pane, or * or something to mean loop over every pane.

**Comment by nicm** [comment]
Try this please which extends it to three forms:
1) `refresh-client -B 'name::format'` <-- no pane
2) `refresh-client -B 'name:%0:format'` <-- only pane %0
3) `refresh-client -B 'name:*:format'` <-- all panes

~~~~
$ ./tmux -Lx -C a
%begin 1593075102 272 0
%end 1593075102 272 0
%session-changed $0 0
refresh-client -B 'foo:*:#{pane_current_path}'
%begin 1593075106 276 1
%end 1593075106 276 1
%subscription-changed foo %0 : /usr/src/usr.bin/tmux2
%session-window-changed $0 @1
%window-add @1
%subscription-changed foo %1 : /usr/src/usr.bin/tmux2
%output %1 nicholas@yelena:/usr/src/usr.bin/tmux2$
%output %1 c
%output %1 d
%output %1
%output %1 /
%output %1 t
%output %1 m
%output %1 p
%output %1 \015\015\012
%output %1 nicholas@yelena:/tmp$
%subscription-changed foo %1 : /tmp

**Comment by gnachman** [comment]
Yeah, just the attached session. Control mode is has lots of assumptions about getting content from only the attached session.

The diff works but the response time is slower than I expected. I measured six seconds between changing directory and getting the %subscription-changed. Is it possible to do it faster? I imagine this is something you have to poll for. I have a heuristic to poll for directory change after receiving a carriage return keypress, but not sure if that would make sense to do in tmux.

**Comment by nicm** [comment]
Yes... it will be at the mercy of something else waking tmux up, because there is no guarantee the path will have actually changed by the time tmux checks it after receiving the most recent output from the shell. So it will not be triggered until there is something else that wakes tmux up, whether it be the user or something like status-interval.

I am not wild about tmux waking up every second but I guess we could do it if there are subscriptions...

**Comment by nicm** [comment]
Try this instead please: [tmux-control-sub3.diff.txt](https://github.com/tmux/tmux/files/4835837/tmux-control-sub3.diff.txt)

**Comment by gnachman** [comment]
That's definitely faster.

Here's the problem I've run in to. I do:

```
set -g status-left 'id=#{window_id} active=#{window_active}'
refresh-client -B 'it2_169:@0:#{T:status-left}'
```

When I change which window is active, I don't get a `%subscription-changed`.

**Comment by nicm** [comment]
It only work for panes not windows, you can't give a window ID.

**Comment by nicm** [comment]
Well to be more accurate you can say:

- nothing meaning the format is expanded for the session using the current window and active pane;
- a pane ID means it is expanded for that pane with no session;
- `*` means each pane in the attached session is looped over and the format expanded for the session, the pane and its window (but not its window link).

We could do window IDs too, but it wouldn't give you window_active because window_active is a window link variable not a window variable. That is, it is a property of the connection between session and window, not a property of the window - window @1 could be at index 0 and index 2 in session xyz so it will have two window links.

**Comment by nicm** [comment]
I think it would be helpful if you could tell me what variables you would need to subscribe to and for what items (global, session, window, pane)?

**Comment by gnachman** [comment]
Sorry for not being clearer about this. I need:

Per pane: `#{pane_current_path}`, `#{pane_title}`
Per window: `#{status-interval}`, `#{T:status-left}`, `#{T:status-right}`, `#{T:set-titles-string}`
Global: `#{set-titles-string}`

**Comment by nicm** [comment]
> status-interval, status-left, status-right, set-titles

These are all session options. In theory status-left and status-right could have window variables in them but it is unlikely. So you could subscribe to these with the latest patch and no ID.

> set-titles-string

This is a session option also but is more likely to have window or pane variables in it. tmux only uses it for the current window though, do you need it separately for each window in the session?

**Comment by gnachman** [comment]
> These are all session options. In theory status-left and status-right could have window variables in them but it is unlikely and if they did tmux itself would always use the current window. So you could subscribe to these with the latest patch and no ID.

It's not quite ideal because in tmux integration mode you can see many windows’ status bars at the same time, and it would be nice for them to have the right values for the window they're in.

> This is a session option also but is more likely to have window or pane variables in it. tmux only uses it for the current window though, do you need it separately for each window in the session?

Yeah, I use it to set the window title. so it should be separate. Would `display-message -t @w '#{T:set-titles-string}'` use the current window and ignore the `-t` argument?

**Comment by nicm** [comment]
display-message -t uses the target for the format, but if you give it a window ID and the window is linked to the session more than once you will get the "best" window index (at the moment this means the current index if it is current window, otherwise the lowest index), so there is no way to distinguish window @99 at session:1 and window @99 at session:2.

We could do the same for subscriptions to window IDs and add @* for all (and change the current * to %*).

Would this matter?

**Comment by nicm** [comment]
Another option would be to specify the subscription as a type plus a target and tmux could follow the normal target lookup process, so you would give for example:

- `w:window` eg `w:@1` or `w:session:2` to subscribe to a window.
- `p:pane` eg `p:%2` or `p:session:2.1` to subscribe to a pane.
- `p*:session` eg `p*:session` or `p*:$2` for all panes in a session, or `p*:` (empty target) for all panes in attached session;
- `w*:session` similarly for all windows in a session or `w*:` for all windows in attached session.

Then `%subscription-changed` would need to include the full target (`session:index`) as well as the ID so you could distinguish the same window at different indexes.

This would be more flexible, but there are a couple of problems:

- It would be best to resolve the target when the subscription is checked rather than when it is added, but this would be quite expensive.

- Doing that could mean if you subscribe to `session:1` it could be window `@1` and later change to window `@99`. Or it could disappear entirely if the window was moved. You could need to keep track of that and add or remove subscriptions.

- Similarly if a session is renamed or a pane moved, although you could use session and pane IDs for those so it would not be a big problem.

**Comment by gnachman** [comment]
> display-message -t uses the target for the format, but if you give it a window ID and the window is linked to the session more than once you will get the "best" window index (at the moment this means the current index if it is current window, otherwise the lowest index), so there is no way to distinguish window @99 at session:1 and window @99 at session:2.

This isn't a terribly important case for me. Although it would seem to make more sense to use the client's currently attached session?

> We could do the same for subscriptions to window IDs and add @* for all (and change the current * to %*), but I guess @* would need to only look at each window once even if it appears multiple times.

I don't need it. I keep some windows hidden, which means I don't care about their updates. It's easy for me to subscribe or unsubscribe as needed.

> w:window eg w:@1 or w:session:2 to subscribe to a window.
> p:pane eg p:%2 or p:session:2.1 to subscribe to a pane.

I think this would solve the problem quite nicely. I'm surprised you don't prefer something like `-t @1` for consistency with other commands, though.

> Then %subscription-changed would need to include the full target (session:index) as well as the ID so you could distinguish the same window at different indexes.

I think we should keep the existing conventions for identifiers in this notification, so `$1 @2` instead of `1:2`.

> Doing that could mean if you subscribe to session:1 it could be window @1 and later change to window @99.

I only ever use the `$`, `%`, and `@`-style identifiers, which don’t change out from under you (I hope!). I suppose you need to support the index-style syntax for consistency. IMO they make sense for interactive use but not in control mode. As far as I'm concerned, feel free to take the easy route here.

**Comment by nicm** [comment]
> This isn't a terribly important case for me. Although it would seem to make more sense to use the client's currently attached session?

It isn't about the session really. If there is a session with three windows `0:@99 1:@100 2:@99` - window `@99`is present twice, so if tmux is only told `@99`, then it has no way to know for sure whether `#{window_index}` should expand to 0 or 2 and `#{window_active}` to 0 or 1.

So the two choices are to either leave those variables out (which is what the most recent diff does), or to make tmux guess, which is what I am suggesting by using the existing target resolution.

> I think this would solve the problem quite nicely. I'm surprised you don't prefer something like -t @1 for consistency with other commands, though.

If it is parsed as a target, you can either give a window as `session:index` in which case tmux knows exactly which window you mean and can fill in `#{window_index}` and the others accurately, or you can give an ID like `@1` in which case tmux will guess the most appropriate session and index itself if needed.

But obviously if you give a `session:index`, then the actual window could change.

You could just use IDs anyway and it probably doesn't really matter - I expect the number of people who will be using iTerm2, have the same window linked to a session multiple times, and want to use `#{window_active}` or similar in their status line will be very small so it probably isn't worth too much worry.

**Comment by nicm** [comment]
type+target will be more generally useful and doesn't leave a big gap, even if for iTerm2 it won't really matter, but looking up the target every second is probably going to be quite expensive... I think I will change it to this and see how it goes, not sure when I will have time to do it.

**Comment by gnachman** [comment]
> So the two choices are to either leave those variables out (which is what the most recent diff does), or to make tmux guess, which is what I am suggesting by using the existing target resolution.

Thanks for the explanation. Leaving the variables out is bad. It looks like the design of %subscribe is underspecified here. I think it would make the most sense to subscribe to @99 and to get updates that are unambiguous like `%subscription-changed 2:@99` as well as `%subscription-changed 0:@99`. I'll need to start tracking window index to direct the update to the correct UI element.

> You could just use IDs anyway and it probably doesn't really matter - I expect the number of people who will be using iTerm2, have the same window linked to a session multiple times, and want to use #{window_active} or similar in their status line will be very small so it probably isn't worth too much worry.

In the first version I will just use IDs because this is a vanishingly small edge case.

**Comment by nicm** [comment]
Yes I think that is the best option, when you subscribe to a window ID you get updates for all instances of that window separately. So we can have `%n` `%*` `@n` and `@*` for single pane, all panes in attached session, single window (potentially in multiple places), all windows in session.

**Comment by nicm** [comment]
Note that this also applies to window variables used in pane formats. If you have pane `%0` tmux can tell that it is only in window `@1` but not what index that window is at, the same as if you had given `@1`. So we would need to give the window index in the pane response as well. I think I will make the response something like:

~~~~
%subscription-changed name $a @b x %c : value
~~~~
Where `a` = session, `b` = window, `x` = index, `c` = pane and any can be `-` if they are not appropriate to that subscription (so a session subscription will not include `b`,`x`,`c` and a window not include `c`.

**Comment by nicm** [comment]
Of course all this makes it rather a pain in the arse to track whether the value has changed or not...

**Comment by nicm** [comment]
Actually it will be OK, I will just track the last value keyed by pair of (window ID, window index) and (pane ID, window index).

**Comment by nicm** [comment]
Can you try this please: [tmux-sub-new.diff.txt](https://github.com/tmux/tmux/files/4871075/tmux-sub-new.diff.txt)

As mentioned above the type can be a empty (for the session), a pane ID (`%0`), all panes (`%*`), a window ID (`@0`) or all windows (`@*`). You will get multiple `%subscription-changed` if a window or pane appears in a session more than once (although obviously only if the value of the format changes for each). It now shows something like:
~~~~
%subscription-changed foo $0 @0 0 %0 : value
~~~~
So session ID, window ID, window index in session, pane ID.

I don't have much more time so only lightly tested, let me know if you see anything funny.

**Comment by nicm** [comment]
You will still only get notifications for your attached session, I put the session ID there in case we want to do other sessions later somehow. You can ignore it if you like for the moment.

**Comment by gnachman** [comment]
This looks good. I think I can get away with ignoring the session/window/index/pane for now; for simplicity I just subscribe separately for each pane.

**Comment by nicm** [comment]
OK I have applied this now, let me know if you see any problems. Thanks!

**Comment by nicm** [comment]
I am not sure if I will put this in 3.2, maybe that would be best. It doesn't have much impact outside of control mode.

**Comment by nicm** [comment]
I have pulled this back to 3.2-rc branch also.

**Comment by gnachman** [comment]
Cool, I'll include it in my 3.4 release would should come out in September to coincide with tmux 3.2.
