### ISSUE TITLE
[Feature request] Permit detach from application side (inner terminal)

### ISSUE THREAD

**Issue by klamonte** [tmux/tmux#2245]
I have not seen this in the documentation, so apologies if it already exists.

I am writing a complex [terminal-based X11-like window manager](https://gitlab.com/klamonte/xtermwm) and would really like to expose a "Application | Detach" item in the menu, which would detach the session just like tmux/screen detach or the detachtty/dtach/abduco/reptyr-type tools.  If this feature cannot exist in tmux, then I will probably write something, but figured it would be worth asking here.

Proposal details:

1. Listen for "CSI 2 t" from an inner terminal, the existing dtterm windowOps sequence for "iconify window".  For tmux, that would be re-used to mean "application requests session detach".
2. tmux responds based on selected policy:
    * (Default) disabled: ignore request.  This matches xterm's default.
    * enabled: detach session
    * ask: popup dialog saying "Application 'blah' in window X pane Y requests session detach.  Detach session?" .  User presses 'y' or 'Y', session is detached, anything else request is ignored.
3. Original dtterm sequence is consumed always, no response is sent to the application.

**Comment by nicm** [comment]
You are talking about when you run your application inside tmux?

There is no way to do this at the moment other than just running `tmux detach-client`, but it would be relatively trivial to implement and I don't mind having it like you describe, although:

- It will have to guess the best client to detach in the same way as doing `detach-client` from inside. That isn't normally a problem if the escape sequence in sent in response to something the user does, since that will be the most recently used client.

- No prompting, just have it either on or off.

- I would prefer no new option but I don't see anything obvious it could be rolled into, so I guess it needs a new one. Anyway, I would name the option something not too specific, so it can be extended if any of the others are added - I don't know maybe just `allow-window-operations`.

**Comment by klamonte** [comment]
'detach-client' might be all that I need, actually.  I just did a quick test with spawning my application with: 'tmux new-session {my program command line}', then inside my program spawned 'tmux detach-client' and it worked fine.  Some massaging of my startup script to ensure a unique session name and that would do it.

I've got what I need afterall, thank you! :)  Feel free to close this anytime.

**Comment by nicm** [comment]
Remember it won't work over ssh though, if you care about that.

**Comment by klamonte** [comment]
I'm fine with closing this.  For anyone who comes later, I ended up implementing the following:

* My startup script has a '--tmux' option, which will prepend my command line with 'tmux new-session -s xtwm-$$ {regular command line} {plus other args}'.
* My main application checks for either those {other args} being set, or TMUX being set in the environment.  If either are true, it adds a "Detach (tmux)" menu item.
* The detach menu item executes either 'tmux detach-client -s xtwm-{pid}' if those {other args} were set, or just 'tmux detach-client' if it saw TMUX.

Net result is exactly what I want: detection of tmux, and application-driven detach.
