### ISSUE TITLE
Can't type/paste certain characters

### ISSUE THREAD

**Issue by kchibisov** [tmux/tmux#2256]
It seems like some recent change broke input of some characters into tmux. Example of char  🤔.
When I type/paste it into tmux, running `cat` or `showkey -a` I get `$`, it happens only with that particular character, some other emojis seems to work.

version: tmux next-3.2

**Comment by krader1961** [comment]
This is (almost?) always due to different programs (tmux, your shell and terminal) having different ideas about the width of an emoji. This is often due to the width being defined differently by two Unicode versions. It's most likely to affect double-width emoji like U+0001F914. Yes, this should work but, frankly, I just avoid using such chars as the problems they cause when used in a fixed width terminal isn't worth it.

**Comment by nicm** [comment]
Actually it is a bug, it should be fixed soon... :-)

**Comment by kchibisov** [comment]
>This is (almost?) always due to different programs (tmux, your shell and terminal) having different ideas about the width of an emoji.

There're no issues with full width chars handling in terminal most of the time. The problem is just that one char since it start being rewritten by tmux on insert somehow. The chars (bytes for it) are incorrect and in outer terminal everything works. Otherwise such bug won't be reported at all.

>Actually it is a bug, it should be fixed soon... :-)

thx.

**Comment by nicm** [comment]
This should be fixed by 7e501f1993cc1e4b8344643bcee449cc8c958d7e.

**Comment by kchibisov** [comment]
yeah, fixed. thanks.
