### ISSUE TITLE
Zoomed panes are not redrawn fully when switching sessions

### ISSUE THREAD

**Issue by lukas-reineke** [tmux/tmux#2260]
### Issue description

When switching to a session with a zoomed pane, the content of that pane does not get re-drawn fully.
The part of the pane that is re-drawn is not related to where the split would be. Its always drawn from the top, but stops at the size the pane would be when not zoomed.

It only happens when:
* the pane is displaying a TUI program like `vim` or `htop`. Normal shell output like `ls` is fine
* the pane does not take up the whole space from top to bottom. (there is a horizontal split. other splits don't affect the outcome)

Examples:
pane X has the problem when zoomed:
```
+-------+
|   X   |
+-------+
|       |
+-------+
```
```
+---+---+
|   | X |
+---+---+
|       |
+-------+
```

pane X has no problem:
```
+---+---+
|   |   |
|   | X |
|   |   |
+---+---+
```
```
+---+---+
|   |   |
+---+ X |
|   |   |
+---+---+
```

### Required information

* No configuration
* tmux version: `next-3.2`
* Platform `linux`
* $TERM: `xterm-kitty` (tested with other emulators as well)

### Screenshots
![DeepinScreenshot_select-area_20200605144442](https://user-images.githubusercontent.com/12900252/83841321-96046180-a73b-11ea-9690-f8f68954ac98.png)
Zoomed pane before switching sessions.

![DeepinScreenshot_select-area_20200605144508](https://user-images.githubusercontent.com/12900252/83841344-a3215080-a73b-11ea-9769-17f1bb78d534.png)
Zoomed pane after switching sessions, and then switching back

**Comment by nicm** [comment]
This (and #2252) are both due to the fact that we resize the grid immediately but we don't do `TIOCSWINSZ` to tell the program until the end of the event loop.

In this case, `switch-client` unzooms the window before selecting it and zooms it again afterwards. It has to do this if the active pane changes because the zoomed pane will be different. But the consequence if the active pane hasn't changed is that the grid is resized smaller when unzoomed then back to its previous size when it is zoomed again, but the application is never told it has been smaller, which matters for programs using the alternate screen because content has been lost and they need to redraw.

There are a few possible things we can do:

1) We can avoid unzooming if the active pane hasn't changed. This is a good idea and similar to what the fix for #2252 does, although it is in a different place (window resizing).

2) We could defer grid resize to the end of the event loop, like `TIOCSWINSZ`. This would work and would have the advantage that nothing need be done at all if the size is changed multiple times but ends up the same size it started with. I think this would cause problems with command sequences though because there will definitely be code that expects the grid size to match the pane size.

3) We could do the `TIOCSWINSZ` immediately on zoom/unzoom. This means the application would be doing extra work, but deferring is only really useful for resizing where the user might be using key repeat or the mouse to resize 100s of times very quickly. Nobody will care if the application has to redraw a couple of extra times when they switch between sessions.

**Comment by nicm** [comment]
This is an issue anywhere you do commands which mean an unzoom/zoom but the zoomed pane does not change:

- `resize-pane -Z ; resize-pane -Z`
- `swap-pane -Z`
- `select-pane -l ; select-pane -l`
- `rotate-window -Z ; rotate-window -Z`

So (1) is not really a practical fix but more of an optimization when we know we will be unzoom/zoom (like your problem with `switch-client`, or #2252), because there is no way for example for the first `resize-pane -Z` in a command sequence to know that a later one will restore the previous state.

I think we need to do (3) - add a flag to say "this resize needs to be complete now" which is what we do for windows.

I'm not really sure what changed that is becoming an issue now...

**Comment by nicm** [comment]
There are non-zoom cases as well, for example:
~~~~
selectl main-horizontal; selectl tiled; selectl main-horizontal
~~~~

**Comment by nicm** [comment]
Can you try this please which tidies up the force resize code and applies it to zoom resizes as well? [tmux-resize.diff.txt](https://github.com/tmux/tmux/files/4735123/tmux-resize.diff.txt)

If this works I will make a separate change not to zoom/unzoom if the pane is not changing which will eliminate the redraw entirely when you use `switch-client` and don't change the pane.

**Comment by lukas-reineke** [comment]
That patch fixes it :+1:

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it will be in GitHub later. No doubt there will be some new problems but we can see how it goes. Thanks!
