### ISSUE TITLE
create window failed

### ISSUE THREAD

**Issue by 333caowei** [tmux/tmux#2281]
tmux version: 2.6-2

When I tried to create a new window, it showed "create window failed, Cannot allocate memory".

The memory of machine is enough.

**Comment by krader1961** [comment]
Tmux 2.6 is very old (~3 years old) which means it is unlikely anyone will spend much time on this issue. Having said that, note that the "Cannot allocate memory" error means that a function such as `malloc()` returned errno `ENOMEM`. Unless you triggered a tmux bug that causes it to leak memory this isn't a tmux issue. It means your system ran out of memory or you ran tmux with a very low limit on the amount of memory it can use (see the `ulimit` command). The only other reason for this failure is because you triggered a tmux bug other than a memory leak. For example, by passing unreasonable values to the tmux function that creates a new window. Thus causing it to allocate an unreasonable amount of memory.

Before spending more time on this you need to provide more information. Specifically: a tmux server log and the OS name and version. Not to mention the steps you took that lead to the failure. For example, was that the first window you created after starting tmux?
