### ISSUE TITLE
allow /etc/tmux.conf or (sysconfdir)/tmux.conf to have highest priority for security/compliance

### ISSUE THREAD

**Issue by carlosmmatos** [tmux/tmux#2308]
### Issue description

Currently, the order of precedence for loading of configuration files is as follows:
`"$(sysconfdir)/tmux.conf:~/.tmux.conf:$$XDG_CONFIG_HOME/tmux/tmux.conf:~/.config/tmux/tmux.conf`

This makes it difficult to enforce a global configuration file to prevent users from changing/overriding certain security controls such as enforcing session lock after inactivity that an organization may want to set. Let me know what you guys think of my PR for this, and if there may be other ways to handle this type of configuration lockdown.

**Comment by nicm** [comment]
I think it is much more usual to want system-wide defaults in `/etc/tmux.conf` that can be overridden in `.tmux.conf`. This is how other programs work like shells.

If you want to change it I suggest you build tmux yourself, but note that changing the order won't really enforce anything, because the user could just turn it off after tmux was started or use `-f` to specify a different configuration file.

**Comment by carlosmmatos** [comment]
yeah, I'm aware of the `-f` option to bypass - this is more of a 'hit the checkbox' config that will help map some security controls..  I agree with you that a rebuild may be more in line with finer grain control.

So if one would want to "lockdown" certain configuration settings.. what would you recommend? Removing the ability to use `-f` and maybe additional checks for command line args?

**Comment by nicm** [comment]
You may be better to change the `set-option` command to forbid an option to be set more than once, or to add a flag to lock an option so it could not be changed (or overridden with a more specific per-window or per-session value).
