### ISSUE TITLE
Can we please change the global default of the `window-size` option

### ISSUE THREAD

**Issue by jspawar** [tmux/tmux#2334]
Hello,

Noticed that there has been quite a bit of confusion surrounding the change of the default value of the `window-size` option to be `latest`. I think given the amount of issues and comments I've seen getting confused about how this has changed, it might be worth considering reverting to a different default like `smallest`?

From what I can understand and hypothesize, `latest` is useful in situations where there is a stale tmux session attached with an undesirable window size; however, I think it is probably a better user experience to teach people how to just detach that stale session. The way I see this is weighing teaching/advertising better how to detach stale sessions vs breaking sharing tmux sessions by default, and from that perspective, breaking user workflows is far worse than a class of documentation concerns.

I couldn't exactly find the motivation for defaulting to `latest` though, so having that might be good as well to understand. Maybe I'm completely off-base with my understanding and I would love to understand more about this specific decision then.

I think at the very least, a breaking change like this could have perhaps been advertised differently? Such as adding some sort of label like `breaking` to the changelog? 

Thanks!

**Comment by nicm** [comment]
The problem of smaller clients limiting the size of larger ones is a longstanding problem and has caused huge confusion and a great number of questions over the years. `latest` is a better default and anyone who for whatever reason might prefer the old behaviour can easily choose to configure it.

**Comment by jspawar** [comment]
It certainly is easy enough to configure as desired; however, I guess I'm still wondering exactly why `latest` is a better default? Just to clarify then, do you believe so specifically in the context of that longstanding problem/confusion of smaller clients limiting size? I.e. it's basically to mitigate that?

**Comment by nicm** [comment]
Yes that's right.

**Comment by nicm** [comment]
Most people who attach multiple times (because they left tmux attached at work, or because their connection dropped, or because they have multiple monitors or workspaces) do not want the size of the client they are using limited by the size of the client they are not using and when it happens it is confusing. Pople ask about it all the time, it is in the FAQ. Now that there is a solution, it should be the default.

**Comment by jspawar** [comment]
Alright fair enough, I trust you know the pains of what issues/questions you get about this behavior the best. As you said, this is easy to configure to revert to using the limiting behavior, so far from a big deal. 

Couldn't find that FAQ, so sorry if this was explained there! Thanks

**Comment by basile-henry** [comment]
I had no idea this was an option! :scream_cat: 

I have been having resizing issues when sharing my tmux session with co-workers when working remotely (which we're doing a lot at the moment :sweat_smile: ), but I didn't know what the root cause of the issue was. I assumed it was incompatibilities in versions of tmux used between users. We used to be able to be several people looking at the same session and switching who was in control very easily. But now with the window resizing whenever someone takes over and with half of the window being out of the screen for the other users it doesn't make for a great experience. We would spend time trying to synchronise the font size / window aspect ratio on each end so that the session wouldn't jump all over the place.

I guess now I know what the option is, and I will make sure to set it on all the machines I use. For what it's worth I don't think this `latest` is a great default. At least with `smallest` you could see something was wrong, it wasn't just hiding part of the window until you take over control.
