### ISSUE TITLE
Tmux not reading the correct tty of the current pane when subshell is spawned

### ISSUE THREAD

**Issue by himat** [tmux/tmux#2341]
### Issue description

Tmux is not correctly reading the correct tty when I use a `poetry` shell.
https://github.com/python-poetry/poetry (poetry is just an alternative virtual environment manager for python instead of virtualenv)

```
> tty 
/dev/ttys001 # original shell

> tmux new

> tty
/dev/ttys004 # tmux shell

> poetry shell
Spawning shell within /Users/x/x/.venv

> . /Users/x/.venv/bin/activate

> tty
/dev/ttys017 # tmux shell with poetry activated

||| <tmux-prefix> + : display-message -p "This is #{pane_tty}" |||
/dev/ttys004 # This is the original tmux shell, not the latest one with poetry activated
```

As you can see, `#{pane_tty}` should have returned `/dev/ttys017` but it returns 004 instead!

I have some commands in my .tmux.conf that run based on what processes are running in the current tty, so since tmux is not reading the correct tty here my commands are getting messed up.
For example, after activating poetry, I open vim. And then I have a command that checks if vim is running in the current tty and if so, then map some commands. But because tmux is still looking at the old tty, it doesn't see that vim is running in my current shell.

### Required information

* tmux version (`tmux -V`). 3.1b
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). 
- Outside tmux: xterm-256color
- Inside tmux: screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
- tmux-client.log: https://pastebin.com/ruKbJg7c
- tmux-out.log: https://pastebin.com/vxk5rrYJ
- tmux-server.log: <this was too big for pastebin to upload as a free user apparently, but I can try to upload this file with other means if you think it is necessary>

**Comment by krader1961** [comment]
Tmux is, correctly, still reading from */dev/ttys004*. The problem here is that your `poetry shell` command is creating a pty (pseudo-tty) and running the virtualized shell on the slave side of the pty. The poetry command then transfers data between the current pty, */dev/ttys004*, and the new sub pty, */dev/ttys017*. You can reproduce the "problem" using the `script` command. This example begins at a shell prompt from a newly attached tmux session:

```
> tty
/dev/ttys011
> script
Script started, output file is typescript
> tty
/dev/ttys033
> tmux display-message -p "This is #{pane_tty}"
This is /dev/ttys011
> exit
Script done, output file is typescript
> tty
/dev/ttys011
> tmux display-message -p "This is #{pane_tty}"
This is /dev/ttys011
```

Tmux has no knowledge of the pty created by `poetry shell`. As far as tmux is concerned it is communicating with the processes running in that tmux session via the pty it created. What you expect to happen is not possible.

**Comment by nicm** [comment]
As @krader1961 said, this is expected if a program running inside tmux creates its own pty - script is a good example, or run tmux inside itself. Your best bet would be to store the tty from the inner pty in a user option with something like `tmux set -p @inner_tty $(tty)` then you should be able to use it from tmux.
