### ISSUE TITLE
Failed to start tmux and attach session via systemd

### ISSUE THREAD

**Issue by century6** [tmux/tmux#2342]
* tmux version : 3.1.
* Platform : Linux aarch64.
* $TERM inside and outside of tmux (`echo $TERM`): Both are Linux.
* Logs from tmux (`tmux kill-server; tmux -vv new`): https://github.com/century6/tmux_log

When tmux is started through systemd to attach to an test session, It will fail. But when I manually enter the shell command (tmux -attach test), this problem does not occur.

**Comment by nicm** [comment]
You are trying to attach tmux from somewhere that is not a tty:
~~~~
1596705059.125219 cmdq_error: open terminal failed: not a terminal
~~~~
If you want to start tmux without a tty you need to use `new -d` and attach from a different terminal later.

**Comment by century6** [comment]
> You are trying to attach tmux from somewhere that is not a tty:
> 
> ```
> 1596705059.125219 cmdq_error: open terminal failed: not a terminal
> ```
> 
> If you want to start tmux without a tty you need to use `new -d` and attach from a different terminal later.

Thank you for your guidance. I successfully started tmux with a tty, but I encountered a new problem: entering any character will cause the tmux client to restart. But when I manually enter the shell command (tmux -u attach -t test), this problem does not occur. Why is that? It seems that starting tmux to attach to a session through systemd will inevitably cause this problem.

Logs from tmux: https://github.com/century6/tmux_log2

**Comment by nicm** [comment]
When you say the client restarts, what do you mean?

**Comment by century6** [comment]
> When you say the client restarts, what do you mean?

When I type a character, the window doesn't respond. After checking the log, it is found that the client process exits and restarts a new process connected to the test session. And when I type it again, it happens again.
 I have uploaded the log files : https://github.com/century6/tmux_log2

**Comment by nicm** [comment]
Can you attach a tmux client like `strace -tt -fostrace.out tmux ....` then reproduce and show me the strace.out file?

**Comment by century6** [comment]
> Can you attach a tmux client like `strace -tt -fostrace.out tmux ....` then reproduce and show me the strace.out file?

https://github.com/century6/tmux_log2/blob/master/tmux_log3.tar.gz

**Comment by nicm** [comment]
Can you do the same with the server? Start the server with `strace -tt -fostrace-server.out tmux start`, then reproduce with a client (preferably also using strace) and send me the logs and strace*.out files.

**Comment by century6** [comment]
> Start the server with `strace -tt -fostrace-server.out tmux start`



> Can you do the same with the server? Start the server with `strace -tt -fostrace-server.out tmux start`, then reproduce with a client (preferably also using strace) and send me the logs and strace*.out files.

https://github.com/century6/tmux_log2/blob/master/tmux_log4.tar.gz

**Comment by nicm** [comment]
Does this fix it (against master)? [x.diff.txt](https://github.com/tmux/tmux/files/5068579/x.diff.txt)

**Comment by century6** [comment]
> Does this fix it (against master)? [x.diff.txt](https://github.com/tmux/tmux/files/5068579/x.diff.txt)

Unfortunately, the problem has not been fixed.
https://github.com/century6/tmux_log2/blob/master/tmux_log5.tar.gz

**Comment by nicm** [comment]
This log says you are still running tmux 3.1 not master.

**Comment by century6** [comment]
> This log says you are still running tmux 3.1 not master.

Well, this is the log of master. The problem has not been fixed.[tmux_log6.tar.gz](https://github.com/century6/tmux_log2/blob/master/tmux_log6.tar.gz)

**Comment by krader1961** [comment]
@century6, If you're running tmux built from the master branch then `tmux -V` should report `next-3.3`.

**Comment by nicm** [comment]
Is this master with the patch applied?

**Comment by century6** [comment]
> Is this master with the patch applied?

Yes.

**Comment by nicm** [comment]
I don't think this is a problem with tmux. Here is what is happening with `/dev/tty2` when tmux decided the client has died:
~~~~
...
1224  23:00:15.768189 ppoll([{fd=3, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=9, events=POLLIN}, {fd=8, events=POLLIN}, {fd=6, events=POLLIN}], 6, {tv_sec=6, tv_nsec=150000000}, NULL, 0) = 1 ([{fd=8, revents=POLLIN}], left {tv_sec=5, tv_nsec=696295120})
1224  23:00:16.222420 ioctl(8, FIONREAD, [0]) = 0
1224  23:00:16.222734 readv(8, [{iov_base=0x2b092350, iov_len=4096}], 1) = -1 EAGAIN (Resource temporarily unavailable)
...
1224  23:00:16.224037 ppoll([{fd=3, events=POLLIN}, {fd=10, events=POLLIN}, {fd=12, events=POLLIN}, {fd=9, events=POLLIN}, {fd=8, events=POLLIN}, {fd=6, events=POLLIN}], 6, {tv_sec=5, tv_nsec=690000000}, NULL, 0) = 1 ([{fd=8, revents=POLLIN|POLLERR|POLLHUP}], left {tv_sec=5, tv_nsec=689225100})
1224  23:00:16.225000 ioctl(8, FIONREAD, 0xffffc513f030) = -1 EIO (Input/output error)
1224  23:00:16.225093 readv(8, [{iov_base="", iov_len=4096}], 1) = 0
~~~~
So the file descriptor is first returning `poll()` as ready for reading (`POLLIN`), but then giving `EAGAIN` when tmux tries to read from it. This happens multiple times.

Then it returns an error from `poll()` (`POLLIN|POLLERR|POLLHUP`) and `readv()` returns 0 meaning that the file descriptor has been closed. There is no intervention from tmux between these two things happening.

This seems like a bug in the kernel tty layer to me.

Does it make any difference if you do `export EVENT_NOPOLL=1` before starting tmux?

What if you attach tmux inside `script` so it is talking to a pty rather than a tty?
