### ISSUE TITLE
3.1b release changed session sort order

### ISSUE THREAD

**Issue by themightyoarfish** [tmux/tmux#2371]
### Issue description

Since some release ago, the sort order for the session list (`<prefix>-s`) has changed from alphabetically to order of creation. This is bad news for me, as i sometimes accidentally kill and then recreate sessions - which then are not behind their usual key.

I could not find this behaviour in any Changes list.

Is this intended?  Can it be changed back? Can it be made configurable?

### Required information

Please provide the following information:

* tmux version 3.1b
* Platform Darwin i386
* $TERM inside and outside of tmux: `screen-256color` inside, `xterm-256color` outside

**Comment by nicm** [comment]
Sort order has not changed in 3.1. You can press O or use -Oname to sort by name.

**Comment by themightyoarfish** [comment]
I see. Does this setting persist or is configurable somewhere? I never had this issue before some recent update.

**Comment by larrylv** [comment]
Same as @themightyoarfish , I believe this issue only happened after the recent upgrade. Previously, after a new session was created, the order will be sorted automatically.

**Comment by larrylv** [comment]
Ok, I think I found a work-around per @nicm 's suggestion. Thank you @nicm !

I was using `bind o choose-session` and it always sorted by name by default previously. But now since that behavior changed, I changed the binding to `bind o choose-session -Oname` and now the behavior is the same as before. @themightyoarfish maybe you should consider doing sth similar.

However I do think this is kind of a breaking change? `choose-session` list used to sort sessions by name by default, but now it's sorted by created time. @nicm please let me know if you want me to git bisect and determine the breaking commit.
