### ISSUE TITLE
Unable to (un)set global env when starting tmux

### ISSUE THREAD

**Issue by Darkshadow2** [tmux/tmux#239]
I just pulled the current code from here, and on restarting tmux, I get shown this output:

```
/etc/tmux.conf:95: no current session
/etc/tmux.conf:96: no current session
```

which corresponds to this:
```
setenv -gu SHLVL
setenv -g IN_TMUX 1
```

It seems that tmux is trying to unset/set these for the session rather than globally, and failing since it is starting up.

(Yes, I know tmux sets environment variables I can test already, but I like setting my own just in case names are changed or that environment variable is no longer set sometime in the future.)

**Comment by nicm** [comment]
setenv needs to be CMD_SESSION_CANFAIL and check for s==NULL. I'll fix it when I get home
On 16 Dec 2015 18:13, Michael Nickerson <notifications@github.com> wrote:I just pulled the current code from here, and on restarting tmux, I get shown this output:

/etc/tmuxconf:95: no current session
/etc/tmuxconf:96: no current session


which corresponds to this:

setenv -gu SHLVL
setenv -g IN_TMUX 1


It seems that tmux is trying to unset/set these for the session rather than globally, and failing since it is starting up

(Yes, I know tmux sets environment variables I can test already, but I like setting my own just in case names are changed or that environment variable is no longer set sometime in the future)

**Comment by nicm** [comment]
This should be fixed, will be there next time GitHub syncs.
