### ISSUE TITLE
Tmux freezed when I reattatched

### ISSUE THREAD

**Issue by polarlights** [tmux/tmux#244]
Well, I installed the newest tmux by Homebew, and I system version is EI Capitan 10.11.1.

`brew install --HEAD tmux`

But recently I find that When I open a iTerm window and run `tmux new -s hello`,  then I close the iTerm window, reopen a new window and type `tmux a -t hello`, I can only input about 4 or 20 character, it's then freezed. I can't input anything except tmux shortcuts. 

Is there anyone who has the same issue like me ?

![tmux_20151919](https://cloud.githubusercontent.com/assets/11143982/11911926/2a19edde-a662-11e5-9048-6b75c60309a7.png)

**Comment by polarlights** [comment]
Maybe it's the reason between zsh tmux plugin with tmux. Now I enable tmux autostart, it works now.

**Comment by zackp30** [comment]
I've had this problem, but not with iTerm, just SSH sessions.

I guess it's because, when my SSH session times out (or you close an iTerm while attached), it leaves a file handle open somewhere, the solution I found was to use <kbd>C-b D</kbd> (ctrl-b capital D) which gives you a list of attached `tmux` clients. Then just use arrow keys to navigate to the old session (kinda hard to distinguish them... but the default cursor position is the current session, so move to any of the others) and hit Enter, that will detach the session and allow you to type again.

I hope this works!

**Comment by polarlights** [comment]
@zackp30  Well, if I use `tmux a -t [target session name]`, It will duplicate another session and get stucked. Kill one of them will be ok. Another computer of mime installed tmux 2.0 works well. I dont't know the reason why.

**Comment by zackp30** [comment]
Yeah, somewhere on the way from 2.0 to Git it started happening. Mildly annoying however, of course killing the dead session is a workaround. But it should be fixed.
