### ISSUE TITLE
First window in new sessions does not inherit environment variables set using hooks

### ISSUE THREAD

**Issue by carlocab** [tmux/tmux#2455]
### Issue description

Shells started with `new-session` do not inherit session environment variables set using hooks. However, subsequent shells that are started using `new-window` or `split-window` do. I can work around this by using my `zshrc` to query the session environment for the variables I need, but it would be nice if I didn't need to do this (and it is redundant for all but the first window in a new session).

I can reproduce the issue by running `tmux -Ltest -ftest.conf` with a single line in `test.conf`:

    set-hook -g session-created 'set-environment FOO bar'

Running `echo $FOO` returns nothing in shell opened by the new session, but doing the same in new windows or panes returns `bar`.

I actually want `FOO` to take a different value for each session. This is why I set it using a hook, rather than just invoking `set-environment` directly. Are hooks run asynchronously? That might explain what's going on.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): `tmux next-3.3`
* Platform (`uname -sp`): `Darwin i386` (macOS 10.15.7)
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` and `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

Attached logs were generated using `tmux -vv -Ltest -ftest.conf new`.

[tmux-client-32936.log](https://github.com/tmux/tmux/files/5489986/tmux-client-32936.log)
[tmux-out-32938.log](https://github.com/tmux/tmux/files/5489987/tmux-out-32938.log)
[tmux-server-32938.log](https://github.com/tmux/tmux/files/5489988/tmux-server-32938.log)

**Comment by nicm** [comment]
`session-created` is fired after the session is created, by which time the window has been created as well. It would be fiddly to do what you want because by the time the `new-session` command is fired it is too late - any hook commands will be executed after `new-session` is finished. You would need to make `new-session` queue the hook and then insert a queue item after the hook to continue creating the new session.

It would be easier to replace `new-session` with a script, either by changing key bindings or with `command-alias`, or to do it in your shell profile as you suggest.

**Comment by carlocab** [comment]
I see. Would including a `before-session-created` hook be theoretically possible?

I know a little C++, and have been meaning to learn C, so I don't mind trying to work on such a hook (at some point, when I understand C a bit better -- which might be a while) if it were possible. I've been interested in additional hooks too (when panes a joined to a window, for example, which I don't think is an existing hook), so I might give those a try too.

**Comment by nicm** [comment]
It is easy to add hooks if they can run after the current command finishes, that is how much of them work - you can just add calls to notify_hook/notify_session/etc.

You want a hook that runs before the command that triggers it which would be difficult to implement because you would need to return from the command and return to it later.

**Comment by carlocab** [comment]
I see. I'll try and have a look at what's there at the moment. Thanks!
