### ISSUE TITLE
Can't use a single command

### ISSUE THREAD

**Issue by CristoAMH** [tmux/tmux#2501]
* tmux version (`tmux -V`).
- tmux 3.1c
* Platform (`uname -sp`).
- Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`)
Outside: Alacritty
Inside: screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
![logs](https://i.imgur.com/1aRpsSY.png)

Basically inside tmux I can't use any command. Even my keyboards arrows doesn't work. So far from what I have searched it seems like something aboyt that my FPATH inside tmux is empty(?). I am stuck. Any clue?

**Comment by nicm** [comment]
Sounds like a zsh problem or a problem with your profiles to me.

**Comment by CristoAMH** [comment]
I tried with Bash aswell. Still not working.

> Sounds like a zsh problem or a problem with your profiles to me.

**Comment by mohkale** [comment]
@CristoAMH 

Looks to me like your PATH is being messed up somewhere. Double check `echo "$PATH"` (should work because echo is  a shell buitlin).  From the looks of it you have got /bin /usr/bin etc. in your PATH so I'm not sure where the issue is. Does this only happen in tmux? Where is ls located on your filesystem, double check you can run it with a fullpath and then try adding that paths directory to your PATH.

Remember you should always export PATH .
