### ISSUE TITLE
Search counter

### ISSUE THREAD

**Issue by qblays** [tmux/tmux#2508]
When using search in copy mode number of current occurrence doesn't change.
Sometimes it shows wrong number of total occurrences.
It works fine on release 2.8.
* tmux version: tmux next-3.3
* Platform: Linux unknown
* $TERM inside: tmux-256color
* $TERM inside: xterm-256color

![2020-12-18-19-44-15](https://user-images.githubusercontent.com/59392870/102634925-fe60e080-416b-11eb-9e13-b1503b4db05c.gif)

**Comment by qblays** [comment]
It updates if the window is resized.

**Comment by nicm** [comment]
I think we will have to remove this because if we only search the visible text in order to generate the marks we have no way of knowing how many matches are hidden.

**Comment by topcat001** [comment]
Yes I noticed this as well. The code that is drawing the (x/y) label probably shouldn't run anymore. When resizing something else runs which just displays a count. Perhaps it can just show how many matches are currently being displayed? As a user I'd be also fine with dropping it altogether.

**Comment by topcat001** [comment]
This particular bug is due to the code at the start of `window_copy_search` [here](https://github.com/tmux/tmux/blob/d936fde7ef62863fbb8b142c3ee229cb460dbfdb/window-copy.c#L2932) which sets the `visible_only` flag. If the search string matches the cached string in `wp` then the `visible_only` flag is set. This case, the counters are no longer updated. So the very first search of a particular string will show the correct counts (or if a new string different from the last one is searched), but searching it again will not.

For repeated searches, if we just do `search-again` then the counts will be shown but they will not change since it is only printing the old values. For a new search with the same string as before we get (0/0) because the counters are never set.

Resizing clears the cache and then the counters are set correctly once, but then they become stale again.

**Comment by topcat001** [comment]
I might be missing something, but if the search did not time out then is it necessary to only search the visible area?

**Comment by nicm** [comment]
It's much faster to only search the visible area so I think we chose to do that when possible, ie when the total count couldn't have changed. TBH I think I would remove the match count - emacs doesn't show one, does vi? What use is it really?

**Comment by topcat001** [comment]
Thanks, I'm totally okay with removing it. I have no use for it myself.

**Comment by topcat001** [comment]
vi also does not show a count.

**Comment by topcat001** [comment]
Looks like if we drop the count altogether then a lot of things can be simplified. I'll look into it more carefully tomorrow :)

**Comment by topcat001** [comment]
Hi, I have removed the counters in https://github.com/topcat001/tmux/commit/fbf30b4d8ae87521e459306b95fe2869c16b1d2d

Some simplifications:
- We only search the visible area now, since there is no count to update.
- Keep only the long timeout.

Please have a look, thanks!

**Comment by nicm** [comment]
Thanks but we don't want to remove the count of total matches, only the current match indicator (so it will still say `1000 results` just never `10/1000 results`).

**Comment by topcat001** [comment]
Thanks for the feedback and sorry I misunderstood. I've updated the code to drop just the current match: https://github.com/topcat001/tmux/compare/d936fde7ef62863fbb8b142c3ee229cb460dbfdb...7dfe82091558e474f86c0ff77a484ac065967e63

I think when we enter copy mode we need to do a full search the first time even if the string and regex have not changed since the last search because more lines may have appeared in the pane and then the count needs to be updated. Refreshing the copy mode content calls `window_copy_size_changed` and then a full search takes place as well.

**Comment by nicm** [comment]
Great stuff, applied now, thanks!

**Comment by rightaway** [comment]
@nicm I'm getting this problem in version 3.1c, was the fix included in that version or it's coming in later version?

I have 2 search results but it shows `1/1 results` regardless of which result I am on by pressing `n`. It should show either `1/2 results` or `2/2 results` depending on which result I'm on.

If I start scrolling with the mouse it changes to `0 results` unless a search result is scrolled into view and then it says `1 result`. Both of those look wrong too.

**Comment by topcat001** [comment]
I think it missed the 3.1c release. It is in master now so 3.2 should have it.
