### ISSUE TITLE
Command length limited not documented

### ISSUE THREAD

**Issue by ole-tange** [tmux/tmux#254]
There is a limit on the length on the command. This limit should either be removed (preferred) or documented in the man page:

    $ tmux1.8 new-session -d echo' '"`yes | head -c 2028`"
    OK 
    $ tmux1.8 new-session -d echo' '"`yes | head -c 2029`"
    command too long

    $ tmux1.9 new-session -d echo' '"`yes | head -c 16344`"
    OK
    $ tmux1.9 new-session -d echo' '"`yes | head -c 16345`"
    failed to send command

**Comment by ThomasAdam** [comment]
I don't see this as a problem, and this is something most people shouldn't be hitting anyway.

**Comment by krader1961** [comment]
I agree that this isn't a problem in practice. A 2KB command buffer should be more than enough. These are supposed to be commands a human would type interactively at a shell; not entire scripts. And removing the limit complicates the code and just shifts the problem. What happens when someone does something really stupid and attempts to send a "command" several hundred megabytes in length? Having said that it would be a good idea to document the limit; preferably with a rationale like the one I mentioned earlier.

**Comment by nicm** [comment]
I don't feel particularly strongly that this needs to be documented but if someone sends a change I'll look at it.
