### ISSUE TITLE
Slow output in `tmux` in recent `xterm`

### ISSUE THREAD

**Issue by agguser** [tmux/tmux#2556]
### Issue description

When using `tmux` (v3.1c) in recent `xterm` (v365) (in `Arch Linux`), output of some programs is very slow (but fast if run in `xterm` outside `tmux`, or in `tmux` in `urxvt` or `xterm` v362).

```sh
$ xterm
$ perl -E 'say for 1..10000'   # fast output

$ tmux -f /dev/null
$ perl -E 'say for 1..10000'   # slow output
$ seq 1 10000   # fast output
```

### Required information

```
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 3.1c
xterm-256color
```

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by agguser** [comment]
Not happen with `tmux next-3.3`. Thanks.

**Comment by nicm** [comment]
So you change the xterm version and not the tmux version and xterm is now slow?

**Comment by nicm** [comment]
Show me the server log please.

**Comment by nicm** [comment]
Looks like xterm 365 is not responding to `\033[>q`, although it does so when I send it manually.

**Comment by nicm** [comment]
Oh no, it does respond. I am reading the wrong thing in the log.

**Comment by nicm** [comment]
xterm 365 works fine for me, show me the tmux server log please.

**Comment by agguser** [comment]
To be clear: tmux 3.1c and next-3.3 are slow in xterm 365, but fast in xterm 362. Tested with `tmux -f /dev/null`.

To produce the "tmux server log" ([tmux-server-17401.log](https://github.com/tmux/tmux/files/5933778/tmux-server-17401.log)), I use `tmux -f /dev/null -vv`, and notice that the output is fast! I don't know how to produce the log without `-v`.

Let me repeat: `tmux -f /dev/null` is slow, `tmux -f /dev/null -vv` is fast.

**Comment by nicm** [comment]
Logging doesn't change anything about how tmux writes to the terminal...

But perl is slow and seq is fast?

Can you do this:

~~~~
$ perl -E 'say for 1..10000'  >perl.out
$ seq 1 10000 >seq.out
~~~~

Then if you do `cat perl.out` is it still slow? Is `cat seq.out` still fast?

Please send me both files.

**Comment by agguser** [comment]
Both are fast (with or without `-vv`). And here are the server logs (with `-vv`): [tmux-server-18106.perl.log](https://github.com/tmux/tmux/files/5933906/tmux-server-18106.perl.log), [tmux-server-18116.seq.log](https://github.com/tmux/tmux/files/5933916/tmux-server-18116.seq.log).

By the way, I found that without `-vv` (where `perl …` is always slow), `seq 1 10000 | sed 's/^//'` is sometimes fast, sometimes slow. (You may try `for i in {1..10}; do seq 1 10000 | sed 's/^//'; done`.)

I don't have a clue why this happens, but all output are fast outside `tmux` or in `xterm 362`.

**Comment by nicm** [comment]
Run `strace -tttt -fo perlstrace.out perl ...` and the same with seq and show me the two strace files.

**Comment by nicm** [comment]
I think perl is slower and is generating output in smaller blocks so tmux does not have so much opportunity to throw it away, but there is no reason it should be hugely slower.

**Comment by nicm** [comment]
Did this definitely start in 365? Is 364 OK?

**Comment by agguser** [comment]
xterm 364 has this problem too! Not sure about 363 (didn't install it).

**Comment by nicm** [comment]
OK can you try 363 as well?

**Comment by agguser** [comment]
xterm 363 has this problem too!

**Comment by agguser** [comment]
Do you still want `strace` output?

**Comment by nicm** [comment]
Are you sure you built 362 and later versions in the same way?

**Comment by nicm** [comment]
There is no real difference between what tmux is doing in the perl and seq cases. How do you mean it is very slow? How are you measuring it? What do you see?

**Comment by agguser** [comment]
I use Arch Linux, where xterm is a binary package (https://archive.archlinux.org/packages/x/xterm/), and I think (not sure) the versions are built the same way (https://github.com/archlinux/svntogit-packages/commits/packages/xterm/trunk).

**Comment by nicm** [comment]
Here is the times for each time tmux scrolls to clear the screen in the two logs:
~~~~
$ grep 39S tmux-server-18116.seq.log
1612542401.204835 /dev/pts/3: \033[39S
1612542401.228608 /dev/pts/3: \033[39S
1612542401.251692 /dev/pts/3: \033[39S
1612542401.264693 /dev/pts/3: \033[39S
1612542401.275106 /dev/pts/3: \033[39S
1612542401.285528 /dev/pts/3: \033[39S
1612542401.296015 /dev/pts/3: \033[39S
1612542401.306906 /dev/pts/3: \033[39S
1612542401.317873 /dev/pts/3: \033[39S
1612542401.328658 /dev/pts/3: \033[39S
1612542401.339424 /dev/pts/3: \033[39S
1612542401.349941 /dev/pts/3: \033[39S
1612542401.360495 /dev/pts/3: \033[39S
1612542401.370868 /dev/pts/3: \033[39S
1612542401.375395 /dev/pts/3: \033[39S
$ grep 39S tmux-server-18106.perl.log
1612542334.523069 /dev/pts/3: \033[39S
1612542334.547057 /dev/pts/3: \033[39S
1612542334.570146 /dev/pts/3: \033[39S
1612542334.582272 /dev/pts/3: \033[39S
1612542334.592759 /dev/pts/3: \033[39S
1612542334.603063 /dev/pts/3: \033[39S
1612542334.613380 /dev/pts/3: \033[39S
1612542334.623886 /dev/pts/3: \033[39S
1612542334.634255 /dev/pts/3: \033[39S
1612542334.644891 /dev/pts/3: \033[39S
1612542334.655404 /dev/pts/3: \033[39S
1612542334.665993 /dev/pts/3: \033[39S
1612542334.676793 /dev/pts/3: \033[39S
1612542334.686961 /dev/pts/3: \033[39S
1612542334.691577 /dev/pts/3: \033[39S
~~~~
You can see that in both there is about 10-20 milliseconds between each one. The total time is 0.1685 for perl and 0.1705 for seq.

So it the only difference can be in how xterm is consuming the data or rendering the output, and it is not doing that slowly enough to be triggering tmux to discard any data because that would appear in the log.

**Comment by nicm** [comment]
Oh wait, that is the two cat lots, let me check the perl/seq directly logs.

**Comment by nicm** [comment]
Oh yeah, it is fast with logging on...

**Comment by nicm** [comment]
Can you do the two strace please of tmux without `-vv` so we can see what tmux is writing and when?

**Comment by agguser** [comment]
With `perl -E 'say for 1..10000'`, "fast" means you see "…9999\n10000\n" nearly instantly; "slow" means you progressively see "…\n1000\n1001\n…2000\n…9999\n10000\n" (it takes about 3 seconds to finish).

Could you please specify the whole `strace` command-line to use? I have no idea.

**Comment by nicm** [comment]
~~~~
strace -ttt -fostrace-perl.out perl  -E 'say for 1..10000'
strace -ttt -fostrace-seq.out seq 1 10000
~~~~

**Comment by nicm** [comment]
Also please do this:
~~~~
tmux kill-server; strace -ttt -fostrace-tmux-perl.out tmux new "sleep 1;perl  -E 'say for 1..10000'"
tmux kill-server; strace -ttt -fostrace-tmux-seq.out tmux new "sleep 1;seq 1 10000"
~~~~

**Comment by agguser** [comment]
[strace-perl.out.txt](https://github.com/tmux/tmux/files/5934343/strace-perl.out.txt) (in tmux, slow)
[strace-seq.out.txt](https://github.com/tmux/tmux/files/5934349/strace-seq.out.txt) (in tmux, now slow)

[strace-tmux-perl.out.txt](https://github.com/tmux/tmux/files/5934359/strace-tmux-perl.out.txt) (slow)
[strace-tmux-seq.out.txt](https://github.com/tmux/tmux/files/5934346/strace-tmux-seq.out.txt) (slow)

[strace-perl-no-tmux.out.txt](https://github.com/tmux/tmux/files/5934353/strace-perl-no-tmux.out.txt) (outside tmux, quite fast)
[strace-seq-no-tmux.out.txt](https://github.com/tmux/tmux/files/5934351/strace-seq-no-tmux.out.txt) (outside tmux, fast)

**Comment by nicm** [comment]
> strace-tmux-perl.out.txt (slow)
> strace-tmux-seq.out.txt (slow)

So when you run tmux in strace, seq is slow as well>

**Comment by agguser** [comment]
Yes!

**Comment by nicm** [comment]
Can you show me the strace from doing this in rxvt instead of xterm, assuming that is fast?
~~~~
tmux kill-server; strace -ttt -fostrace-tmux-perl.out tmux new "sleep 1;perl  -E 'say for 1..10000'"
~~~~

**Comment by agguser** [comment]
[strace-tmux-perl.urxvt.out.txt](https://github.com/tmux/tmux/files/5934509/strace-tmux-perl.urxvt.out.txt) (fast)

**Comment by nicm** [comment]
Can you show me the same thing using xterm-362 as well please?

**Comment by agguser** [comment]
[strace-tmux-perl.xterm362.out.txt](https://github.com/tmux/tmux/files/5934529/strace-tmux-perl.xterm362.out.txt) (fast, but little slower than urxvt)

**Comment by nicm** [comment]
In both these strace's, tmux is only able to read 30-50 bytes from perl each time, so it is not able to throw away much data and it all has to go to the terminal. The difference must be that rxvt is able to update much faster than xterm. But in the tmux -vv logs you showed earlier, it was reading 4095 bytes each time which means it could throw away a lot of data.

**Comment by agguser** [comment]
From xterm 363 change log (https://invisible-island.net/xterm/xterm.log.html#xterm_363), is there anything that might cause the problem?

**Comment by nicm** [comment]
Yes, I had looked already and didn't see anything obvious.

There is a bit of a difference in how much tmux is able to write to newer xterm version:
~~~~
                strace-tmux-perl.out.txt readv:  2790 366201 131.255
                strace-tmux-perl.out.txt writev: 10421 71163 6.82881
          strace-tmux-perl.urxvt.out.txt readv:  2275 364595 160.262
          strace-tmux-perl.urxvt.out.txt writev: 12115 166984 13.7832
       strace-tmux-perl.xterm362.out.txt readv:  2349 366201 155.897
       strace-tmux-perl.xterm362.out.txt writev: 12192 169467 13.8999
~~~~
The average read is a little lower (131 vs 155) but the average write is significantly lower (6 vs 13).

**Comment by nicm** [comment]
Hold on, this is including the perl output. This is more accurate:
~~~~
                strace-tmux-perl.out.txt readv:  2645 130558 49.3603
                strace-tmux-perl.out.txt writev: 418 22251 53.2321
          strace-tmux-perl.urxvt.out.txt readv:  2128 128952 60.5977
          strace-tmux-perl.urxvt.out.txt writev: 2112 118072 55.9053
       strace-tmux-perl.xterm362.out.txt readv:  2204 130558 59.2368
       strace-tmux-perl.xterm362.out.txt writev: 2189 120555 55.0731
~~~~
So either I am still parsing the files wrong, or tmux is writing much less data to xterm 365...

**Comment by nicm** [comment]
I have no time to look at this further today but it does appear there is some difference in how xterm 365 is accepting data. The fact tmux seems to be sending less makes me think it is going into redraw mode at least once but I can't see that in the strace. Anyway I will take another look next week.

**Comment by ThomasDickey** [comment]
Offhand, the change for `CopyWait` is performance-related (but that change supposedly limits the newer behavior to configurations using active-icon, e.g., if the window manager is fvwm2).

**Comment by agguser** [comment]
I use `fvwm 2.6.9`.

**Comment by agguser** [comment]
After testing with `dwm`, outputs are fast! So the problem occurs "in tmux in xterm 363+ in fvwm". But I wonder why no such problem outside tmux?

**Comment by krader1961** [comment]
> But I wonder why no such problem outside tmux?

The answer is almost certainly because both programs are using one or more [heuristic](https://en.wikipedia.org/wiki/Heuristic)(s) that interact in an unexpected, deleterious, manner. Welcome to the real world of software engineering.

**Comment by agguser** [comment]
The problem disappears when I disable xterm's active icon (using `xterm -ai`). Thanks everyone, my problem is solved now. You may close this issue, add note about this problem and the workaround, or try to fix the "heuristic".

**Comment by nicm** [comment]
If xterm is too slow to accept data then tmux will switch to redrawing intermittently instead of sending the data as it comes in, because otherwise if you do something unbounded like `yes` then tmux will end up buffering so much data that it will not be able to respond to key presses. This trades throughout for responsiveness. Because it is fast outside tmux, I expect it is on the borderline of the decision to do this, but tmux can't know that running perl is going to stop so I suspect it is redrawing for some of the time, although I couldn't tell for sure from the strace.

The reason is it fast with logging is that this slows tmux itself down which means instead of processing 50 or so bytes at a time from perl, it can has full 4095 byte blocks, which means that it is able to discard much more data (if you scroll 100 lines on a terminal which is only 20 lines high, tmux will only send 20 lines to the terminal if the 100 lines are all received together in one read() from the pty).

Without tmux it is quite different and perl is paced to what xterm can accept because the pty buffer is limited and

**Comment by nicm** [comment]
I wonder if we should artificially slow down incoming data to give tmux more opportunities to discard unnecessary lines. The problem with this is that it will slow down seeing for applications which do not scroll in order to improve applications that do. Although we could turn it off when reading from applications using the alternate screen. It does punish fast terminals and networks to help slow ones however. Maybe I will give it a try at some point.
