### ISSUE TITLE
Add option to put window list in the absolute centre of the terminal

### ISSUE THREAD

**Issue by vimpostor** [tmux/tmux#2578]
From the manual page:
```
status-justify [left | centre | right]
Set the position of the window list component of the status line: left, centre or right justified.
```

I know it is intentional that `centre` puts the window list in the relative `centre`, that is in the center of the available free space.
However it would be very nice if we could also put the window list in the absolute centre of the entire horizontal space. Maybe the syntax could be `set -g status-justify abs-centre`.

A not unreasonable (and I think very common) usecase for this is that when the length of the left and right statusline components differ depending on the current window, it will cause the centred window list to flicker to different positions upon window switch. This is especially annoying when you use the mouse to switch windows.

If you need further details for this usecase, take a look at https://github.com/vimpostor/vim-tpipeline/issues/6

**Comment by nicm** [comment]
Can't you pad your status-left and status-right so they are always the same width?

**Comment by vimpostor** [comment]
Well the `#{p}` option for padding does not seem to work with commands.
For example `set -g status-left '#{p20:#(printf test)}'` does not output 'test' padded to a length of 30, but instead outputs nothing. Maybe I am using it wrong?

**Comment by nicm** [comment]
No it wouldn't, but if you are using printf why not make it do the padding?

**Comment by vimpostor** [comment]
Because I am not using printf. This was just an example, in reality I am using a much more complicated command, that outputs tmux options. For example the output of my command might be: '#[fg=#cfcfcf,bg=#212121]test'. Now in order to pad this from my command's site, I would have to implement partial tmux parsing (because just calling string length on that string would ignore the fact that the '#[fg=#cfcfcf,bg=#212121]' part does not add any length to the final parsed statusline string).

Of course for that color sequence computing the final added string length (which is always 0) is easy, but it gets even harder for other tmux format sequences. From tmux's side this would be much easier, as tmux knows the final parsed string.

**Comment by vimpostor** [comment]
If you guide me through what is the cleanest way to implement this, I can implement this myself. Or maybe it would just be easier to make the `#p{}` option work for commands too?

**Comment by nicm** [comment]
Sure, I am OK with adding it especially if you are going to do it.

I think we need to add a new alignment, so it is quite complicated:

- Add it to `enum style_align` and the corresponding bits in `style_parse` and `style_tostring`. I think I'd prefer `absolute-centre` rather than `abs-centre`

- Add a new item to `options_table_status_justify_list` in `options-table.c`. This should match the name used in `style.c` or it won't work.

- Then the big changes are in `format-draw.c`.

- If you look at `format_draw` there is a screen created for each section of the line - left, centre, right. This is where text that belongs to each section is added. You will need to add a new one, make sure the indexes in the enum and in `names` match up. The `map` variable maps a style to a screen, so you need to add your new list index in the right place in it too.

- Once it has gathered all the text into the correct screens, it calls one of four functions to draw, depending where the window list is placed. Each one takes seven screens - the left, centre and right contents, the list left, list and list right contents, and `after` which is any content that goes after the window list in the same alignment. So if `format_draw_centre` is called with left=Z, centre=Y, right=X, list_left=a, list_centre=b, list_right=c and after=A, then it writes `Z  YabcA   X`.

- You'll need to add your new list to each of these functions as well and decide how it fits together with the existing left, right, centre. I am not really sure how it will fit, I guess it should just draw over the top.

- Then you will need a new function to deal with the list itself being in the absolute centre, this will be similar to `format_draw_centre` except with different calculations for the position.

**Comment by vimpostor** [comment]
Hi sorry for the late reply, I was quite busy the last days. Today I had time to hack around a bit and it was actually quite easy to implement this using your instructions. :)

I just need to clean up and refactor my patch a bit before submitting, but in order to do so I need to understand a few things first:
- What is `after` used for? I don't quite seem to understand its purpose, when we already have `list_right` coming after `list`.
- How can we achieve to have a nonempty value for `list_left` and `list_right` via the config?
- How can we achieve to have a nonempty value for `centre` via the config? That is, I don't really understand the difference between `centre` and `list_centre`.

**Comment by nicm** [comment]
The window list is made up of three parts. `list_left` and `list_right` are the left and right markers for the window list and `list_centre` is the window list itself. `after` is any non-list text that goes after the window list at the same alignment as the list. If there are more windows than fit in the available space for the window list, then `list_left` or `list_right` will be used. They are not empty in the default `status-format[0]`.

`centre` is any text that appears in the centre. If the window list is in the centre then this will be the text before the window list, and `after` will be the text after the window list. If the window list is not in the centre then `centre` will be the entire text for the centre and `after` will be whatever text is after the status line in the alignment it has.

**Comment by vimpostor** [comment]
[0001-Allow-to-centre-window-list-in-the-absolute-centre.patch.txt](https://github.com/tmux/tmux/files/6095865/0001-Allow-to-centre-window-list-in-the-absolute-centre.patch.txt)

Hi I finally managed to clean up my patch. Attached you will find it. Actually after cleaning up, the patch file was quite straight forward. In the new method `format_draw_absolute_centre()` I draw `left` and `right` and `centre` like always, but the list is drawn in the absolute centre over the rest. For this simple patch there is no code to detect if `list` is large enough to draw over other stuff, for example `left`, but maybe this is something that can be added later if a specific behaviour is wanted (but honestly I think just drawing over the rest is the best behaviour).

In the config, the new behaviour can be activated using: `set -g status-justify absolute-centre`

Also here is a asciinema recording showcasing the different behaviour: First I use the old relative centre justify. As you can see at the very bottom, the status bar window component flickers much with the old setting. At 0:10 I switch to the new absolute centre, and the flickering is gone: https://asciinema.org/a/zECnasMwRqPg5TztGNO1xPBcp

**Comment by nicm** [comment]
Hi

This looks good and is definitely on the right lines but it is not quite enough to only draw the list in the centre, for example this doesn't work:
~~~~
set -g status-format[0] '#[align=left]LEFT#[align=absolute-centre]CENTRE#[align=right]RIGHT'
~~~~
You are writing the "CENTRE" text into `LIST_ABSOLUTE_CENTRE` but then you only do anything with it if the list is in the absolute centre, you need to add code to the existing functions (`format_draw_none` etc) to draw it even if the list is elsewhere (or entirely turned off). I think this should be pretty simple since it will just draw the absolute centre text over the top of whatever is already drawn.

If the list is in the centre it seems good however, so it is pretty close. This seems fine:
~~~~
set -g status-format[0] '#[align=left]LEFT#[align=absolute-centre]#[list=on]LIST#[nolist]AFTER#[align=right]RIGHT'
~~~~

Thanks

**Comment by vimpostor** [comment]
Yep you are right, I didn't think about the non-list centre.
I have fixed this in the attached patch now. For the case where there is both an absolute-centre list and an absolute-centre non-list text. The non-list centre will be written **before** the list centre, but both will be centred together, which will make it consistent for all cases where there is no list in the centre (either because the list is empty and in the absolute centre or because the list is not in the centre).
[0001-Allow-to-centre-window-list-in-the-absolute-centre.patch.txt](https://github.com/tmux/tmux/files/6110999/0001-Allow-to-centre-window-list-in-the-absolute-centre.patch.txt)

**Comment by nicm** [comment]
Looks great. Applied to OpenBSD now, will be in GitHub next time it syncs up. Thanks!
