### ISSUE TITLE
What if there *is* a way of telling C-<letter> from C-S-<letter>

### ISSUE THREAD

**Issue by DanielVartanov** [tmux/tmux#2634]
As mentioned in https://github.com/tmux/tmux/issues/627, https://github.com/tmux/tmux/issues/674 and https://github.com/tmux/tmux/issues/309#issuecomment-185369061, `tmux` has no chance to tell from `C-i`, `C-I` and `Tab` as the terminal emulator would return the same number for all three of them.

But there is a standard which gains traction: [fixterms](http://www.leonerd.org.uk/hacks/fixterms/)
There are already patches for terminal emulators to support it ([example](https://st.suckless.org/patches/fix_keyboard_input/), [example](https://groups.google.com/g/iterm2-discuss/c/KpSlgnY_zxw?pli=1)), but the standard also requires _the applications_ to adopt it too.

Here is a nice TL;DR from @cstrahan on the whole picture of the issue, it can save you some time: https://github.com/neovim/neovim/issues/176#issuecomment-37070131 

So my actual questions are:
* Was this discussed by the maintainers before?
* Does it sparkle any enthusiasm among them?
* Will it be welcomed if anyone (maybe me) implements it one day and proposes as a PR?

**Comment by nicm** [comment]
This is xterm's "modifyOtherKeys" set to 2. I believe xterm (and perhaps mintty) is the only terminal which supports this, are there any other terminals that you have in mind?

modifyOtherKeys 1 has a little wider support, including iTerm2.

tmux supports modifyOtherKeys 1, see https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys.

If you want to do it, I don't mind supporting modifyOtherKeys 2 (perhaps adding a new `all` value to `extended-keys`; it would also need the `extkeys` terminfo entry changed to take an argument).

**Comment by mohkale** [comment]
> are there any other terminals that you have in mind?

I've tried binding shift sequences with [st](https://github.com/mohkale/st) in the past and it's never worked for me. I guess because st also sets `modifyOtherKeys` to 2. While not builtin, there's a patch to build st with this extended keys support (it's the first example linked above).

> If you want to do it, I don't mind supporting modifyOtherKeys 2

I'm not sure how this would work but I'm seriously looking forward to if/when this happens :smile:.

**Comment by nicm** [comment]
Someone emailed me earlier and said it worked aside from some keys like C-Backspace, at least for binding keys in tmux. But I don't have time to try it.

**Comment by mohkale** [comment]
> Someone emailed me earlier and said it worked aside from some keys like C-Backspace, at least for binding keys in tmux.

It works with some. For example C-1 (`tmux bind C-1 display-message hello-world`) now works but C-S-o (`tmux bind C-S-o display-message hello-world`) doesn't.

**Comment by nicm** [comment]
Does `C-O` work for `C-S-o`?

**Comment by mohkale** [comment]
> Does C-O work for C-S-o?

Doesn't appear to,

**Comment by nicm** [comment]
Probably either isn't recognised or isn't mapped to the right key_code internally, look at tty_keys_extended_key for incoming (from client) or near end of input_key for outgoing (to pane). It should log what it is getting and what it thinks it is if you use -vv.

Also make sure it isn't switching the terminal back to modifyOtherKeys = 1 which it will do if it recognises it supports the keys.

**Comment by mohkale** [comment]
@nicm 

Thanks for the tips. [Here's](https://github.com/tmux/tmux/files/6259119/tmux-server-1025916.log) my server log file.

The relevent parts seems to be:

```
1617639328.842200 /dev/pts/7: read 7 bytes (already 0)
1617639328.842235 /dev/pts/7: keys are 7 (\033[79;6u)
1617639328.842249 /dev/pts/7: extended key \033[79;6u is 60000000004f (C-S-O)
1617639328.842255 /dev/pts/7: complete key \033[79;6u 0x60000000004f
```

Looking into my terminal emulator source and trying `C-v C-S-o` outside of tmux, that is what it enters.

> Also make sure it isn't switching the terminal back to modifyOtherKeys = 1 which it will do if it recognises it supports the keys.

Not sure how to check whether this is happening ?

**Comment by nicm** [comment]
OK so tmux is seeing the 79 = O and 6 = C-S and combining them to get `C-S-O` rather than `C-S-o` or `C-O`. But you will only be able to bind `C-S-o` or `C-o` because we parse the string `C-O` as `C-o` (because normally `C-O` doesn't exist).

We could convert an incoming `C-S-O` into `C-O` or `C-S-o` but I am not sure I like that idea because it is rather making assumptions about the keyboard layout (is `S-o` always `O`?).

I think the best thing to do here would be to drop the conversion and allow you to bind `C-S-O`, although it is a bit unintuitive to have to bind `C-S-O` rather than `C-S-o` when for most people they will be the same. Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/6259223/x.diff.txt)

You can check if it is turning it back to 1 by looking for `\033[>4;1m` in the log.

**Comment by mohkale** [comment]
@nicm 

My leader-key seems to have stopped working with the patch you've shared.

Here's the [server](https://github.com/tmux/tmux/files/6259291/tmux-server-1032480.log) log file.

**Comment by nicm** [comment]
Er yes. Try this instead: [x.diff.txt](https://github.com/tmux/tmux/files/6259310/x.diff.txt)

**Comment by mohkale** [comment]
@nicm 

Yep. C-S-O is working :joy:.

**Comment by nicm** [comment]
OK great, I'm not wild about `C-S-O` but I don't see an alternative really, tmux knows nothing about the real keyboard layout.

**Comment by nicm** [comment]
Can you try this as well please which may fix some problems with backspace: [y.diff.txt](https://github.com/tmux/tmux/files/6259399/y.diff.txt)

I don't know if tmux will correctly generate the keys for applications inside, I don't have time to try that.

**Comment by mohkale** [comment]
@nicm 

I'm not completely sure I fully understand why C-S-O is happening, but so long as it's consistent I'm okay with it. If we end up having to bind both C-S-O and C-S-o because of variations in the keyboard layout then I'd be hesitant to ask for this.

> OK so tmux is seeing the 79 = O and 6 = C-S and combining them to get C-S-O rather than C-S-o or C-O. But you will only be able to bind C-S-o or C-o because we parse the string C-O as C-o (because normally C-O doesn't exist).

Is there a reason we don't simply downcase 79 to `O` before joining onto C-S? Like I'd imagine there're some key combinations we want to still be uppercase (eg. M-O) but I'd be fine with migrating to `M-S-O` if needed.

> Can you try this as well

Will do, but I don't have a binding with backspace and I'm not sure how to do so. Could you share an eg. (`tmux bind C-BACKSPACE display-message "Hello World"`).

**Comment by nicm** [comment]
Don't worry about testing anything specific just let me know if it breaks anything else with extended keys.

The reason it is happening is because `S-o` generates `O` but the terminal is *also* telling tmux that `Shift` is pressed, so tmux sees `S-O`. But that isn't a real key on most people's keyboards, you press `S-o` and you get `O`, so people will think of it either as `O` or as `S-o` - `S-O` doesn't make much sense.

We could downcase `S-O` to `S-o` or remove the Shift to leave `O` easily enough but I don't know if there are international keyboard layouts where `S-o` and `O` are *not* the same.

Also it will make life difficult when passing the keys on to applications inside tmux that also want extended keys because when it got to that stage tmux wouldn't know whether it needed to send `C-S-o` or `C-O` or `C-S-O` (although it probably wouldn't matter which it chose).

I think for all the people who will care it is probably better just to require the bindings to match what the terminal sends, so you will need to bind `C-S-O` if that is what the terminal sends. If the terminal sent `C-S-o` instead then you would have to bind that.

**Comment by mohkale** [comment]
> Don't worry about testing anything specific just let me know if it breaks anything else with extended keys.

All right. No issues on my setup, both `C-1`, `C-S-O` and some of my regular bindings seem to be working.

> so you will need to bind C-S-O if that is what the terminal sends. If the terminal sent C-S-o instead then you would have to bind that.

Hmmm... not ideal, but better than the current approach of the key combinations not being bindable at all. Might be nice to add some sort of alias bindings where you can say treat binding X as the same as binding Y, but otherwise I don't mind this. Thanks for explaining in such detail :smile:.

**Comment by nicm** [comment]
BTW you can do `C-b /` and press the key and tmux will show what it thinks it has.

**Comment by mohkale** [comment]
> BTW you can do C-b / and press the key and tmux will show what it thinks it has.

Damn it, I rebound that to search forward. Thanks for the tip, sounds like it'll come in really useful when trying to diagnose this.

**Comment by nicm** [comment]
bind-key    -T prefix       /                    command-prompt -k -p key "list-keys -1N \"%%%\""

**Comment by nicm** [comment]
OK I have found one other problem where tmux is not converting Ctrl keys if they are sent as Ctrl flag + x rather than C-x which. Looks like your terminal doesn't do it (but xterm does). [z.diff.txt](https://github.com/tmux/tmux/files/6259605/z.diff.txt)

I am waiting for someone to get back to me about Backspace and then I will apply this. Thanks!

**Comment by nicm** [comment]
I have applied this now, let me know if you see any further problems. Thanks!

**Comment by nicm** [comment]
I have actually changed my mind and am going to go the other way and convert C-S-X into C-S-x and C-X into C-x. Here is the change I intend to make: [x.diff.txt](https://github.com/tmux/tmux/files/6271771/x.diff.txt)

**Comment by mohkale** [comment]
@nicm 

Just cloned from master and tried out your patch. No issues for me everythings working great :smile:.
