### ISSUE TITLE
Rare race condition leaves zombie

### ISSUE THREAD

**Issue by msharov** [tmux/tmux#2679]
### Issue description

On startup I create a pane for a script that usually exits immediately. This can sometimes leave the script process a zombie. Reproducing the problem has been difficult, and it has started after a CPU upgrade, not a tmux upgrade.

In the source, in spawn.c:458, the following appears to unblock signals after spawn before enabling events on the pane.

```c
sigprocmask(SIG_SETMASK, &oldset, NULL);
window_pane_set_event(new_wp);
```

You seem to be using libevent for signal handling, which is not familiar to me, but this looks like the one place where a SIGCHLD could slip through. 

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.2
* Platform (`uname -sp`): Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`): tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`); no consistent problem reproduction

**Comment by nicm** [comment]
The signal handler is in place before signals are blocked and the signal should be delivered after we restore the signal mask. IIRC the reason signals are blocked are because libevent delivers signals from signal handler to the event loop by using a pipe and if the signal handler were fired in the child it could write to the pipe twice.

You will need to try an reproduce with tmux logging, preferably with strace as well. Or at least just with strace so we can see signal delivery around the fork.

**Comment by msharov** [comment]
I'm sorry, but that's rather a lot of work... I guess I'll just ignore the zombies when they happen.
