### ISSUE TITLE
Possible regression: tmux silently swallows extended keys

### ISSUE THREAD

**Issue by mohkale** [tmux/tmux#2705]
### Issue description

My terminal emulator has special extended keys for C-i and C-m distinct from the standard translation of these key sequences to TAB and RET respectively.

Up until recently I used to be able to bind TAB and C-i independently without issue. For example after running `tmux bind-key -T prefix / command-prompt -k -p key "list-keys -1N "%%%""`. I can do `<prefix> / C-i` and it shows C-i, whereas `<prefix> / TAB` showed TAB.

However now `C-i` is shown as TAB and C-m is shown as RET.

I tried installing an older build (not sure about the specific commit, the version still says next-3.3) and this wasn't an issue there dispite using the same config. I believe this is a regression.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). `tmux next-3.3`
* Platform (`uname -sp`). `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`). `st-256color`, `tmux-24bit`
* Logs from tmux (`tmux kill-server; tmux -vv new`). [older-server-log](https://github.com/tmux/tmux/files/6459489/tmux-server-82895.log), [master-server-log](https://github.com/tmux/tmux/files/6459498/tmux-server-88764.log)

**Comment by mohkale** [comment]
Worth noting other extended keys work fine. `C-1` or `C-S-a` are Ok, it's just C-i, C-m and I imagine some of the other special keys which are implicitly translated to other keys.

**Comment by nicm** [comment]
tmux only has one representation for `C-i` and `C-m` and they are the same as `Tab` and `Enter`.

The problem if we had two is - if you do `bind C-i lsk` which do you mean? If someone is using a terminal without extended keys, `C-i` won't work anymore.

**Comment by nicm** [comment]
Yes, I know, it is intentional. I'll have to think about what to do, I don't want `C-i` to stop working for everyone not using extended keys.

**Comment by mohkale** [comment]
@nicm 

> I don't want C-i to stop working for everyone not using extended keys.

Fair enough, but the issue I have is in emacs I've bound C-i seperate from TAB and tmux seems to send TAB in both cases. I can understand tmux internally treating C-i as TAB but when sending to a pane I'd prefer it sent the same input that was sent to tmux instead of deciding to send what it thinks the input was.

Admittedly I'm not very experienced in the domain of terminal emulators. There might be some special mode or sequence emacs has to send to get this working, not sure whether this is an application problem or a tmux one :/.

**Comment by mohkale** [comment]
@nicm 

Actually if you enable extended keys shouldn't you expect C-i to stop working as TAB. You're sending different sequences so expecting the same behaviour seems odd.

**Comment by nicm** [comment]
If someone does `bind C-i lsk` in `.tmux.conf` but their `C-i` key actually sends `Tab` then if tmux treats them differently `C-i` will not work.

**Comment by mohkale** [comment]
> emacs will need to send the sequence to enable extended keys

How do I check whether it's done this or not, other extended keys (eg. C-1) work fine so it might've.

> you will need to set extended-keys to always.

I did try that before opening the issue, didn't have any noticable difference.

> But at the moment C-i and Tab will be the same no matter what.

Yep. That's my issue :yum:. Would you be open to distinguishing them through a terminfo extension or something to that affect.

**Comment by nicm** [comment]
We currently (deliberately) only support modifyOtherKeys mode 1 which does not alter `Tab`/`C-i`.

It would be nice to support modifyOtherKeys mode 2 also but it changes a lot more keys as well. So the easier stuff is:

---

1. tmux would have to represent the keys differently internally, I am not sure whether it is better to replace `C-i` with `KEYC_CTRL|'i'` and leave `Tab` as `\011` or to replace `Tab` with `KEYC_TAB` and leave `C-i` as `\011`. Similarly for `C-a`, does it become `KEYC_CTRL|'a'` or remain `\001`? It seems more consistent to do the former, but probably less disruptive to do the latter.

2. All the internal use of keys would have to change to the new mapping (key-string.c, status.c, mode-tree.c, window-*.c).

3. Incoming keys (tty-keys.c) would need to map the keys correctly, and Backspace would need to be dealt with.

4. When writing keys to panes which have not sent the escape sequence or have requested mode 1, keys would need to be mapped, so `KEYC_CTRL|'i'` sends `\011`, `KEYC_CTRL|'a'` sends '\001` and so on. We already do this to map, for example, `C-S-i` to `C-i` - see input-keys.c:486.

---

The problems come with key bindings:

1. If someone binds `C-i`, `C-I` or `Tab` in `.tmux.conf` at the moment, they are currently the same. Likewise, `C-S-i`, `C-S-I` or `S-Tab` are all `S-Tab`. We do not want to break this, and I am not sure the best way to do it. Perhaps we add a separate modifier for "mode 2 ctrl key" so `C-i` would have to be bound as `E-i` or something, if you bind `C-i` you end up with `Tab` as before. Not very intuitive however.

2. modifyOtherKeys = 2 terminals send `C-S-A` (27;6;65) for `C-S-a`. But we need `C-A` and `C-a` to both be `C-a`. This is not so big a problem I think because I don't know of any terminals that actually send `C-S-a` (27;6;97), so it is probably OK just to force all `C-A` to `C-a` on input and map `C-S-a` to `C-S-A` on output for mode 2 panes.

**Comment by mohkale** [comment]
@nicm 

Have you had a chance to think more on modifyOtherKeys mode 2?

I just did a system upgrade which accidentally upgraded tmux as well and now I'm gonna have to revert back to make sure all my keybindings still work :grin:.

**Comment by nicm** [comment]
I started looking at it but it is substantial work and I don't have time to do it at the moment.

**Comment by liaden** [comment]
Just a heads up but I ran into what I assume is the same thing with <c-cr> and <s-cr> when going from 3.1 to 3.2a.

**Comment by rbjorklin** [comment]
I've also just ran into this. If you're on Fedora the easiest work-around is to just downgrade to the [tmux-3.1c-2.fc34](https://koji.fedoraproject.org/koji/buildinfo?buildID=1695502) package.

**Comment by ziontee113** [comment]
Thanks to @rbjorklin 's comment, I downgraded tmux to version 3.1_c and things work fine. I still have to manually map those escape codes in my kitty config, but it's working now.

**Comment by huwqchn** [comment]
Any updates?

**Comment by hagata** [comment]
I've ended up here as a new to tmux user, who uses Colemak DH.

For users of Colemak everything H,J,K,L is remapped to M,N,I,E for directional controls and not being able to remap `C-m` and `C-i` as expected for switching panes for example has been impossible so far

**Comment by huwqchn** [comment]
> I've ended up here as a new to tmux user, who uses Colemak DH.
> 
> For users of Colemak everything H,J,K,L is remapped to M,N,I,E for directional controls and not being able to remap `C-m` and `C-i` as expected for switching panes for example has been impossible so far

I also a Colemak user, I use N,U,I,E for movement, I use Ctrl-i for move to right panel, just like my neovim config.

**Comment by benoitlouy** [comment]
I'm also a colemak-dh user and I use `C-i` to move to a different pane. Being able to bind `C-i` independently of `Tab` would be great.

In the meantime I found a workaround:
* configure your terminal to send a sequence of characters when `C-i` is pressed. For instance, I configured alacritty to send `\x1b[24~\x09` (`F12` then `Tab`)
* configure tmux to switch to a different key table when the first character of the sequence is received. In my case I have
	```
	bind-key -T root         F12        set key-table virt
	```
* bind `C-i` in the specified key table. In my case I want the `C-i` control character to be passthrough if vim is running in the current pane. Otherwise I want to move to the panel below. At last I ask tmux to switch back to the root key table.
	```
	bind-key -T virt 'C-i' if-shell "$is_vim" "send-keys Escape '[105;5u'" "select-pane -U" \; set key-table root
	```

Tested with tmux 3.3a

All credit goes to @listx from whom I stole [this trick](https://github.com/listx/syscfg/blob/ec89be4969/tmux/.tmux.conf#L347-L349).

**Comment by tiagovla** [comment]
I found two ~~hackish~~ ways of doing it while there is no proper solution. The first one is to manually add the extended keys to `input_key_defaults` and the second one is to add them on the fly to `input_key_tree`.

https://github.com/tiagovla/tmux/commit/b6be05261a4d92cf41156ccbf5f41d19ca18665f

**Comment by ziontee113** [comment]
Thank you so much @tiagovla, I installed your fork and it worked perfectly. Still have to add the special keymaps to my `kitty.conf` but it works :+1:

**Comment by huwqchn** [comment]
> Thank you so much @tiagovla, I installed your fork and it worked perfectly. Still have to add the special keymaps to my `kitty.conf` but it works +1 Now I don't have to deal with tmux crashing whenever I yank in vi mode any more (had that issue when using tmux version 3.1_c)

> I found two ~hackish~ ways of doing it while there is no proper solution. The first one is to manually add the extended keys to `input_key_defaults` and the second one is to add them on the fly to `input_key_tree`.
> 
> [tiagovla@b6be052](https://github.com/tiagovla/tmux/commit/b6be05261a4d92cf41156ccbf5f41d19ca18665f)
I installed this fork too, but <C-i> and <Tab> still the same key

**Comment by huwqchn** [comment]
@tiagovla  @ziontee113  I installed this fork too, but <C-i> and <Tab> are still the same key

**Comment by huwqchn** [comment]
> > @tiagovla  @ziontee113  I installed this fork too, but  and  are still the same key
> 
> Are they different in your terminal without tmux? If so, what terminal are you using?
I use Kitty as my terminal. As a user of Colemak-DH, I use Ctrl + N, E, I, O to select panels. Everything works fine when I'm not using Tmux. However, when I use Tmux, Ctrl + I and Tab are the same key,even I installed your fork, and my Tab key is bound to too many functions.

**Comment by huwqchn** [comment]
> > @tiagovla  @ziontee113  I installed this fork too, but  and  are still the same key
> 
> Are they different in your terminal without tmux? If so, what terminal are you using?

I use Kitty as my terminal. As a user of Colemak-DH, I use Ctrl + N, E, I, O to select panels. Everything works fine when I'm not using Tmux. However, when I use Tmux, Ctrl + I and Tab are the same key, even I installed your fork, and my Tab key is bound to too many functions.

**Comment by tiagovla** [comment]
> > > @tiagovla  @ziontee113  I installed this fork too, but  and  are still the same key
> > 
> > 
> > Are they different in your terminal without tmux? If so, what terminal are you using?
> 
> I use Kitty as my terminal. As a user of Colemak-DH, I use Ctrl + N, E, I, O to select panels. Everything works fine when I'm not using Tmux. However, when I use Tmux, Ctrl + I and Tab are the same key, even I installed your fork, and my Tab key is bound to too many functions.

Do you have this
```
map ctrl+i send_text normal,application \x1b[105;5u
```
in your kitty.conf?

**Comment by huwqchn** [comment]
> > I use Kitty as my terminal. As a user of Colemak-DH, I use Ctrl + N, E, I, O to select panels. Everything works fine when I'm not using Tmux. However, when I use Tmux, Ctrl + I and Tab are the same key, even I installed your fork, and my Tab key is bound to too many functions.
> 
> Do you have this
> 
> ```
> map ctrl+i send_text normal,application \x1b[105;5u
> ```
> 
> in your kitty.conf?

I have this
# Ctrl + I remap
map ctrl+i send_text all \x1b[105;5u

**Comment by tiagovla** [comment]
> map ctrl+i send_text all \x1b[105;5u

It works for me on kitty. I checked it using ``showkey -a``. Maybe you are executing the wrong version of tmux? Try to kill the current tmux server and to open the local tmux that you built from source?

**Comment by huwqchn** [comment]
> > map ctrl+i send_text all \x1b[105;5u
> 
> It works for me on kitty. I checked it using `showkey -a`. Maybe you are executing the wrong version of tmux? Try to kill the current tmux server and to open the local tmux that you built from source?

It works, Thank you so much, you done a great job

**Comment by huwqchn** [comment]
> > map ctrl+i send_text all \x1b[105;5u
> 
> It works for me on kitty. I checked it using `showkey -a`. Maybe you are executing the wrong version of tmux? Try to kill the current tmux server and to open the local tmux that you built from source?

```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-i if-shell "$is_vim" 'send-keys C-i'  'select-pane -U'
```
But when you bind C-i, it is still bound to the Tab key.

**Comment by tiagovla** [comment]
> But when you bind C-i, it is still bound to the Tab key.

Still gotta figure it out how `key_bindings_add` works in `key-bindings.c`.

**Comment by tiagovla** [comment]
> But when you bind C-i, it is still bound to the Tab key.

https://github.com/tiagovla/tmux/commit/8c29aa35dfe8ecbed20fda792f4a551250371450

**Comment by edte** [comment]
> I use `Tab` to switch between buffers and select items from the autocompletion menu in neovim. The fact that tmux can't distinguish between `Tab` and `C-i` makes it impossible for me to do that **and** use the jumplist feature in neovim because going forward in the jumplist is bound to `C-i`. A fix for this issue would be greatly appreciated.



I have a similar problem. If I use tab mapping as %, I cannot use the jump function of ctrl+i itself. But I checked and found that kitty and nvim already support separating the two. When I set it up as follows, it works normally.

in kitty.conf 
```
map ctrl+i       send_text application \033[105;5u
```
in kitty, and then configured it in nvim
```
if vim.env.TERM == 'xterm-kitty' then
    print("test")
    vim.cmd([[autocmd UIEnter * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[>1u") | endif]])
    vim.cmd([[autocmd UILeave * if v:event.chan ==# 0 | call chansend(v:stderr, "\x1b[<1u") | endif]])

    vim.cmd("nnoremap <c-i> <c-i>")
    vim.cmd("nnoremap <ESC>[105;5u <C-I>")
    vim.cmd("nnoremap <Tab>        %")
    vim.cmd("noremap  <ESC>[88;5u  :!echo B<CR>")
    vim.cmd("noremap  <ESC>[49;5u  :!echo C<CR>")
    vim.cmd("noremap  <ESC>[1;5P   :!echo D<CR>")
end
```
Now when not using tmux, tab and ctrl+i are successfully separated and work very well, but once tmux is used, ctrl+i and tab are together again.

**Comment by stevenxxiu** [comment]
@tiagovla Could you add support for `Ctrl + m` too for your branch? Thanks!

**Comment by LinuxIsCool** [comment]
> Thanks to @rbjorklin 's comment, I downgraded tmux to `version 3.1_c` and things work fine. I still have to manually map those escape codes in my kitty config, but it's working now.
> 
> Here's what I'm adding to my `kitty.conf`
> 
> ```
> # Ctrl 0 - 9
> map ctrl+0 send_text all \x1b[48;5u
> map ctrl+1 send_text all \x1b[49;5u
> map ctrl+2 send_text all \x1b[50;5u
> map ctrl+3 send_text all \x1b[51;5u
> map ctrl+4 send_text all \x1b[52;5u
> map ctrl+5 send_text all \x1b[53;5u
> map ctrl+6 send_text all \x1b[54;5u
> map ctrl+7 send_text all \x1b[55;5u
> map ctrl+8 send_text all \x1b[56;5u
> map ctrl+9 send_text all \x1b[57;5u
> 
> # Ctrl + . , ;
> map ctrl+. send_text all \x1b[46;5u
> map ctrl+, send_text all \x1b[44;5u
> map ctrl+; send_text all \x1b[59;5u
> 
> # Shift + Enter
> map shift+enter send_text all \x1b[13;2u
> 
> # Ctrl + I & Ctrl + M Remaps
> map ctrl+i send_text all \x1b[105;5u
> map ctrl+m send_text all \x1b[109;5u
> 
> # Ctrl + Shift Remaps
> map ctrl+shift+h send_text all \x1b[72;6u
> map ctrl+shift+j send_text all \x1b[74;6u
> map ctrl+shift+k send_text all \x1b[75;6u
> map ctrl+shift+l send_text all \x1b[76;6u
> 
> map ctrl+shift+u send_text all \x1b[117;6u
> map ctrl+shift+o send_text all \x1b[111;6u
> map ctrl+shift+p send_text all \x1b[112;6u
> 
> map ctrl+shift+s send_text all \x1b[108;6u
> ```

How can I do this for alacritty?

**Comment by LinuxIsCool** [comment]
Got it. 

Downgrade to 3.1c and add the following to alacritty.yml:

```
key_bindings:
    - { key: I, mods: Control, chars: "\x1b[105;6u"
```

**Comment by realSaltyFish** [comment]
@mohkale Thanks for the pointer to the related snippet. I revisited this issue today because I can no longer ignore the inconvenience of not being able to yank in vi mode in version 3.1_c. Could someone help me check my understanding:

This function `tty_keys_extended_key` essentially handles CSI u sequences. Applications that do support CSI u sequences will ask about the availability of support in the terminal emulator, and the terminal emulator (I am using kitty) will start sending these sequences instead of legacy keycodes.

Normally without tmux this should work fine, but tmux intercepts the CSI u sequences and translates those that correspond to Ctrl-keys back into their original forms. IMO this is unnecessary and incorrect behavior. If the terminal emulator does not support CSI u sequences, it would not have sent those in the first place so this function is never invoked. I think tmux should honor the terminal emulator's intention and not interfere with applications that explicitly ask for CSI u support.

I have also confirmed that removing this translation does NOT break legacy terminal emulators. I recompiled tmux without the following lines:

```c
		else if (onlykey >= 97 && onlykey <= 122)
			onlykey -= 96;
```

If I configure kitty to send `\x1b[105;5u` for `ctrl+i`, `ctrl+i` can be delivered correctly in Neovim. Otherwise (if I don't specify this keymap in kitty config) it delivers Tab.

I think it is fully safe to remove these lines, and all Neovim/Emacs/kakoune/etc. users will be happy then.

@nicm Please point out if I missed anything. Otherwise if we could agree on this I'll create a PR.

**Comment by realSaltyFish** [comment]
Found some references:
- https://www.leonerd.org.uk/hacks/fixterms/
- https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
I plan to rework this function to match the specification I found. Let me know if it doesn't make sense or needs more discussion.

**Comment by stevenxxiu** [comment]
See also? [Comprehensive keyboard handling in terminals - kitty](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). It's an improved [Fix Terminals - Please](https://www.leonerd.org.uk/hacks/fixterms/) that's used by many programs.

**Comment by tummetott** [comment]
> See also [Comprehensive keyboard handling in terminals - kitty](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). It's an improved [Fix Terminals - Please](https://www.leonerd.org.uk/hacks/fixterms/) that's used by many programs.

Yess I second this. If tmux would support kitty's keyboard protocol all problems would be solved as it's superior and backward compatible with fixterm CSI u sequences

**Comment by sotte** [comment]
For completeness I'm cross linking this (closed) issue https://github.com/tmux/tmux/issues/3335 which proposes to implement the [kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). This would make it easier to handle/distinguish key sequences like `ctrl-i` and `tab`.

**Comment by nicm** [comment]
Mode 2 is now supported and mode 1 more fully as of tmux 3.5a, although I would probably use master since there have been a few fixes.
