### ISSUE TITLE
[Strange bug] Resize Windows terminal with Tmux and give some strange issue

### ISSUE THREAD

**Issue by buinguyenhoangtho** [tmux/tmux#2740]
# Info
**Platform**: WSL2 + Window Terminal
**OS**: Windows 10 21H1 (OS Build 19043.1055)
**tmux-v**: 3.0a
**uname -sp**:Linux x86_64
**echo $TERM**:screen-256color```
**Shell:** fish- omf + tmux-zen plugins

# Problem
When im closing every session on tmux, it give me this strange background issue

![tmux bug](https://user-images.githubusercontent.com/76900905/121793200-f075af00-cc26-11eb-9c1e-765c23df864e.PNG)

Please help.

**Comment by krader1961** [comment]
You need to tell us what you mean by "strange background issue". What is unexpected about the background of the image you showed us? Also, it is not clear what steps you took to reach that state. That is, what commands and/or keystrokes did you type? Too, it looks like that screen image is a tmux session which is confusing since your problem statement implies you have closed all tmux sessions.

Finally, what is the value of `$TERM` outside of tmux?

**Comment by buinguyenhoangtho** [comment]
Oh im sorry about confused. You see im facing the dots line above the status bar.. It only occur when i'm trying close session by using `crl+w` ( my keybind) 
![image](https://user-images.githubusercontent.com/76900905/121794148-48fd7a00-cc30-11eb-8f8f-b66b5c264ca4.png)
. 
My `$TERM`:screen-256color

**Comment by krader1961** [comment]
> My $TERM:screen-256color

If that is the value of `$TERM` outside of a tmux session that will cause problems. Unless, of course, you have nested tmux sessions.

The dots you are seeing are because you have connected to a tmux session from multiple clients with different terminal sizes.

**Comment by buinguyenhoangtho** [comment]
So there is no bug overall right? . So one more question. Is it possible to stop the session created when i start new terminal?

**Comment by nicm** [comment]
Does this still happen with tmux 3.2a or master?

**Comment by buinguyenhoangtho** [comment]
@nicm wait why my tmux is in 3.0? im installed it from apt-get

**Comment by nicm** [comment]
Only you can answer that.
