### ISSUE TITLE
Zenify the redraws

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2774]
I recently started using a wonderful tmux statusline https://github.com/gpakosz/.tmux. While launching tmux, the status line rapidly changes what it displays, which leads to a distracting UI. I filed a bug on their project: https://github.com/gpakosz/.tmux/issues/496. The author of the plugin replied that it is a tmux limitation. Is that true, and can it be solved? Perhaps a command that freezes the status line till a certain event.

Corollary: By extension if there is a way to freeze redrawing entire tmux window till a certain event happens, it can make the interface of tmux-resurrect also more zen. For instance, I would want to know when all the tmux-resurrect panes are drawn behind the scene and programs in it already started, and then do only one screen redraw so all changes appear at once.

> Given I am talking about events. Coming from Vim world, IMO something like Vim auto-commands can make automating tmux very easy and powerful.

**Comment by gpakosz** [comment]
@nicm It basically boils down to launching `#(/tmp/foo.sh)` command from the status line. Which depending on the time it takes to proceed displays the "infamous" not ready message.

I think I tried to print a new line at the beginning of `/tmp/foo.sh` in a attempt to work around the behavior but I don't think it's enough.

Any idea?

**Comment by nicm** [comment]
I don't know what you mean by "zen" or "zenify".

You will only see the message once, after the command has printed output tmux will reuse that until it changes (unless you are running a different command each time which I do not recommend).

**Comment by reportaman** [comment]
Ok, here we go: https://www.urbandictionary.com/define.php?term=zenify

Zen is synonymous with something that promotes focus, is not distracting, and every activity is reasoned & minimal.

**Comment by nicm** [comment]
I know what zen is, I don't know what it means in the context of this issue.

**Comment by reportaman** [comment]
@nicm Here's a video that shows the status line flickering, showing intermediate states before settling down to a stable value. Depending on the fields one adds, there can be more flickers. For instance if I enable showing weather in the status line. What this ticket asks for is a way for script/plugin authors to be able to suspend redraws till they have collected all stable information to be displayed, so user doesn't see intermediate/transitional/temporary/unstable states.


https://user-images.githubusercontent.com/71736629/125506383-53e5af5b-ab36-41de-a0a3-367133526987.mp4

**Comment by nicm** [comment]
tmux can't know what the command will output until it does so, it has to print something, so I don't see what we can do here.

You could try running your command in `client-attached`, putting the result in a user option and using that from the status line (you may need to do `refresh -S` but I'd try without first). But even if you do that you will just get empty space in the status line until the command is finished.

**Comment by nicm** [comment]
I don't see anything in your video, maybe it is too fast for me to see?

**Comment by nicm** [comment]
I'm not sure an "I'm ready" command is practical. What should tmux do in the meantime? Show an empty status line?

**Comment by reportaman** [comment]
Probably because its covered by the media buttons. The following recording has some padding at the bottom.
 
https://user-images.githubusercontent.com/71736629/125507093-1a13d382-2e29-42e5-aa05-5bb09deb3716.mp4

**Comment by reportaman** [comment]
@nicm Yeah thats not what I was thinking. Vim/Neovim gives plugin writers control over when to redraw screen. https://neovim.io/doc/user/various.html.

That allows plugin writers to do a bunch of work together and redraw only once the contents are ready to be displayed. So user sees only minimal transitions/screen redraws... Not sure how the interface would look like for tmux...

**Comment by nicm** [comment]
I don't really know what you are suggesting from this documentation, tmux already provides similar ways to trigger a redraw.

AFAIK @gpakosz's status line is a bunch of shell scripts which are invoked by tmux when it needs to redraw, there is no process controlling them all.

If he wanted to do all the work separately and update them atomically he could by putting the content in user options and setting them all at once in one command sequence.

But that won't help your problem because tmux still has to show *something* before the options are ready.

**Comment by nicm** [comment]
@gpakosz what would you like to see here?

**Comment by reportaman** [comment]
Ok what if we limit to just controlling the time of redraw the statusline? If you mean tmux still has to show something in statusline, then it can show old value/blank value till a equivalent of ``:redraws[tatus][!]`` for tmux is issued. 

From your comment it seems like @gpakosz can do something already to avoid showing intermediate values...

**Comment by nicm** [comment]
tmux does show the old value if there is one, but there is no old value until the command finishes. The problem is when you run the command for the first time where it has to show some placeholder. 

I am open to allowing the placeholder to be specified (I have suggested this before) but it may not solve your problem because the command will still flicker when it jumps from placeholder to real value unless the content has a fixed size.

What I am suggesting is that instead of running all the guff from the status line with `#()`, running it in the background and writing it into user options. This means that when a client is attached, the correct values will already be available to tmux, and all of the user options can be set atomically in one command sequence. For example, you might write a script something like this:
~~~~
while :; do
        foo1=$(date +%s)
        foo2=$RANDOM
        tmux set -g @foo1 "$foo1" \; set -g @foo2 "$foo2"
        sleep 1
done
~~~
And then do this from .tmux.conf:
~~~~
run -b 'exec sh /tmp/foo.sh'
set -g status-format[0] '#{@foo1} #{@foo2}'
~~~~
So `/tmp/foo.sh` runs all the time and the content is always available (except when the server is started for the first time) and not bound to tmux redrawing the status line.

Of course the script would need to be sophisticated enough to understand different sessions and set the right content on each session, I am not sure exactly how that would work, it will depend on exactly what is being shown in the status line.

**Comment by toddyamakawa** [comment]
What about some kind of weird format like:

```
#(sh /path/to/script.sh, "loading...")
```

Then the user can specify what gets shown (in this example it's `loading...`) until the script finishes running?

**Comment by nicm** [comment]
How is "loading..." going to flicker any less than what tmux shows now?

**Comment by toddyamakawa** [comment]
"loading..." would flicker, but the user could just give an empty string, so it wouldn't flicker. I just saw your other post though and that looks like a good solution

**Comment by nicm** [comment]
If you are showing an empty string and it jumps to "ABCD" it will still flicker, the only way to avoid it would be to show "XXXX" and that only works if you know exactly how long the output will be which is not always the case.

I am open to allowing the placeholder to be specified but I don't think it will fix the problem.

**Comment by gpakosz** [comment]
> @gpakosz what would you like to see here?

@nicm Sorry I was AFK while you were having the conversation.

Let me please detail the concrete case.

The command launched from the status line is `#(cut -c3- ~/.tmux.conf | sh -s _username #{pane_tty} #D)`. The `.tmux.conf` from Oh my tmux! is a polyglot: it's both a valid tmux configuration file and a POSIX shell script. For the sake of simplicity, let's pretend the command is `#(username.sh #{pane_tty} #D)`.

So what does `username.sh` do? It uses the value of `#{pane_tty}` to call `ps -t` and inspect the process chain (in the parent / child process sense). From the output of `ps`, it's capable of returning the username of the "leaf process" running in a specific pane. It's even capable of detecting the leaf process is `ssh` and in that case return the username used to connect to a remote server.

As you can imagine, inspecting the output of `ps` and piping to `awk` to implement the introspection logic takes a bit of time. Which is why tmux displays its `<... not ready>` message and what @reportaman calls "flickering". 

I understand why tmux does so and I'm living with it. I also understands it's doing it only the first time and then reuses the previous output. Which is why I'm also passing `#D` so that `username.sh` doesn't return an outdated value in case the tty is recycled.

In the implementation of `username.sh`, I could use `echo` or `printf '\n'` to output a blank line. Which will mitigate the `<... not ready>` phenomenon but won't eliminate it entirely AFAIK.

Can I use tmux user variables? I can give it a try. It means I will end up with 1 user variable per pane. And likely I need to replace `#(username.sh #{pane_tty} #D)` by `#(set_username.sh #{pane_tty} #D)#{get_username.sh #D)`:
- `#(set_username.sh #{pane_tty} #D)` would e.g. set the `@u#D` user variable, say `@u%1`
- `#(get_username.sh #D)` would do `tmux show -v '@u%1'` (here I'm shelling out as printing `'#{@u#{pane_id}}'` directly from the status line doesn't seem to work or I don't know the proper syntax)
- I also suspect this will introduce some lag and when switching pane the username in the status line will update less fast (here it feels instant)

What's the alternative to using user variables. From time to time, I wonder whether we could have a special syntax instead of `#()` so that e.g. `#{silent:command)` silences the `<... not ready>` message. I'm not sure it's elegant. Maybe we could use `#(s/<.* not ready>//:command)`. In any case, I doubt having a `not-ready-format` option is sound. I would set such an option to the empty string, which would solve the use case I just described but maybe would prevent users from having useful feedback in case other commands are note ready.

All in all, I'm not asking for anything as this won't solve the "problem" for all the versions of tmux I support: 2.4 to 3.2 so far.

Hope that sheds some light on why the issue was opened in the first place!

**Comment by gpakosz** [comment]
BTW

> What I am suggesting is that instead of running all the guff from the status line with `#()` ...

I'm using this strategy for e.g. updating the load average values or the battery bar indicator. But for username and hostname indicators I need them to update right when changing panes. Using `#(username.sh #{pane_tty} #D)` and `#(hostname.sh #{pane_tty} #D)` straight from status line provides that. At the expense of that short lived "flickering" upon launch. This is the compromise I made

**Comment by nicm** [comment]
An alternative to `#()` for per-pane stuff would be to use hooks or control mode to listen for new panes and then set a user option on the pane which you can use from the status line, but this would be substantially more complex. And for anything that could change after pane creation (eg if the user ran ssh), you would need to poll or modify tmux to report it (if it was able to). There would be a short time where there was nothing for tmux to show in either case anyway.

We can add a way to configure the placeholder, or to apply format operators to the output so you can discard it yourself. But are there any other possibilities?

**Comment by nicm** [comment]
> printing '#{@u#{pane_id}}' directly from the status line doesn't seem to work

I thought you could do this with `E:` but it doesn't work so we would need to either make it work or - perhaps better - add a new format operator (maybe `V:` for expand and then lookup the result as a variable).

**Comment by nicm** [comment]
You should be able to set the option on the pane with `set -p` and then just use `#{foo}` since pane option will override window and session (but not global!).

But it is a bit academic because it would still be empty until your set-username script finished.

**Comment by gpakosz** [comment]
> We can add a way to configure the placeholder, or to apply format operators to the output so you can discard it yourself. But are there any other possibilities?

I'm not pushing.
Something I just tried, assuming `/tmp/foo.sh` just sleeps:
```
$ tmux set -g status-right '#(echo && tmux refresh-client && /tmp/foo.sh 1)
```
(I'm using `/tmp/foo.sh 1`, `/tmp/foo.sh 2` etc to force a new job).
With `refresh-client`, tmux replaces the `<... not ready>` placeholder by blank (caused by `echo`) quite fast but the `<... not ready>` string is still visible for a small amount of ms.

> I thought you could do this with `E:` but it doesn't work

Yeah I tried it as well 🙂

**Comment by gpakosz** [comment]
> But it is a bit academic because it would still be empty until your set-username script finished.

Also I think I'm back to square one as `#(set_username.sh #{pane_tty} #D)` will itself exhibit the `<... not ready>` placeholder even when printing an empty line is the first thing the script does 🙃

**Comment by nicm** [comment]
No matter what you do there will be short period between exec, the shell getting its act together and then printing something, and tmux reading that output.

We would need a way to set the placeholder for set_username.sh which if it existed you may as well just use for the main script instead, so yes back to square one.

**Comment by gpakosz** [comment]
Another idea would be to "warm up" the job queue by calling `username.sh` from `tmux.conf` (with `run` or `run -b`) before tmux displays the status line for the first time.

**Comment by nicm** [comment]
That would be possible - but what good would it be? You can't print anything useful until there are some panes, and if you are going to just print a blank line it would be simpler just to make the placeholder configurable.

**Comment by nicm** [comment]
Anyway the format job list is part of the client, so doing it from .tmux.conf would make no difference, it runs a new one for each client.

**Comment by nicm** [comment]
How about this which starts off empty and only changes to `not ready` if the `#()` if the second changes without it producing any output: [x.diff.txt](https://github.com/tmux/tmux/files/6812211/x.diff.txt)

**Comment by gpakosz** [comment]
> Anyway the format job list is part of the client, so doing it from .tmux.conf would make no difference, it runs a new one for each client.

I see.
Well... Again, I'm not pushing. 

> How about this which starts off empty and only changes to `not ready` if the second changes without the `#()` producing any output
This has the merit of not introducing any option or format and can solve it.
So with this patch, `<... not ready>` would only appear if the command didn't produce any output after `status-interval`?

**Comment by nicm** [comment]
It would only appear if the command didn't produce any output if the second had ticked over at the next redraw, which may be `status-interval` or may be earlier if something else triggers it, for example the user creates a window.

I might change it to guarantee at least a second or two instead.

**Comment by nicm** [comment]
This will guarantee at least 1 second and up to 2: [x2.diff.txt](https://github.com/tmux/tmux/files/6812225/x2.diff.txt)

You can see it with eg:
~~~~
set -g status-format[0] '#(sleep 20; echo foo)'

**Comment by nicm** [comment]
I think this would do - if your command can't produce any output in a second then you should rethink having it in `#()`.

**Comment by gpakosz** [comment]
I tried the patch. It works.

What made the "flickering" annoying is that the `cut -c3- ~/.tmux.conf | sh -s ...` is long and as such perceive the `<... not ready>` briefly appearing. Even more so when e.g. written in white over a red background, which is the default colorscheme of Oh my tmux!

![image](https://user-images.githubusercontent.com/553208/125531465-c8978770-a058-43e7-a935-df22a138b821.png)

With the patch, I don't even need to make `username.sh` output a blank line as its first instruction.
Here, it gives the command enough air to do its job 👍

**Comment by nicm** [comment]
OK I will apply this change now.

**Comment by gpakosz** [comment]
> OK I will apply this change now.

The first or the second one?

**Comment by nicm** [comment]
The second one.

The reason I prefer to keep "not ready" rather than removing it entirely is that if a script gets stuck in a loop or otherwise can't be started, it seems not useful at all if its output disappears rather than saying something obvious about it.

**Comment by gpakosz** [comment]
> The reason I prefer to keep "not ready" rather than removing it entirely is that if a script gets stuck in a loop or otherwise can't be started, it seems not useful at all if its output disappears rather than saying something obvious about it.

Totally agree. And this is why I never pushed for removing it after you explained your point of view the very first time.

Thank you for introducing that 1s delay which solves that very peculiar use case.

**Comment by reportaman** [comment]
@nicm @gpakosz The 1 second delay... will it affect users ability to work by 1 second? or is the status asynchronous? If it will make launching tmux by 1 second then please consider adding a switch to disable this feature.

**Comment by nicm** [comment]
No it does not, but try it and see?

**Comment by reportaman** [comment]
@nicm @gpakosz Did either of you release a patch somewhere?

**Comment by reportaman** [comment]
I confirm that this works great now, and no longer see the intermediate status flash with red background. Also to confirm the 1s delay doesn't block the user.
