### ISSUE TITLE
True color not wroking

### ISSUE THREAD

**Issue by vivekvpandya** [tmux/tmux#2783]
### Issue description

Tmux true colors not working, also how to verify that ~/.tmux.conf is actually being used?
relevant seting from my ~/.tmux.conf 

```
   # modern colors
   set -g default-terminal "screen-256color"
   # tell Tmux that outside terminal supports true color
   set -ga terminal-overrides ",xterm-256color*:Tc"
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
   tmux 3.1c
* Platform (`uname -sp`).
  Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
   outside tmux $TERM prints alacritty
   inside tmux $TERM prints screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux_server_log.txt](https://github.com/tmux/tmux/files/6834088/tmux_server_log.txt)
[tmux-client_log.txt](https://github.com/tmux/tmux/files/6834089/tmux-client_log.txt)
[tmux-out_log.txt](https://github.com/tmux/tmux/files/6834090/tmux-out_log.txt)

**Comment by nicm** [comment]
It has not worked, because TERM outside tmux is not `xterm-256color`, it is `alacritty`, so it will not match your `terminal-overrides`.

You can check if it has been enabled by looking at:
~~~~
$ tmux info|grep rgb
 207: setrgbb: (string) \033[48;2;%p1%d;%p2%d;%p3%dm
 208: setrgbf: (string) \033[38;2;%p1%d;%p2%d;%p3%dm
~~~~
If it says `missing`, then it will not work.
