### ISSUE TITLE
Feature request: Highlight text based on regexp

### ISSUE THREAD

**Issue by pbartyik** [tmux/tmux#2797]
### Issue description

It'd be nice to be able to highlight/color text based on regexp match. This comes in hand when connecting to devices which do not color text (network gear, firewalls, etc).

There is already a [patch](https://gist.github.com/pxsta/5f86092eec0d611c2770#file-tmux-highlight-text-patch) for this, could that be merged into master, or a better alternative be created?

### Required information

Please provide the following information:

* tmux version (`tmux -V`). next-3.3
* Platform (`uname -sp`). Linux unknown (arch)

**Comment by nicm** [comment]
This patch is not suitable to be included as it is, so someone would need to finish it off. Most notably:

- I do not like the license. It needs to either use the ISC license the rest of tmux, or simply say "By Your Name. Public domain." It needs to go at the top of the new files.

- I think it should use an array option instead of using an option like this, it would be better not to require a new `OPTIONS_TABLE_HIGHLIGHT`.

- What happens if I want to highlight a string but it is split over multiple buffers?

- Cannot use `stderr` and should not use `strcpy`, also a number of style issues.

**Comment by nicm** [comment]
I have added this to the todo list but I wouldn't hold your breath.

If I was to do this, instead of doing it in input.c where it will very difficult to catch strings split across multiple reads, I would start a timer to run every 0.5 seconds or so when the pane was changed which would run until there was a period with no changes to the pane. Then when it fired, it could sweep any new content in the pane for matches and highlight them.
