### ISSUE TITLE
client-focus-in, and pane-focus-in event issues

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2808]
### Issue description

The new client-focus-in/client-focus-out need two things to work well:

1. A hook_client value to know which tty client the hook was run from. If I have two clients open side by side, and I switch the focus between them then the client_tty values for the corresponding client_focus_in and client_focus_out are the same. Ideally, the client_focus_out will have previous clients tty as hook_client and client_focus_in will have new client's tty as hook_client. At present it is not knowable which client one is exiting, and going into.

2. If I have two clients with same session attached to both of them and switch the focus between them (click on the same pane in both clients), it exposes an events asymmetry. The pane-focus-in event is triggered only when focus goes in one of the two clients. This does not happen if one were to move the focus outside of both clients, and then to the target client. In that case pane-focus-in is triggered regardless of the client.

> Hopefully the events pane-focus-in & pane-focus-out that get triggered while switching from one client to another does not show wrong hook_client. Put another way, hook_client is a good value to have even for them.

### Required information

* tmux version: tmux next-3.3.
* Platform (`uname -sp`): Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color outside, tmux-256color inside.

**Comment by nicm** [comment]
If you have two clients showing the same pane and you switch between them, I don't think pane-focus-in/out should be triggered at all because the same pane is still focused. Are you saying they are being triggered or are not?

I am not sure about adding extra variables to the hooks, I'll take a look at some point.

**Comment by reportaman** [comment]
@nicm Yep pane-focus-in is triggered. Here's the test case:

1. create a new tmux session
2. create a vertical splits so you have two vertical panes
3. attach the same session in another terminal window
4. click mouse on the same pane in two terminal windows, one after another

During 4,  you will observe that pane-focus-in will be triggered when you click on one of the client, but won't be triggered when you click on another. This is what I meant by "asymmetry" in events.

**Comment by nicm** [comment]
I cannot reproduce this, are you using the same terminal program for both clients?

You can see that every time I change between the two terminals, I get corresponding out and insequences: 

https://user-images.githubusercontent.com/304243/128829775-1b67c130-e2a6-4580-bd33-d76823e7a8eb.mov

I am not entirely convinced I should be getting any sequences because the pane has not really changed, but they are definitely matching.

**Comment by reportaman** [comment]
@nicm I tried again, I did get it once but not while recording screen :(

The problem of not enabling pane-focus-in is that hook_pane is empty for client-focus-out and client-focus-in. If its guaranteed to have correct values, then yes you could decide to remove pane-focus-in for such case.

Anyway: in the process I found two other 100% reproducible behaviors that are worth taking a look:

1. whenever I launch neovim in a pane (even with ``nvim --clean``), it causes pane-focus-in to trigger.
2. in the example of two clients with same session and two panes, if I click on a previously unfocussed pane in the other client, it issues pane-focus-in for the focused pane in new client, pane-focus-out, and pane-focus-in for the intended pane.


Though for my case of measuring duration spent in each pane 2. is harmless, not sure if thats what you intended. Just letting you know...

**Comment by nicm** [comment]
You will always get a focus event when the application turns on focus events so it knows whether it starts with focus or not. Why don't you just ignore events if they are the same as the current state for the pane?

**Comment by reportaman** [comment]
@nicm I did ask that question to myself, and what you suggest is not possible without post-processing text logs generated. Lets take one representative example, and it will show where having an option to synchronize events makes developing plugins easier for tmux.

Problem statement: Log duration (in seconds) spent in each pane on the fly while using tmux, without using activity monitoring. Also, show live chart of activity in one pane of tmux (just like we see in a live dashboard). We should take care of the possibility that focus can go outside tmux, or can go in another client of tmux.

Possible solution & difficulty: Print a line with event-type, unix time (using a utility like date), pane number, session name, etc in a activity log file called activity.log. We print only unix times of events, not duration of time spent in every pane in this log, because that is simply not possible given that execution order of the ``run-shell`` scripts called by each event's hook is not guaranteed to be in order. Then in the dashboard process, monitor the file activity.log to see what all new events got printed in activity.log. Here's things get complicated: given execution order of ``run-shell`` scripts was not in order, one will have to look at the timestamps of events to guess what actually happened: for instance when there are two tmux clients and focus moves between them, the order of events that get printed could be: ``pane-focus-in -> pane-focus-out -> client-focus-out -> client-focus-in``, while the natural logical order is something like: ``pane-focus-out -> client-focus-out -> client-focus-in -> pane-focus-in``. Moreover, if the dashboard process reads file after every few seconds, it can come across more lines, and given they are out of order too, it just lends itself to more bugs/difficulty.

In my observation writing plugins/extensions that rely on information from multiple events will get simplified if there is a way of enforcing a strict execution order of hook event commands. Tmux provides wait-for, but that does not apply to hooks as execution of hooks is issued by tmux not the user, so user cannot add ``wait-for -S`` followed by ``wait-for``.

What I am asking for is a global option that when set, will ensure a strict FIFO order of hook scripts. So the execution order of hook scripts will follow their natural order like: ``pane-focus-out -> client-focus-out -> client-focus-in -> pane-focus-in``.

**Comment by nicm** [comment]
You won't get ordering between pane and client events because they are delivered off different queues and anyway in some cases they are dependent on the order the terminal delivers events. I don't think we can change this, even if we made tmux enforce an ordering, different terminals could behave differently.

You won't get ordering between panes either because the events are flagged by pane and then processed in order of client. We could change this to use a single queue of focus events like we do for resize.

Ordering within a pane should be guaranteed, so you should never get an "in" for pane %0 before a corresponding "out" for the same pane. The most recent state for each pane should always be correct, otherwise the events are not useful. If this is not the case, it is a bug.

I don't really understand why you need client events anyway. Why not just log when the state changes for each pane?

**Comment by nicm** [comment]
Let me look into the ordering between panes and maybe between clients, I think it might be not too hard to change. It might not be today though.

**Comment by nicm** [comment]
Can you try this which changes so focus is driven by events rather than by walking the panes at the end of the event loop? This means the out then in should be ordered between previously focused and now focused panes and should be queued with pane before client on out and vice versa on in. [tmux-focusx.diff.txt](https://github.com/tmux/tmux/files/6978844/tmux-focusx.diff.txt)

**Comment by reportaman** [comment]
@nicm Looks great in my testing!

**Comment by reportaman** [comment]
@nicm Except that now hook_client is the same in client-focus-in and client-focus-out

**Comment by nicm** [comment]
hook_client is the same for the pane or client hooks?

**Comment by reportaman** [comment]
@nicm So far I have only printed hook_client for client hooks, so don't know how they print for pane hooks. Here's an example from my testing:

```
{"event":"clientout", "time":"08:46:53 PM", "clienttty":"/dev/ttys002" , "session":"launchpad", "window":"main", "pane":""}
{"event":"clientin", "time":"08:46:57 PM", "clienttty":"/dev/ttys002" , "session":"launchpad", "window":"main", "pane":""}
```

**Comment by nicm** [comment]
It is different for me, and there is no reason `hook_client` should have changed, it is set directly from the client sending the key.

**Comment by reportaman** [comment]
@nicm Yes that's correct, am sorry for the confusion. I still had ``$(tmux display-message -p -F "#{client_tty}")`` in one of the files.

I just tested by changing that to hook_client I capture in hook command, and worked well :)

**Comment by nicm** [comment]
I have applied this now but keep an eye out for anything strange, thanks!

**Comment by reportaman** [comment]
@nicm Thanks! Sure will do! 

Is there a case/if-else tree in your code or some advanced documentation somewhere that is suggestive of the order of events or their precedence?

**Comment by nicm** [comment]
No you would have to look at where the notify_* functions are called.
