### ISSUE TITLE
Feature: Toggle line selection

### ISSUE THREAD

**Issue by neightchan** [tmux/tmux#2840]
### Issue description

Currently, tmux has via `send-keys -X rectangle-toggle` the ability to toggle rectangle selection on and off.  When a selection is already active, toggling rectangle selection on behaves very much like toggling on visual block mode in vim: the rectangular selection is based off of the original selection.

Tmux also has `send-keys -X select-line`.  When starting a brand new selection, this behaves like visual line mode in vim.  However, when a selection is already active, the `select-line` command ignores the previous selection and selects instead the line that the cursor is currently on.

It would be nice to have the ability to toggle "line selection" on and off.

### Required information

```
$ tmux -V
tmux 3.2a
```

**Comment by bew** [comment]
Looks like you want a way to extend the selection, instead of making a new one.

This is also something I'd like to have, I was thinking about having all these additional commands:
- `extend-selection`
- `extend-select-word`
- `extend-select-line`
- (`extend-select-last` ? to continue with the last mode, one of char/word/line)

**Comment by nicm** [comment]
Added to todo list.

**Comment by bew** [comment]
Thanks can, is there a way to subscribe to that todo list?
(in a similar way I can subscribe to when an issue is closed)

**Comment by nicm** [comment]
I don't think so, but you can just see here https://github.com/tmux/tmux/wiki/Contributing#small-things.
