### ISSUE TITLE
Crash with command-alias expansion

### ISSUE THREAD

**Issue by systemmonkey42** [tmux/tmux#2868]
### Issue description

Hi

I am having tmux crash (fault) with the following minimal config on the latest build. 

Using a sample 'tmux.conf'

```
set-option -s command-alias[100] "next-active-pane=if-shell -F '#{P:#{?#{pane_input_off},,1}}' { select-pane -t '{next}'; if-shell -F \"#{pane_input_off}\" { next-active-pane } }"

bind-key -T root         Tab                          'next-active-pane'
```

Launching TMUX, splitting it into three panes, and disabling the centre pane (select-pane -d), the <kbd>Tab</kbd> binding will cycle through each pane, skipping the disabled one.

As of commit 5ed5b11b this configuration will crash tmux, either on startup, or when pressing the hot key.

Commit 0f02fecd (two commits earlier) worked as expected.

I strongly suspect between 0f02fecd and 5ed5b11b, code was introduce the expand the macro all at once, rather than conditionally at run-time.

Due to the recursive nature of the macro, this now fails.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).   master (Commits 5ed5b11b to HEAD)
* Platform (`uname -sp`).   Linux Ubuntu 20.04
* $TERM inside and outside of tmux (`echo $TERM`).  xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).:  tmux-server-log is 900,000 lines.  Let me know if you are unable to reproduce and I will provide one.

**Comment by nicm** [comment]
Thanks. I will look at this next week, it may be better to install aliases
as a special type of command and process them at execution time, although
if that isn't possible we may just need to forbid this.

You should be able to just make the recursive call a string instead of
using {}. though.

**Comment by systemmonkey42** [comment]
Thanks,  replacing `{ next-active-pane }` with ` 'next-active-pane' ` fixed it.

Clearly it would be nicer to give an error than crashing out though.

**Comment by nicm** [comment]
This disables expanding aliases from inside aliases: [x.diff.txt](https://github.com/tmux/tmux/files/7139613/x.diff.txt)

I would like it if it worked (although I am not wild about `command-alias` as it is), but I don't think it is worth it until I know where I'm going with these changes, since it is so easy to use a string instead.

I originally started doing this (making `{}` parsed into tmux commands) so that `list-keys` could print them more nicely. I haven't done that yet...

And I am thinking that the way it works now has too many limitations and it would be better if instead of both tokenizing and validating the command when parsing, it just tokenized it, and left the validation until later. So something in between how it worked before and how it works now.

But I am not really sure how it should look at the end. It seems like it would be nicer if it was simpler and more script-y, but I don't really know how that would work...

**Comment by nicm** [comment]
Hmm it is a bit chicken-and-egg really... if it doesn't lookup the command when it tokenizes it, it doesn't know what flags take arguments and which don't, which means it can't really do much beyond keeping it as a big list of strings which is not great for `list-keys`. Although it would still know what was a command and what wasn't.

Ideally I think we would ditch `command-alias` in favour of some sort of function thing, so you could write:
~~~~
some-command-to-set-a-function next-active-pane {
    if-shell -F '#{P:#{?#{pane_input_off},,1}}' {
        select-pane -t '{next}'
        if-shell -F '#{pane_input_off}' { next-active-pane }
    }
}
~~~~
But the problem with this is - what about trailing arguments? We'd need some equivalent to the shell's `"$@"`. Although I suppose that wouldn't be all that different from replacing `%%`...

Getting rid of `command-alias` will break configs though.

**Comment by systemmonkey42** [comment]
> ... some sort of function thing ...
> Getting rid of command-alias ...
tmux-4a?

BTW, I've been meaning to ask what is the correct method for doing
```
if version <= 3.1 {
    bind-key this way
    set-option              -g status-bg                     "colour235"
    set-option              -g message-fg                 "colour222"
} else {
    bind-key that way
    set-option              -g message-style                 'bg=colour238,fg=colour222'
}

```

Thanks

**Comment by nicm** [comment]
For `set-option` you can use `-q`.

Or use `%if` and `#{version}`.

But if your target version is too old for those, you have to use `if-shell`.

**Comment by nicm** [comment]
I applied this for the moment anyway. Thanks!
