### ISSUE TITLE
pane-exited hook fires in the wrong pane

### ISSUE THREAD

**Issue by maciejjan** [tmux/tmux#2882]
### Issue description

If the `pane-exited` hook is set locally for a pane, it does not run when *this* pane is closed. Instead, it runs when *another* pane is closed and this pane gets focus.

### How to reproduce

Open a new tmux session and execute the following commands in the shell:

```
tmux set-hook -p pane-exited 'display-message foo'
tmux splitw
exit
```

This displays the message, although the pane that was terminated is not the one with the hook. On the other hand, this:

```
tmux set-hook -p pane-exited 'display-message foo'
tmux splitw
tmux selectp -U
exit
```
does not display the message.

### Required information

* tmux version (`tmux -V`): `next-3.3` (latest commit: `7186ab25`)
* Platform (`uname -sp`): `Linux x86_64`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` inside, `st-256color` outside

**Comment by nicm** [comment]
I don't think `pane-exited` is actually useful as a pane option at the moment because by the time the hook is fired the pane (and its hooks) are gone, so it will only ever be fired when the pane with the hook ends up as the active pane after another pane exits. It probably shouldn't fire in this case but then it would never do anything...

You are better off using a window hook and checking `hook_pane` or `pane_id`.

**Comment by nicm** [comment]
I think we need to revisit how hooks are invoked and how the state they will need is stored.

**Comment by maciejjan** [comment]
Thank you for the explanation. I was able to achieve the desired effect (run a command when the current pane is closed) using:
```
set-option -p remain-on-exit on
set-hook -p pane-died "display-message foo ; kill-pane"
```

**Comment by nicm** [comment]
Yes, that's a good idea.
