### ISSUE TITLE
[Feature Request] OSC777 desktop notifications support

### ISSUE THREAD

**Issue by pinkfluid** [tmux/tmux#2915]
The OSC777 escape sequence is used to send desktop notifications from the terminal -- this seems to be gaining popularity among various terminals. It is supported by `foot`, `kitty`, `iTerm2`, `Gnome Terminal` and `Microsoft Terminal` just to name a few.

Currently it seems that tmux just swallows the OSC777 code and nothing happens on the terminal. There exists various hacks around the internet, which use `tmux list-clients` to get the real tty and send the code there but this is far from perfect.

Tmux could implement something similar to `set-clipboard`, where tmux could emulate a desktop notification via `display-message` or it could forward the OSC777 code to the real terminal (or both).

I might volunteer to do the work if there's enough interest in this, however this might take a long time :)

**Comment by nicm** [comment]
Since this is a one off event for a single terminal and not something tmux needs to restore when reattached or copy to other terninals, there seems no need for explicit support, you can just use the passthrough sequence. https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it

**Comment by pinkfluid** [comment]
@nicm It works, thank you! This solves the issue, at least for my use case.

This is the sequence that I used to show a desktop notification:
```
printf "\x1bPtmux;\x1b\x1b]777;notify;%s;%s\a\x1b\\" title body
```

I'll close the ticket.
