### ISSUE TITLE
C-M-* is not recognized after enabling extended-key with iTerm2 + tmux

### ISSUE THREAD

**Issue by laggardkernel** [tmux/tmux#2965]
### Issue description

Setup `modifyOtherKeys` in iTerm2 -> Profile -> Keys

- xterm control sequence can enable modifyOtherKeys mode
- Left Option key: ESC+
  - Apps can change this

tmux

```conf
# tmux.conf
set-option -gs default-terminal "tmux-256color"
set-option -s extended-keys on
```

`tmux -f ./tmux.conf -S ./tmux.socket`, test key pressings:

1. C-l
2. M-l
3. C-M-l

```
# extended-keys off
❯ cat
^[[C^[l^[^L
```

```
# extended-keys on
❯ cat
^[[C^[l^L
```

The way `C-M-l` detected is changed from `^[^L` to `^L`. 

Keybing in my shell doesn't work as expected. But the `S-M-` (not `C-M-`) key bindings do work correctly, still detected as `^[L` by my Zsh shell.

BTW, cause I'm using a mac, I can't test the Meta key bindings in `xterm` cause the <kbd>Option</kbd> is used to type in diacritical marks on macOS. Besides xterm and iTerm2, I don't know any other terminals support `modifyOtherKeys`. So I can't test the problem with other terminals.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.2a
* Platform (`uname -sp`). Darwin i386
* $TERM inside and outside of tmux (`echo $TERM`). tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). 
[tmux-extended-key-problem.tar.gz](https://github.com/tmux/tmux/files/7459431/tmux-extended-key-problem.tar.gz)

**Comment by nicm** [comment]
I do not see you pressing `C-M-l` in this log:
~~~~
$ egrep 'keys are|input_key:' tmux-server-85562.log
1635845376.602126 /dev/ttys016: keys are 29 (\033[>0;95;0c\033P>|iTerm2 3.4.12\033\\)
1635845376.602171 /dev/ttys016: keys are 19 (\033P>|iTerm2 3.4.12\033\\)
1635845377.811991 /dev/ttys016: keys are 1 (c)
1635845377.812264 input_key: c
1635845377.899529 /dev/ttys016: keys are 1 (a)
1635845377.899654 input_key: a
1635845378.152260 /dev/ttys016: keys are 1 (t)
1635845378.152415 input_key: t
1635845378.452427 /dev/ttys016: keys are 1 (\r)
1635845378.452622 input_key: \r
1635845380.310716 /dev/ttys016: keys are 3 (\033OC)
1635845380.310905 input_key: \033[C
1635845381.343501 /dev/ttys016: keys are 2 (\033l)
1635845381.343677 input_key: \033
1635845381.343685 input_key: l
1635845382.434762 /dev/ttys016: keys are 10 (\033[27;5;76~)
1635845382.434939 input_key: \f
1635845384.072107 /dev/ttys016: keys are 1 (\003)
1635845384.072229 input_key: \003
1635845385.446687 /dev/ttys016: keys are 1 (\004)
1635845385.446809 input_key: \004
~~~~
`\033[27;5;76~` is `C-l` (or actually `C-L`, but tmux does not differentiate), on which tmux sends `\f` (`C-l`).

`\033l` is `M-l` on which tmux sends `\033l`.

So it appears iTerm2 is not sending `C-M-l` to tmux. I suggest you try a newer iTerm2 version because I have 3.4.20211023-nightly and it appears to work, although iTerm2 does not encode any of the three keys as extended keys (correctly, since they have acceptable existing forms).

**Comment by laggardkernel** [comment]
> So it appears iTerm2 is not sending C-M-l to tmux. I suggest you try a newer iTerm2 version because I have 3.4.20211023-nightly and it appears to work

I forgot to report the version iTerm2. And you're right, this a bug in iTerm2 3.4.12. After upgrading to a nightly build of iTerm2, 3.5.20211101-nightly, the problem resolved.

Sorry to have bothered you 😅
