### ISSUE TITLE
Hardware cursor issues

### ISSUE THREAD

**Issue by tspivey** [tmux/tmux#2970]
### Issue description

The hardware cursor doesn't move while editing the command line, or while selecting a window with choose-tree.
I use a screen reader, and it uses the hardware cursor position as a base to let me start exploring the screen.

While editing the command line, the hardware cursor stays where it was before I pressed C-b :.
When selecting a window with choose-tree, I can't tell which one I'm selecting, because the cursor isn't on the selected line of the list.

### Required information

* tmux version: tmux next-3.4 (git commit: 77fc7ac3be1320a02cf82c329d0031a472b8cf8f)
* Platform: Linux x86_64
* $TERM outside tmux: xterm
* $TERM inside tmux: tmux-256color

[logs.zip](https://github.com/tmux/tmux/files/7508176/logs.zip)

**Comment by nicm** [comment]
The command prompt does not use the cursor. IIRC there is a reason for this but I've forgotten what it is.

We could put the cursor on the right line in choose modes.

**Comment by tspivey** [comment]
Thanks, I would appreciate that.

**Comment by nicm** [comment]
Please try this [x.diff.txt](https://github.com/tmux/tmux/files/7519202/x.diff.txt) which should 1) place the cursor at the selected line in choose mode and 2) place the cursor at the current editing position in the command prompt. The cursor remains off (invisible) in both cases, unless you have forced it to always be on.

I think the reason I made tmux draw the cursor itself for the command prompt is so that it could control the colour - I use a yellow cursor and on the default yellow background it is invisible. But the cursor is turned off so there is no reason not to position it appropriately anyway.

**Comment by bew** [comment]
Would you consider making it visible? With potentially custom shape?
This could help distinguish normal/insert mode when vi mode is enabled, by using the cursor line shape for insert, and cursor block mode for normal (like in neovim)

**Comment by nicm** [comment]
TBH I think it is OK as it is for the command prompt.

But you can force the cursor always to be visible by doing:
~~~~
set -as terminal-overrides '*:civis@'
~~~~

**Comment by nicm** [comment]
Did you test this change?

**Comment by tspivey** [comment]
Tested and working fine. I've been running this for a few days now, and the cursor tracks in the command line and the window/session list.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!
