### ISSUE TITLE
bash in tmux can't receive ESC key

### ISSUE THREAD

**Issue by walkerxk** [tmux/tmux#2978]
### Issue description

Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* tmux 3.2a
* Platform (`uname -sp`). 
* Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
* outside of $TERM is xterm, insite of $TERM is screen
* Logs from tmux (`tmux kill-server; tmux -vv new`).
* 
[tmux-client-1829746.log](https://github.com/tmux/tmux/files/7560226/tmux-client-1829746.log)
[tmux-out-1829748.log](https://github.com/tmux/tmux/files/7560227/tmux-out-1829748.log)
[tmux-server-1829748.log](https://github.com/tmux/tmux/files/7560228/tmux-server-1829748.log)
When I hit Ctrl+v Enter Ctrl+v ESC Ctrl+v Enter, outside tmux, I got:
![good](https://user-images.githubusercontent.com/3411710/142358621-70be08cd-78c4-4f1f-b8d8-c8a5dbdd61a3.png)
When I hit Ctrl+v Enter Ctrl+v ESC Ctrl+v Enter, inside tmux, I got:
![bad](https://user-images.githubusercontent.com/3411710/142358713-1c2dd5a1-5cea-4d25-b339-d22f5a35a0b4.png)
It seems like tmux can't receive ESC key, so just print ^V

**Comment by nicm** [comment]
No sign of Escape in this log (`\026` is C-v):
~~~~
1637206664.673539 /dev/pts/7: keys are 18 (\033P>|mintty 3.5.2\033\\)
1637206666.362008 /dev/pts/7: keys are 1 (\026)
1637206667.221887 /dev/pts/7: keys are 1 (\r)
1637206668.258680 /dev/pts/7: keys are 1 (\026)
1637206669.884198 /dev/pts/7: keys are 1 (\026)
1637206670.328261 /dev/pts/7: keys are 1 (\r)
1637206681.783274 /dev/pts/7: keys are 1 (\004)
~~~~
So seems like your terminal is not sending it to tmux.

tmux enables mintty's alternative escape feature, which should make it send `\033O[` instead of `\033` for Escape, but I don't see that being sent.

**Comment by walkerxk** [comment]
Sorry, it is the problem of docker, thanks for you help.
