### ISSUE TITLE
Feature Request: Missing OSC query sequences

### ISSUE THREAD

**Issue by rvaiya** [tmux/tmux#3004]
The OSC 4 query sequences appear to be missing. Additionally it would be nice if tmux could query the underlying terminal for the default colors in the event that they are not set. 

Finally the response format should be changed to `rgb:/ffff/ffff/ffff` rather than `rgb:ff/ff/ff`.

I think the latter might technically be supported by the spec but every terminal I have seen in practice (libvte terms, iterm, alacritty, kitty, xterm) use four character hex sequences with the first two bytes representing the rgb color component and the last two either being zeroed out or repeated (more common).

**Comment by nicm** [comment]
Two digits is absolutely supported, look at XParseColor(3). But I have changed it to four.

I don't have any plans to make tmux query the terminal for colours because I think it doesn't really make much sense in the presence of multiple clients.

I've added OSC 4 query, it will be there next time GitHub syncs up.

Thanks!

**Comment by rvaiya** [comment]
Fair enough. Thanks for the quick patch and the boon that is tmux in general :).
