### ISSUE TITLE
Add option to separate command-prompt line from status-line.

### ISSUE THREAD

**Issue by sanscore** [tmux/tmux#301]
I have two issues with the present way the `command-prompt` is displayed. 

The first being, at times, I am trying to write a command such as `swap-window` that I need to know both the source and destination prior to typing `prefix :`. So, I'll start to type a command, only to realize I don't know which one, or both, windows that I want to swap.

The second is that `status-position top` would be a nice setting for me because sometimes the status-line can be a distraction. However. I don't expect/want the command-prompt to be at the top of the window. So, I am just SOL.

An alternative solution would be to have two status lines. I'm not advocating for this solution, but it could have interesting possibilities; have two, stacked status-lines, or one on-top and one on-bottom.

**Comment by nicm** [comment]
I don't have strong feelings about this. It should not be hard to make the command prompt appear one line above the status line (it will basically be the same as when the status line is off).

**Comment by nicm** [comment]
I have added a note to TODO file.

**Comment by j0hnsmith** [comment]
I'd also like this. As a workaround I've tried status line at the top of the screen but prefer it at the bottom, being able to have a blank line between my prompt and status line would be perfect.

I know a note has been added to `TODO` but since this feature has not yet been added why has this issue been closed? It would make sense (unless I'm missing something) to keep it open so people can subscribe to follow progress/find out when this functionality has been added.

**Comment by sanscore** [comment]
@j0hnsmith: This is still something that I am interested in, but I figure that this item is closed because of this comment https://github.com/tmux/tmux/issues/301#issuecomment-183301223. I take it that @nicm doesn't feel the request is something that is necessary for Tmux; Rather, there are other requests/issues that have higher priority. But, he's willing to accept a PR that supplies the functionality.

I'm not a strong C programmer so I haven't spent much time tracking down how one would implement the feature. 🙁
