### ISSUE TITLE
systemd integration (for systemd-oomd primarily)

### ISSUE THREAD

**Issue by benzea** [tmux/tmux#3024]
Some distributions (e.g. Fedora) are starting to use systemd-oomd by default. Doing so means that the userspace OOM killer will always kill an entire cgroup rather than just a single process. This has many advantages, e.g.:
 * fork bombs can be easily detected and killed
 * resources can be distributed more fairly
 * better cleanup, as all processes belonging to the cgroup can be killed together

To better integrate this, tmux should launch each pseudo terminal in a separate cgroup. This can easily be done by moving the new PID into a separate transient systemd scope (requires a single DBus call to move the PID and ideally waiting for this to complete/error before `exec`'ing the child).

For reference, this is what VTE (the GNOME terminal library) does: https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/systemd.cc

**Comment by nicm** [comment]
I revisited this fairly recently, see this comment (including the diff) and the subsequent comments in the issue: https://github.com/tmux/tmux/issues/428#issuecomment-623491932

The consensus was that this was now pointless since either affected systems have by now worked around these problems, or it was impossible for tmux to sanely configure it anyway.

I don't use systemd at the moment, so I don't intend to do any further work on this myself for now, but if this kind of change (see the diff in the linked comment) now makes sense and you would like to open a PR then I'll take a look at it.

**Comment by benzea** [comment]
Ah, hmm, maybe the whole systemd integration needs some more thought overall.

In general, the issue here is a different one though (and, it is actually solvable entirely without dbus). Here we want to separate each of the pty's into a separate cgroup. The purpose is so that when the OOM killer (i.e. systemd-oomd) kills an entire cgroup, only the processes for one pty are killed rather than also including tmux itself and all other pseudo terminals.

**Comment by nicm** [comment]
OK we can do whatever you like in a new `compat/forkpty-linux.c` or `compat/forkpty-systemd.c`, so long as new dependencies on nonstandard libraries (ie, not libc) are optional.

**Comment by benzea** [comment]
Cool, should be easy enough to do something within those constraints!

**Comment by nicm** [comment]
I am closing this but please feel free to open another issue or a PR if you have anything further. Thanks!
