### ISSUE TITLE
Feature: pane-colours, and window-style as session scope option

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3062]
### Issue description

It would be nice to have an ability to have ``pane-colours`` palette to be set as a session scope option. Currently that does not seem to be the case. As of now, setting ``pane-colours`` palette works well for pane, window, or global scopes.

> Not sure if -s works, for server scoped pane-colours. Didn't test it yet.

Same with background and foreground:

``tmux set window-style "bg=<background>, fg=<foreground>`` should ideally set the window-style for all current and future windows of the session.

**Comment by reportaman** [comment]
Same with background and foreground:

``tmux set window-style "bg=<background>, fg=<foreground>`` should ideally set the window-style for all current and future windows of the session.

**Comment by nicm** [comment]
There are no such thing as session options. I have looked before at making option inheritence go global -> session -> window -> pane (that is, have one global list), but it is difficult because there are cases where there is either no or multiple sessions, so it is hard to choose which option to pick.

**Comment by reportaman** [comment]
Ok thanks. I can achieve the effect of inheriting pane colors from first window of the session by using after-new-window hook. The hook will copy colors from the first window of the session to the new window.
