### ISSUE TITLE
Cannot start tmux on macOS with the m1 chip

### ISSUE THREAD

**Issue by searene** [tmux/tmux#3075]
I cannot start tmux on macOS with the m1 chip. Here is the steps to reproduce it:

```sh
git clone git@github.com:tmux/tmux.git
cd tmux
sh autogen.sh
./configure --disable-utf8proc && make
./tmux
```

Then I got the result:

```sh
[1]    88227 killed     ./tmux
```

I tried to get the log using the method illustrated [here](https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md#how-do-i-get-logs-from-tmux), but failed:

```sh
$ ./tmux -Ltest kill-server

[1]    88259 killed     ./tmux -Ltest kill-server
$ ./tmux -vv -Ltest -f/dev/null new

[1]    88275 killed     ./tmux -vv -Ltest -f/dev/null new
```

My output of `uname -sp`:

```
Darwin arm
```

**Comment by krader1961** [comment]
Enable core dumps (usually via something like `ulimit -c unlimited`). Then reproduce the problem and examine the core file: `lldb -c /cores/*` followed by `bt` to show a process backtrace.

Note that I have no problem building and running tmux built from the current master on macOS and a x86_64 architecture. I don't have a modern Apple Macbook that uses an ARM m1 chipset to test. While it is unlikely the problem you're observing is due to the system architecture (since lots of tmux users run it on Linux ARM) it is definitely a possibility given the quirks of the Apple macOS platform.

**Comment by reportaman** [comment]
I don't get this same error on macOS Apple M1 with the same steps.

**Comment by krader1961** [comment]
> I don't get any error on macOS Apple M1 with the same steps, tmux just works fine.

I don't understand. Enabling core dumps would not, can not, change the behavior of tmux. Or are you saying that you can no longer reproduce the problem regardless of whether core dumps are enabled? In which case perhaps this should be closed.

P.S., It wouldn't surprise me if macOS was sending SIGKILL to your tmux process(es) due to an OOM (out of memory) situation since that is probably the most common reason for a shell to report a process was "killed". And the reason you can't reproduce the problem is because your system no longer has its memory overcommitted.

**Comment by reportaman** [comment]
@krader1961 You are confusing me with the author of the ticket.

**Comment by krader1961** [comment]
@reportaman: Ahh, yes, which reinforces my hypothesis the problem is an OOM condition on the O.P.'s system. Not a problem with tmux.
