### ISSUE TITLE
CSI u sequence passed differently

### ISSUE THREAD

**Issue by felberj** [tmux/tmux#3086]
### Issue description

> ✅ Please read https://github.com/tmux/tmux/blob/master/.github/CONTRIBUTING.md
before opening an issue.

> ✅ If you have upgraded, make sure your issue is not covered in the CHANGES file
for your version: https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

> ✅ Describe the problem and the steps to reproduce. Add a minimal tmux config if
necessary. Screenshots can be helpful, but no more than one or two.

.tmux.conf
```
$ cat .tmux.conf
set-option -g default-command bash
set -g default-terminal "tmux-256color"

set -g extended-keys on
set -sag terminal-features 'xterm*:extkeys'
```

Pressing Ctrl+Shift+N **outside** tmux:

```
$ printf '\033[>4;1m'
$ cat
^[[110;6u
```

Pressing Ctrl+Shift+N **within** tmux:

```
$ tmux
$ printf '\033[>4;1m'
$ cat
^[[14;2u
```

I expected the tmux output to be the same as the outside tmux output

> ❌ Do not report bugs (crashes, incorrect behaviour) without reproducing on a tmux
built from the latest code in Git.

I only reproduced it with the lastest release.

**Update**: I can also reproduce this from master

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.2a
* Platform (`uname -sp`): Linux unknown
  * outside: xterm-256color
  * inside: tmux-256color
* $TERM inside and outside of tmux (`echo $TERM`).
  * outside: xterm-256color
  * inside: tmux-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
[tmux-logs.zip](https://github.com/tmux/tmux/files/8140284/tmux-logs.zip)

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by felberj** [comment]
Yes, I just cloned git and `make`d it.

Same issue when I execute ./tmux

**Comment by nicm** [comment]
What terminal are you using?

**Comment by felberj** [comment]
I am using [SecureShellApp](https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo?hl=en) from ChromeOS.

This is the config I am using (importable via options->restore backup on the left): [backup_preferences.json.txt](https://github.com/tmux/tmux/files/8140455/backup_preferences.json.txt)

Notably I mapped "Control-Shift-N" to `^[[110;6u`

**Comment by nicm** [comment]
xterm does not modify `C-S-n` when modifyOtherKeys=1, but when it is 2 it generates `^[[110;5u` for `C-n` and `^[[78;6u` for `C-S-n`.

Still, the intent of `^[[110;6u` is clear enough (`n` and `C-S-`), so we should probably be treating it the same as `^[[110;5u` (although we again have the problem that tmux doesn't really *know* that on any particular keyboard `S-n` and `N` are the same).

But since we only support modifyOtherKeys=1 at the moment so that would mean mapping it to `C-n` like xterm does which is probably not what you want. I would like to add support for modifyOtherKeys=2 but it is not easy so I have not got to it yet.

I suggest that in the meantime, you configure your terminal to send `^[[78;6u` for `C-S-n` like xterm does, and then bind tmux to send the sequence you want:
~~~~
bind -n C-S-n send Escape '78;6u'
~~~~

**Comment by felberj** [comment]
The problem persists if I map C-S-n to `^[[78;6u`, it works outside of tmux and within tmux it is also translated as 

outside:

```
$ printf '\033[>4;1m'
$ cat
^[[78;6u
```
inside:

```
$ tmux
$ printf '\033[>4;1m'
$ cat
^[[14;2u
```

Binding the key works, but I will need to do this for every key and key combination (meta, shift, control).

```
bind -n C-S-n send Escape '[78;6u'
```

**Comment by nicm** [comment]
Are you trying it with master? Show log please from master when you press `^[[78;6u`.

**Comment by felberj** [comment]
Running

```
$ ./tmux kill-server; ./tmux -vv new
$ printf '\033[>4;1m'
$ cat
^[[14;2u^[[14;2u^[[14;2u^[[14;2u
```


[tmux-server.log](https://github.com/tmux/tmux/files/8140879/tmux-server.log)
[tmux-out-3232594.log](https://github.com/tmux/tmux/files/8140883/tmux-out-3232594.log)
[tmux-client-3232592.log](https://github.com/tmux/tmux/files/8140884/tmux-client-3232592.log)

**Comment by nicm** [comment]
Hah yes I see it too now when I try, I wasn't looking at ther right thing...

I will take a look at fixing this later. However, this will mean fixing it to - like xterm - send `C-n`, because tmux does not support modifyOtherKeys=2, only 1.

So if you want to use keys that are only modified by modifyOtherKeys=2 and not by 1, you will need to use `send-keys`.

**Comment by nicm** [comment]
Actually, since xterm never sends these, we could probably safely map them...

**Comment by nicm** [comment]
Does this fix the keys for you? [x.diff.txt](https://github.com/tmux/tmux/files/8141062/x.diff.txt)

**Comment by felberj** [comment]
Yes, this fixes it

**Comment by nicm** [comment]
AApplied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by vbauerster** [comment]
I found possibly wrong sequence for `ctrl + enter` https://github.com/tmux/tmux/issues/2880#issuecomment-1055426066 with tmux compiled from latest master.

**Comment by nicm** [comment]
This should be fixed as soon as GitHub syncs up.
