### ISSUE TITLE
[bug]^[[>1;95;0c[exited]

### ISSUE THREAD

**Issue by hktalent** [tmux/tmux#3135]
Mac OS
$ tmux -V
tmux 3.2a

```
$ tmux
[exited]
^[[>0;95;0c^[P>|iTerm2 3.4.15^[\%                                                                               
 tools $ 0;95;0c>|iTerm2 3.4.15


$ tmux   
^[[>1;95;0c[exited]
 bin $ 1;95;0c

```

**Comment by krader1961** [comment]
@nicm, I appreciate why you closed this issue since it's missing a lot of information and is borderline incoherent. However, I've been seeing the same thing for a long time on macOS using iTerm2. I hadn't opened an issue because (until recently, see below) it only happens in a single window when I run my `home attach` command to instantiate iTerm2 terminals that then ssh to my home server and do a `tmux attach-session` in each terminal. I've simply been pressing Ctrl-C in the affected Elvish shell to eliminate that unexpected text from the command line.

What follows are some notes I wrote recently after I started debugging this behavior when I wrote a tool in Go to generate screen images known as "ttyshots" for the Elvish shell. That tool uses Tmux to capture the contents of a terminal that includes ANSI X3.64 escape sequences for conversion to HTML. Each invocation of that tool generates output like this:

```
84;0;0c>|tmux next-3.484;0;0c>|tmux next-3.484;0;0c>
```

This seems to be related to INPUT_CSI_DA_TWO in https://github.com/tmux/tmux/blob/master/input.c.

Same thing occurs when running "home attach" but in that case it reports the iTerm2 identification code:

```
0;95;0c>|iTerm2 3.4.20200917
```

Yep, using `script` to capture the raw data when generating a "ttyshot" shows it is due to the "device attributes" CSI:

```
^[[>c^[[>q^[[1;1H^[[>84;0;0c^[P>|tmux next-3.4^[\^[[?25l^[[K
````

Okay, The problematic CSI sequences are being sent by `tty_send_requests` in tty.c. Which is called from server_client_command_done` in server-client.c. Which is called from `server_client_dispatch_command`.

That's as far as I've gotten in tracking down the cause of this behavior. I tried googling for other reports but, unsurprisingly given all the short tokens and punctuation that is ignored by search engines, I couldn't find any reports of this behavior that yielded an answer for how to suppress it.

**Important:** I don't recall seeing this behavior when I used Fish (and before that Zsh) as my interactive shell. However, I switched to Elvish to two years ago and don't recall seeing this behavior until sometime in the past year. So while this might be due to a quirk of how Tmux and Elvish interact it could just as easily be due to upgrading Tmux, iTerm2, or some other change.

**Comment by nicm** [comment]
They appear because the tmux server is exiting before the terminal responds to the queries, there is no way to cancel them once they are requested. This is almost always due to a configuration error.

If you genuinely don't want tmux to request them then remove `XT` and `clear`, but then tmux will not be able to detect your terminal type. Or don't attach it.

**Comment by hktalent** [comment]
@Phil-Barber
👍 Sure enough, it's OK
@tmux kill-server

**Comment by nicm** [comment]
Why do you need to attach tmux if it is not being used interactively?

**Comment by nicm** [comment]
You could do it using send-keys instead then you wouldn't need to attach.

**Comment by krader1961** [comment]
> You could do it using send-keys instead then you wouldn't need to attach.

Sure, but that would add significant overhead to the process of generating a "ttyshot". I neglected to mention that the reason the program relays the tmux output to the enclosing terminal is because I was originally using [Asciinema](https://asciinema.org/). I was simulating a human by sending keystroke with variable delays (similar to how the `expect` command does so) and wanted to see how that looked in real-time as the "ttyshot" was being generated. I then decided that the value of an Asciinema recording was negligible in this context and switched to using `tmux` to capture a static image of the final shell session state (basically what exists now with the "ttyshots" being generated by hand). I didn't, however, remove the relay of the tmux shell session output to the enclosing terminal. Hence the relay of the problematic "device attributes" CSI without dealing with the consequence.

For my purposes simply eliminating the relay of `tmux` output to the enclosing terminal is the simplest, and most efficient, solution. Since I've removed the simulation of pacing human input seeing the interaction in real-time is no longer useful. Thus, I'm no longer relaying the device attributes command issued by tmux to the enclosing terminal and therefore no longer need to deal with any response from the terminal. Problem solved.

Thanks for a great tool, @nicm, and timely feedback on issues.
