### ISSUE TITLE
application mouse mode not enabled in upper pane

### ISSUE THREAD

**Issue by mined** [tmux/tmux#3142]
In installed package versions 3.0a, 3.1, mouse motion reporting (DECSET 1003), if used by an application, was not properly reset by tmux on detach, which would not disturb xterm but would leave mouse motion reporting active e.g. on LXterminal, despite resetting 1000 and 1002 modes. So I tried to upgrade to self-built tmux next-3.4.
Apparently this issue is gone in 3.4 but a more tricky one appeared:

If I start tmux with two initial panes:
tmux -u att -t w1 || (tmux -u new -d -s w1; tmux split -t w1 -v; tmux -u att -t w1)
I cannot enable mouse application mode in the upper pane at all, while in the lower pane it works.

(Side note: Is there a more elegant way to run tmux with a specific session, whether it runs already or not?)

**Comment by nicm** [comment]
Logs?

**Comment by mined** [comment]
How?

**Comment by mined** [comment]
[tmux-logs.zip](https://github.com/tmux/tmux/files/8402272/tmux-logs.zip)

**Comment by nicm** [comment]
Here is what I see in I can see in `tmux-server-1969468.log`:
~~~~
1648892509.921724 /dev/pts/4: mouse input (SGR): \033[<0;68;7M
1648892509.979085 /dev/pts/4: mouse input (SGR): \033[<0;68;7m
1648892511.569324 input_parse_buffer: %0 ground, 48 bytes: \033[?1h\033[?9h\033[?1000h\033[?1002h\033[?1004h\033[?7700h\033[H\033[J
1648892512.627852 /dev/pts/4: mouse input (SGR): \033[<2;38;8M
1648892512.718238 /dev/pts/4: mouse input (SGR): \033[<2;38;8m
~~~~
So you clicked the mouse twice, once before enabling the mouse in the pane and once after.

tmux is receiving both because you have turned the `mouse` option on, so it has already sent SM 1006/1000/1002.

It looks like tmux is correctly ignoring the first pair and then forwarding the second:
~~~
1648892512.630189 writing mouse \033[M"F( to %0
1648892512.718720 writing mouse \033[M#F( to %0
~~~~
This all looks correct to me: `"` is  2 (button 3) and `#` is 3 (release); `F` is 37; '(' is 7.

How are you testing? Do you see no output if you test with `printf` and `cat`?

**Comment by mined** [comment]
> How are you testing?

.tmux.conf has set -g mouse on
Run tmux -u new -d -s w1; tmux split -t w1 -v; tmux -u att -t w1
Cursor is in lower pane. Click once to switch to upper pane
Run my favourite text editor (mined), which enables mouse modes.
Left click to position cursor, right click to open application menu, mouse scroll...: nothing happens.
[tmux-logs.zip](https://github.com/tmux/tmux/files/8419392/tmux-logs.zip)
Same in lower pane: mouse works.

> Do you see no output if you test with printf and cat?

Sorry, I failed so far to narrow down the test case and factor out the editor.
I could however identify that the behaviour slipped in between these commits:
commit 54773d23b5ceb779c524dcac6bf3b848886fb6d6 (mouse fails)
commit 4c07367bfe626fce990f5b5b2d00516ae8249a93 (mouse works)
The intermediate commits fail to build.

**Comment by nicm** [comment]
I cannot see you clicking on the lower pane at all in this log, only the upper pane. Did you click on both?

I can see tmux sending the mouse sequences to pane `%0` which will be the first pane created:
~~~~
1649147175.205632 writing mouse \033[M"/% to %0
1649147175.316500 writing mouse \033[M#/% to %0
1649147180.595620 writing mouse \033[M"/% to %0
1649147180.684178 writing mouse \033[M#/% to %0
~~~~
Does the mouse work in other applications?

I think you will need to figure out whether your application is not receiving them or whether it is discarding them because they are either incorrect or it believes them to be incorrect.

If you run the applcation using `strace -vvtttfostrace.out mined` and then reproduce then look at the `strace.out` log, can you see the mouse sequences being read from the pty? Show me the `strace.out` file if you are unsure.

**Comment by mined** [comment]
I did not click on the lower pane.
The mouse works in other applications and I can well believe that the editor is doing something unusal that might lead to strange interworking but the thing is it works in the lower pane and it used to work in both before that commit.
I'm attaching an strace, there is a write of mouse mode enabling sequences around line 600.
[strace.zip](https://github.com/tmux/tmux/files/8420378/strace.zip)

**Comment by nicm** [comment]
Can you show me a log from running the same editor and clicking the same way in top and bottom panes so we can see what the difference in the mouse sequences tmux sends are?

**Comment by mined** [comment]
Yes:
[strace-lower.zip](https://github.com/tmux/tmux/files/8420432/strace-lower.zip)
And I also discovered something else:
In the lower pane, the editor is getting sent a focus in sequences (CSI I),
while in the upper pane, the editor is getting sent a focus out sequence (CSI O), after which it will indeed ignore mouse sequences because it assumes the window does not have focus.

**Comment by mined** [comment]
... and there are no further focus sequences sent to either pane when switching panes.

**Comment by nicm** [comment]
The previous log you sent does not have `focus-events` turned on, nor does tmux send SM 1004, so these focus events must be coming from the terminal unprompted.

**Comment by nicm** [comment]
Hah wait no.

**Comment by nicm** [comment]
Does this fix it:
~~~~
--- a/input.c
+++ b/input.c
@@ -1798,6 +1798,8 @@ input_csi_dispatch_sm_private(struct input_ctx *ictx)
                        screen_write_mode_set(sctx, MODE_FOCUSON);
                        if (wp == NULL)
                                break;
+                       if (!options_get_number(global_options, "focus-events"))
+                               break;
                        if (wp->flags & PANE_FOCUSED)
                                bufferevent_write(wp->event, "\033[I", 3);
                        else
~~~~

**Comment by nicm** [comment]
Applied now, thanks!
