### ISSUE TITLE
Cannot copy multiline text with differeent tmux sessions with vim 

### ISSUE THREAD

**Issue by sajusat** [tmux/tmux#3154]
### Issue description

Copying multi-line text from vim from different tmux sessions using "+y and "+p does not work. It is only pasting the last two lines to the destination vim.
I am running the tmux in Alacritty terminal.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
  tmux 3.0a
* Platform (`uname -sp`).
   Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
  inside : screen
  outside: xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).
  server exited unexpectedly  <= when there were other tmux sessions running
  no server running on /tmp/tmux-1000/default <= when run on new Alacritty terminal.

**Comment by krader1961** [comment]
This issue might be related to some behavior of tmux but it's impossible to tell from the problem statement. I am especially perplexed by the statement that "it is only pasting the last two lines to the destination vim." In part because yanking and pasting are asymmetrical in the sort of situation implied by the original problem statement.
