### ISSUE TITLE
rethink locks

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#3157]
Clean implementation of lock command does not seem to be available across operating systems. https://stackoverflow.com/questions/4891791/where-is-the-source-for-usr-bin-lock Given tmux popups/hooks have evolved since lock feature was made available, it might be worthwhile to rethink how we do locking.

Even if locking is not made part of tmux code, an API change to popups+hooks could make it simple to code simple and real locking scripts I guess.

Most hooks are after-fact hooks that are run after user runs a tmux command. This includes hooks named ``after-*``, and others like ``client-session-changed``, etc. Adding a few before-fact hooks that are run before certain events like changing client's session is about to change, etc could be used in conjunction with popup to ask for user to enter password? And only if the password is correct would it actually do the following operation like changing the client's session.

**Comment by krader1961** [comment]
It's not clear what you're requesting. The `lock` command dates back to when users interacted with UNIX via terminals like a DEC VT100 or a Televideo 950 connected to the computer via RS232 (or the equivalent via a modem). The user had a single "window" provided by the terminal. Even when `screen` was used to divide that terminal "window" its `lockscreen` command only applied to its controlling pty (as best I recall). Which means it only affected that specific terminal attached to `screen`; not any other terminal. The tty lock mechanism is no longer relevant or useful. It's about as useful as the `write` command to send a message to another user on a different tty.

This seems like an example of the [XY Problem](https://xyproblem.info/).

**Comment by krader1961** [comment]
Are you asking for a default `lock-command` value that works on every system even if it doesn't have a `lock` command? Nonetheless, I don't see how this is useful. What is to stop a user from connecting to the tmux session again? Thus creating a new "client" that isn't locked? Again, this still seems like an XY Problem.

It seems like you're asking for a fundamental rethink of the tmux client security model that isn't based on the old VT100 terminal connected via RS232 model. But without saying so directly.

**Comment by nicm** [comment]
The reason for an external lock program is so that tmux does not need to be setuid/setgid, which is not an option.

Can you be more specific in what you are proposing? What exact API changes would you like to see and how would it be better than using an external lock command?

**Comment by reportaman** [comment]
@nicm Hmm, maybe a different approach, which would not add any new hooks or change popup might be cleaner. Not sure why tmux will have to be setuid/setgid, unless I am missing something. If you are looking for a way to authenticate user, then Unixes seem to have PAM https://stackoverflow.com/a/66853251/15239054, https://en.wikipedia.org/wiki/OpenPAM. I tried the code in https://stackoverflow.com/a/66853251/15239054 on macOS, and it seems to work correctly.

The idea is if the user has locked the server/session/client/pane then to unlock it user will have to pass PAM authentication. Ideally the PAM authentication C code like in https://stackoverflow.com/a/66853251/15239054 would be inside tmux. That way someone cannot go on the command line and kill a PAM process. As an example: if one kills (``kill -KILL <pid_of_bashlock>``) the bashlock script marketed for tmux on macOS here: https://github.com/acornejo/bashlock, it unlocks tmux. Not sure if vlock on linux suffers from same problem... Such unlocking would not be possible I guess with the PAM authentication was part of tmux server. 

Also, currently if tmux lock-server is active, and if one does tmux attach in a new terminal, then they can use the locked session in that client, and perhaps even kill the old client (again bypassing the lock). In new interface, if a lock is enabled, tmux will ask for PAM authentication before user could interact with (server/client/session/window/pane)

1. If server is locked, then without PAM authentication, user should not be able to do any interaction with tmux.
2. If client is locked, then without PAM authentication, user should not be able to unlock that client or see/reattach the session running in it.
3. If session is locked, then without PAM authentication, user should not be able to see or attach that the session in new client
4. If window is locked, then without PAM authentication, user should not be able to see, move that window to another session
5. If pane is locked, then without PAM authentication, user should not be able to see or send keys to that pane.

Not sure if pane locking with PAM can restrict a user to use reptyr (https://github.com/nelhage/reptyr) to move the process of the pane to another tty outside tmux. A hopeful comment/limitation of reptyr is mentioned on its GitHub page:
> Unfortunately, if you background it, you will still have to run "bg" or "fg" in the old terminal. This is likely impossible to fix in a reasonable way without patching your shell.

@krader1961 
> It seems like you're asking for a fundamental rethink of the tmux client security model that isn't based on the old VT100 terminal connected via RS232 model. But without saying so directly.

Sounds like. If we are to comeup with a new spec or goal, I think a one principle should be that a locked element of tmux cannot be seen or interacted with unless it is unlocked. Or a more relaxed principle could be that a locked element is too difficult to see or interact with.

**Comment by nicm** [comment]
PAM is not portable and involves loading a load of shared objects into tmux, this should not be done in the main tmux process.

**Comment by reportaman** [comment]
@nicm Ok, then perhaps tmux can ask for custom lock password, encrypt it using crypt system-call. And then instead of using PAM, tmux would ask user for that lock password, do crypt and string compare?

**Comment by nicm** [comment]
How would that be better than using lock/vlock?

**Comment by reportaman** [comment]
As I mentioned in PAM proposal, an external command like bashlock (marketed vlock equivalent for macOS) can be killed with ``kill -KILL <pid_of_basklock>`` & that immediately unlocks tmux. If locking and authentication is handled by tmux server process, it won't be that easy.

Also, when I run the PAM authentication program in https://stackoverflow.com/a/66853251/15239054, it shows RES usage as 8880 bytes. IMO 8kb ram usage if not much for modern laptops/ desktops. Moreover, the whole idea of shared object is that it's shared between processes. One could use dlopen to open shared object instead of loading it at launch time. dlclose also closes it if no other process is using it...

**Comment by nicm** [comment]
If someone has access to your user (or is root) and can kill your processes then they already have full access to everything, there is no way to prevent this. Locking is intended to prevent people who do not already have access to your user getting access.

It isn't about memory use, it is about security. tmux is a relatively complex process and has the ability to create shells or run any process, not to mention any that are already running inside tmux. Authentication should not happen in the same address space.

**Comment by reportaman** [comment]
As @krader1961 opined we are talking 2 different useable models. 

No that's not true that if a user can kill a process they can do anything. If that were true statement then users wouldn't need to sudo to change contents of certain directories.

The kind of lock usage you are thinking might be well and good for that usecase. What I am thinking is if I share a VNC session with a kind enough colleague, or if I am sharing the same tmux server with them (on modern desktop environment which allows multiple terminal windows and panes), I should be able to have some tmux session which can be locked to a password I don't share with them (this could be root password, or a dummy account named tmux I create just for this purpose).

In such a case a concern that tmux is a program that can create shell is not applicable anyway... 

Another possibility is that tmux adds some special hooks that (if set) are run before certain events like tmux attach, tmux new-session. The hook can call a PAM C program . If the program fails (I.e it returns non-zero exit status) then tmux won't proceed to fulfill tmux attach/ tmux new-session. This would be kinda tmux detach lock. One can only open tmux if their PAM authentication passes.

Either way it would be a feature that is for a different usecase as current "lock" feature. So both should perhaps coexist. In which case again native PAM support should not be a concern...

**Comment by nicm** [comment]
You are confusing different things. sudo allows one user to run a command as another user, or as root. If you run a command as your user and then you log in as the same user again, nothing stops you from killing that command, because is is owned by the same user.

Similarly, if someone has access to your user account, nothing tmux can do will prevent them doing whatever they want - within the limits of what your user is allowed to do. If tmux runs another program to lock a terminal, they can kill it (unless the program is setuid and changes to another user). If tmux locks internally, they can attach gdb or ptrace or whatever they like to poke around in tmux's memory to unlock it or to get whatever they want.

tmux does not have internal user permission boundaries, if you allow another user acess to your tmux, they have full access to your account. The only restriction tmux offers is to make a client read-only, and this is a convenience not a security feature.

If you want to share tmux securely or with people you do not trust, create a dedicated user, run tmux as that user and allow everyone access to that user.

**Comment by reportaman** [comment]
One can compile tmux without debug symbols or strip tmux binary of symbols. If they can load tmux in gdb to change state of tmux without symbols, just to see my tmux panes then they perhaps deserve it. Not every security feature is for an expert to break into... Security is also not about distrust, at times we don't want someone to accidentally break something.

**Comment by nicm** [comment]
OK well we are not going to offer security measures that are ineffective.

**Comment by reportaman** [comment]
It seems like Linux too has improved security modes when dealing with this gdb problem you mention. https://stackoverflow.com/a/2308661 We use macOS, and am pretty sure lldb doesn't allow that.

**Comment by nicm** [comment]
We're not going to rely on system-wide platform-specific configuration to let tmux keep a security promise.

**Comment by krader1961** [comment]
Security is hard. Half-assed security features are worse than none at all because they only give the illusion of security. You also need to keep in mind that tmux runs on many flavors of UNIX so whatever this feature looks like conceptually it needs to be possible to implement it on all those platforms. So using PAM on Linux might be reasonable but you need to consider how to implement it on other platforms which don't have PAM.

@reportaman: If you're giving someone access to your system via VNC then they are running as you on the system. Even if tmux provided a way to lock some, or all, tmux sessions that wouldn't keep the user who has access to your system from simply killing the tmux server process. And, obviously, they can simply start a new terminal process and have access to a shell CLI **running as you**. I'm still very confused how you think a new tmux "session lock" feature does anything particularly useful given the use case you described.

**Comment by reportaman** [comment]
OpenPAM is from BSD Unixes, and it's also apparently preinstalled on macOS. I compiled the program for which I provided link and it compiled without any problem.

I don't think you read the point that I made: PAM can be used to authenticate even as another user. So even if someone has access to the system, assuming that the system is configured with security level to not allow same user from using gdb/etc to change the state of another process, they cannot unlock tmux. It's foolproof & robust. Now if we are to make assumption what happens to users who don't enable such cross-process security: karma, it's how they have set up their system. As I also mentioned, macOS (a SUSv3 Unix) has such security enabled by default (read about SIP). The fact that someone can kill a process they can't have access to is not an issue. Sysadmins can't protect from people going to server room and cutting electrical wires either...

**Comment by krader1961** [comment]
I don't think it is reasonable to require installing, and configuring, OpenPAM to use tmux. But that's not especially important since you still haven't described, AFAICT, a coherent security model that is independent of whether it is implemented using PAM, OpenPAM, or some other mechanism. You probably need to take a step back from a focus on the implementation to better describe the scenarios your proposal protects against.

You also completely missed my point regarding your scenario where you wanted to support sharing your system using VNC. Did I misunderstand? Because if someone is attaching to your system, as yourself, using VNC then they **are you** and the tmux security feature you are proposing is essentially useless. So I'm still very confused what use case(s) you are trying to support.

**Comment by reportaman** [comment]
It need not be OpenPAM. If you read all of my comments I also said we could just do a crypt() and strcmp() based internal authentication where tmux saves the result of crypt(<tmux-password>) in its virtual memory and then compares that to what user asking for authentication enters. That has no additional dependency, and is part of POSIX. OpenPAM/LinuxPAM has the advantage that one can ask to authenticate as any user, not just the current logged in user. You probably didn't read that either. That too allows a 3rd password (other than current user or guest user). One can lock a pane to be opened by only a 4th user using their own credentials (by specifying while locking which username to authenticate against while unlocking). Moreover, VNCs use a different password than Unix user password. So again no, the person logging to your VNC session cannot do whatever would usually require your Unix password.

**Comment by nicm** [comment]
You are suggesting that tmux have its own security boundary inside the Unix user security boundary. I am not going to attempt this. If someone logs in as you then they are you and tmux is not going to pretend otherwise.

tmux cannot solve the problem of you killing the lock program to get access to a locked shell, because you could just kill tmux instead. Unless tmux is setuid/setgid, and I'm sure you can see why that is a very bad idea.

Trying to implement some sort of password per pane would be crazy - once you have attached, there are more than 100 commands available. Are you going to audit them all? There is a huge surface here, it is not happening. And in the end how would it be much better than just running `lock` in the pane?

An implementation that simply requires a password to attach isn't much better. If tmux is already attached then it has to act like `lock`, and guess what, you can still just kill it to get access to your shell. And even if you detach and log out first, what is it really protecting? Even with halfarsed nonportable sysctls (and no security flaws in all the programs you are running!) anyone who has access to your user can still do so much - run your programs, kill them, read your files.

Even making tmux privilege separated has so far proved impossible to do without huge impact to performance or removing or neutering features that people rely on (not that it hasn't been suggested just doing this).

I am not planning to add some mickey mouse password thing that covers half the cases on one or two platforms and gives barely any realistic protection just to be left with a lifetime of dealing with CVEs.

If you want a tmux server that you cannot attach to without a password, run it as another user.
