### ISSUE TITLE
[server exited unexpectedly] with send-keys in copy-mode

### ISSUE THREAD

**Issue by bfrg** [tmux/tmux#3175]
### Issue description

1. Open new tmux server: `tmux -Lfoo -f/dev/null`
2. Go into copy-mode: `C-b [`
3. In the tmux command line run: `:send-keys -F -N #{copy_cursor_y} k`

Result:
```
[server exited unexpectedly]
```

### Required information

* tmux version next-3.4
* Platform Linux
* $TERM inside `tmux-256color` and outside of tmux `alacritty`

**Comment by topcat001** [comment]
I was able to verify this. AFK now but will look into it soon, thanks!

**Comment by topcat001** [comment]
From a very quick look on my phone it seems that `cmd_send_keys_exec` is missing the code to handle `-F` and process the format. However presence of the format bypasses the normal empty argument error check and causes a null argument (in the RB tree entry) in `stryonum` further down.

**Comment by topcat001** [comment]
I looked at this a bit more and the problem is with `args_strtonum`. It is possible to crash tmux from other commands which call this also, like `resize-window`. Example: `:resize-window -x`, i.e., pass an empty argument to it. I am thinking about updating `args_strtonum` with an empty argument check for the passed flag, and also add format support to it: when it does receive a valid string and `-F` is given, it will process any formats in the string before trying to convert to a number. Thoughts welcome!

I'll update soonish.

**Comment by nicm** [comment]
Yep, it looks like it should check if `value->string` is `NULL` also. Allowing it to expand formats would be OK but you'd need to pass in the `F` flag and the item as well. I wonder if an `args_get_and_expand` would be useful as well, not sure.

**Comment by topcat001** [comment]
In the following diff I added the check for missing arguments, and format support for numerical arguments. I didn't refactor formatting args generically yet, but I'll look into that separately later. Please have a look, thanks!
![strtonum diff](https://user-images.githubusercontent.com/22438522/166616111-839406d7-8f9a-48ca-a90c-76a82184bcba.png)

**Comment by nicm** [comment]
Hi @topcat001 - I have applied the validation part of this (to GitHub since I haven't had time to sync up OpenBSD after unlock yet), but I'm not convinced that `args_strtonum` should look for `F` itself, I think it would be better if that was passed in as a separate argument (`int expand` or similar) or there was a separate function (`args_strtonum_and_expand`?) , to let the caller decide if it should expand or not.

Some of the commands that use `args_strtonum` do not accept `F`, and some of them use it differently (such as `split-window`), so I think we will need to add the APIs and then go through the commands individually and decide what they would do (most could probably just expand by default TBH and don't need an extra `F` flag).

**Comment by topcat001** [comment]
Yes forcing `F` in `args_strtonum` is a bit heavy-handed. I will try the argument approach and selectively turn it on for cases where it makes sense.

**Comment by topcat001** [comment]
Hi, I have updated the code with the new function and for now only enabled `send-keys`. Please have a look, thanks!
![strtonum diff-a](https://user-images.githubusercontent.com/22438522/168447887-c7698153-da40-4023-aac3-11e457cd04b5.png)

**Comment by nicm** [comment]
Looks good, but `p` is intentionally not in the man page because it is deprecated in favour of `-s 10%` (they now use `args_percentage`). You could add a comment to this effect in `cmd_join_pane_entry`.

What other commands are you going to add this to?

**Comment by topcat001** [comment]
Thanks! We can drop the man page changes. `-l` is already documented in `cmd_join_pane_entry` so I think it's okay as it is.

In addition to `send-keys`, the following other commands could use the new function:
`capture-pane`: `-S`, `-E`
`split-window`: `-l`
`join-pane`: `-l`
These would then need a `-F` flag to turn formats on.

**Comment by nicm** [comment]
OK should we do them all at once?

**Comment by topcat001** [comment]
Sure, thanks! I'll post an update soon.
