### ISSUE TITLE
greater than and less then operator fails for numbers more than 1 digit.

### ISSUE THREAD

**Issue by cevhyruz** [tmux/tmux#3189]
I don't quite understand how a string comparison works as it is not well documented on manpage.
consider this simple greater-than test:
```bash
function tmux_test() {
  declare -a foobar=(
    "#{>:1,5}"
    "#{>:2,5}"
    "#{>:3,5}"
    "#{>:4,5}"
    "#{>:5,5}"
    "#{>:6,5}"
    "#{>:7,5}"
    "#{>:8,5}"
    "#{>:9,5}"
    "#{>:10,5}"
    "#{>:11,5}"
    "#{>:12,5}"
    "#{>:13,5}"
    "#{>:134,5}"
    "#{>:120,5}"
    "#{>:150,5}"
  )
  for case in "${foobar[@]}"; do
    tmux display -p "${case}"
  done
}
```
It only returns 1s from 6-9 then the rest are all 0s. Is this intentional or am I doing it wrong?

**Comment by krader1961** [comment]
It is intentional and you're doing it wrong. 😄 String comparisons use lexicographical ordering. Essentially what you were taught in elementary school when alphabetizing text. Look at the tables in `man ascii`. The character `1` has a value less than the character `5`. If you want to compare numbers use the `e` modifier. From the tmux man page:

```
Numeric operators may be performed by prefixing two comma-separated alternatives with
an `e' and an operator.
```
