### ISSUE TITLE
window mark is cleared on killing a tab with 'set -g renumber-windows on'

### ISSUE THREAD

**Issue by bsdmp** [tmux/tmux#3214]
### Issue description

$ cat test.conf                 
set -g renumber-windows on

$ tmux -Ltest -f test.conf  new

Create new pane
Mark new pane with Ctrl-b m
Switch to old pane
Destroy it
Mark from previous pane will disappear

With
$ tmux -Ltest -f/dev/null new

Bug is not presented

### Required information

* tmux version (`tmux -V`). tmux openbsd-7.1
* Platform (`uname -sp`). OpenBSD amd64
* $TERM inside and outside of tmux (`echo $TERM`). screen

**Comment by nicm** [comment]
Yes, this is not ideal...

**Comment by lucilanga** [comment]
The same issue is present when trying to move a tab, I suppose it's the same behavior, due to the fact that move-window is actually replacing src-window with dst-window. This is unfortunate trying to cope with renumber-windows off, as you close old tabs newer created ones are created in-place of the old ones, ie. all over the place, so one has to move a window but then marked window is lost nonetheless.

**Comment by nicm** [comment]
This should be fixed in OpenBSD now, will be in GitHub when it syncs later. Thanks!
