### ISSUE TITLE
Numpad partially works

### ISSUE THREAD

**Issue by mrx23dot** [tmux/tmux#3230]
### Issue description
My numpad works great outside tmux.

But after I start tmux I cannot use: `/*-+` (it does nothing when I press them), only numbers and enter work.
So the issue must be with tmux.

Also according to my regional settings have `.` configured as `,` outside tmux, but tmux ignores that and uses dot instead. So I guess tmux doesn't inherit regional settings.

This is out of the box, I didn't change anything.

**versions**
tmux 3.1c
Debian10
echo $TERM inside: **screen**
echo $TERM outside: **xterm**
remote via Putty

**Comment by nicm** [comment]
Logs from 3.3a or master please.

**Comment by nicm** [comment]
Your terminal is sending the wrong sequences for these keys:
~~~~
1655556460.448825 /dev/pts/0: keys are 3 (\033OQ)
1655556460.768743 /dev/pts/0: keys are 3 (\033OR)
1655556461.390785 /dev/pts/0: keys are 3 (\033OS)
1655556461.752723 /dev/pts/0: keys are 3 (\033Ol)
~~~
`\033OQ`, `\033OR, `\033OS, `\033Ol` are `PF2`, `PF3`, `PF4` and `,`.

tmux does not recognise any of these (although we should probably add them).

`/`, `*`, `-` and `+` should be `\033Oo`, `\033Oj`, `\033Om` and `\033Ok`.

See the third table in this section: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys (SS3 is `\033O`).

**Comment by nicm** [comment]
I don't know what you mean when you say it "works".

**Comment by nicm** [comment]
How are you testing it?

**Comment by nicm** [comment]
tmux turns on what is called "application keypad" mode which makes the keypad send escape sequences instead of numbers or symbols, this lets applications tell the difference between `1` on the number row and `1` on the keypad (the latter sends the escape sequence `\033[q`). (I got the link for the list of keys wrong earlier, it is actually here: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-VT220-Style-Function-Keys.) tmux does this so that applications inside tmux can use the same feature and so that users can bind keypad keys in tmux itself (for example `bind KP1 ...`). If the application inside tmux does not request this mode, tmux has to translate the keys - for example map `'033[q` to `1` - so it is important that the terminal and tmux agree on which key each escape sequence means.

Your terminal is sending the wrong sequences for some of these keys which means that tmux does not understand them. This is most likely to be either a bug in putty or a disagreement about the key mappings between Windows and putty. You are probably best to report this to the putty developers.

In the meantime, you can probably work around this by setting them up as user keys, something like:
~~~~
set -s user-keys[0] "\eOQ"
set -s user-keys[1] "\eOR"
set -s user-keys[2] "\eOS"
set -s user-keys[3] "\eOl"
bind -n User0 send '/'
bind -n User1 send '*'
bind -n User2 send '-'
bind -n User3 send '+'
~~~~
Note that `\eOQ` can also be used by the real `F1` function key so it is possible your actual `F1` key will stop working, but best try it and see.

**Comment by nicm** [comment]
Your other option may be to disable tmux's use of this mode, you can try that by doing:
~~~~
set -as terminal-overrides '*:smkx@:rmkx@'
~~~~

**Comment by nicm** [comment]
-s absolutely does exist.

**Comment by nicm** [comment]
tmux set command, not shell...

**Comment by nicm** [comment]
IMO it is nonsense to send `PF2` for a key which has a label on it saying `/` even if the original terminal had `PF2` in that position on its keyboard. 

`\033OQ` is an actual F1 on some terminals but tmux doesn't have it builtin so it will get it from terminfo where it matters and we could probably just list these sequences as variants without doing any harm.

**Comment by nicm** [comment]
I don't think we can do anything useful here. I can make it so that tmux understands `PF2` etc and you can bind it for tmux itself, but tmux doesn't know what the key actually is, so it cannot usefully map `PF2` to `/` - you would still need to configure tmux to do that yourseld. Also `\033Ol` should be `,` but you have it sending `+` - there is no way for tmux to have both.

I don't think we can do anything that would be better than just disabling `smkx` so you get whatever was sent to the terminal originally.

**Comment by nicm** [comment]
tmux command "set" not shell command...
