### ISSUE TITLE
Feature request: vim like jump list to jump between panes across windows/sessions

### ISSUE THREAD

**Issue by poetaman** [tmux/tmux#3258]
### Issue description

Tmux ``last-pane`` or ``select-pane -l`` do not jump to the real last pane if last pane was in another window or session.

While maybe it is possible to define a user option for every pane and record such information, it would still be limited, as it won't be a moving list of panes user visited.

What is being requested? A Vim-style jump list feature, so user can move between panes with ease just like they navigate within Vim with C-o and C-i, or open jump list to choose to jump to (based on visit-age).

This will supercharge navigation in tmux as users will be able to jump back and forth between older visited panes and younger visited panes. IMO with just 2 keybindings that user could specify with such a feature, it could become a preferred way of navigating as it does not require using mouse or remembering session name, window name/ window number.

An additional setting if such a feature is implemented would be the depth of the jump list.

**Comment by nicm** [comment]
It isn't really any use describing features in terms of what vim does because I don't use it.

I don't know if a global last-pane list would be terribly useful, it seems more useful to go back to where the session was like tmux does. If you want to jump to a particular window or pane you can already do it with choose mode.

**Comment by reportaman** [comment]
It is useful because user doesn't need to think name of session, and window number to get to where they want to. For people with amazing memory it might look like its unnecessary, having a global last-pane list would be beneficial for those with not so amazing memory especially while multi-tasking. It would also reduce mental tedium for those with amazing memory, as they just need to press one of two key-bindings to move back and forth.

Ok, will explain any vim feature analogy going forward.

**Comment by mohkale** [comment]
Huh, I actually wanted something like this a while back and wrote [this](https://github.com/mohkale/dotfiles/blob/d72b19e1ac9dbbc919fab9146591a83b57ddeaee/prog/tmux/tmux-cmds/jump-marked) and [rebound ' to it](https://github.com/mohkale/dotfiles/blob/d72b19e1ac9dbbc919fab9146591a83b57ddeaee/prog/tmux/tmuxrc#L74).
