### ISSUE TITLE
tmux can hang if command outputs invalid ANSI escape sequences

### ISSUE THREAD

**Issue by jlebon** [tmux/tmux#3317]
### Issue description

If a command outputs a certain incomplete ANSI escape sequence, tmux hangs for a bit before you can `Ctrl+C` out of it. During the time it hangs, all subsequent output to the console is lost.

Reproducer:

```
$ echo -e 'Mounting \e[0;1;39mdev-mqueue.mount\e…POSIX Message'
```

Notice how it hangs after **mount** and never prints "POSIX Message":

![image](https://user-images.githubusercontent.com/11934099/187457563-9bf463ea-e938-41ac-8184-9b913a7f2219.png)

The example program which does this is systemd: https://github.com/systemd/systemd/issues/24502. We've hit this in Fedora CoreOS when running via QEMU and following the serial console. The original bug report is https://github.com/coreos/fedora-coreos-tracker/issues/1179.

GNOME Terminal at least does not seem susceptible to this.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

tmux next-3.4
(compiled from git master f7b30ed3d410561ac1609b3634cd8aa6855c19bf)

* Platform (`uname -sp`).

Linux x86_64

* $TERM inside and outside of tmux (`echo $TERM`).

xterm-256color

* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-513120.log](https://github.com/tmux/tmux/files/9453537/tmux-client-513120.log)
[tmux-out-513122.log](https://github.com/tmux/tmux/files/9453538/tmux-out-513122.log)
[tmux-server-513122.log](https://github.com/tmux/tmux/files/9453539/tmux-server-513122.log)

**Comment by jlebon** [comment]
Ahh gotcha. So this is not actually a tmux bug. That said, I wonder if tmux should output the partial sequence when it times out on the basis that if it wasn't a complete sequence, it must've been part of the output. Also, would it make sense to lower the timeout value?

> Best bet is not to do this.

Yes, clearly systemd needs to be fixed here.

**Comment by nicm** [comment]
It happens that this unterminated sequence will work in some terminals but not in tmux, but try, for example, `printf '\033]2;…'` and you'll see that many terminals don't even have a timeout.

I think it is better to discard the data - we don't know what it could be, I don't think it is safe to assume it is meant to end up printed. We could ignore the sequence if it contained UTF-8 (which appears to be what other terminals do), but that will only help this case, there would still be lots of other ways to truncate escape sequences that could cause problems.

We increased the timeout a couple of years ago because people wanted to send large amounts of data with OSC to set the clipboard or whatnot, so I don't want to reduce it.

**Comment by jlebon** [comment]
Ack. If you think there's nothing we can do here to improve the user experience, feel free to close this out.

**Comment by nicm** [comment]
I really don't, sorry. There is no way we can helpfullly second guess what applications send. In the meantime if you piped the command through `cat -v` it would work around it.
