### ISSUE TITLE
Synchronized Update doesn't work.

### ISSUE THREAD

**Issue by sstepashka** [tmux/tmux#3325]
### Synchronized Update doesn't work.

I tried to use synchronized update  (https://gitlab.com/gnachman/iterm2/-/wikis/synchronized-updates-spec
) for an application (Emacs, there is no support in master yet, I am working on it locally). Looking onto the code, the feature is implemented and should work, but I can't make it work on my machine. 

My terminal config comes from https://github.com/syl20bnr/spacemacs/wiki/Terminal.

When I use SU outside of tmux (I use Alacritty or iTerm2), the feature work correctly and the screen update as expected. But, when I launch the application inside of  tmux session, then I still see flickering issue (partial screen update).

Here's emacs thread about the issue for the context: https://lists.gnu.org/r/bug-gnu-emacs/2022-08/msg02470.html

I tried to run tmux explicitly enabling the feature:
```
tmux -T sync
```

Overriding the capability inside of config:
```
set -g terminal-overrides ',xterm-24bit:Sync'
```

In order to test it, I use iTerm2 which has 1 second timeout for the sync update and the lag is visible:
```
echo -e '\eP=1s\e\\'
```

When I launch the command w/o tmux, I see the delay, but but I do that inside of tmux session, no delay. It looks like tmux doesn't propagate information about sync update.

```
% uname -sp && tmux -V && echo $TERM
Darwin arm
tmux 3.2a
xterm-24bit
```

Could anybody help me to debug the issue? 

Thank you!

**Comment by nicm** [comment]
tmux does not do anything with sync sequences from applications but instead uses it for its own updates, so this test will not work.

**Comment by sstepashka** [comment]
oh, now I understand it. 

Should tmux pass the escape code to the parent terminal in such case or it would just "eat" that? Should I wrap it into some additional code sequence which tmux would propagate to the parent terminal?

**Comment by sstepashka** [comment]
I tried 
```
printf '\ePtmux;\e\eP=1s\e\e\\\e\\'
```

but it doesn't work... iTerm doesn't receive the expected sequence.

**Comment by nicm** [comment]
No it doesn't. It would need to mediate in some way between different panes doing it at the same time.

**Comment by sstepashka** [comment]
Yeah, this is what I was thinking about.

I assume, if we'd like to have it on tmux, someone has to implement it? :)

**Comment by nicm** [comment]
Yes, I don't think it would be too hard, it might be enough just to stop tmux ending it if an application had started it, but we probably need some timeout.

**Comment by sstepashka** [comment]
I found this timeout configurations:
 - Alacritty 150ms
 - iTerm2 1 second.

**Comment by sstepashka** [comment]
I can try to implement this, if you have any guidance, feel free to share :) 

First, I will send a fix to Emacs, then I will start to work on tmux.

Thank you!

**Comment by nicm** [comment]
Currently tmux will start a sync at the first sequence that moves the cursor, and then stop it (if started) at the end of the server loop when the current read event and any additional writing must have completed.

Probably it would be enough to also start (if not already started) when an application requests it. But in that case we may not want to stop at end of loop because the data the application is syncing may cover multiple reads. So that stop should be skipped. But we don't want to allow an application in one pane to hold up output from others, or from tmux itself.

I think what I'd probably do is try something simple like:

- If application sends a sync start, store the time in the pane if not already set. If the sync has not already been started, start it.

- If an application sends a stop, clear the time in the pane.

- At the end of the loop, if the sync time in a pane is older than N milliseconds (150 seems reasonable), clear it.

- If no panes have a sync time, end the sync (if it was started).
