### ISSUE TITLE
Support for Kitty's keyboard protocol

### ISSUE THREAD

**Issue by hovsater** [tmux/tmux#3335]
### Issue description

[Kitty's keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) is a modern attempt at defining a keyboard protocol, solving many of the [shortcomings](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#bugs-in-fixterms) of [previous](http://www.leonerd.org.uk/hacks/fixterms/) attempts. It's also becoming increasingly popular as a number of tools now support it.

- The [foot terminal](https://codeberg.org/dnkl/foot/issues/319)
- The [WezTerm terminal](https://wezfurlong.org/wezterm/config/lua/config/enable_kitty_keyboard.html)
- The [notcurses library](https://github.com/dankamongmen/notcurses/issues/2131)
- The [crossterm library](https://github.com/crossterm-rs/crossterm/pull/688)
- The [neovim text editor](https://github.com/neovim/neovim/pull/18181)
- The [kakoune text editor](https://github.com/mawww/kakoune/issues/4103)
- The [dte text editor](https://gitlab.com/craigbarnes/dte/-/issues/138)

While tmux have support [extended-keys](https://github.com/tmux/tmux/wiki/Modifier-Keys#extended-keys) it requires the terminal to support [modified-keys](https://invisible-island.net/xterm/modified-keys.html) in order for it to work. Kitty, for instance, no longer [supports it](https://github.com/kovidgoyal/kitty/commit/d6a43a7729d50b6f452ccdb93c746b0e115ebd38).

I think adding support for this protocol would be much appreciated by a lot of people, including me.

**Comment by nicm** [comment]
I don't mind supporting this but I don't intend to work on it, at least not in the near future. If you want to work on it, feel free to let me know if you have questions.

**Comment by hovsater** [comment]
Great. 🙂 I'm not sure how qualified I am, but I'd be willing to give it a shot. Any pointers/tips to get me started?

**Comment by nicm** [comment]
Initially I would probably just try to get tmux to understand the sequences itself rather than supporting it for applications inside tmux.

For this, I would:

1) Add a terminfo flag capability something like `Kitk` and a terminal feature, something like `kitkeys` - look at how the `Eneks` capability and `extkeys` feature are implemented. Since I expect anyone else who implements this will do it the same way as Kitty, I don't think we need separate enable/disable/query capabilities, a single flag capability will be fine. This means the user can use features config to turn this on even if autodetection doesn't work, and can see if it has been detected.

2) The way the spec suggests detecting this is a little silly, but it is not too much work. tmux does not currently request DA, but it does request DA2 and XDA in `tty_send_requests`, you can send `\033[?u` first in the same function (still if `VT100LIKE` is set though) and then check for the response in `tty-key.c` (look at how `tty_keys_device_attributes` processes the DA2 response). If a response is received correctly, you can add the feature you added in step (1) (`tty_add_features(&c->term_features, "kitkeys", ",");`).

3) If the capability is available, emit the enable sequence in `tty.c` when setting up the terminal in `tty_start_tty` and the disable sequence in `tty_stop_tty`. I suggest turning off as much legacy stuff as possible.

4) Process the new key sequences. This is the bulk of the work. I would add a function to `tty-keys.c` like `tty_keys_extended_key` but which instead detects a Kitty key sequence and returns the key. This should only work if the capability is present. If this is going to be a significant amount of code or include large tables then I would probably break it off into `tty-kitty.c` file or something. If the protocol can replace existing key handling entirely, you can probably ignore any sequences it doesn't understand rather than continuing to try them as an extended or standard key sequence. If there are keys that tmux cannot currently represent, if they are simple then add them but if not I would ignore them for now and add support for that separately.

If you then want to support the protocol for applications inside tmux, you will need to:

1) Add support for the new query, enable and disable sequences to `input.c` and a new screen flag to mark it as enabled.

2) Teach `input_key` how to generate the new sequences.

But do this as a separate change.

**Comment by nicm** [comment]
I'll close this but feel free to ask any questions here and I will reopen or to open a PR. Thanks.
