### ISSUE TITLE
Behavior difference between tmux and tmux+mosh in 3.3a

### ISSUE THREAD

**Issue by achernya** [tmux/tmux#3339]
### Issue description

Hello from the mosh maintainers! We (@bbarenblat and myself) are currently preparing on upload of mosh 1.4  to Debian, and noticed that when running the mosh test suite (which uses tmux), tests pass on Debian bullseye (tmux 3.1c) but fail on Debian sid (3.3a).

The specific test in question is `emulation-attributes-bce.test`, [specifically these lines](
https://github.com/mobile-shell/mosh/blob/f3665fb99bffc5929193a204d8540d74749b52c3/src/tests/emulation-attributes.test#L127-L133) that are testing BCE.

This test is comparing the output of running some escape sequences in each of tmux alone ("direct" in mosh parlance) or mosh inside tmux ("baseline" in mosh parlance) and checks to make sure we get the same byte sequence in both cases.

We ran a `git bisect`, and it identified https://github.com/tmux/tmux/commit/ded695504faad8f5d6430731f0bcb9beb0e1430a as the culprit. Looking at the results visually, the screenshots look identical

3.1c tmux only
![3 1c-tmux-mosh](https://user-images.githubusercontent.com/1041517/191637492-15f64c29-dca7-4b5e-8b2d-4e491e450288.PNG)
3.1c tmux + mosh
![3 1c-tmux-only](https://user-images.githubusercontent.com/1041517/191637497-2872eac5-7cf4-4887-ad19-d7dd18a67772.PNG)
3.3a tmux only
![3 3a-tmux-mosh](https://user-images.githubusercontent.com/1041517/191637498-09b04f71-5c9d-42ad-a65a-d05dbbf07235.PNG)
3.3a tmux + mosh
![3 3a-tmux-only](https://user-images.githubusercontent.com/1041517/191637499-397c8b0c-e4ac-47a9-bd28-cb8dcf009c81.PNG)

Looking at the raw CSI sequences,

```
--- baseline.capture    2022-09-21 21:17:47.446046021 -0400
+++ direct.capture      2022-09-21 21:17:48.514041438 -0400
@@ -4,3 +4,3 @@
-ESC[49mdoneESC[42m
-ESC[49mendESC[42m
-ESC[49m@@@ server complete @@@ESC[42m
+ESC[49mdone
+end
+@@@ server complete @@@
```

we see the default green background CSI is elided after end, which ends up cascading. It's interesting that tmux doesn't do this same "optimization" when mosh is involved, presumably because mosh is moving the cursor around and redrawing thing that results in the previous behavior.

Can you help us understand what the commit referenced above is intended to do? I'm not entirely sure how to reconcile our test suite, since ultimately this does produce the same visual result, but that's hard to test compared to our current byte-sequence comparison technique.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): tmux 3.1c and tmux 3.3a
* Platform (`uname -sp`). Linux unknown (Debian bullseye, Debian sid)
* $TERM inside and outside of tmux (`echo $TERM`). screen-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`). N/A

**Comment by nicm** [comment]
tmux may overallocate each line so it tracks the last used cell (`cellused`). This commit changes `capture-pane` only to process each line up to the last used cell rather than processing every allocated cell.

So probably the reason it used to emit SGR 42 was because there are empty cells after the end of each line which were previously output and they needed the green background colour. They would then probably have then been trimmed if you are not using `-J` or `-N`.

I suppose it could be argued tmux should always include a sequence at EOL to reset the background colour because although this file will look correct at the top of the terminal, if you `cat` the `capture-pane` output at the bottom (so they cause a scroll), on a BCE terminal the rest of each of these the lines *should* be filled by the background colour. OTOH, the point of the escape sequences in `capture-pane` is to indicate what colour the text should be, not to exactly emulate the output under every circumstance (what if terminal you `cat` it to doesn't have BCE?). If you want to see exactly what the application sent to tmux, better to use `pipe-pane`.

**Comment by nicm** [comment]
Maybe you could run both baseline and direct tests at the same time using the same tmux rather than running direct live but using a cached baseline? I assume this is why the output is different. That would show mosh is causing no change no matter how tmux decided to represent it with `capture-pane`.

**Comment by achernya** [comment]
The tests are being run with the same tmux, we do not cache the results to our repository. There is a behavior difference when mosh is inside tmux 3.3a compared to when the test is run in tmux directly without mosh.

**Comment by nicm** [comment]
OK so is mosh sending something that causes tmux to consider the lines longer than the visible text? If you add `-J` to `capture-pane` are there spaces at the end of the lines in one case but not the other?

**Comment by achernya** [comment]
I've modified the mosh `e2e-test-server` script to include `-J`

```
-if ! tmux capture-pane -et "$TMUX_PANE"; then
+if ! tmux capture-pane -J -et "$TMUX_PANE"; then
```

it looks like this produces even more diffs
```
--- baseline.capture    2022-09-22 10:32:07.165807364 -0400
+++ direct.capture      2022-09-22 10:32:08.233807206 -0400
@@ -1,24 +1,24 @@
-ESC[48;2;255;0;255mTrue color                                                                      
-ESC[48;5;32m256 color                                                                       
-ESC[42m16 color                                                                        
-ESC[49mdoneESC[42m                                                                            
-ESC[49mendESC[42m                                                                             
-ESC[49m@@@ server complete @@@ESC[42m                                                         
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
-                                                                                
+ESC[48;2;255;0;255mTrue color
+ESC[48;5;32m256 color
+ESC[42m16 color
+ESC[49mdone
+end
+@@@ server complete @@@
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
```

There's 2 types of diffs here. The first is the lack of the CSI 42m before-versus-after (what we're interested in) and the other is the background status (mosh fills the cells with spaces while tmux does not). I think this makes `-J` not suitable for us in general, but the behavior difference continues to be visible.

Here are the 2 capture files if you want to inspect them with hexdump
[baseline.capture.gz](https://github.com/tmux/tmux/files/9626808/baseline.capture.gz)
[direct.capture.gz](https://github.com/tmux/tmux/files/9626809/direct.capture.gz)

**Comment by nicm** [comment]
Yes, so you can see in the `baseline.capture` file that mosh is causing tmux to allocate the entire line - every line has full width of spaces on it. `capture-pane` will first generate each line with all the spaces and then trim them.

The interesting question is why it is generating an SGR 42 at EOL because it seems like the rest of each line should be the default colour...

What is mosh sending to tmux? Is it clearing with EL or just sending a newline? Please run tmux with `-vv` and show me the server log files.

**Comment by nicm** [comment]
Hah, wait, the output is correct. The actual test is clearing the lines:
```
	    printf '\033[48;2;255;0;255m\033[H\033[JTrue color\n'
	    printf '\033[48;5;32m\033[J256 color\n'
	    printf '\033[42m\033[J16 color\n'
	    printf '\033[0mdone\n'
````
So it is what I originally thought, you are losing the SGR 42 because tmux does not proceed beyond the end of the used part of the line, which means it does not see the additional SGR 42 as necessary (it never actually looks at any of the empty cells with green background).

**Comment by nicm** [comment]
I assume the underlying reason is that mosh is emulating BCE by clearing with spaces rather than using ED, which is why tmux doesn't know where the text on each line really ends. Lines cleared with ED or EL are filled with cells in the background colour but do not update the used position.

I think the best bet here is to add a flag to proceed to the end of the line like it did before.

It would be possible to trim trailing escape sequences, but they may be needed by the next line and it would be tricky to figure that out.

**Comment by nicm** [comment]
OK, it does not need a new option because stopping at `cellused` only matters with `-J`, so the old behaviour can continue as the default and we enable the new behaviour with `-J`.

Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/9627599/x.diff.txt)

This adds a `-T` flag but you should not need to use it.

**Comment by achernya** [comment]
With x.diff.txt applied to master, the test fails in `-J` and passes without it!

**Comment by nicm** [comment]
I have applied this to OpenBSD now, it will be in GitHub later and in the next tmux release. Thanks!

**Comment by achernya** [comment]
Thanks so much!
