### ISSUE TITLE
Removal of c0-* function is a major performance problem

### ISSUE THREAD

**Issue by bijancn** [tmux/tmux#338]
For all of us who have to deal with large ouput the two options 
```
setw -g c0-change-trigger 10
setw -g c0-change-interval 250
```
were really helpful. Without them the performance is a pain.
Try something like
```
time seq -f 'foo %g' 1000000
```
on 2.0 (7536d69) and with the current ed598e9. On 2.0 with those settings, tmux remains responsive and  draws way faster.

**Comment by bijancn** [comment]
no comment? not marked as duplicate of something? not so nice :/

**Comment by nicm** [comment]
Well, your issue does not really say anything. Of course, we are aware of the problem.

c0-change-* did not work very well, so I replaced it with something I thought worked better. Unfortunately, this doesn't work very well either, and has some side effects. It's not an easy problem to solve because there is a chain of buffering between the applications (multiple, all potentially writing at different rates) inside tmux and the terminals (also potentially multiple, with different characteristics). Even without ssh - with ssh it is much worse.

I need to revisit this area again, but I don't have time at the moment. I think the idea behind c0-change-* may be worth another go in a slightly different form.

**Comment by LeCoyote** [comment]
What exactly is the "something" that works better and how does one enable/tune it? I am regularly "locked out" of my tmux when I compile stuff and I'd love to hear about how to solve this problem :) Cheers!

**Comment by victor-yarema** [comment]
@ThomasAdam , @nicm wrote "It's not an easy problem to solve". It means that the problem EXISTS. Then why did you just close this issue? Is there another one that represents this problem?

**Comment by ThomasAdam** [comment]
Yes.  This was **two** to **three** years ago, @victor-yarema -- why are you commenting on this now?  Since then, we've used rate-limiting techniques which generally speaking seem to work OK.
