### ISSUE TITLE
tmux interfers with OSC 52 when running in mosh

### ISSUE THREAD

**Issue by ncfavier** [tmux/tmux#3423]
### Issue description

When running tmux inside of mosh inside of alacritty, OSC 52 commands do not set the clipboard.

I am using the command `printf '\e]52;c;aGVsbG8=\a'` to copy a string. It works fine in Alacritty, the terminal emulator I'm using. It works fine in a tmux session. It works fine in a tmux session over ssh. It works fine in a mosh session. It **doesn't work** in a tmux session over mosh.

I followed the instructions in https://github.com/tmux/tmux/wiki/Clipboard. I added `set -g set-clipboard on` to my configuration, as well as `set -as terminal-features ',tmux-256color:clipboard'` and `set -as terminal-features ',xterm-256color:clipboard'` (`TERM` is set to `xterm-256color` in mosh and `tmux-256color` in tmux).

```
tmux info | grep Ms
 192: Ms: (string) \033]52;%p1%s;%p2%s\a
```

I would expect tmux to pass the sequence unmodified to mosh, which then handles it correctly.

### Required information

Please provide the following information:

* tmux version (`tmux -V`). 3.3a
* Platform (`uname -sp`). Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`). `tmux-256color` inside; `xterm-256color` outside
* Logs from tmux (`tmux kill-server; tmux -vv new`). https://gist.githubusercontent.com/ncfavier/b2afdf5e81be1686800984fdac98735d/raw/b58ac3a728f09bb8e9de4ee8d7fedbfebcbd279d/tmux-server-2536236.log

**Comment by krader1961** [comment]
This is not a Tmux problem. It's due to how Mosh works. Google "mosh osc 52". See, for example, https://github.com/mobile-shell/mosh/pull/1054. Mosh causes problems like you're seeing due to its optimization of traffic to drop what it considers irrelevant data in order to maximize interactive responsiveness. Do you see this problem using Mosh when both computers are on the same local network? My intuition is that you won't see the problem in that scenario, but I don't use Mosh so that's just a guess. For all I know Mosh will even drop data even when both systems are on the same LAN; thus causing problems for sequences like OSC 52.

**Comment by ncfavier** [comment]
Thanks, the workaround linked in that PR fixed the issue.
