### ISSUE TITLE
v3.3a: `/` (describe key binding) does not work for user defined key bindings

### ISSUE THREAD

**Issue by clarkwang** [tmux/tmux#3438]
### Issue description

For example, with `bind  |  split-window -h`, pressing `<c-b> / |` displays `Unknown key: |`.

### Required information

* tmux version (`tmux -V`).

   - 3.3a
   - also tried master branch (commit 789cb91f311c1)

**Comment by nicm** [comment]
You didn't give the key a note to show.

**Comment by clarkwang** [comment]
I did not realize it requires a note. Rather than display `Unknow key: ...` can we at least show what the key is binding to?

**Comment by nicm** [comment]
It would be ok if it said something like "No note for key |".

**Comment by nicm** [comment]
I think it should be either notes or commands, not a mixture. You can change the `/` binding to remove `-N` if you want to see commands.

**Comment by clarkwang** [comment]
> You can change the `/` binding to remove `-N` if you want to see commands.

Could you elaborate how? I did not find a *describe-key* command so remove `-N` from what?

**Comment by nicm** [comment]
`tmux lsk '/'` will show you the current binding. It is the one in the `prefix` table, you can bind it without `-N` (so just `-1`):
~~~~
$ tmux lsk '/'
bind-key -T copy-mode-vi / command-prompt -T search -p "(search down)" { send-keys -X search-forward "%%" }
bind-key -T prefix       / command-prompt -k -p key { list-keys -1N "%%" }
$ tmux bind -Tprefix / 'command-prompt -k -p key { list-keys -1 "%%" }'
~~~~
But actually, it won't really work the way I thought because `-1` only works with `-N`. So that needs to be fixed.

**Comment by nicm** [comment]
I fixed `-1` and `-N` now if you build from master in a few hours after GitHub syncs up.

**Comment by clarkwang** [comment]
> I fixed `-1` without `-N` now if you build from master in a few hours after GitHub syncs up.

It works. Thanks.
