### ISSUE TITLE
Nvim lose colors

### ISSUE THREAD

**Issue by simafrus** [tmux/tmux#3480]
In tmux my vvim lose colors, although zsh draw colors well. I try all variations of adding "256 color" to configs but nothing works

nvim 0.8.3
tmux 3.3a
gnome terminal
fedora 37

left: zsh and nvim in tmux
right: both in own gnome-terminal window
![image](https://user-images.githubusercontent.com/107239964/221352112-dcce3aff-408d-4469-991c-951612181ac8.png)

**Comment by nicm** [comment]
Seems like a vim problem to me.

**Comment by comfortablynick** [comment]
I have mine set as `TERM=tmux-256color` and everything works perfectly.

**Comment by simafrus** [comment]
> set

where?

**Comment by comfortablynick** [comment]
Looking at it further, this is what I have. I'm not sure how much is needed but I remember having to do some tweaking for tmux 3.0. It also looks like I had to handle Mac differently than Linux.

```tmux
if-shell -b "[ $(uname -s) = Darwin ]" {
    set  -g  default-terminal   "xterm-256color"
} {
    set  -g  default-terminal   "tmux-256color"
}

set -sa terminal-overrides ",xterm-256color:RGB"                                                          # utf8/color hack
set -sa terminal-overrides ',*:Smulx=\E[4::%p1%dm'                                                        # undercurl support
set -sa terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colours - needs tmux-3.0
```

This issue may help: https://github.com/tmux/tmux/issues/3218

**Comment by krader1961** [comment]
@comfortablynick, The problem with macOS is that some things, like the terminfo files it ships with, are often quite old. My recommendation is to simply install a private copy a modern tmux-256color definition in the *~/.terminfo* directory. I've attached the one I've been using for several years but you should probably look around for an official copy since mine is at least four years old.
[tmux-256color.terminfo.txt](https://github.com/tmux/tmux/files/10936642/tmux-256color.terminfo.txt)
