### ISSUE TITLE
Leak in file_{vprint,print_buffer,error}?

### ISSUE THREAD

**Issue by jwboyer** [tmux/tmux#3521]
### Issue description

I'm working on a covscan report against 3.2a, but the code in file.c is unchanged in master at the moment so it should be relevant still.

It's confused about the `cf` variable being allocated with this sequence:

```
        if ((cf = RB_FIND(client_files, &c->files, &find)) == NULL) {
                cf = file_create_with_client(c, 1, NULL, NULL);
                cf->path = xstrdup("-");

                evbuffer_add_vprintf(cf->buffer, fmt, ap);

                msg.stream = 1;
                msg.fd = STDOUT_FILENO;
                msg.flags = 0;
                proc_send(c->peer, MSG_WRITE_OPEN, -1, &msg, sizeof msg);
        } else {

```

Here's the error from covscan (ignore the line numbers):

```
Error: RESOURCE_LEAK (CWE-772): [#def3]
tmux-3.2a/file.c:233: alloc_fn: Storage is returned from allocation function "file_create_with_client".
tmux-3.2a/file.c:233: var_assign: Assigning: "cf" = storage returned from "file_create_with_client(c, 1, NULL, NULL)".
tmux-3.2a/file.c:246: leaked_storage: Variable "cf" going out of scope leaks the storage it points to.
#  244|   		file_push(cf);
#  245|   	}
#  246|-> }
#  247|   
#  248|   /* Report an error to a file. */
```

So it's noting the allocation via `cf = file_create_with_client(c, 1, NULL, NULL);` but it never sees whatever it needs to see that would free `cf` before the function exits, claiming the local variable going out of scope leaks the allocated memory.  I'm not super familiar with the code yet, but should this section be calling file_push or file_fire_done after proc_send?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
* Platform (`uname -sp`).
* $TERM inside and outside of tmux (`echo $TERM`).
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
On the face of it, it would leak if `c->flags & CLIENT_ATTACHED` is true in `file_create_with_client` and `c->session != NULL && (~c->flags & CLIENT_CONTROL)` is false in `file_can_print`.

But can this happen? There are two possibilities:

- A client with `CLIENT_ATTACHED` but a `NULL` session. These are meant to be equivalent. It is easy to see that `CLIENT_ATTACHED` is never set without a session and it is never cleared. `c->session` is only cleared on detach and it's hard to see a path that would end up in `file_create_with_client` but perhaps it could happen.

-  An attached control client. None of these functions should ever be called for control clients  because they manage the client's streams differently. And if you look at the callers of `file_print` and `file_write` they all have a check for `CLIENT_CONTROL` and use `control_write` instead. So this can't happen.

But it is not very clear. It should probably be changed to use a consistent check for attached clients (`c->session != NULL`) and to explicitly ignore control clients early (maybe with a fatal).

**Comment by nicm** [comment]
I think `file_can_print` should just be the same check as `file_write`:
~~~~
if (c == NULL ||
    (c->flags & CLIENT_ATTACHED) ||
    (c->flags & CLIENT_CONTROL))
    return 0;
~~~~
That would mean that `file_create_with_client` could only be reached with `CLIENT_ATTACHED` set in `file_write` and `file_read` which always end up exiting through `file_fire_done`.

**Comment by jwboyer** [comment]
I tried that, but I don't think covscan is smart enough to know the client/callback model here regardless of what the code does.  It seems to struggle with allocations/frees in anything wrapped in TAILQ for example.  I might just have to annotate this code to silence it.

At some point I'll try running covscan on the top of the tree and see what comes of it.

**Comment by nicm** [comment]
I changed this now, thanks!
