### ISSUE TITLE
Bad CPU type in executable on M1 mac

### ISSUE THREAD

**Issue by rchen19** [tmux/tmux#3526]
### Issue description
When running terminal in native arm64 mode, cannot run any tmux command in x86_64 model with prefix `arch -x86_64`:

```
➜  ~ uname -m
arm64
➜  ~ arch -x86_64 tmux -V
arch: posix_spawnp: tmux: Bad CPU type in executable
```

While if the terminal is started in x86_64 mode (using Rosetta2), tmux can be started normally (in x86_64) model, and can be subsequently attached to from terminal running in native arm64 mode:

```
➜  ~ arch -x86_64 zsh
conda x86_64 is activated
➜  ~ uname -m
x86_64
➜  ~ tmux -V
tmux 3.3a
```

### Required information

Please provide the following information:
Darwin arm
tmux 3.3a
xterm-256color

**Comment by nicm** [comment]
This seems like a problem with your build rather than with tmux itself.

**Comment by krader1961** [comment]
What does the `file` command output? If it doesn't output something like the following then what you're trying to do won't work:

```
~> file /bin/sh
/bin/sh: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/bin/sh (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/sh (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

As far as I know tmux isn't packaged as a universal binary by package managers like Homebrew. And definitely won't be a universal binary if you built tmux from source. Why are you trying to use the `arch` command to run Tmux?

**Comment by rchen19** [comment]
> What does the file command output? If it doesn't output something like the following then what you're trying to do won't work

It does, I use `arch` regularly with GNU Screen. I just would like more conveniently start a Screen or tmux session in x86_64 mode to run some code in x86 environment, instead of starting a terminal in x86 mode first.

> As far as I know tmux isn't packaged as a universal binary by package managers like Homebrew.

This actually answered my question, Thanks. Perhaps I should just go ahead close.

**Comment by krader1961** [comment]
> Although, doesn't the fact that it can be started in both arm64 and x86_64 terminal suggest it is a universal binary?

No. On Apple Silicon (arm64) the OS will automatically run an x86_64 binary via Rosetta CPU emulation. Again, if you use the `file` command it will tell you whether or not it is a universal binary. You're getting the "Bad CPU type in executable" error because your tmux binary is arm64. On my Apple M1 server:

```
~> file /opt/bin/tmux
/opt/bin/tmux: Mach-O 64-bit executable arm64
~> arch -x86_64 /opt/bin/tmux
arch: posix_spawnp: /opt/bin/tmux: Bad CPU type in executable
```

My tmux binary is not a universal executable (and neither is yours). Since it doesn't contain an x86_64 binary the OS can't run it on that emulated CPU architecture. I still don't understand why you're doing this. MacOS will automatically run x86_64 binaries via Rosetta regardless of the CPU architecture of the terminal. And if the binary you're trying to run is universal (containing both arm64 and x86_64) you want the arm64 binary. It makes no sense to force it to run the x86_64 binary. Unless you're a developer creating universal macOS binaries and want to verify the x86_64 variant works.
