### ISSUE TITLE
Idea: provide a way to create a single pane in the corner

### ISSUE THREAD

**Issue by eval-exec** [tmux/tmux#3544]
### Issue description

I just came up with a idea: It would be nice if tmux can create a single pane on the top right corner, just the image illustrate:

<img width="1920" alt="Drawing" src="https://user-images.githubusercontent.com/46400566/234059209-ac4e95f5-5ce0-47e4-af0d-472b188a9404.png">

Then I can view more content in the main window. 

And we can move the little pane to top-left, bottom-left, bottom-right, or anywhere we want. 

Do you think this is a good idea?

**Comment by bfrg** [comment]
I think what you're asking could be accomplished with popup windows. The downside is that a popup window is drawn on top of the pane(s) and so everything behind the popup is not visible. Unfortunately, at the moment a popup window always has focus. Once you open it, you cannot move the focus to the other panes. There is a TODO item in the [wiki](https://github.com/tmux/tmux/wiki/Contributing#medium-things) (see 8th item) to fix this:

> Allow focus to be put back to pane while leaving popup open, and back to popup later. Problem: what if a pane is completely obscured by popup?

I don't know how much work it would be to implement non-rectangular panes. Probably a lot of work. :smile:

**Comment by nicm** [comment]
Drawing content of nonrectangular panes should not be a huge step because this is necessary for popups so it already works.

A bigger difficulty would be that the pane layout is expected to be a grid without overlaps or gaps.

A better approach would be to allow focus to move out of popups into a pane in the background and the current window and active pane changed. Passing input through should not be terribly difficult but there are questions about other things.

This is already on the todo list:

> Allow focus to be put back to pane while leaving popup open, and back to popup later. Problem: what if a pane is completely obscured by popup?

And I don't have any plans to work on it, so I'm going to close this, but if you want to try feel free to ask questions on this issue or open a PR.
