### ISSUE TITLE
Fix screen length calculation of characters for ambiguous width such as Emoji

### ISSUE THREAD

**Issue by TKNGUE** [tmux/tmux#357]
When I use double width words in status-line, tmux's layout is  collapsed due to character which has ambiguous width such as 🌝.

I suggest that we deal with such ambiguous width character as double width character on calculating length on screen, or provide such option to set (looks better to me).
This method is de-facto standard to deal with ambiguous words in many software.

**Comment by nicm** [comment]
Since tmux in Git master now uses wcwidth() this choice is entirely
determined by the libc on your platform.
On 4 Apr 2016 9:32 p.m., "Takeppa" <notifications@github.com> wrote:

When I use double width words in status-line, tmux's layout is collapsed
due to character which has ambiguous width such as 🌝.

I suggest that we deal with such ambiguous width character as double width
character on calculating length on screen(or provide option to set).
This method is de-facto standard to deal with ambiguous words in many
software.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/tmux/tmux/issues/357>
