### ISSUE TITLE
Reorder session indexes

### ISSUE THREAD

**Issue by martin-braun** [tmux/tmux#3597]
### Issue description

I have to work on several sessions, with several windows. It makes no sense to dump every window in a single session, I'm talking about 10 to 15 windows. I love to use `PREFIX+(` and `PREFIX+)` to navigate between sessions quick. It's faster than `PREFIX+s+[0-9]` ... if there wasn't the problem with ordering.

I'm not satisfied with ordering sessions by names and renaming those to match the order I desire. Too much overhead, why not simply adding a command `swap-client` that works like `swap-window` with relative number support, so it becomes ease to map and use?

`swap-client -l` is not sufficient when you have to bounce back and forth between 3 sessions. Just too much overhead.

### Required information

```
Darwin i386, macOS 13.4.1 (22F82)
tmux 3.3a
screen-256color
```

**Comment by nicm** [comment]
Sessions don't have numbers, they only have names. If you want to keep them numbered it would be relatively easy to write scripts to swap two numbers, renumber them, etc.

**Comment by martin-braun** [comment]
@nicm I know right, I even came up with a pretty [sophisticated solution](https://stackoverflow.com/a/76543333/1540350) that allows me to jump to a session given a single letter at best.

It's still longer than it has to be. Re-ordering doesn't need numbers, indexes are enough. Obviously, you can't set numbers then, but you still could swap places.

**Comment by nicm** [comment]
I don't know what you mean "places". Sessions (and panes) don't have a fixed position like windows. If you have sessions A,C and you rename A to D then they are ordered C,D. If you create B they are ordered B,C,D. `switch-client -n` and `-p` will follow this ordering.

Are you confused because it says "index" in tree mode? This is sorting by the session ID which can't change by definition. This is the best we can do to keep the ordering static in tree mode, but it isn't used anywhere else.

**Comment by martin-braun** [comment]
@nicm "Sessions (and panes) don't have a fixed position like windows."

This is the point I am making. Why not give it "places", so it can be ordered like windows? Sessions should be as flexible as windows in that regard. Right now, the experience between sessions and windows is not coherent.

**Comment by nicm** [comment]
These things are not all the same, they are not meant to be coherent. Sessions don't need a position, they only need a unique name. Windows don't have a unique name, and they are all shown together on the screen, so the order matters and they have an index. Panes have an index, but it is based on their position in the window.

tmux has always worked this way and I don't see a need to make a complicated change to its behaviour just because you don't like either of the existing ways to do what you want...

**Comment by martin-braun** [comment]
@nicm 

> Sessions don't need a position

Well, they do need positions *if you want to reorder them*.

> tmux has always worked this way and I don't see a need to make a complicated change to its behaviour just because you don't like either of the existing ways to do what you want...

It's all about evolving software to make it better, it's not? If it comes with the price of performance, I fully agree not to do that, but I doubt the performance cost is significant enough to justify a rejection when [I'm not the only one asking for this](https://www.google.com/search?q=tmux+reorder+%22session%22).

I will still respect your decision, I'm free to fork and offer that behavior on my own.

**Comment by nicm** [comment]
> Well, they do need positions if you want to reorder them.

You can reorder them, by renaming them - they are ordered by name.

The point I am making is that it does not seem worth changing the existing behaviour and adding new commands and all the hassle and extra code that doing this involves, when it should be trivial to implement number ordering by naming your sessions appropriately and writing a couple of scripts.

If you wanted, you could even change the formats in the status line and in tree mode to conceal that the names have a prefix to enforce their ordering.

**Comment by martin-braun** [comment]
@nicm Fair enough.
