### ISSUE TITLE
PATH value is modified by tmux and erased altogether on child pane

### ISSUE THREAD

**Issue by EdmundsEcho** [tmux/tmux#3613]
Great tool.  I use it 99% of the time for several years now. 

### Issue description

If I compare the `PATH` values of my terminal with that within tmux, the sequence of values changes.  Furthermore, the `PATH` is empty in a child window.

This bug in itself might not be an issue if tmux knows to search the parent.  That said, it is an issue because in the child pane, I'm getting "env: node: No such file or directory" errors.

### Required information

Please provide the following information:

* tmux version (`tmux -V`): 3.3a
* Platform (`uname -sp`): Darwin arm
* $TERM inside and outside of tmux (`echo $TERM`): alacritty for both
* Logs from tmux (`tmux kill-server; tmux -vv new`): ?? I'm not sure where to find this

**Comment by krader1961** [comment]
Tmux does not modify the `PATH` env var. It does cache the `PATH` from the first client to create a session. There is something odd about your Tmux and shell configurations. You also provide insufficient information to make any meaningful diagnosis. For example, what command produces the `env: node:...` error? What is the value of the `PATH` var?

I suggest starting with some basic debugging steps. For example, run `tmux kill-server`, double-check there are no Tmux processes still running, then start a single session using just the default Tmux config: `tmux -f /dev/null`. Does the problem still occur?

**Comment by nicm** [comment]
If you create a new pane from the shell (whether it be split or the first pane in a new window or session), tmux will copy `PATH` from the shell where you ran tmux.

If you create the pane from inside tmux or from .tmux.conf or somewhere else where there is no shell, tmux will copy from the session environment.

What happens to `PATH` after that is up to your shell. I expect the reordering is because your shell profiles move elements around.

I'm not sure about the empty `PATH`, perhaps there is no `PATH` set when the tmux server is started so there is nothing to copy into the new pane? Check `tmux showenv -g`.

You can see what tmux is giving the shell in various cases by doing `set -g remain-on-exit on` and then doing, for example, `tmux neww -- env A=B` (the `A=B` makes sure tmux runs `env` directly and doesn't use a shell).

Alternatively, get the server log from tmux and look for where it says "spawn_pane: environment".

**Comment by EdmundsEcho** [comment]
@nicm
> If you create the pane from inside tmux or from .tmux.conf or somewhere else where there is no shell, tmux will copy from the session environment.

This is interesting.  It had me try to run the "split-window" command directly to see if the behavior was different than what was configured in `.tmux.conf`...to no avail.  I still keep getting: 

```fish
env: node: No such file or directory
```

Resetting the server did not unify the $PATH values between the first and second "pane" or "window".  That said, I'm not getting an empty $PATH anymore; that may have been an artifact of troubleshooting without a full server-reset "between tries".

I'll try the `showenv -g` commands next.

**Comment by krader1961** [comment]
If you're getting the error `env: node: No such file or directory` every time you create a new Tmux window then something in your shell startup scripts is trying to run `env node` and `node` cannot be found in `PATH`. You're saying this doesn't happen when starting a new terminal window; i.e., outside of Tmux? Regardless, this is going to be due to something unique to how you have configured Tmux, your shell, and/or how you're starting the first Tmux session.

**Comment by EdmundsEcho** [comment]
@krader1961 good observation.  I looked for something like that in the past but never found anything.  This issue goes away when I completely reset my PATH (see below).

A couple more data points.  Only to level-set, I believe this is a fish-shell/tmux interaction.  I have been using the relatively new `fish_add_path` that checks that the entry is not already in place before appending.  

```fish
fish_add_path $HOME/.krew/bin
fish_add_path ...
```    

### `set -U fish_user_paths` improved performance and fixed the 'node error'
There is this other command that I never used which "globally and permanently" updated the `PATH`.  I suspect that various installations may have used this option.  I avoided ever using it so that I could track the PATH value based on my `config.fish`.  

The punchline: I completely reset my fish-shell path entry using `set -U fish_user_paths`.  I have also chosen to include this reset command at the top of my config (for now anyway).  The effect was dramatic:

1. the delay in firing up a shell has essentially disappeared
2. the size of my path is two-thirds what it was (I have a backup of the original)

What remains uncertain is if resetting the value with each start-up will ignore the apple os system's initial settings to which I believe I was appending without the reset. TBD.

### tmux PATH is inconsistent

When I fire up tmux, tmux appends to the `PATH`; my `nvm` entry shows up twice at the end of PATH.  However, when I fire up a second pane or window, I get a copy of the original shell PATH (single `nvm` entry). This behavior is consistent for all subsequent panes.

**Comment by EdmundsEcho** [comment]
Comparing the `env` and `tmuxenv -g` show two different versions of the `PATH`:

### `env`
```fish
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/opt/homebrew
...
/Users/edmund/.asdf/shims:/Users/edmund/.nvm/versions/node/v20.3.1/bin
```

### `tmuxenv -g`
```fish
PATH=/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin
```

**Comment by krader1961** [comment]
> When I fire up tmux, tmux appends to the PATH.

Again, that is not true. What is probably happening is the shell started by Tmux is modifying `PATH`. In fact, I'll bet that if you simply type `fish` (or `bash`, or whatever shell Tmux runs when you create a new window) you'll see the same `PATH` modification occur.

I used Fish for several years and contributed several hundred changes to the project. I switched to Elvish because I didn't like the gratuitous, backward incompatible, changes that were being made without so much as a transition period. Also, the Fish universal variable mechanism should have been ripped out long ago. It causes far more problems than the meager benefit it provides. 

What is `tmuxenv -g`? Do you mean `tmux showenv -g`? That "Comparing the env and tmuxenv -g show two different versions" is not at all surprising. It simply means the shell being run by Tmux when you create a window is modifying `PATH`.

**Comment by EdmundsEcho** [comment]
@krader1961 
> I used Fish for several years and contributed several hundred changes to the project

wow, thank you for your contributions and help here.  

>> When I fire up tmux, tmux appends to the PATH.

> Again, that is not true.

Ok.  

>   I'll bet that if you simply type fish ... or whatever shell Tmux runs when you create a new window, you'll see the same PATH modification occur.

I think that's at the heart of it.  In my config I do have the following fish-related settings.  

```fish
# shell
set -g default-command /opt/homebrew/bin/fish
set -g default-shell /opt/homebrew/bin/fish
```

### PS
> Fish universal variable mechanism should have been ripped out long ago

I conquer all the way.

**Comment by krader1961** [comment]
There is nothing wrong with changing the default shell in your *~/.tmux.config* file. I happen to have `set -g default-shell /opt/bin/elvish` in mine. The important thing is your Fish configuration. It's causing your problems. Note that running `set -U fish_user_paths` inside your *config.fish* isn't doing what you think. By the time that command is executed the value of that var has already been used to modify `PATH`.

**Comment by EdmundsEcho** [comment]
@krader1961 
> Note that running set -U fish_user_paths inside your config.fish isn't doing what you think

Can you think of a way where I might clear the fish-shell PATH information (the global, hidden values), at the start of each read of the config.fish?

Also, I was thinking it would be great to avoid re-computing the PATH value each time I fire up a new window in tmux.  Perhaps there is a way to identify that scenario to guard the PATH setting? (that way tmux will copy what was in the previous shell?)

**Comment by krader1961** [comment]
It should only be necessary to run `set -U fish_user_paths` once. Assuming, of course, you don't run any command that recreates that var. Which is what you're doing with the `fish_add_path` commands in your *config.fish*. See https://fishshell.com/docs/current/cmds/fish_add_path.html. You should add the `--path` option to those commands to avoid the problems caused by `fish_user_paths`.

If you have more questions about configuring Fish you should ask the community of Fish users. Good luck.

**Comment by EdmundsEcho** [comment]
@krader1961 and @nicm Thank you both for your help.  I have a solid number of ways to dig-into future issues with how tmux and my shell work together to set the PATH value.

**Comment by EdmundsEcho** [comment]
## Update

when firing-up a new window or pane in tmux, I would often get at failed call to node (`env: node: No such file or directory`).  A solution that seems to work is to only set the default shell, and not the initial command.  This may seem clear in hindsight but I can imagine valid reasons to set both.  

`.tmux.conf`
```
# shell
set -g default-shell /opt/homebrew/bin/fish
# set -g default-command /opt/homebrew/bin/fish << disable eliminates the node error
```

What remains is how/why I get different path values between shell, first tmux window, and subsequent tmux windows.  Three different versions.
