### ISSUE TITLE
tmux uses deprecated libevent API (that does not pass event_base explicitly)

### ISSUE THREAD

**Issue by azat** [tmux/tmux#3623]
API that works without base (using global base) had been deprecated long time ago (AFAIR already more then 10 years), so are you interested in using newer API?

I guess I can take a look

**Comment by nicm** [comment]
No, OpenBSD is not going to move from libevent 1.4 so tmux will remain using this API. Besides it has no need for multiple event bases.

**Comment by azat** [comment]
Interesting.

I see that there is [libevent 2.1 in OpenBSD](https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/devel/libevent2/) am I missing something?

Also just to underline, first 1.4 release had been done in 2008 (15 years ago) and the last in 2015 (8 years from now), and it is already not supported anymore. Plus in future we may need to break some backward compatibility to cleanup the code, but we do not want to break any user.

So, do you saying that tmux should be compatible with libevent 1.4 forever?

Maybe it is OK if there will be some old version that 1.4 compatible then?

**Comment by azat** [comment]
Also there a note in README about dependency from libevent 2.x - https://github.com/tmux/tmux/blob/e4c4ceb2865fd9d2006a85c7f48bb7b6dd2f5c49/README#L11

**Comment by nicm** [comment]
libevent 1.4 is in OpenBSD base system, and has been since 2002 (Niels Provos was an OpenBSD developer), as is tmux. libevent 2 is a package.

It was decided some years ago not to move to libevent 2 because it does too much and it is not easy to break out the bits that we need. However, there has recently been some focus on libevent 1.4 and it's clear that by modern standards the API has some flaws, particularly around error handling. So it is possible we might bring in some parts of the libevent 2 API - I personally would like this, although I don't currently intend to do the work myself.

Anyway tmux is staying with the 1.4 API. The portable tmux documentation says 2.x firstly because I don't want to encourage portable users to use 1.4, and secondly because tmux requires 1.4.14 (for my backport or `event_readln`) and some platforms are (or were) still on older versions for their "old libevent" package and it is simpler just to tell people to use 2.

**Comment by nicm** [comment]
If you break the libevent compat in 2, I will probably just write my own compatibility wrapper for tmux portable, although of course I'd prefer if you didn't :-).

**Comment by azat** [comment]
>libevent 1.4 is in OpenBSD base system

I see, I guess this is it - https://github.com/openbsd/src/tree/master/lib/libevent

>So it is possible we might bring in some parts of the libevent 2 API

You mean for OpenBSD project itself?

>If you break the libevent 1 compat in 2, I will probably just write my own compatibility wrapper for tmux portable, although of course I'd prefer if you didn't :-).

Noted :)

**Comment by nicm** [comment]
Yes, sorry, I meant for OpenBSD. There are lots of inconsistencies in error returns and errno use in libevent 1.4 and sometimes it will even just exit or abort rather than returning, which libraries really should not do, so we may fix them. Also we don't like exposing the structs so we may bring in versions of functions like `evbuffer_pullup`. But it has only been discussed as a side note of someone working on something else so I don't know if it will happen. I don't intend to do it myself now in any case.
