### ISSUE TITLE
manpage broken on new debian with new groff

### ISSUE THREAD

**Issue by depesz** [tmux/tmux#3653]
Hi,
I'm using debian trixie, and they changed groff to new one, which changes - character into ‐. This makes it impossible to search in docs for commands with -:

```
=$ man tmux | grep -c move-window
0
```

Apparently the problem is related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1041731

While I'm not putting any blame on tmux, perhaps we could get the manpage modified to escape - to \- ?

**Comment by nicm** [comment]
This is silly, Debian need to fix it.

**Comment by depesz** [comment]
for whoever is interested: filed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043196

**Comment by g-branden-robinson** [comment]
> This is silly, Debian need to fix it.

This isn't a Debian problem--it is withdrawal of a kludge in _groff_ upstream that's coddled ignorant man page composition since about 18 years ago, when Unicode/UTF-8 support in terminal emulators was becoming more widespread.  Debian, or any _groff_ user with root on the system, can restore the kludge by altering the _man.local_ file as described in _groff_'s [PROBLEMS](https://git.savannah.gnu.org/cgit/groff.git/tree/PROBLEMS?h=1.23.0#n82) file.

In the meantime, I recommend altering one's text searches by typing `.` instead of `-`, as in `move.window`.

If `move-window` is a literal--which, checking my local copy of _tmux_(1), it is--then it needs to spell ASCII hyphen-minus characters with `\-` in its man page, not with a plain `-`, which is a hyphen.

This fact is widely understood by experienced _man_(7) authors.  _man-pages_(7) says:

> ###    Generating optimal glyphs
>     Where a real minus character is required (e.g., for numbers such as
>     -1, for man page cross references such as utf-8(7), or when writing
>     options  that  have  a  leading  dash,  such  as in ls -l), use the
>     following form in the man page source:
>
>         \-
>
>     This guideline applies also to code examples.
>
>     The use of real minus signs serves the following purposes:
>
>     •  To provide better renderings on various targets other than ASCII
>        terminals, notably in PDF and on Unicode/UTF-8‐capable
>        terminals.
>
>     •  To generate glyphs that when copied from rendered pages will
>        produce real minus signs when pasted into a terminal.

The _groff_man_(7) (in _groff_ 1.22.4) and _groff_man_style_(7) pages (_groff_ 1.23.0) offer similar advice.

_mandoc_char_(7) also recognizes the distinction, though it claims it is irrelevant.  I believe that claim to be mistaken.

The hyphen, dash, and minus sign are not the same things, and if one is employing a sizable character repertoire, as one does in PDF documents or Unicode-enabled terminals, one must distinguish these things.  Joe Ossanna, the author of AT&T Unix _troff_, faced a similar situation in about 1973, and that is how we got here.

Here is an excerpt of the _groff_char_(7) man page from _groff_ 1.23.0 explaining the background.

> ### History
>     A consideration of the typefaces originally available to AT&T nroff
>     and troff illuminates many conventions that one might regard as
>     idiosyncratic fifty years afterward.  (See section “History” of
>     roff(7) for more context.)  The face used by the Teletype Model 37
>     terminals of the Murray Hill Unix Room was based on ASCII, but
>     assigned multiple meanings to several code points, as suggested by
>     that standard.  Decimal 34 (") served as a dieresis accent and
>     neutral double quotation mark; decimal 39 (') as an acute accent,
>     apostrophe, and closing (right) single quotation mark; decimal 45
>     (-) as a hyphen and a minus sign; decimal 94 (^) as a circumflex
>     accent and caret; decimal 96 (`) as a grave accent and opening
>     (left) single quotation mark; and decimal 126 (~) as a tilde accent
>     and (with a half‐line motion) swung dash.  The Model 37 bore an
>     optional extended character set offering upright Greek letters and
>     several mathematical symbols; these were documented as early as the
>     kbd(VII) man page of the (First Edition) Unix Programmer’s Manual.
>
>     At the time Graphic Systems delivered the C/A/T phototypesetter to
>     AT&T, the ASCII character set was not considered a standard basis
>     for a glyph repertoire by traditional typographers.  In the stock
>     Times roman, italic, and bold styles available, several ASCII
>     characters were not present at all, nor was most of the Teletype’s
>     extended character set.  AT&T commissioned a “special” font to
>     ensure no loss of repertoire.
>
>     A representation of the coverage of the C/A/T’s text fonts follows.
>     The glyph resembling an underscore is a baseline rule, and that
>     resembling a vertical line is a box rule.  In italics, the box rule
>     was not slanted.  We also observe that the hyphen and minus sign
>     were already “de‐unified” by the fonts provided; a decision whither
>     to map an input “-” therefore had to be taken.
