### ISSUE TITLE
tmux runs ~/.bash_logout on exit, which may break the user's whole login session

### ISSUE THREAD

**Issue by maidentaiwan** [tmux/tmux#3680]
### Issue description

On exit, tmux runs the bash configuration file ~/.bash_logout. This has bad side-effects if tmux is run in a shell window on a graphical desktop such as KDE or GNOME. The code in ~/.bash_logout is meant to be run exactly once when the user logs out, in this case from KDE/GNOME, but tmux runs it *early*. A typical line in ~/.bash_logout is:

```
test -n "$SSH_AGENT_PID"  && eval `/usr/bin/ssh-agent -k`
```

which kills `ssh-agent` globally for the user. tmux runs it. The overall effect on the user looks like this:

1. User is happily launching SSH sessions that authenticate with ssh-agent.
2. User runs tmux.
3. User exits tmux.
4. All future SSH connection attempts mysteriously fail because ssh-agent is dead.
5. User is forced to shut down all their applications and log out from KDE or GNOME and log back in, so ssh-agent restarts and all shells inherit the proper SSH environment variables.

I don't know if this is a software issue or a documentation issue, but at the very least, please please warn about this issue in giant flaming red letters in your manpage (and provide a workaround). It took me several hours of diagnosis to figure out why all my SSH connections could no longer authenticate properly. I had no idea the culprit was tmux.

Thanks for listening!

### Required information

Please provide the following information:

* tmux version (`tmux -V`). tmux next-3.4
* Platform (`uname -sp`). Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`). Inside: xterm-256color. Outside: screen.
* Logs from tmux (`tmux kill-server; tmux -vv new`). Attached.
[tmux-client-16632.log](https://github.com/tmux/tmux/files/12507957/tmux-client-16632.log)

**Comment by krader1961** [comment]
Don't take this the wrong way but you seem to be a wee bit confused. Tmux does not run any shell specific scripts. Your shell, Bash, is running that script. From the Bash man page:

       When  a  login  shell  exits,  bash  reads  and  executes  commands  from  the file
       ~/.bash_logout, if it exists.

So the solution is to not run Bash as a login shell when launched by Tmux.

**Comment by maidentaiwan** [comment]
Thanks very much for the response. I'm aware that bash sources its scripts, but tmux is the trigger: its default behavior is to run a login shell. Is that correct? If so, then by default, tmux's actions cause ~/.bash_logout to run on exit, and you get the use case I spelled out in my steps 1-5.

Would you ever consider changing tmux's default behavior to run a non-login, interactive shell? I believe the "screen" command does.

If not, is there a way to to make tmux run non-login, interactive shell so it only sources ~/.bashrc and not the login-related scripts? I don't see an option for it. If there's a way to do it, would you consider spelling it out on the man page, with a warning that if you don't use it, tmux runs a login shell that may source your shell's logout scripts early?

Thanks again.

**Comment by nicm** [comment]
tmux uses login shells because each pane is detached from the external environment, so it is a new login. This is not going to change.

**Comment by nicm** [comment]
You can configure it by setting `default-command`. I thought this was in the FAQ but apparently not...

**Comment by krader1961** [comment]
>  I'm aware that bash sources its scripts, but tmux is the trigger: its default behavior is to run a login shell.

Yes, but your problem statement said this:

> On exit, tmux runs the bash configuration file ~/.bash_logout.

Honestly, that legacy shells like Bash, Zsh, and Ksh, distinguish "login" shells from other shell invocations was a mistake. I say that as someone who has been using Unix operating systems since the early 1980's (when connecting to a Unix system was typically done via RS-232) and spent over a decade as a support engineer for Sequent Computer Systems and then IBM. Modern shells like [Elvish](https://elv.sh) don't make any such distinction. As @nicm points out you can configure Tmux to not launch a "login" shell; which might solve your problem. I say "might solve" because I haven't seen anyone use a *~/.bash_logout* script in a very long time and didn't expend any effort to understand why you are using that script. You wrote:

> The code in ~/.bash_logout is meant to be run exactly once when the user logs out,

The concept of logging in or out is ill defined. Back in the 1980's it meant logging in by typing your user ID and password to a program like [getty](https://wiki.archlinux.org/title/getty) to get a new shell session. Today the concept of "logging in" is less well defined than it was back then and now causes more problems than it solves.

**Comment by krader1961** [comment]
Ugh! Because I was curious, @maidentaiwan, I googled "bash kill ssh-agent on logout" which lead me to read things like https://unix.stackexchange.com/questions/667266/why-should-i-kill-ssh-agent-on-logout which caused me some pain because I did a [Picard double face palm](https://www.youtube.com/watch?v=2aJREW3dp_c) due to the idiocy of the question and answers.

**Comment by maidentaiwan** [comment]
@nicm - Thank you very much for your informative replies. They were immediately helpful.

@krader1961 - Thank you for imparting your four decades of Unix experience. I too learned Unix on PDP-11s & VAXes in the 1980s. Interesting to meet someone with similar background.
