### ISSUE TITLE
Sixels not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by ferdinandyb** [tmux/tmux#3684]
### Issue description

I tried building sixel support, but it doesn't seem to work for me. I'm on commit `e2635660` (current master). I did a `reset --hard origin/master`, then

```
sh autogen.sh
./configure --enable-sixel --prefix=$HOME/.local
make
```

I tried both contour and wezterm. `cat tools/image.sixel` work in both of them without tmux, but not with tmux (started as `./tmux`, I also played around with and without my `.tmux.conf`). My knowledge of build tooling is limited, so I'm not entirely sure, but I think this actually does build with sixels enabled, yet it doesn't work, but of course I may have just made a mistake in building ...

### Required information

Please provide the following information:
```
❯ uname -sp && tmux -V && echo $TERM

Linux x86_64
tmux next-3.4
contour
```

inside tmux term is: `tmux-256color`
my OS is: Ubuntu 22.04.3 LTS

logs from ` tmux kill-server; ./tmux -vv -f /dev/null new` and then `cat tools/image.sixel`:
client log: https://0x0.st/HfHu.log
server log: https://0x0.st/HfHM.log

**Comment by rockorager** [comment]
This worked for me:

```
git clone https://github.com/tmux/tmux.git
cd tmux
sh autogen.sh
./configure --enable-sixel
make && sudo make install
```

**Comment by ferdinandyb** [comment]
I got an email about a comment, but it's gone... Anyway, it suggested to reclone, so I did so, now something actually happens, but under both wezterm and contour I see this for about a second, and then it disappears (the new prompt is inserted below):

![image](https://github.com/tmux/tmux/assets/6343487/837a3dd7-498c-4c6d-bfe9-68db580b3411)

**Comment by nicm** [comment]
Your terminal reports itself as VT525 which tmux does not detect as supporting SIXEL, so you will need to tell tmux it is supported with `set -as terminal-features 'contour:sixel'`.

**Comment by uspasojevic96** [comment]
> Your terminal reports itself as VT525 which tmux does not detect as supporting SIXEL, so you will need to tell tmux it is supported with `set -as terminal-features 'contour:sixel'`.

Shouldn't tmux then be querying DA1 to see if terminal supports SIXEL?

**Comment by nicm** [comment]
Of course it looks at DA1, but VT525 terminals never support SIXEL so we were ignoring them (although I have now changed that since it's much more likely to come across a terminal emulator that pretends to be VT525 than a real VT525).

**Comment by christianparpart** [comment]
> Of course it looks at DA1, but VT525 terminals never support SIXEL so we were ignoring them

I think we should agree on whether we code for 100% hardware emulation for powerplants that need this (losely quoted) or more for the past 20 years.

Contour reports VT525, because it supports VT sequences from that VT level. Certainly not all, because we are not even trying to emulate hardware 100% here. But I think it is worth implementing that might make sense to have.
And since the spec itself denotes Sixel is to be advertised through DA1, I really see absolutely no reason why the VT level should be looked at.

> (although I have now changed that since it's much more likely to come across a terminal emulator that pretends to be VT525 than a real VT525).

The user can change that in the config file as initial level, or it can be changed at runtime via VT sequence. But bare in mind, that this will also constrain the number of VT sequences available based on that VT you asked it for to be. 

To my understanding, I did not find any source of truth "mandating" that anything beyond VT340 MUST NOT support Sixel. And it is not even required IMHO, because you simply look at DA1 for feature detection. In other words, what's this there for if it's not to be used by apps at all?

on your "pretend" argument. We implement what makes sense, and therefore expose that VT level, but there is no reason to emulate the full hardware. So I'd like to take your argument here with a little bit grain of salt.

**Comment by nicm** [comment]
You seem to be reading a lot more into the word "pretends" than it means.

In any case, tmux is now changed to also look for the SIXEL flag for VT525.

We should probably use DECSLRM and DECFRA on terminals later than VT420 as well, it looks as if at least VT510 has it and there is no reason to think VT520 and VT525 would not... maybe I will change that also.

**Comment by nicm** [comment]
Ah, the reason I left out 65 was because xterm does not list 65 for DA:
~~~~
            ⇒  CSI ? 1 2 ; Ps c  ("VT125")
            ⇒  CSI ? 6 2 ; Ps c  ("VT220")
            ⇒  CSI ? 6 3 ; Ps c  ("VT320")
            ⇒  CSI ? 6 4 ; Ps c  ("VT420")
~~~~
The VT510 sends 64 as well according to the manual.

The VT520 manual says it sends 65 and accepting it won't do any harm. It doesn't list SIXEL but we know that already and the number isn't reused...

**Comment by ferdinandyb** [comment]
Thanks, I now seem to be closer, but not quite: https://0x0.st/HfNw.mp4

The sixel image briefly flashes up and then is cleared. Wezterm again behaves the same as contour. @christianparpart does it work for you?

**Comment by nicm** [comment]
Show me the tmux log of sending a SIXEL and then it clearing please.

**Comment by ferdinandyb** [comment]
tmux out: https://0x0.st/HfNg.log
tmux client: https://0x0.st/HfNE.log
tmux server: https://0x0.st/HfN6.log

**Comment by nicm** [comment]
Does it make any difference if you do this:
~~~~
set -as terminal-overrides '*:Sync@'
~~~~

**Comment by ferdinandyb** [comment]
I was not sure if I can just set that with `prefix+:` so I also added that to the conf, but it doesn't seem to change anything.

**Comment by nicm** [comment]
Hmm. Can you set your shell prompt to a plain `$` without anything else in it and see if the problem still remains? If it does, please give me a new server log.

**Comment by ThomasDickey** [comment]
> Ah, the reason I left out 65 was because xterm does not list 65 for DA:
> 
> ```
>             ⇒  CSI ? 1 2 ; Ps c  ("VT125")
>             ⇒  CSI ? 6 2 ; Ps c  ("VT220")
>             ⇒  CSI ? 6 3 ; Ps c  ("VT320")
>             ⇒  CSI ? 6 4 ; Ps c  ("VT420")
> ```
> 
> The VT510 sends 64 as well according to the manual.
> 
> The VT520 manual says it sends 65 and accepting it won't do any harm. It doesn't list SIXEL but we know that already and the number isn't reused...

I hadn't noticed that in ctlseqs.ms, but it's not simple -

I see that on page 1-6, the VT520 reference manual says that DA returns 64 for VT520, and 65 for VT525 (which I thought was odd, but followed that), but on 4-35 in the response for DA2 it says that both return 65, and on 5-11 it goes back to 64 (VT520) and 65 (VT525, color).

xterm code returns 65 in DA, 64/65 in DA2 (ctlseqs.ms needs some tweaks).

**Comment by ferdinandyb** [comment]
I removed my entire .zshrc for good measure and indeed that makes the issue go away. Just to clarify: without tmux my .zshrc worked just fine.

Ok, so I played around a bit, it works even with a default powerlevel10k prompt, so I'm guessing either the two line prompt, or the prompt removing feature and tmux isn't playing nice together.

**Comment by ThomasDickey** [comment]
> Ah, the reason I left out 65 was because xterm does not list 65 for DA:
> 
> ```
>             ⇒  CSI ? 1 2 ; Ps c  ("VT125")
>             ⇒  CSI ? 6 2 ; Ps c  ("VT220")
>             ⇒  CSI ? 6 3 ; Ps c  ("VT320")
>             ⇒  CSI ? 6 4 ; Ps c  ("VT420")
> ```
> 
> The VT510 sends 64 as well according to the manual.
> 
> The VT520 manual says it sends 65 and accepting it won't do any harm. It doesn't list SIXEL but we know that already and the number isn't reused...

I don't recall seeing a VT510 reference manual, e.g., on [bitsavers](http://www.bitsavers.org/pdf/dec/terminal/vt5xx/).

**Comment by nicm** [comment]
Thanks @ThomasDickey - I clearly checked ctlseqs, rather than actually trying it or looking at the xterm code.

I think DA1 is always 65 for both VT520 and VT525 (both are "level 5") but DA2 is 64 for VT520 and 65 for VT525 (their "identification code"). Page 1-6 is referring to DA2 not DA1, so the manual looks like it is consistent to me:

- DA1 - page 4-35, both 65; page 5-9, VT520 is 65.

- DA2 - page 1-6, VT520 64, VT525 65; page 4-35, VT520 64, VT520 65; page 5-11, "The VT520 has an identification code of 64 (65 for color terminal)".

VT510 is a "level 4" terminal so its get 64 in DA1, but in DA2 its "identification code" is 61.

Reusing the numbers in DA1 and DA2 wasn't all that helpful of them...

**Comment by ferdinandyb** [comment]
> Does this fix it?
> 
> ```
> --- a/screen-write.c
> +++ b/screen-write.c
> @@ -1370,12 +1370,12 @@ screen_write_reverseindex(struct screen_write_ctx *ctx, u_int bg)
>         struct screen   *s = ctx->s;
>         struct tty_ctx   ttyctx;
> 
> +       if (s->cy == s->rupper) {
>  #ifdef ENABLE_SIXEL
> -       if (image_free_all(s) && ctx->wp != NULL)
> -               ctx->wp->flags |= PANE_REDRAW;
> +               if (image_free_all(s) && ctx->wp != NULL)
> +                       ctx->wp->flags |= PANE_REDRAW;
>  #endif
> 
> -       if (s->cy == s->rupper) {
>                 grid_view_scroll_region_down(s->grid, s->rupper, s->rlower, bg);
>                 screen_write_collect_flush(ctx, 0, __func__);
> ```

Thanks, it does! 

Stupid question, but I copied this to file and then tried `git apply patchfile` and it complained that the patch is corrupt at line 18 (the file was 17 lines long). Considering that it was just 5 lines I added it manually, but I'm guessing there would have been an automatic way that works?

**Comment by nicm** [comment]
git apply is not very good, you can probably apply it with patch -p1.

I have applied this fix now, thanks!

**Comment by ferdinandyb** [comment]
Thanks very much, having sixels in tmux is super great :)

**Comment by nicm** [comment]
It turns out we can't use DECFRA and DECSLRM on VT525 because VTE have rather ruined it by saying they are VT525 but not actually supporting its features... it probably isn't a big issue since the main benefit of those is on xterm and it defaults to VT520 (which we can detect with DA2).

We can still look for SIXEL for VT525 anyway since it has a parameter...

**Comment by ThomasDickey** [comment]
xterm defaults to VT420 (where left/right margins were introduced).  VT525 technically introduced some of the ECMA-48 stuff, but those details were in use by xterm several years before VT525 documentation was freely available, so that was moot.  VTE defaults to VT525 for, as one might say, "non-technical reasons".

**Comment by christianparpart** [comment]
Contour defaults to VT525 für technical reasons. This is configurable though.

**Comment by ThomasDickey** [comment]
You might want to clarify that -- in a quick look at the source code, I see only a subset of VT220, along with features from xterm and urxvt (and a few other items, but nothing specific to VT525).

**Comment by christianparpart** [comment]
@ThomasDickey you are right, it is not much. I think the best way to find out is by looking at [src/vtbackend/Functions.h](https://github.com/contour-terminal/contour/blob/64175df4c9b8000ba9154a4aead72fb027fc5315/src/vtbackend/Functions.h#L352-L423) and grepping for `::VT5`. At least `DECSCUSR` from VT520 is implemented (which xterm does as well, and documents it as VT520).

We also implement `DECPS`, which was said to be introduced by VT520 here: https://github.com/microsoft/terminal/issues/8687.

There may be more, I don't know. I personally found it not quite nice to actually find out what VT sequences were introduced by which VT version (if you know a good way, I'm all open :) )
