### ISSUE TITLE
It is very easy to bypass a locked session

### ISSUE THREAD

**Issue by ewscott9** [tmux/tmux#369]
You can easily bypass a locked tmux session with tmux attach. Are there any plans on making a locked session require a password before being re-attached, like gnu screen?

I am using tmux 2.0 on ubuntu15.10. 
My lock command is: set-option -g lock-command vlock

**Comment by nicm** [comment]
No, if someone had access to your account in order to do "tmux attach" then they would be able to bypass any locking anyway.

**Comment by ewscott9** [comment]
If that's the case, what is the point of locking the session? I mean this earnestly; I can think of a reason why locking the session would be useful. 

I feel like there should be some way to password protect a tmux session, or server.

**Comment by nicm** [comment]
It locks the individual terminal where the client is running securely. So
long as someone does not have access to your account in another way, that
is safe. The only way for tmux to lock  that could not be undone by someone
with access to your account would be for tmux to become setuid or setgid
which would be more dangerous. And really, what does locking the server get
you if someone can access your account already.

On 13 Apr 2016 3:46 a.m., "Eric Scott" <notifications@github.com> wrote:
>
> If that's the case, what is the point of locking the session? I mean this
earnestly; I can think of a reason why locking the session would be useful.
>
> I feel like there should be some way to password protect a tmux session,
or server.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
<https://github.com/tmux/tmux/issues/369#issuecomment-209201724>

**Comment by ewscott9** [comment]
Okay, that does make sense. Thanks for clearing that up.

**Comment by t0d0r** [comment]
> And really, what does locking the server get
> you if someone can access your account already.

I can't agree with that.For example I have multiple ssh connections to the external servers running in tmux. If someone reattach tmux session without password, he will got access to all of these connections. Locking session with password it will prevent local attackers to have access to these sessions, he need to figure out ssh passwords or use keylogger somehow.

**Comment by ntnn** [comment]
@t0d0r In which case they can still simply kill the locking process and they're in.

**Comment by t0d0r** [comment]
@ntnn, killing locked tmux  must kill all processes spawned by that session, so in that way all ssh connections will be closed.

**Comment by brandonpoc** [comment]
I agree a password feature similar to GNU Screen would be nice. Indeed if someone has access to the local shell they would be able to bypass it if they were crafty - e.g. access the memory of the session and overwrite the (hashed) password or remove it, or access one of the TTYs. But this would require a good amount of skill and, as a way of keeping out most people, a passworded session would work great. I never experienced anyone successfully hacking my password-protected SCREEN sessions on public UNIX servers with many users, including in the situation that they were trying to access it to get access to a IRC session so that they could op themselves or to access SSH sessions that were running within.

Screen's password is setup in such a way that upon attaching you have to enter the password that matches the hashed password stored in either the .screenrc or set via the :password command. Is this not possible with tmux's infrastructure, to set it up to where in order to attach to a tmux session one would have to enter a password in a similar fashion? To go out on a limb and stretch it even further, one could (in the case of a password being set) enable anti-debugging techniques like trying to prevent PTRACE attaching in order to foil memory manipulation.

Just an idea. I don't know how tmux works under the hood, but if GNU Screen has the capability, it'd be nice for tmux to have it as well (if possible).

**Comment by balkierode** [comment]
I wan't to see locking feature for privacy of tmux buffer.  Assuming they will be encrypted with the passphrase. I could have a personal chat / email or sshed into some server. I understand that if I just leave them running, tmux can't help much as the user having access to my account can read their memory. But I am aware of that and I quit those before detaching/locking tmux(Have timeouts/ callbacks that quits those processes). I am just interested in protecting the tmux buffer that has all the output/commands I entered without having to delete the window/session. I understand its not perfect, but can be another line of defense.

**Comment by Swivelgames** [comment]
@nicm No chance of this ever seeing the light of day, is there? :/

**Comment by Swivelgames** [comment]
@nicm No chance of this ever seeing the light of day, is there? :/

For what it's worth, I share the concerns that @t0d0r @brandonpoc and @balkierode have all brought up. That's what led me here. I'm using `vlock` right now, but I was a bit concerned when: (1) I locked one and it didn't lock the other, and (2) I was able to simply re-attach to a window I had previously locked that had a live SSH connection open. I was opening to use lock as a way of keeping these processes running without the need to worry about someone being able to re-attach to these.
