### ISSUE TITLE
Some of the charactors are not visible in tmux 2.2

### ISSUE THREAD

**Issue by ToruIwashita** [tmux/tmux#376]
Some of the charactors that has been displayed in tmux 2.1(e.g. ⚠, ⚡) are not visible in tmux 2.2.

##### - tmux 2.1
![tmux_2 1](https://cloud.githubusercontent.com/assets/3197608/14606494/777e122a-05b8-11e6-9ef2-514dd7195330.gif)

##### - tmux 2.2
![tmux_2 2](https://cloud.githubusercontent.com/assets/3197608/14606498/7fbc1d24-05b8-11e6-9a12-3334c7486207.gif)

**Comment by actionless** [comment]
can reproduce it as well on Arch Linux, tmux 2.2

that seems to be related with what now it's saying what this option is deprecated:
```
#set-option -g status-utf8 on
```

**Comment by nicm** [comment]
What use are animations of this? Where is the test file? And the tmux logs?

**Comment by nicm** [comment]
Use this please:

tmux -Ltest -f/dev/null -vvvv new

Then cat the test file, then exit and send me the tmux-server-*.log file from the current directory.

**Comment by actionless** [comment]
i am using powerline-ish font with few special characters and some of them (`\ud7fc`, `\ud7fd`) can't be displayed through tmux after updating to `2.2`


[cut.txt](https://github.com/tmux/tmux/files/234618/cut.txt)

**Comment by nicm** [comment]
Your log file is incomplete. Is this OS X?

**Comment by actionless** [comment]
sorry, i thought i've pasted only the related range, here is the full log:

**Comment by actionless** [comment]
sorry, i thought i've pasted only the related range, here is the full log:

[tmux-server-6398.log.txt](https://github.com/tmux/tmux/files/234660/tmux-server-6398.log.txt)

**Comment by nicm** [comment]
Please apply this diff https://github.com/tmux/tmux/files/175737/x.txt and run:

tmux -vvvv -Ltest -f/dev/null new

Then cat the problem file, then exit tmux, and send me the new log file.

**Comment by actionless** [comment]
[tmux-server-18510.log.txt](https://github.com/tmux/tmux/files/234688/tmux-server-18510.log.txt)

**Comment by nicm** [comment]
The first character looks fine, so I don't know why it is not showing up, it appears for me. Does "tmux lsc" inside tmux show that the client is UTF-8?

For the second character, your platform wcwidth() is returning -1. This is correct, because U+D7FC is not a valid Unicode character. If you want to define your own Unicode characters, you should put them in the BMP private use area (U+E000 to U+F8FF), which most platforms assume is width 1.

**Comment by ToruIwashita** [comment]
The animations are created by gifgrabber.
http://www.gifgrabber.com/index

**Comment by ToruIwashita** [comment]
I tried to run `tmux -vvvv -Ltest -f/dev/null new` command.

test file:
 [test.txt](https://github.com/tmux/tmux/files/236014/test.txt)

log before applying the patch:
 [tmux-server-57534.log.txt](https://github.com/tmux/tmux/files/236015/tmux-server-57534.log.txt)

log after applying the patch:
 [tmux-server-61188.log.txt](https://github.com/tmux/tmux/files/236025/tmux-server-61188.log.txt)

**Comment by nicm** [comment]
Your platform wcwidth() is returning -1 for characters U+26A0 and U+26A1. These characters are common symbols that appear to have been present since Unicode 4.0 in 2003, so this is a bug in your system locale implementation. I suggest you see if an upgrade is available or report it to your platform maintainers.

**Comment by ToruIwashita** [comment]
Oh, I got it. Thank you for your support!
