### ISSUE TITLE
Feature Request: Select pane by name

### ISSUE THREAD

**Issue by gdkrmr** [tmux/tmux#3765]
tmux can name panes with
```bash
tmux select-pane -T name
```

It would be great if the named pane could be referred to by its name when using commands, e.g.
```bash
tmux send-keys -t name
tmux select-pane -t name
```

**Comment by nicm** [comment]
They are called pane titles not pane names but the distinction doesn't really matter. We have not done this before because panes are not guaranteed to have a useful title and you can't see them by default anyway, but it wouldn't do any harm.

If you want to have a go you would probably need to change `cmd_find_get_pane`. I would probably make it similar to `cmd_find_get_session` - check as exact match first, then as a prefix then using `fnmatch`. Duplicate matches should be an error.

**Comment by lrfurtado** [comment]
I will give this a shot , seems like a cool initial task work on.
