### ISSUE TITLE
New windows and panes open in wrong directory when using shell pipes

### ISSUE THREAD

**Issue by mmottl** [tmux/tmux#3767]
### Issue description

Assume I'm in directory `~/tmp` with the following prompt:

```bash
~/tmp$ echo | sleep 60
```
When I execute this and then immediately open a new Tmux pane or window, instead of ending up in `~/tmp`, Tmux would put me in my home directory as seen with this prompt:

```bash
~/$
```

Note the slash after the `~`. My usual prompt for being in my home directory would just be `~$`. If it weren't for the pipe, Tmux would correctly keep me in my last directory (`~/tmp`). For example, the following prompt, where `|` has been replaced with `;` would work just fine and keep me in `~/tmp`:

```bash
~/tmp$ echo; sleep 60
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

```
tmux 3.3a
```

* Platform (`uname -sp`).

```
Darwin arm
```

* $TERM inside and outside of tmux (`echo $TERM`).

Inside:
```
tmux-256color
```

Outside:
```
xterm-256color
```

* Logs from tmux (`tmux kill-server; tmux -vv new`).

[tmux-client-76134.log](https://github.com/tmux/tmux/files/13628174/tmux-client-76134.log)
[tmux-out-76136.log](https://github.com/tmux/tmux/files/13628175/tmux-out-76136.log)
[tmux-server-76136.log](https://github.com/tmux/tmux/files/13628176/tmux-server-76136.log)

**Comment by krader1961** [comment]
On a brand new Macbook Air I can't reproduce your problem. Can you reproduce the problem without a Tmux config? That is, kill the existing Tmux server then do `tmux -f /dev/null` and try to reproduce.

**Comment by mmottl** [comment]
When I use `tmux -f /dev/null`, then e.g. splitting the window won't keep the last directory even without calling a command with a pipe (or any command).

If all I put in `.tmux.conf` is:
```
bind % split-window -h -c "#{pane_current_path}"
```

Then splitting a window will preserve the current path. But it still won't work if I execute `echo | sleep 60`. I'm able to reproduce this reliably with various terminals (iTerm2, Apple Terminal) as well as shells (bash, zsh), and even without running any of my shell startup scripts.

One thing I've just figured out is that it's actually not the home directory that will become the new current working directory in a new pane, but it will be the directory in which Tmux was started.

**Comment by krader1961** [comment]
> One thing I've just figured out is that it's actually not the home directory that will become the new current working directory in a new pane, but it will be the directory in which Tmux was started.

I just tested this on my main macOS system and found that appears to be the case. Opening a new Tmux window consistently results in the new shell having */Applications* as its CWD (which was probably the CWD when I started Tmux on that system).  My original attempt to reproduce the problem was probably not sufficiently evil to detect the actual behavior. However, I just tested this on Linux and saw the same behavior as Tmux on macOS. That is, creating a new window uses the CWD when the Tmux server was started and ignores any `cd` executed in the first window.

What would it mean for Tmux to honor the CWD of a window when creating a new window given that it manages multiple windows? And some of those windows may be running commands like `ssh` to a different system where the CWD is not present on the system where the Tmux server is running? Which Tmux window CWD should be used when creating a new window?

Heck, just creating a iTerm2 window, without any involvement of Tmux, and pressing [Cmd-N] to create a new iTerm2 window puts the new shell in the CWD of original window before I typed `cd /someplace-else` in that original window. In other words, even without the involvement of Tmux I see the behavior you think is wrong.

**Comment by nicm** [comment]
pane_current_path is best effort, if it can't figure out what the foreground process is or if that process has changed its working directory to something odd, you will not get the directory you might expect. If you need the new working directory to be always predictable, pass -c with the path you want.

**Comment by mmottl** [comment]
Thanks, no problem! Only one last question: is there anything I can call within a shell script to give a hint to Tmux on what the current path for subsequently opened panes should be, without actually opening a pane?
