### ISSUE TITLE
Fail `bind-key -r -T root C-1 send-keys foo`

### ISSUE THREAD

**Issue by owenstake** [tmux/tmux#3807]
### Issue description

I want to bind `ctrl+1` to send a string "foo" by `bind-key -r -T root C-1 send-keys foo` . But it takes no effect.

### Required information

Please provide the following information:

* tmux version (`tmux -V`).             tmux 3.3a
* Platform (`uname -sp`).               Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).        xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).    na

**Comment by krader1961** [comment]
That's because historically the Ctrl modifier only affected a subset of the ASCII characters and was a no-op when applied to something like the `1` key. This shortcoming has been addressed relatively recently by the introduction of the "extended keys" protocol. See https://github.com/tmux/tmux/wiki/Modifier-Keys.

**Comment by krader1961** [comment]
@owenstake: You upvoted my comment but didn't close this issue. So I am confused. Are you waiting to close this issue until you have verified my comment by modifying your environment to enable extended keys and that causes your Tmux key binding to work?
