### ISSUE TITLE
.tmux.conf line endings

### ISSUE THREAD

**Issue by jftuga** [tmux/tmux#3841]
This occurs in 3.4 but don't think it was a problem in earlier versions.  I noticed that my `.tmux.conf` file uses `CRLF` line endings instead of `LF`.  I must have accidentally saved it this way in my git repo -- I honestly don't know why or how this happened.

When tmux encounters an empty line only consisting a `CRLF`, this vague error message occurs:

     /home/jftuga/.tmux.conf:4: unknown command:

I don't expect this to actually be fixed but thought I would bring it to your attention.  You can close this issue if you do not think it warrants any further discussion as the vast majority of config files will be using `LF` line endings.

**Comment by krader1961** [comment]
> I don't expect this to actually be fixed...

Well, it isn't actually broken so there isn't anything to fix. This happens with older versions of tmux and there is nothing in the changelog to suggest how config file line endings are handled has changed. The most recent entry in the *CHANGES* file that documents how config file parsing has changed was for version 3.0. So unless you were using a 2.x version it is unlikely that simply upgrading tmux is the reason you're now seeing that error.

The "unknown command" error is cryptic because it outputs the literal CR character (the command it doesn't recognize) -- moving the cursor to column one.

As for how this can happen read https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings. Do you use Windows as well as Unix style OSes? Did you perhaps edit your *.tmux.conf* on Windows?

Since Tmux currently doesn't support Windows there isn't a compelling reason to modify it to handle a config file that uses Windows style line endings as well as Unix. On the other hand it would probably be straightforward to handle both LF and CRLF line endings. Doing so, or at least issuing a clearer warning when CRLF line endings are detected, might be justified from a usability viewpoint. But it's probably something someone like yourself, who cares about the issue, will probably need to write the relevant patch rather than expect the project owner to do so.
