### ISSUE TITLE
Charset issue?

### ISSUE THREAD

**Issue by gkostyanikov** [tmux/tmux#389]
I'm on latest tmux installed by homebrew's `brew reinstall --HEAD tmux`. After last reinstall (i'm doing it pretty much every day) i've started to got broken chars in my tmux session when typing cyrillic chars(same text in compare with vanilla fish-shell prompt):
![image](https://cloud.githubusercontent.com/assets/666122/14908920/3922af1e-0de6-11e6-91ee-f2793f0e347f.png)

.tmux.conf
https://gist.github.com/gkostyanikov/bbc1a6b47291edfc7a8519eecdd22531

**Comment by krader1961** [comment]
FWIW, I don't see any reason to think this is a fish issue but as a contributor to the fish shell project I feel compelled to ask if you have tested the behavior with the git head version (or at least the 2.3.0 version that recently entered beta testing). That's because there have been changes to the fish shell that affect its handling of escape prefixed sequences. You will probably need to execute `set -g fish_escape_delay_ms 100` as the default timeout up until a few minutes ago was 10 ms.

Too, it would be good to capture the broken char output using the `script` command.

**Comment by gkostyanikov** [comment]
@krader1961 sure, now i'm on `fish, version 2.3b1`
 
`script` command captures: https://gist.github.com/gkostyanikov/fef0f7a1012344d53ed5a36ebb19bc97

**Comment by nicm** [comment]
Do this:

tmux -vvvLtest -f/dev/null new

Then type ONE broken character, exit tmux, and send me the tmux-server-*.log.

**Comment by gkostyanikov** [comment]
@nicm https://gist.github.com/gkostyanikov/f3377ee01e2c95824a315e52df3b4c0f

**Comment by nicm** [comment]
Your tmux is not up to date, please do a git pull from master then rebuild and do the same thing.

**Comment by gkostyanikov** [comment]
https://gist.github.com/gkostyanikov/9a4fcdd113fb4f37e8204f1e51655456

<img width="568" alt="2__fish___users_gkostyanikov__fish_" src="https://cloud.githubusercontent.com/assets/666122/14913182/c7c7fe7c-0e09-11e6-994b-be4df1f9e410.png">

**Comment by nicm** [comment]
Ok I found a problem, please wait a few hours for GitHub to sync then try again.

**Comment by nicm** [comment]
You can try now.

**Comment by cgull** [comment]
This is a long-standing issue with Mosh, see mobile-shell/mosh#234 for example.  It's a virtual terminal as well, so has all the issues tmux will with platform `wcwidth()` implementations. It has some extra ones because it actually runs two virtual terminals, server into client, and platform `wcwidth()` implementations vary, as you are finding out.  People often run tmux inside Mosh, adding a third virtual terminal, but for some reason we haven't had too much Unicode compatibility trouble between tmux and mosh.

It would be great if everybody working on console-mode virtual-terminal programs (`screen`, `tmux`, `mosh`, and the 17 other things I can't remember) got together and created a standard `wcwidth()` (or similar) implementation/library that is fast, current on Unicode, and supports the needs of console-mode programs well.  That way we could avoid inter-system and inter-program Unicode incompatibilities.

Unfortunately, Unicode is a living/changing specification, so there's always going to be some compatibility issues.

**Comment by nicm** [comment]
Someone in https://github.com/tmux/tmux/issues/328 is using a thirdparty library but on a quick look it appears to be part of a language rather than something widely available, although I could be wrong there. I don't object to adding configure magic for tmux to link against a third party library but I do not think we should return to carrying around our own wcwidth() implementation.

I suspect a bad system wcwidth() would be virtually impossible to detect so it would be up to the user or packager to choose to use the alternative where the system one is substandard.

**Comment by cgull** [comment]
Thanks for the reference to [utf8proc](https://github.com/JuliaLang/utf8proc)-- I'm going to investigate that for Mosh.

**Comment by gkostyanikov** [comment]
Sorry for late feedback, checked right now and problem with tmux on master is still here. Tried the stable one (2.1 `brew install tmux`) and everything went fine here. Also tried `printf '\u0440\n' (russian "р" ) sucсessfully:
![image](https://cloud.githubusercontent.com/assets/666122/15010177/73776c48-11f3-11e6-9648-3c52309eb84b.png)

**Comment by nicm** [comment]
You could take a screenshot and draw on it but you didn't think it worth showing any updated logs?

**Comment by gkostyanikov** [comment]
killed tmux server and now it works as expected, sorry)

**Comment by nicm** [comment]
Ok cool :_)
