### ISSUE TITLE
Loading time for zsh is too slow

### ISSUE THREAD

**Issue by bryant-the-coder** [tmux/tmux#3900]
![image](https://github.com/tmux/tmux/assets/92417638/1e79cb67-30ca-424c-a1db-7f2044c4cdd9)

### Required information

Please provide the following information:

* tmux version (`tmux -V`).

> tmux 3.4

* Platform (`uname -sp`).
> Linux unknown
* $TERM inside and outside of tmux (`echo $TERM`).
> OUTSIDE: xterm-kitty
> INSIDE: xterm-kitty

* Logs from tmux 
* [tmux-client-9741.log](https://github.com/tmux/tmux/files/14665948/tmux-client-9741.log)
* [tmux-out-9743.log](https://github.com/tmux/tmux/files/14665950/tmux-out-9743.log)
[tmux-server-9743.log](https://github.com/tmux/tmux/files/14665951/tmux-server-9743.log)

**Comment by krader1961** [comment]
To a shell like Zsh or Bash the Tmux application looks pretty much like any other terminal; e.g., Xterm or iTerm2. So what makes you think Tmux is the reason your shell is slow (whatever that means)?

As for your "argument list too long" errors that is probably because you have a glob (e.g., `*`) in your *.zshrc* that is expanding to too many files. Possibly the CWD is not what your *.zshrc* expects so the glob isn't matching the expected files.

P.S., Using `TERM=xterm-kitty` inside a Tmux session is likely to cause problems.

**Comment by nicm** [comment]
This is clearly a zsh problem.
