### ISSUE TITLE
tmux hangs on shutdown

### ISSUE THREAD

**Issue by FG-TUM** [tmux/tmux#3905]
### Issue description

It appears that tmux hangs for me during the system shutdown sequence until it hits a timeout. On shutdown, the screen goes black except for a blinking underscore on the top right of the screen, and after ~1 minute, the system actually shuts down. Looking into jounarlctl points to tmux:

```bash
$ sudo journalctl -p5
...
$DATE $HOST systemd[516]: tmux-spawn-0da6b2e5-ae04-4127-bc87-bd60a864da69.scope: Stopping timed out. Killing.
$DATE $HOST systemd[516]: tmux-spawn-0da6b2e5-ae04-4127-bc87-bd60a864da69.scope: Killing process 1232 (bash) with signal SIGKILL.
$DATE $HOST systemd[516]: tmux-spawn-0da6b2e5-ae04-4127-bc87-bd60a864da69.scope: Failed with result 'timeout'.
``` 

This suspicion is further confirmed as the system shuts down significantly faster if tmux is not running.

This was tested with an empty bashrc and empty tmux.conf a.

### Required information

Please provide the following information:

```bash
$ uname -sp && tmux -V && echo $TERM

Linux unknown
tmux 3.4
screen-256color
```
Outside of tmux:
```bash
$ echo $TERM
xterm-256color
```

(I'll gladly provide more info if needed)

[tmux-server-3472.log](https://github.com/tmux/tmux/files/14694576/tmux-server-3472.log)

**Comment by nicm** [comment]
Something is broken on your system because it took more than 100 seconds between tmux being told the child in the last pane had exited and the kernel telling it the pty file descriptor had been closed:
~~~~
$ egrep '(%0 error|server_signal|server loop exit)' tmux-server-3472.log
1711021031.487216 server_signal: Child exited
1711021133.563554 %0 error
1711021133.567671 server loop exit
~~~~
What are you running in the pane? Do you see this if you run `exec sleep 1000` instead?

Do you see this if you start tmux normally and then exit it by typing `exit` at the shell?

**Comment by FG-TUM** [comment]
> What are you running in the pane?

In the tmux pane? Nothing besides bash or zsh. The system uses Cinnamon as a DE and tmux runs in a gnome-terminal. I just noticed if I connect to a different tty, launch tmux there and then issue a poweroff / reboot it doesn't hang. So it might not be directly tmux but something that interacts with it?

> Do you see this if you run exec sleep 1000 instead?

The hanging? Nope. Here is the log for `exec sleep 5`: [tmux-server-2746_sleep.log](https://github.com/tmux/tmux/files/14695544/tmux-server-2746_sleep.log)

> Do you see this if you start tmux normally and then exit it by typing exit at the shell?

The hanging? Nope. Here is the log for `exit`: [tmux-server-2290_exit.log](https://github.com/tmux/tmux/files/14695550/tmux-server-2290_exit.log)

**Comment by FG-TUM** [comment]
Here is [strace.txt](https://github.com/tmux/tmux/files/14696594/strace.txt) (GitHub doesn't allow `.out` uploads :roll_eyes: )

> Does it work if you make your shutdown process kill tmux with tmux kill-server or by sending it SIGTERM rather than killing the processes inside tmux and letting tmux exit itself that way?

Probably? Not sure how to go about that but closing all tmux sessions before shutting down prevents the holdup.

**Comment by nicm** [comment]
Can you do this without logging please so there is less noise?

**Comment by FG-TUM** [comment]
Sure, here you go: [strace_noLog.txt](https://github.com/tmux/tmux/files/14793005/strace_noLog.txt)

**Comment by nicm** [comment]
This strace doesn't show much because it looks like it is being killed before tmux is.

Anyway, I think your shutdown process is doing something funny because it clearly works when either exiting the process inside tmux manually or killing tmux directly with SIGTERM.

**Comment by egrajeda** [comment]
Hello, my shutdown was hanging as well and I just managed to pinpoint it to tmux. I have the exact same messages that @FG-TUM shared (did you manage to fix it somehow BTW?).

I'm in Archlinux and in my case I confirmed it started to happen when I upgraded from 3.3_a-7 to 3.4-4. I'll try to troubleshoot a bit more in my end and see if I can find something useful.

**Comment by FG-TUM** [comment]
> did you manage to fix it somehow BTW?.

Nope not yet :(

**Comment by egrajeda** [comment]
Yesterday I managed to narrow down the problem to this commit: https://github.com/tmux/tmux/commit/b9524f5b72d16bd634fc47ad1a4a9d3240bd4370.

So far I've confirmed the issue happens when you compile with `--enable-systemd`. And I've confirmed the issue disappears when you compile with `--enable-systemd --disable-cgroups` (disabling some of the functionality of the previous commit).

@FG-TUM If you use Archlinux you could use [tmux-git from the AUR](https://aur.archlinux.org/packages/tmux-git) and you won't have the problem, as it doesn't compile with systemd.
