### ISSUE TITLE
Full ASCII character set fails to display

### ISSUE THREAD

**Issue by h3xx** [tmux/tmux#394]
**Symptom:**

tmux strips non-utf8 characters from outputting to a terminal configured for full latin1 output.

**Example:**

Inside xterm, running [this script](https://gist.github.com/ca34a6c95b65590384e3e24f74eff839):

![screenshot-2016-0501-1730](https://cloud.githubusercontent.com/assets/615684/14944498/36bd4218-0fba-11e6-9276-811ee362ea4c.png)

Now running the same script inside tmux started with `tmux -f /dev/null`:

![screenshot-2016-0501-1730-1](https://cloud.githubusercontent.com/assets/615684/14944503/6482ff8a-0fba-11e6-9b80-a3f3c1c74016.png)

Running tmux 2.2.  This used to work in 2.1.

    TERM=xterm-256color
    LC_COLLATE=C
    LC_*=en_US

Fairly certain it was broken by 26945d7956bf1f160fba72677082e1a9c6968e0c when it started setting LC_CTYPE at the top of `main`. (Why is it dictating my CTYPE?)

**Comment by nicm** [comment]
tmux only supports UTF-8 now.

**Comment by h3xx** [comment]
Why?

**Comment by nicm** [comment]
Because supporting multiple charsets is a pain and UTF-8 is now the
standard.

**Comment by h3xx** [comment]
AFAIK ASCII is also a standard.

**Comment by krader1961** [comment]
ASCII != ISO 8859-1 (aka "latin1"). Also, Unicode (especially UTF-8) is a superset of ASCII. It was deliberately designed so that ASCII code points were identical in the Unicode standard.

As a maintainer of the fish shell I agree with @nicm: Trying to support both Unicode and ISO 8859 is impossible to do without causing someone, somewhere, to be surprised and annoyed. I was a UNIX support engineer in the 1990's when ISO 8859 was being widely deployed and Unicode was still a novelty. Absolutely no one liked ISO 8859. Not customers. Not vendor support teams. Anyone still using it today is a masochist.

**Comment by h3xx** [comment]
Okay, so I use a character set nobody uses. I'm not arguing tmux should support it.

What I'm saying is that every other program in my toolkit supports it, but tmux is stripping out the characters that A) the programs making the output think my terminal can display and B) the terminal is configured to display correctly.

tmux is sitting between the programs I run and the terminal, stripping out characters it shouldn't be.

Is there a reason it needs to be stripping characters that don't resolve to Unicode code points, or is this a side-effect of something in the code?

**Comment by krader1961** [comment]
I wasn't calling you names, @h3xx. I was pointing out that anyone using a ISO 8859 encoding should expect problems. It's like the old joke where someone goes to a doctor and says "it hurts when I do X" and the doctor's reply is "stop doing X". Stop using ISO 8859-1. Everyone knew it was a bad idea the day after it became a standard and started using it (and most people knew it was a bad idea during the RFC phase of the standardization process).

The first thing to note is that ISO 8859 uses all possible 256 single-byte code points. It is intrinsically incompatible with UTF-8 since there is no unambiguous mapping from one to the other. Which means that any program which supports ISO 8859 has to, by definition, treat every byte as a legal code point. Which also means it can't do anything sensible with UTF-8 sequences that are not pure ASCII. Presumably the tmux maintainers had good reasons for not implementing support for ISO 8859.

**Comment by krader1961** [comment]
Also, I bet tmux's predecessor, screen, supports ISO 8859 so there's always that option if you really need to use obsolete standards from the late 1980's.

**Comment by krader1961** [comment]
@h3xx: You commented by adding the "confused" emoji to both of my comments without any additional comment on your part. So I am confused why you are "confused" :-)

Do you still believe that ISO 8859 encodings (such as "latin1") can still be supported by tmux while also supporting UTF-8? Or are you claiming that tmux should not support UTF-8 when the locale is a ISO 8859 locale such as "latin1"? The former is impossible. The latter is possible from a strictly technical perspective. However, doing so will result in many problems from a practical perspective; e.g., other tmux users being confused by its behavior.

**Comment by nicm** [comment]
Yes and the person being surprised and annoyed is me. UTF-8 is annoying
enough on it's own and supporting all the other charsets is worse (it is
not just a matter of passing them through). UTF-8 is now widely enough
adopted that supporting it alone is practical.

**Comment by AmokHuginnsson** [comment]
@krader1961, @nicm, sorry guys but what you did removing support for ISO 8859 encodings was very uncool. I like ISO-8859-2 encoding and use it exclusively everywhere. And at the same time I do not like UTF-8. What you did is forcing me to either switch to UTF-8 or stop using tmux entirely. And I do not like the idea of being forced to change my preferred encoding for one program. Are there any chances to revert this change? Or should I look for tmux alternative?

**Comment by krader1961** [comment]
@AmokHuginnsson, I didn't change anything as I'm not a maintainer of tmux. But, for what it's worth, the fish shell project, where I am a core dev, will be switching from using wide characters to using UTF-8 internally in the future. When we do so we might support ISO 8859-1 (only because doing so is borderline trivial) but don't intend to support any other ISO 8859 variants or other coding schemes (e.g., shift-JIS).

It's a Unicode world. Unicode is the only sane character coding standard which means UTF-8 for exchanging data between programs. I think you're going to have a hard time convincing @nicm to add support for ancient standards that were a PITA to deal with when they were widely used and are now historical footnotes (or well on the way to being such).

**Comment by h3xx** [comment]
I have half a mind to fork and create a 2.1 maintenance branch that receives only patches from upstream.
