### ISSUE TITLE
tmux -2 gets stuck in bright colors on linux-console

### ISSUE THREAD

**Issue by 9001** [tmux/tmux#3976]
the following printf produces incorrect colors when tmux is running in 256color mode (`tmux -2u`):

```bash
printf '\033[91mbri \033[31mreg \033[22;31mreg \033[0m.\033[31mreg \n\033[31mreg\n'
printf 'TERM=%s\n\n' "$TERM"
```

This reproduces on all `linux` consoles, both bios/uefi, both with/without nomodeset.

I have tested this on archlinux 2024.05.01 (tmux 3.4 with 43e5e80343185e69a1b864fc48095ede0b898180 reverted, [buildscript](https://gitlab.archlinux.org/archlinux/packaging/packages/tmux/-/blob/7862ac7606e532d8573a1c683734c702d348b937/PKGBUILD)) and alpine 3.19.1 (tmux commit fbe6fe7f55cfc2a32f9cee4cb50502a53d3ce8bb, [buildscript](https://git.alpinelinux.org/aports/tree/main/tmux/APKBUILD?id=3f1b530bf82bd7a5cec403ad3f396529c93298a5)), and am seeing the same behavior on both:

![tmux-2bug-arch-or8](https://github.com/tmux/tmux/assets/241032/dd980492-a03c-4131-bbf7-475828f8d677)

`\033[91mbri \033[31mreg` prints incorrectly also outside of tmux, but `\033[22;31mreg` gets it back to regular non-bright colors, with the same correct behavior both outside tmux and inside tmux without `-2`. However, `tmux -2` gets stuck in bright colors for the rest of the line.

Additionally, after detaching and reattaching (both using `tmux -2`), the issue now spreads to the remaining lines as well, no longer confined to just the line with the bright color.

`uname -sp && tmux -V && echo $TERM` on alpine-3.19.1:
Linux unknown
tmux next-3.4
linux

`uname -sp && tmux -V && echo $TERM` on archlinux-2024.05.01:
Linux unknown
tmux 3.4
linux

$TERM inside tmux: tmux-256color
$TERM outside tmux: linux

tmux logs [tmux-lincon-bright.zip](https://github.com/tmux/tmux/files/15283014/tmux-lincon-bright.zip) were made on archlinux using `tmux -vv -Ltest -f/dev/null -2 new` and only covers the initial new-session, `bash a`, and detach, not the reattach

**Comment by nicm** [comment]
This is not very clear. SGR 22 does not turn off aixterm bright colours (SGR 91), it only turns off bold (SGR 1). Compare in xterm:

![Screenshot 2024-05-13 at 12 33 22](https://github.com/tmux/tmux/assets/304243/5d8e6ad1-084c-4c98-8de2-370fd2224862)

Do you have an example of the problem that does not involve SGR 22?

**Comment by 9001** [comment]
yes, the following also reproduces the same issue: `printf '\033[96mbri \033[0;36mreg\n`

**Comment by nicm** [comment]
OK please show a screenshot of that inside tmux for you and the server log from running just that command.

**Comment by 9001** [comment]
Alright :+1: here's the new logs and the screenshot; I also included a separate run without `-2` in case it could be useful to diff

[tmux-lincon-bright-v2.zip](https://github.com/tmux/tmux/files/15300757/tmux-lincon-bright-v2.zip)

![tmux-2bug-arch-v2-or8](https://github.com/tmux/tmux/assets/241032/f9210b2b-ee72-452e-961d-e20829e3d41d)

**Comment by nicm** [comment]
OK so if you do not give `-2` tmux assumes the terminal does not support aixterm bright colours (it thinks all terminals with < 16 colours don't, it only checks `AX` for SGR 39 and 49), so it is using bold:
~~~~
\033[31m\033[1mbri \033[m\033[31mreg
~~~~
tmux assumes that all 256 colours support aixterm bright colours, so when you give `-2`, it uses them and sends:
~~~~
\033[91mbri \033[31mreg
~~~~
But it appears your terminal has a bug - when the colour is changed away from an aixterm bright colour, it is changing to the bright variant of the new colour. I assume this is because it does not really have separate bright colours but is instead implementing them by using the same flag as SGR 1 and simply does not clear the flag correctly when it sees the SGR 31.

I don't think there is a workaround for this without code changes, except maybe by inserting `\033[22m` (assuming the terminal supports it) into `setaf`.

It would be nice to have a way to disable bright colours, since your terminal doesn't really support them it wouldn't make any difference. The best way would probably would be to make tmux check `AX` (and make it implicitly add `AX` if `colours` >= 16), then it would be enough to include `linux*:AX@` in `terminal-overrides` (we could do this by default).

**Comment by 9001** [comment]
Thanks for narrowing this down! Yeah this looks like a linux bug, nice.

I tried to patch `setaf` by editing the `linux` terminfo, but it doesn't seem to take effect in tmux. What I did was decompile the original definition with `infocmp linux`, then edit and rebuild with `tic`. But even if I make `setaf` something like `\E[0;33m` it doesn't affect the output in tmux. I can see that tmux reads my modified terminfo with strace, and I also tried to edit the other terminfo that I see tmux loading, `screen-256color`.

However I can confirm that the change does take effect for some other programs, for example vim, where everything is now yellow.

I'm guessing I misunderstood and you had another approach in mind? And maybe I should mention that the program that generates the initial escape sequences does not rely on termcap, it's all handwritten escape sequences.

**Comment by 9001** [comment]
> Did you restart tmux entirely after installing with tic?

Yep, even did a full reboot just to be absolutely sure 👍

> you may end up turning off bold when you want it on

I guess the "good" news is that the terminal doesn't support bold text in the first place (at least with the default font) so that's not a concern in my case hehe

**Comment by nicm** [comment]
If you run `infocmp` do you see your changes? Are tmux and infocmp linked against the same ncurses libraries?

**Comment by 9001** [comment]
can confirm that infocmp says `setaf=\E[0;33m` both with `TERM=linux` and `TERM=screen-256color` on alpine, and for `TERM=linux` and `TERM=tmux-256color` on archlinux, and yes, both infocmp and tmux are linked to `/usr/lib/libncursesw.so.6` according to `ldd`.  I am also seeing the same behavior both on archlinux and alpine.

there is an interesting difference however; when running tmux without `-2` it *does* have an effect, in the sense that everything has become grayscale; it only does white and bright-white, not the expected everything-is-yellow. But `tmux -2` is entirely unaffected by the change

**Comment by nicm** [comment]
Oh sorry, I think with -2 tmux might override or ignore setaf because obviously if you need -2 you are telling it the external terminfo entry is not capable of 256 colours.

**Comment by nicm** [comment]
tmux knows that sending `\033[31m` will change the colour so it does not send `\033[0m` if only the colour has changed (no attributes). But that's an idea, we could just make it send SGR 0 if the current colour is an aixterm colour and the new one isn't, something like this:
~~~~
diff --git a/tty.c b/tty.c
index 0a6780f6..35df4ac5 100644
--- a/tty.c
+++ b/tty.c
@@ -2972,6 +2972,15 @@ tty_colours_fg(struct tty *tty, const struct grid_cell *gc)
        struct grid_cell        *tc = &tty->cell;
        char                     s[32];

+    /*
+     * If the current colour is an aixterm bright colour and the new is not,
+     * reset because some terminals do not clear bright correctly
+     */
+    if (tty->cell.fg >= 90 &&
+        tty->cell.bg <= 97 &&
+        (gc->fg < 90 || gc->fg > 97))
+        tty_reset(tty);
+
        /* Is this a 24-bit or 256-colour colour? */
        if (gc->fg & COLOUR_FLAG_RGB || gc->fg & COLOUR_FLAG_256) {
                if (tty_try_colour(tty, gc->fg, "38") == 0)

**Comment by 9001** [comment]
Yeah, that would work -- although it would also clear the background color...

How about sending `\033[22m` instead, since that correctly unsets the bright-flag on this particular terminal?

It should be a no-op on terminals which have the correct behavior, so I don't immediately see any issues with always doing that, even though it is only strictly necessary when running tmux with `-2`, since `printf '\033[91mbri \033[31mreg'` gives the correct output when tmux uses the `linux` terminfo, and `printf '\033[91mbri \033[22;31mreg'` works outside of tmux -- and should have worked with `tmux -2` as well, if it wasn't for tmux (presumably) eating the `22m`.

**Comment by nicm** [comment]
There is no terminfo capability for 22 so we would have to add one and it isn't worth it.

tmux will set the background colour again if it is not default after SGR 0.

**Comment by 9001** [comment]
> tmux will set the background colour again if it is not default after SGR 0.

oh nice, sounds like a good idea then :+1:

**Comment by nicm** [comment]
Does the change above fix the problem for you?

**Comment by 9001** [comment]
Sorry to say, but not quite. The following now works as intended:
* `printf '\033[96mbri \033[36mreg\n'`
* `printf '\033[96mbri \n\033[36mreg\n'`
* `printf '\033[96mbri \033[0m\n\033[36mreg\n'`

however, there appears to still be edgecases, at least including these:
* `printf '\033[96mbri\033[K\n\033[36mreg\n'`
* `printf '\033[96mbri\033[J\n\033[36mreg\n'`

here's the log for `\033[K`: [tmux-lincon-bright-v3.zip](https://github.com/tmux/tmux/files/15327309/tmux-lincon-bright-v3.zip)

**Comment by nicm** [comment]
This is because tmux is just setting the default colour (SGR 39) which apparently doesn't really turn off bright either. Try this instead [tmux-sgr0-bright.diff.txt](https://github.com/tmux/tmux/files/15434161/tmux-sgr0-bright.diff.txt) which always uses SGR 0 if no `AX` and removes `AX` from `linux*`.

**Comment by 9001** [comment]
Finally had a chance to test the patch, and it seems to work great :+1: 

Feel free to close this issue unless you can think of some other edgecases I should try :>

And thanks for maintaining tmux btw, not sure what I'd do without it hehe

**Comment by nicm** [comment]
I have applied this now, will just have to hope it does not cause problems with any other terminals now! Thanks!
