### ISSUE TITLE
Cursor position sometimes incorrect in LXC

### ISSUE THREAD

**Issue by tatokis** [tmux/tmux#4116]
### Issue description

Using tmux inside an LXC container (through lxc-attach) sometimes results in the cursor being in the wrong position, resulting in confusing and garbled text being shown, especially in text editors.

### Required information

```
$ tmux -V # c36ffcbe
tmux next-3.5
$ uname -sp
Linux x86_64
outside-tmux$ echo $TERM
xterm-256color
inside-tmux$ echo $TERM
tmux-256color
```

[tmux-client-2807737.log.gz](https://github.com/user-attachments/files/16923637/tmux-client-2807737.log.gz)
[tmux-out-2807739.log.gz](https://github.com/user-attachments/files/16923638/tmux-out-2807739.log.gz)
[tmux-server-2807739.log.gz](https://github.com/user-attachments/files/16923639/tmux-server-2807739.log.gz)

The steps to reproduce this issue are a bit complicated:
First, an LXC container needs to be set up. (**NOT** LXD, which has an `lxc` command. Unsure if affected.)

In this case, I am using an Arch Linux container. Ensure nano and tmux are installed in the container.

1. `sudo lxc-attach container_name`
2. `echo -e "Hello\nGoodbye World!" > test`
3. `nano test`
4. Press the right arrow key until the cursor goes past the end of the first line and on to the second one (6 presses).
5. Press any key to type a single character (`1` for example)
6. Press the left arrow twice so that the cursor moves to the line above
7. Press the down arrow to move the cursor one line below. Notice how it has moved to the start, but nano thinks it's in the same column.
8. Type another key (`2` for example)
9. Notice how the text is garbled. (Depending on the case, I've seen it shift characters to the right while typing as would be expected, causing confusion since editing takes place in the wrong column.)
![nano garbled text](https://github.com/user-attachments/assets/8451f79c-d97f-4a3b-b842-f644430ec7ee)
10. Save, exit, `cat test` and notice it actually says `1Good2bye World!`

When performing the above procedure without being inside tmux, in step 7 the cursor remains in the same column when moving to the second line.

**Comment by nicm** [comment]
What terminal are you running this in?

**Comment by tatokis** [comment]
Reproduced in gnome-terminal on Ubuntu {20,22}.04, but it also happens with urxvt on Arch.

**Comment by tatokis** [comment]
It still occurs, unfortunately.
```
# tmux kill-server
no server running on /tmp/tmux-0/default
# cat ~/.tmux.conf 
set -as terminal-overrides '*:csr@'
```
and then ran `tmux`.

I am confident it is reading the config file because if I type a random string in it, it throws an error.
```
/root/.tmux.conf:2: unknown command: randomstring
```

**Comment by nicm** [comment]
I suspect `lxc-attach` is translating `\n` to `\r\n`, or perhaps it does not correctly handle `tcsetattr` and the tty is?

That would explain why the cursor moves to the start of the line when you press the Down key, because tmux is sending `\n`:
~~~~
1725827038.665491 writing key 0x400000010e1a9 (Down[C]) to %0
...
1725827038.665661 input_parse_buffer: %0 ground, 21 bytes: \033[?25l\033[34h\033[?25h\033[3d
...
1725827038.665739 server_client_reset_state: cursor to 5,2
1725827038.665743 /dev/pts/5: \n
~~~~
And `vt220` has `cud1` as `\n` but `ansi` does not:
~~~~
$ infocmp -x vt220 ansi
...
cud1: '\n', '\E[B'.
~~~~
Try sending this outside tmux:
~~~~
stty raw; printf 'Hello\nWorld\r\n'; stty sane
~~~~
It should look like this:
![Screenshot 2024-09-10 at 16 51 13](https://github.com/user-attachments/assets/a659a605-04ef-4924-9bce-7d836a26fe28)

**Comment by tatokis** [comment]
Sure enough:
![stty_raw_hello_world](https://github.com/user-attachments/assets/0b6d63c6-e673-4be9-96c2-24488d0445a8)

Looks like this is a bug in lxc then.

**Comment by nicm** [comment]
Yes you will need to report it to them.
