### ISSUE TITLE
How to customize a pane border for SSH connection?

### ISSUE THREAD

**Issue by saindo** [tmux/tmux#4224]
tmux 3.0a on Ubuntu 20.04; $TERM :xterm-256color | screen

Target:
When, or upon, I log onto a remote host by SSH, 

1. I want to set the bg color of current pane to "yellow". 
(Now I'm setting option right before SSH command in Bash. Of coz the bg color remains yellow after I log out.)

2. Also, I've already included #T in pane title with "set -g  pane-border-format", but I still want to set the fg color of current pane title to something like fg="red blink". Here #T always matches with #{m:*Remote*,#T} when SSH logged in.
(I tried #{?#{m:*Remote*,#{P: #T } },red,default}, but it did not work. 

After I log out from the remote host, I want to reset this pane back as it was before.

Please help me with achieving this. TKS!

**Comment by nicm** [comment]
I'm not sure there is a way to set this using an expression in `window-style` because it is not evaluated often enough, so you will either need to use one of the hooks (maybe `window-renamed`, not sure which would work) or - perhaps easier - by making a wrapper shell function or script around SSH that issues the tmux commands you want.
