### ISSUE TITLE
High CPU usage when dealing with programs generating very long lines

### ISSUE THREAD

**Issue by depesz** [tmux/tmux#423]
I originally encountered the problem when using pg_basebackup - tool to setup copy of PostgreSQL database, but this perl script does similar thing:

```
#!/usr/bin/env perl
use strict;
$|++;
my $i = 0;
while ($i < 1202434182) {
    print "\r $i/1202434182 kB (x%), something else, text filler ";
    $i+=int(rand() * 5 + 1 );
}
```

When I run it within tmux, cpu usage of tmux server skyrockets. What's worse, after the script will be terminated, cpu keeps being highly used, and decreases (cpu usage) very slowly.

With this syntetic test is behaves actually slighly better, but when I was running 4 pg_basebackups in separate windows in tmux, for ~ 10 hours, then cpu usage was high even many hours later, even when windows that ran pg_basebackup were already closed.

I checked, and similar effect was observable from simple "rxvt" or "xterm" terminal emulators, though not from "konsole".

I will be filling a bug in pg_basebackup too, as it's output rate is definitely too high, but perhaps something could be done in tmux itself?

I see this problem in tmux 2.2, on kubuntu xenial.

**Comment by depesz** [comment]
Checked, and it looks that single pg_basebackup generates progress information with rate of 320KB/s - i.e. ~320000 characters per second.

**Comment by depesz** [comment]
To further help with the problem, repeating it, I modified the script to be:

```
#!/usr/bin/env perl
use strict;
my $top=1000000;
$|++;
my $i = 0;
while ($i++ < $top) {
    print "\r $i/$top kB (x%), something else, text filler ";
}
```

Running it as:

time ./bad.pl

in clean "konsole" took 1.3s. In rxvt - 1.1s. In tmux - 36 seconds.

**Comment by nicm** [comment]
Please try this which should help your case: 
[x.txt](https://github.com/tmux/tmux/files/284176/x.txt)

Random strings will still be slow, I'll have a look at that later, I think there is something funny going on.

**Comment by nicm** [comment]
Here is another diff with some additional improvements: [xx.txt](https://github.com/tmux/tmux/files/286187/xx.txt)

**Comment by depesz** [comment]
The patch (xx.txt) doesn't apply to 2.2 sources, and also doesn't seem to apply to current (fetched now) github repo. Sorry - how do I test it?

**Comment by nicm** [comment]
Yes you were too slow and I had already applied some of it ;-). Please try this one [x.txt](https://github.com/tmux/tmux/files/289162/x.txt). It will only apply against Git master.

**Comment by depesz** [comment]
It's much better now.

My bad.pl from couple of comments ago (the one with my $top=1000000;), in old tmux:

```
=$ time perl bad.pl 
 1000000/1000000 kB (x%), something else, text filler 
real    0m36.489s
user    0m0.404s
sys     0m0.760s
```

in konsole:

```
=$ time perl bad.pl 
 1000000/1000000 kB (x%), something else, text filler 
real    0m1.207s
user    0m0.352s
sys     0m0.812s
```

in tmux from git head with latest patch:

```
=$ time perl bad.pl 
 1000000/1000000 kB (x%), something else, text filler 
real    0m8.359s
user    0m0.380s
sys     0m0.908s
```

**Comment by depesz** [comment]
I ran also "tmux new-session 'perl bad.pl'" via perf. And this is its report (top 10 lines):

```
Overhead  Command       Shared Object          Symbol
  16.84%  tmux: server  libc-2.23.so           [.] __strcmp_sse2_unaligned
   7.28%  tmux: server  tmux                   [.] options_tree_RB_FIND
   6.78%  tmux: server  tmux                   [.] screen_write_cell
   4.93%  tmux: server  tmux                   [.] input_parse
   4.26%  tmux: server  tmux                   [.] tty_write
   3.99%  tmux: server  libevent-2.0.so.5.1.9  [.] evbuffer_add
   3.80%  tmux: server  tmux                   [.] grid_set_cell
   3.00%  tmux: server  tmux                   [.] grid_get_cell
   2.67%  tmux: server  tmux                   [.] tty_putc
   2.60%  tmux: server  tmux                   [.] options_find
```

**Comment by nicm** [comment]
OK, I have had to drop some of the optimizations I made because I don't think they are safe.

I have applied the other ones, and an additional bit to cache the window style options.

Here is the only change I have left outstanding right now, but it is the one that makes the most impact. I need to decide what to change it to.

If you wait a couple of hours for Git master to sync up (you will see a commit with your name in), then you can try that.

~~~~
Index: tmux.h
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tmux.h,v
retrieving revision 1.632
diff -u -p -r1.632 tmux.h
--- tmux.h	30 May 2016 09:50:20 -0000	1.632
+++ tmux.h	30 May 2016 09:52:58 -0000
@@ -60,7 +60,7 @@ struct tmuxproc;
 #define NAME_INTERVAL 500000
 
 /* The maximum amount of data to hold from a pty (the event high watermark). */
-#define READ_SIZE 128
+#define READ_SIZE 4096
 
 /* Attribute to make gcc check printf-like arguments. */
 #define printflike(a, b) __attribute__ ((format (printf, a, b)))

**Comment by depesz** [comment]
Will do, thank you.

**Comment by depesz** [comment]
I see commit with my name in https://github.com/tmux/tmux/commit/36ab4c7c49d8ffbde113048acb8a6a05ceb00fdc. compiled, ran test - 10.9s

then I made the change you mentioned in previous comment (larger read_size) - with this change, time used: 9.7s

**Comment by depesz** [comment]
full output of bad.pl is 53888896. Assuming that newest tmux, with patch, can output it in 9.7s, it means it does it at 5.3MB/s. What dark magic can konsole do to achieve over 36MB/s ?!

**Comment by nicm** [comment]
Konsole is in a much better position to optimize because it is drawing
directly to the screen with GUI primitives. tmux has to not only update its
own internal screen but also send anything that has changed to Konsole and
wait for it to draw it. So you are not comparing like with like in the
first place and I expect tmux will always be a bit slower, although how
much slower I am not sure. How long does tmux take if you run it detached
with eg:

tmux new -d 'time perl bad.pl; sleep 1000'

Then wait long enough for it to finish and then tmux attach to see the time.

Possibly Konsole is batching changes together (because clearly the 1% print
will shortly be replaced by 2%, if we wait for a bit we could probably drop
the 1% entirely and it is going so fast you wouldn't notice). That would be
an obvious optimization, but tmux is not really set up to do that, and I'm
not sure if would be worth the complexity for general use. We would need to
make some sort of changeset system. It would be complicated by the fact
that we are not just replacing individual cells, we also want to use the
terminal features to clear entire lines etc. Still maybe worth looking at
at some point.

**Comment by nicm** [comment]
We would not even have to explicitly wait, we could just batch across one
read(). But the changes needed would be the same.

**Comment by depesz** [comment]
re: tmux/detached: real    0m2.328s

**Comment by depesz** [comment]
OK. I guess current is "better enough"

**Comment by nicm** [comment]
Here is another diff that skips writes to the same cell within the same read(): [tmux-dirty.diff.txt](https://github.com/tmux/tmux/files/344465/tmux-dirty.diff.txt)

I tried to do a full changes system where we track everything that has changed and skip updating the grid as well as the tty, but it becomes too slow quite quickly without lots of huge and complicated data structures. So this is a lot simpler, it continues to update the grid but just marks each cell as changed rather then writing it to the tty. It waits to do the write until either it is finished with the read() or it hits something that requires the tty to be up to date (scrolling, for example). I also removed the previous is-this-the-same checking because if we aren't going to write to the tty anyway, then reading the cell back from the grid all the time is slower than just writing it again. Also a couple of other minor optimizations.

**Comment by nicm** [comment]
It is not that much faster with your original test because basically it is ending up writing the same thing as before:

$ time (perl bad.pl;echo)
 1000000/1000000 kB (x%), something else, text filler
    0m05.20s real     0m01.14s user     0m01.17s system
$ time (perl bad.pl;echo)
 1000000/1000000 kB (x%), something else, text filler
    0m07.31s real     0m01.24s user     0m01.11s system

But it is substantially faster with a file that just swaps between writing two different different strings ([test.txt.bz2.txt](https://github.com/tmux/tmux/files/344469/test.txt.bz2.txt)):

$ time (cat tmp/test.txt; echo)
123456123456123456123456123456123456123456
    0m04.11s real     0m00.00s user     0m00.31s system
$ time (cat tmp/test.txt; echo)
123456123456123456123456123456123456123456
    0m22.02s real     0m00.00s user     0m00.30s system

**Comment by nicm** [comment]
Here is another diff which brings back the skip code, but improved so it doesn't need to do a full read of the grid cell in most cases: [tmux-dirty-skip.diff.txt](https://github.com/tmux/tmux/files/344482/tmux-dirty-skip.diff.txt)

This is probably the best of both worlds, it is a little slower with the scripts but I think there are more real world opportunities for skipping characters that are already on screen than programs that try to write twice to the same cell.

**Comment by nicm** [comment]
Here is latest and probably final version: [tmux-dirty-skip-2.diff.txt](https://github.com/tmux/tmux/files/344623/tmux-dirty-skip-2.diff.txt)

**Comment by depesz** [comment]
WOW. This patch is simply great.

Comparison, bad.pl:

- tmux 2.1: 36 second
- konsole: 1.3s
- tmux git head + patch from above comment: 1.6s

**Comment by nicm** [comment]
Applied now, thanks.
