### ISSUE TITLE
Tmux does not start a shell when a nameless environment variable is present

### ISSUE THREAD

**Issue by Jasu** [tmux/tmux#425]
Linux 4.5, Tmux 2.2, no tmux.conf, shell is zsh.

The following command hangs, requiring killall -9 tmux. The green info bar shows, but the shell does not start. I can create new windows with Ctrl+b c, but they start without shell too.

env "=Hello" tmux

After running the command, there are three tmux processes:

jasu      3075  0.0  0.0  20772  2932 pts/10   S+   10:52   0:00 tmux
jasu      3077  0.2  0.0  23164  3232 ?        Ss   10:52   0:00 tmux
jasu      3078  100  0.0  23164   584 pts/1    Rs+  10:52   0:04 tmux

**Comment by nicm** [comment]
Well, this is a bug somewhere, I would say either in glibc or GNU env(1). glibc will not allow you to manipulate an variable in environ with an empty name using setenv/putenv/unsetenv. But you can set up such a variable using env.

But in any case, we can get around this, because there is a way to clear the environment without using unsetenv. Please try this: 
[x.txt](https://github.com/tmux/tmux/files/283880/x.txt)

You will lose any variables with empty names inside tmux but they are not useful anyway.

**Comment by Jasu** [comment]
Thanks, the patch works like a charm!

putenv actually lets you set one with an empty name, compiled with gcc 6.1.1 and glibc 2.23-4 from Arch repos. setenv/unsetenv do not work with an empty name. Posix mentions setenv and unsetenv failing with an empty name, but not putenv.

The bug causing this in the first place is most likely in LilyTerm, I'll try to debug it later...

**Comment by nicm** [comment]
Yes, you are right, I checked putenv but I must have read the code wrong.

**Comment by nicm** [comment]
Fixed thanks.
