### ISSUE TITLE
Cursor won't re-appear when using tput 

### ISSUE THREAD

**Issue by sheerun** [tmux/tmux#429]
How to reproduce:

Env: OSX 10.10, newest iTerm 2.9.20160523 (or Terminal app), zsh 5.2 (or bash 3.2)

1. Launch tmux
2. `tput civis`
3. `tput cvvis`

As changing type of terminal of shell doesn't make the problem go away, the issue is most likely with tmux. I use default configuration (i.e. no .tmux.conf or .zshrc files). 

Related issue: 

https://github.com/tj/git-extras/issues/538

**Comment by nicm** [comment]
cvvis is very visible are you sure it sends something useful? Perhaps you
want cnorm.

How to reproduce:

Env: OSX 10.10, newest iTerm 2.9.20160523 (or Terminal app), zsh 5.2 (or
bash 3.2)

   1. Launch tmux
   2. tput civis
   3. tput cvvis

As changing type of terminal of shell doesn't make the problem go away, the
issue is most likely with tmux. I use default configuration (i.e. no
.tmux.conf or .zshrc files).

Related issue:

tj/git-extras#538 <https://github.com/tj/git-extras/issues/538>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/429>, or mute the thread
<https://github.com/notifications/unsubscribe/AASkc_nDG1EVQYJdD8YnKJG_RV9z0RWXks5qGDQZgaJpZM4IpEIx>
.

**Comment by sheerun** [comment]
`tput cnorm` shows cursor again, so that solves part of my issue, thanks

On the other hand `tput cvvis` still works without issues without tmux and fails to restore when in tmux.

**Comment by nicm** [comment]
It is not a requirement that cvvis restore the cursor, and tmux doesn't support very visible cursor in any case.

**Comment by nicm** [comment]
Actually, I lie, we do support it. But it is not required that it turn the cursor visible.

**Comment by nicm** [comment]
You can see in xterm terminfo:

$ TERM=xterm tput cvvis|cat -v
^[[?12;25h

cvvis turns the cursor very visible (SM ?12) and on (SM 25).

But in screen and tmux terminfo:

$ TERM=tmux tput cvvis|cat -v
^[[34l

It just turns the cursor very visible (SM 34, which is the same as ?12).

**Comment by sheerun** [comment]
So the issue is with tput? Do you maybe know where to file an issue?

**Comment by sheerun** [comment]
By the way, I'm not using `tmux` as term, but `screen-256color` (set in tmux.conf). The result is the same htough, instead `^[[?12;25h` it outputs `^[[34l`.

**Comment by nicm** [comment]
You could talk to the ncurses-bug ML and see if the screen and tmux
terminfo entries (and no doubt there are others) should be changed, but
even if it is changed it will be years before updated terminfo databases
make their way out to most platforms. It is clear that you cannot rely on
cvvis implying cnorm and assuming that it will is a mistake.

**Comment by sheerun** [comment]
ok, fair enough. thank you for support. I pinged author or git-extras to replace cvvis with cnorm

**Comment by sheerun** [comment]
It helped when I changed following:

```tmux
set -g default-terminal "screen-256color"
```

to 

```tmux
set -g default-terminal "xterm-256color"
```

**Comment by nicm** [comment]
This may cause you problems with other programs. If it does please do not
report that here unless you can reproduce with screen-256color :-).
