### ISSUE TITLE
Support libsixel

### ISSUE THREAD

**Issue by HalosGhost** [tmux/tmux#44]
I would love to see support for [libsixel](https://github.com/saitoha/libsixel) in tmux. While I recognize that this is not something that tmux can do unless the underlying terminal supports it, at the moment, there does not seem to be a way to have sixel function at all within tmux.

**Comment by nicm** [comment]
I think this is extremely unlikely to happen.

**Comment by HalosGhost** [comment]
Not to be rude, but may I ask why?

**Comment by nicm** [comment]
I am not interested in graphics in the terminal and there are few practical uses for them anyway. Even if you come up with a diff, unless it is very small it would be very difficult to convince me it'd be worth it. But I wouldn't discourage you from working on it, just don't expect it to end up in tmux, it'd have to be a fork.

**Comment by HalosGhost** [comment]
Fair enough; well I will look into what it would take to implement it myself, and I hope you change your mind about it in the future. Thanks for the consideration in the meantime! :smile:

**Comment by saitoha** [comment]
@HalosGhost I wrote a convenient patch for tmux.
https://gist.github.com/saitoha/ad59c1c4be095accaf4e

It doesn't provide the entire support of SIXEL graphics, but it is enough for me.
It doesn't work on XTerm because It requires left-right margin terminal feature (VT class 4, DECLRMM, DECSLRM). Its default mode (VT420 mode = class 4) conflicts SIXEL graphics feature.
mlterm and RLogin can enable both of them at the same time, so I tested it on them.
Then you have to add the following line to your .tmux.conf.
```
set -ga terminal-overrides ',xterm*:smglr=\E7\E[?69h\E[%i%p1%d;%p2%ds\E8:mgc=\E7\E[?69l\E8'
```

**Comment by HalosGhost** [comment]
It seems this patch does not manage to offer support for sixel in tmux through yaft unfortunately; but I appreciate your effort!
