### ISSUE TITLE
split-window IDs mix up when splitting using -t option

### ISSUE THREAD

**Issue by markmcb** [tmux/tmux#441]
From a terminal, I execute:
```
tmux split-window -v -t SESSION:WINDOW.1
tmux split-window -v -t SESSION:WINDOW.2
```

I expect pane ids as follows:

```
|-------------|
|      1      |
|-------------|
|      2      |
|-------------|
|      3      |
|-------------|
```

I get: 
```
|-------------|
|      1      |
|-------------|
|      3      |
|-------------|
|      2      |
|-------------|
```
If I've provided a command, it is executed in the correct window, so it seems only the IDs are misplaced.

When I manually split them using hotkeys the IDs are assigned as expected.

**Comment by markmcb** [comment]
Possibly relevant, I have in my .tmux.conf:
`setw -g pane-base-index 1 `

**Comment by markmcb** [comment]
Oh, and I'm on v2.1 packaged with Fedora 23.

**Comment by nicm** [comment]
I am pretty sure you are missing out a step here, because if you do
exactly as you described, you will get 1,2,3. I think you are missing
out the bit where you change the active pane back to pane 1 before you
run the command to split pane 2.

In any case, new panes are inserted in the list after the active pane,
regardless of which pane is being split.

I have a feeling I changed this before but the person didn't test the
fix, or we decided it didn't matter.

**Comment by markmcb** [comment]
After the active pane? Hmmm. Well I guess the bit I left out is I use this in a boot-time script to get everything set up, so I was thinking -t would allow me to reference the panes as needed. The split seems to work as expected, but the ID assignment isn't obvious (and it doesn't seem to be noted in the man page).

So it sounds like I'd need to add a few select-pane commands in my script to make it do what I expect. Let me try and I'll report back.

**Comment by markmcb** [comment]
Ah ha, I was using the -d option in my script, which wasn't making the split active. So either removing -d or using select-pane works. Thanks for the help.
