### ISSUE TITLE
Refreshing Tmux Status After Process Exits

### ISSUE THREAD

**Issue by twodee** [tmux/tmux#454]
When I execute a command like `mutt` or `vim`, the name of the executable appears in the `tmux` status bar, replacing the `1:zsh` string telling me the pane number and shell. This is nice.

However, when I exit these child processes, the status is not restored to `1:zsh` until I execute another action or wait for the default status interval of 15 seconds to elapse. I want the status bar to reflect the current foreground process. How can I update the status bar to revert back as soon as the child process exits?

I know I can set the status interval to a shorter time with something like this:

    set status-interval 5

But I don't need faster updates. Just one update at the right time.

I tried using precmds in `zsh` to force a refresh before the new command prompt appears:

    function precmd() {
      tmux refresh-client -S
    }

I verified that this function ran, but the status was not refreshed.

Tmux is v2.1 or v2.2, installed via homebrew and running under OS X 10.11. I did not experience this delay in 1.9a or 2.0.

**Comment by nicm** [comment]
Are you using automatic-rename or is your shell doing the renaming?

**Comment by twodee** [comment]
My zsh configuration is all self-written and doing nothing. I have this in `tmux.conf`:

    setw -g automatic-rename on

Interestingly, I tried querying the value with this line at the `tmux` command prompt:

    show-window-options automatic-rename

When the option is off, I get a listing that shows the option as being off. When the option is on, I see no result whatsoever.

**Comment by nicm** [comment]
tmux should update the window name with automatic-rename when the active pane sees output, and at most once every half a second. Are you saying that if you do exactly this:

tmux -Ltest -f/dev/null new
top

Then wait until the name changes to "top", then exit top - the name does not change back for 15 seconds?

**Comment by nicm** [comment]
I can't reproduce this, but I wouldn't be surprised if it can happen. There is of course a race between any output that is happening while or after the process in the pane is exiting and tmux updating the name. If tmux sees the final output and reads the name before the process has actually exited, it will get the old name and not check again until there is further output in the pane. status-interval should be irrelevant though, redrawing the status line is not related to automatic-rename (which is why refresh -S doesn't help).

The easiest way to force automatic-rename to update manually is to just do:

tmux setw -u automatic-rename

**Comment by twodee** [comment]
Regarding the `top` test, the behavior is as you say. (Though the label appears as `which` for whatever reason.) The label persists after the process exits until I take further action.

Putting the `tmux setw -u automatic-rename` in zsh's precmd sadly does not update the status bar either.

**Comment by nicm** [comment]
I guess zsh is running it too early.

**Comment by kurko** [comment]
I see the same behavior on 2.8 and bash. Same behavior with `vim`, or even `sleep 5`.
