### ISSUE TITLE
Override allow-rename

### ISSUE THREAD

**Issue by dragonxlwang** [tmux/tmux#455]
I am using oh-my-zsh with tmux. The default of allow-rename is on. And oh-my-zsh is refreshing the title by shortened path or program name. Once I manually set the name, however, tmux still allow title to be renamed by oh-my-zsh. 

This behavior is different from what is with automatic-rename, which would fix the name after manual set of the name.

Is there a way to discard program set name after manual rename?

Thanks,

**Comment by nicm** [comment]
No, but you can set allow-rename off yourself for that window after you
rename it.

I am using oh-my-zsh with tmux. The default of allow-rename is on. And
oh-my-zsh is refreshing the title by shortened path or program name. Once I
manually set the name, however, tmux still allow title to be renamed by
oh-my-zsh.

This behavior is different from what is with automatic-rename, which would
fix the name after manual set of the name.

Is there a way to discard program set name after manual rename?

Thanks,

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/455>, or mute the thread
<https://github.com/notifications/unsubscribe/AASkc6PIaW0uxEr7vc-MAfZaaVwOGMUAks5qMHBxgaJpZM4I20d6>
.

**Comment by dragonxlwang** [comment]
Can you let me know how to disable allow-rename for one window? So that I can bind key with rename-window and disable allow-rename.

**Comment by nicm** [comment]
Use set-option.

**Comment by dragonxlwang** [comment]
I meant to ask how to specify the current window? Should I use something like below?
```
setw -t +0 allow-rename off
```

**Comment by nicm** [comment]
No -t at all

**Comment by dragonxlwang** [comment]
Thanks,
