### ISSUE TITLE
Ctrl-C fails to stop commands spewing output

### ISSUE THREAD

**Issue by ijt** [tmux/tmux#468]
If I run a command such as ls -R / or yes, tmux locks up and won't allow me to stop the process with ctrl-C. I'm using version 2.3.

I tried the solution from Stack Overflow: http://superuser.com/questions/456798/tmux-slow-to-interrupt-process-with-ctrl-c, but the options they describe don't appear to be available anymore.

I wouldn't mind helping out with a fix if someone can suggest a rough idea of a solution.

**Comment by ijt** [comment]
Digging into this a bit, the change that removed the c0-* options (c0-change-trigger and c0-change-interval) is 3f4ee98162cd5bb7000f93fec0e631e123b1281d. I'm going to adjust the settings that are hard-coded in this change to see if that fixes the problem in my environment.

**Comment by ijt** [comment]
Of the three parameters controlling spew in 3f4ee98, there is only one left now: READ_SIZE. I tried repeatedly reducing that by half from 128 until it was down to 4 but it didn't help.

**Comment by ijt** [comment]
I tried again with tmux 1.8 and it responds immediately to ctrl-C, so I'm going back to tmux 1.8 for now.

**Comment by bendikro** [comment]
Has this issue been fixed?

**Comment by mtekp** [comment]
i am on tmux-2.9_a-2 and ctrl + c doesnt work for me. May be I will move to tilix :(

**Comment by krader1961** [comment]
@mtekp Please don't comment on closed issues that are three years old. If you're having a problem open a new issue and link to the issue(s) you think is relevant. Also, it is pretty unlikely your situation has anything to do with tmux since handling [ctrl-C] is normally done by the OS tty driver. You should start by checking the output of `stty -a` to confirm that `intr = ^C` and `icanon isig` are set. If they are then open a new issue and include log files from starting the tmux server with `tmux -vv`.
