### ISSUE TITLE
Seemingly no differentiation between key and shift-key

### ISSUE THREAD

**Issue by izemmouri** [tmux/tmux#478]
Hi,

As I tried to bind M-key and M-Shift-key to 2 different commands, I realized tmux didn't seem to differentiate between keys and shifted keys. I don't know if I'm missing something or if this was the intended behaviour. If it was indeed the intended behaviour, would you mind indicating me which file in the source code is responsible for it?

Best regards

**Comment by krader1961** [comment]
What key are you trying to apply the [shift] modifier to? Because things like [shift]+[enter] don't normally make any sense unless you've done something unusual to your terminal configuration. Try removing the tmux bindings then run `od -tx1z` or `xxd` and press the keys you're trying to bind. I'm betting those commands will show the same sequence of characters with and without the [shift] modifier. In which case there is no way for tmux to distinguish the two cases.

**Comment by izemmouri** [comment]
You opened my eyes. Thank you.
I guess the workaround would be to make my terminal send some escape sequence known to tmux for the [shift]+[enter] combination (like the sequence for a function key, say F3) and then bind F3 to a command in tmux.
Would there be any way to make tmux recognize an arbitrary key sequence that wouldn't conflict with the ones it already knows about? For example, if I made urxvt send "\e0pq" for shift+enter, would there be a way to tell tmux that "\e0pq" is, say, key "Senter", and the bind M-Senter to a command?

**Comment by krader1961** [comment]
Unfortunately tmux only allows single character sequences or a few special key names defined in the terminfo definition. Possibly prefixed with `M-` which simply means an extra escape character is the first char of the sequence. So you can't bind an arbitrary sequence like you can in shells like zsh or fish. So you'll need to reuse the sequence sent by another key (e.g., [F3]).
