### ISSUE TITLE
Mouse resize allow more than needed

### ISSUE THREAD

**Issue by YPetremann** [tmux/tmux#483]
When resizing a pane with mouse, it allow one move more than needed, this result in opposite pane wall to move one character in the opposite direction.

Demonstration : https://asciinema.org/a/6r1bosqk3e2ovtjuwl81rfjz4

**Comment by nicm** [comment]
Is this also fixed by the same patch?

**Comment by YPetremann** [comment]
This is not fixed with the patch of issue #484.

**Comment by nicm** [comment]
If you use the keys then resizing downward will make the pane above smaller if there is no room below. This is intentional. The same happens with the mouse, but it is impossible to keep the mouse stationary when dragging, so if the border line doesn't move, you stop dragging, so you see this effect.

Please try this: [xxx.diff.txt](https://github.com/tmux/tmux/files/438843/xxx.diff.txt)

**Comment by nicm** [comment]
Applied this now.
