### ISSUE TITLE
less doesn’t see the screen above the prompt

### ISSUE THREAD

**Issue by jooadam** [tmux/tmux#492]
Inside tmux opening a file in `less` the screen is cleared, but text is displayed starting on the line formerly below the Bash prompt. Outside of tmux text is displayed starting at the top of the screen.

(Ubuntu 16.04, xterm-256color / screen)

**Comment by jooadam** [comment]
See also: http://stackoverflow.com/questions/34651567/why-less-command-in-tmux-show-output-not-on-beginning

**Comment by krader1961** [comment]
I don't see a difference in behavior. Can you show an example of both behaviors? I recommend using asciinema to capture what is written to the terminal. Note that using the less `-c` flag would seem to produce the behavior you describe when running less "outside of tmux". While running less in both environments enter the characters `-c` and report whether it writes

> Repaint by scrolling from bottom of screen  (press RETURN)

or

> Repaint by painting from top of screen  (press RETURN)

on the less status line.

**Comment by jooadam** [comment]
I don’t really understand what `-c` is supposed to do, but it doesn’t result in the same behaviour outside of tmux. I have attached an [asciinema recording](https://github.com/tmux/tmux/files/390499/tmux-less.json.txt).

**Comment by townba** [comment]
The difference is with the behavior of switching to the alternate screen in the terminal. In some terminal emulators, like GNOME Terminal, the cursor is moved to the home position; in others, like iTerm2 and xterm, it is not. To test this, you can use `tput smcup ; echo foo ; sleep 2 ; tput rmcup`.

**Comment by jooadam** [comment]
@townba Can you elaborate? Why is the difference inside and outside of tmux? By the way, the above was observed using Gnome Terminal.

**Comment by krader1961** [comment]
I played your asciinema recording three times. I see no difference in behavior between the tmux and non-tmux environments. The behavior you're seeing is due to the use of the alternate screen that @townba mentioned. The reason it starts "on the line formerly below the Bash prompt" is because that's how most terminals behave given their initialization string found in the terminfo definition. If the file has fewer lines than the height of the terminal `less` does not move the cursor to the top of the screen unless you've specified the `-c` or `--clear-screen` flag.

Personally I dislike that behavior so I have a `LESS` env var that includes, among other things, `--no-init` to keep it from using the alternate screen. This is not a tmux issue unless I've completely misunderstood your problem and your asciinema recording did not capture the real problem.

**Comment by jooadam** [comment]
You didn’t see the difference because you played it inside tmux :) Play it outside of tmux and you will see the difference :)

**Comment by townba** [comment]
tmux is handling the alternate screen for you. In GNOME Terminal with no tmux, GNOME Terminal handles it.

If you always want programs that use cursor addressing to move the cursor to the home position in tmux, you can create a custom terminfo entry. Put the following into a file called `screen-smcuphome.tic`:

```
screen-smcuphome|VT 100/ANSI X3.64 virtual terminal with smcup home-cursor hack,
        smcup=\E[?1049h\E[H, use=screen,
```

Compile the entry using `tic -a screen-smcuphome.tic`. Make sure it works in tmux by using `TERM=screen-smcuphome less <text file>`.

You can set tmux to always use `screen-smcuphome` instead of `screen` in `.tmux.conf`:

```
set -g default-terminal screen-smcuphome
```

**Comment by townba** [comment]
tmux is handling the alternate screen for you. In GNOME Terminal with no tmux, GNOME Terminal handles it.

If you always want programs that use cursor addressing to move the cursor to the home position in tmux, you can create a custom terminfo entry. Put the following into a file called `screen-smcuphome.tic`:

```
screen-smcuphome|VT 100/ANSI X3.64 virtual terminal with smcup home-cursor hack,
        smcup=\E[?1049h\E[H, use=screen,
```

Compile the entry using `tic -a screen-smcuphome.tic`. Make sure it works in tmux by using `TERM=screen-smcuphome less <text file>`.

You can set tmux to always use `screen-smcuphome` instead of `screen` in `.tmux.conf`:

```
set -g default-terminal screen-smcuphome
```

**Comment by krader1961** [comment]
> You didn’t see the difference because you played it inside tmux.

No, I did not. I replayed it in a fresh iTerm2 terminal. It's a bad idea to make assertions when you have no evidence or at best very weak evidence for your conclusion.

I also played it in a Xquartx xterm terminal and saw no difference in behavior. Which is not too surprising because asciinema simply captures the raw output sequences. Which means that the terminal you replay the capture on can affect what you see.

I uploaded your capture to asciinema.org and you can [replay it](https://asciinema.org/a/86l1d6w4go0serjv14qqgpsvo) for yourself. I still don't see a difference in behavior. Which is probably because your terminal is doing something different than most other terminal implementations. However, having said that I get identical behavior with

```
tput smcup; echo hello; sleep 5; tput rmcup
```

in gnome-terminal and xterm under Ubuntu 16.04 whether or not I'm in a tmux session. So there is something unusual about your environment. Which is almost certainly that your non-tmux terminfo environment does not use the alternate screen capability while tmux does so by default.

If you already have a `LESS` env var add `--no-init` to it; otherwise `export LESS="--no-init"` and see if you get behavior closer to what you want. You might also want to try invoking it as `less -c` (and you can, of course, add that to your `LESS` env var). I don't like the `-c` behavior but YMMV.

**Comment by krader1961** [comment]
Also, there isn't any need to create a custom terminfo file. You can tell tmux to not use the alternate screen and ignore any attempt to do so by adding the following lines to your *~/.tmux.conf* file:

```
# Disable use of the "alternate screen" so I can use the terminal's scrollback
# buffer (per https://github.com/ThomasAdam/tmux/blob/master/FAQ).
set-option -ga terminal-overrides ",xterm*:Tc:smcup@:rmcup@"
set-option -ga terminal-overrides ",screen*:Tc:smcup@:rmcup@"
```

That's from my personal *~/.tmux.conf* where you can see from the comment that I'm doing so for a different reason.

**Comment by townba** [comment]
(I see the same moving-cursor-to-home behavior in GNOME Terminal on Ubuntu 14.04 that jooadam does, so it might not be that unusual.)

The issue (I don't really think it's a problem since tmux is doing what some other popular terminal emulators do) is not that tmux is using the terminal's alternate screen (because it's not – at least, not in this case). It's that tmux's implementation of the alternate screen behaves differently from some terminal emulators. That's why krader1961's `terminal-overrides` settings are not sufficient to change this behavior.

From what I can tell, `terminal-overrides` are only for the terminal in which tmux is running, not tmux itself. For example, I used iTerm2 3.0.5 (with `TERM=xterm`) and ran tmux with just those settings. tmux (and programs running under tmux) will use `TERM=screen` (as expected), and I can see that `smcup` is still set even though the `terminal-overrides` setting removed it from the ("outer") terminal:

```
$ tput smcup | hexdump -C
00000000  1b 5b 3f 31 30 34 39 68                           |.[?1049h|
00000008
$ tmux info | grep smcup
 192: smcup: [missing]
$
```

I believe you really do need the custom terminfo to change the behavior of programs that use the alternate screen if you want them either (A) to put the cursor at home when switching to it or (B) to not use the alternate screen (by using `smcup@, rmcup@` in the terminfo entry instead of merely adding `\E[H` to `smcup`). (Unless you simply tell programs themselves to not use an alternate screen, but that might not always be possible.)

**Comment by jooadam** [comment]
@krader1961 I’ve settled for `-c` for now, thanks for that!

@townba If that is the case, i.e. tmux is doing something that is normally the responsibility of the terminal, and different terminals handle it differently, wouldn’t it make sense it to be configurable? /cc @nicm

**Comment by nicm** [comment]
Almost all terminals (including - importantly - xterm) preserve the cursor position across smcup/rmcup. tmux is a terminal and like all terminals we choose a behaviour, and in this case I think our behaviour is correct. And making something this trivial configurable would be silly.

I suspect this may be a bug in VTE; gnome-terminal 3.18.3 with VTE 0.42.5 behaves correctly, I don't have any later versions around but there is some evidence in the code this may be a regression which has been fixed very recently.

**Comment by townba** [comment]
(All the terminals I've tried, including tmux, preserve the cursor position across smcup/smcup. This is merely about the cursor position immediately *after* smcup.) It's already configurable – you just have to use terminfo to configure it. :-)
