### ISSUE TITLE
"{client_*}" vars only show creating session's client when using shared session groups.

### ISSUE THREAD

**Issue by dalejung** [tmux/tmux#503]
If you create 2 sessions that share the same group, then client commands like `tmux display-message -p "#{client_pid}" are stuck on the creating session's client.

Let's say you have:
```
Client_1
  Session_1
    Window_1

Client_2
  Session_2
    Window_1
```
Window_1 is created by Session_1.

Both clients will post the pid of Client_1.

However, if you detach the creating session and attach a new session:
```
Client_1
  Session_3
    Window_1

Client_2
  Session_2
    Window_1
```
the two clients will print out the correct client pid.

Interstingly, if you attach the creating session to any Client, that window now locks onto that Clients pid.

I'm running tmux from master baf1550 (today).

**Comment by nicm** [comment]
This is because running display-message inside tmux will get the current session from $TMUX if it is valid, and then uses that to work out the current client. By destroying the original session you make $TMUX invalid and it is ignored.

At one point we didn't use $TMUX for the session but we added it back not so long ago. I quite like that it does, even if it is not always ideal with windows linked into multiple sessions.

If you want tmux to pick the "best" (that is, most recently used) session and then the best client attached to it, you can unset $TMUX.

**Comment by dalejung** [comment]
What are the implications of unsetting $TMUX? I use that for detecting whether I'm inside of tmux but I suppose I could use $TMUX_PANE instead.

I think this is also the root of split-window opening panes in the wrong window.

**Comment by nicm** [comment]
TMUX is only used for this and for the warning about nested attachs.

**Comment by dalejung** [comment]
Just for posterity sake. Instead of unsetting the `$TMUX` var, I modify it to an invalid value to trigger the client detection I want. Unsetting was a no go since other programs used that var for detection.

So far so good.

```
if [ -n "$TMUX" ]; then
  export TMUX="${TMUX}999"
fi
```

**Comment by dalejung** [comment]
Err. Just saw https://github.com/tmux/tmux/issues/521
