### ISSUE TITLE
select-pane should have an option not to wrap around

### ISSUE THREAD

**Issue by bk2204** [tmux/tmux#546]
If I am in the leftmost pane of a two-pane window, and I use select-pane -L, tmux will switch to the rightmost pane (wrap around).  It would be great to have an option to just ignore that command if we're already at the leftmost pane.  This happens with all directions, not just left.

**Comment by ThomasAdam** [comment]
No.  This has been discussed before.

**Comment by john-kurkowski** [comment]
Fork that does it: #501

**Comment by jeffeb3** [comment]
I'm not sure where this has "been discussed before", but I've been using tmux for a while (more than a year, and it's my main development environment). This definitely would be a great feature to add. If you don't want it, then you don't have to enable it, but I think the argument could be made that it makes sense to have it not wrap. The fact that there's a script, and a fork to fix this should be a pretty good indication that it's a worthwhile feature to add into tmux.

Not even sure if this comment will be seen since it's on a closed ticket, but I thought I would put in my $0.02.
