### ISSUE TITLE
"All Motion" mouse events not being sent since tmux 2.0

### ISSUE THREAD

**Issue by chjj** [tmux/tmux#55]
All Motion (`CSI ? 1003 h`) no longer has any effect. Cell Motion (`CSI ? 1002 h`) still works fine. This looks like a tmux issue to me. All Motion still works in XTerm(318) and urxvt v9.21 without tmux.

This issue cripples any terminal app that requires hover effects.

See: chjj/blessed#145

**Comment by nicm** [comment]
We don't support it any more.

**Comment by chjj** [comment]
I see. Why is it no longer supported?

**Comment by nicm** [comment]
It never worked very well and barely anything uses it, it made the new
mouse code simpler.

**Comment by chjj** [comment]
That's really a shame. Barely anything used it because terminal apps are _still_ growing up: it's not just a bunch of programs from the 80s and 90s. They haven't fully explored what they're capable of yet. I really hope you guys reconsider your position.

**Comment by nicm** [comment]
I'm probably not going to add it again until something I want to use needs it (which I expect will be never) but I don't object if someone else does.

**Comment by chjj** [comment]
@nicm,

That's really heartbreaking. Could I refactor the previous implementation and change your mind?

Tmux is one of the most beautifully-written C programs I've ever seen. Nicholas, I've read your code. I've reused your code in my own projects. I love it. I love tmux. But I expected the author of tmux would have a real passion for terminals. There is nothing that could change your mind about this... other than a terminal app you say will never exist?

I can't think of many well-established terminal programs off the top of my head that use it... What about ANSI art editors? All the unix clones of TheDraw? Surely they use all-motion for certain features? Should people have to start up a non-multiplexed terminal to use them? tmux is the odd man out now.

I really hope other terminal developers don't follow suit here. If Thomas Dickey and Marc Lehmann also decided all-motion was worthless, the terminal itself would be a far less dynamic canvas for amazing programs. I guess that's now the case since everyone already uses tmux on top of their terminal of choice.

Was the all-motion code truly that complex? Could we talk about it more? I'm seriously down in the dumps right now just knowing this. I'm sad. This is a huge step backwards for the terminal, and I want the terminal to have a bright future.

**Comment by nicm** [comment]
If you send me a diff that adds it again (I don't think it would even
necessarily be very big) I'll look at it.

**Comment by chjj** [comment]
Thank you. I'll get to work on it.

**Comment by saitoha** [comment]
@chjj I agree with you. [MinEd](http://towo.net/mined/)'s menu bar is given as an example of typical program which uses All Motion Mouse efficiently.

**Comment by nicm** [comment]
So I have looked at this again recently and it is not terribly hard to do.

The main problem is that if we have pane A with 1003 enabled and pane B with 1002, we need to set 1003 outside tmux in order to get all the mouse events we need for pane A, but we need to suppress the ones that pane B doesn't want. That is, the movement events that happen without a button pressed.

If we only had to cater for SGR mouse mode it would be easy because buttons is only ever 3 for this event, but in 1002 mode we can't differentiate the movement events from a normal release event.

The best I can come up with is to look at the previous event instead (which happily tmux already keeps) - if it is drag+release as well, then the current event is a movement event. However, this may mean we miss events, for example the first movement event after a wheel button press.

Anyway, please try this, which seems to work for me: [all-mouse.diff.txt](https://github.com/tmux/tmux/files/699956/all-mouse.diff.txt)

There is a good possibility this will break the mouse in some obscure way so it needs testing.

**Comment by nicm** [comment]
I have applied some trivial parts of this, here is an updated diff: [all-mouse2.diff.txt](https://github.com/tmux/tmux/files/700285/all-mouse2.diff.txt)

**Comment by arcanis** [comment]
I would be interested in this feature too. Not supporting all-mouse events might not seem much, but it prevents some of us from using this feature in our applications if we happen to use tmux in our regular development workflow, which is a shame.

**Comment by nicm** [comment]
Did you test it?

**Comment by arcanis** [comment]
Not yet, I haven't build tmux from its sources yet. I'll give it a try.

**Comment by arcanis** [comment]
I've been playing with it, it seems to work fine. I've also made a test with a pane using `1003h`, another with `1002h`, and another with `1000h`, and they all received the requested events as expected.

**Comment by nicm** [comment]
What application are you using that uses it?



On 31 Jan 2017 3:37 pm, "Maël Nison" <notifications@github.com> wrote:

I've been playing with it, it seems to work fine. I've also made a test
with a pane using 1003h, another with 1002h, and another with 1000h, and
they all received the requested events as expected.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/55#issuecomment-276397709>, or mute
the thread

**Comment by arcanis** [comment]
Currently, none myself (but I'm writing a library that supports and make this feature quite useful for hover effects : https://github.com/manaflair/mylittledom). My long term goals are to write a terminal editor with it, and being able to detect mouse hover would go a long way to implement things such as symbol annotations.

**Comment by nicm** [comment]
I have applied this now, will see if it causes any problems. Thanks.
