### ISSUE TITLE
vi-copy and vi-choice not working

### ISSUE THREAD

**Issue by will118** [tmux/tmux#592]
I recently did a `brew upgrade` and tmux updated (to HEAD d54e990).

With the following config file:
```
❯ cat .tmux.conf
bind-key -t vi-copy v begin-selection
```
I get this when starting tmux: `unknown key table: vi-copy`

There is similar issue (#585) but it seems this user resolved their problem somehow.

From what I can tell, the `vi-edit` and `vi-copy` options are deprecated in favour of `vi-choice`?

However if I replace it with this:
```
❯ cat .tmux.conf
bind-key -t vi-choice v begin-selection
```
then I get: `unknown command: begin-selection`

Then I searched the source and found how it was being set, and used that:
```
❯ cat .tmux.conf
bind -Tcopy-mode-vi v send -X begin-selection
```

This works but I'm not convinced it's the correct solution?

Apologies if I missed something obvious. I also realise that I'm not exactly running a release.

**Comment by nicm** [comment]
This was documented in the commit message for 76d6d3641f271be1756e41494960d96714e7ee58.

**Comment by will118** [comment]
Seems I didn't look hard enough, thanks a ton Nicholas.

Speedy reply!

**Comment by nicm** [comment]
Basically you now need to bind your key in the copy-mode-vi table now, look at how the default key bindings are done with "tmux lsk". For your example: bind -Tcopy-mode-vi v send -X begin-selection

**Comment by jayniz** [comment]
Perhaps this can save somebody one or two minutes:

```
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
```

can be changed to

```
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection
```

Bonus: on MacOS Sierra you can drop `reattach-to-user-namespace`, but make sure you have the "Applications in terminal may access clipboard" option set when using iTerm2.

**Comment by kesselborn** [comment]
Late comment on @CallumHoward's question:

    bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

jumps to the bottom after copying

**Comment by 1ambda** [comment]
my configuration looks like

```
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -Tcopy-mode-vi Escape send -X cancel
bind-key -Tcopy-mode-vi V send -X rectangle-toggle
```

**Comment by mrolli** [comment]
To confirm what @jayniz has posted above:
With iterm-2.4 on Sierra using iTerm2 with activated "Applications in terminal may access clipboard" the following works for me:

```
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel pbcopy
```

reattach-to-user-namespace is NOT necessary anymore!
Using copy-pipe-and-cancel makes it jump to bottom as before after copy action. If don't want this behaviour just used copy-selection (without pbcopy then) and you're done.

**Comment by ohjames** [comment]
The suggestions work for vi-copy-mode but vi-choice-mode doesn't work. List of default key bindings also don't choose any key tables containing `choice`. Maybe those bindings are hardcoded now?

**Comment by ohjames** [comment]
Tried this also but no joy:

```
set-hook -g before-choose-session "bind-key -Troot n send-keys -X down"                                                                          
set-hook -g after-choose-session "unbind-key -Troot n"                                                                                           
```

The default key bindings aren't so good for COLEMAK keyboard layout.

**Comment by nicm** [comment]
vi-choice are hardcoded but I'm open to adding extra bindings within reason
and if they don't conflict.

**Comment by ohjames** [comment]
On colemak n and e are in the position where j and k are on qwerty. Colemak is the second most popular layout after qwerty now (excluding regional variations of qwerty). Next the Dvorak people will complain though.

Are you opposed to making these configurable again? It doesn't have to be via key-tables, could be done via hooks or something.

Hard coding qwerty kinda feels insensitive to those of us with RSI and other disabilities who moved off that layout to seek a more ergonomic setup.

**Comment by nicm** [comment]
It will not be configurable again.

**Comment by ohjames** [comment]
It's time for those of us not on qwerty to seek an alternative then, what a shame.

**Comment by nicm** [comment]
I've said I don't mind duplicate bindings if they don't conflict but if you
don't suggest them then they won't be added. Hooks are not really suited to
this I think but perhaps it is possible.



On 7 May 2017 10:18 am, "James Pike" <notifications@github.com> wrote:

It's time for those of us not on qwerty to seek an alternative then, what a
shame.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/592#issuecomment-299692506>, or mute
the thread

**Comment by mrolli** [comment]
@ohjames What's the matter. @nicm offered to add extra bindings. You havn't argued for/against this, you didn't even mentioned his proposition. And additionally... if you choose to put this down, don't choose for all others to do the same - that's a shame. ;-)

**Comment by ohjames** [comment]
I did suggest `n` and `e` for colemak, bit given that I'm disabled I have a lot of empathy for other disabled people, so a solution that helps me but not Dvorak people won't feel good enough.

**Comment by nicm** [comment]
If we added a format like pane_in_copy_mode you could bind the keys you
want in the root table using "if -F 'pane_in_copy_mode' send n"

**Comment by ohjames** [comment]
That would be cool, it doesn't matter *how* it's configurable to me, just that it is. With one handed keyboards you need to enter a new mode in order to hit up/down cursors, so those can be very inconvenient to use (at least 3 presses including entering and leaving cursor mode). On non-qwerty keyboards the `j` key is put in a hard to reach place (given how infrequently the letter j is used).

**Comment by nicm** [comment]
Or better a format like pane_mode_name (which would be useful for other
things too). But that would be a pain if you want to change multiple modes.

Ultimately choose mode _could_ use send -X too but I'm not sure it is worth
it, it uses like 10 keys.

**Comment by nicm** [comment]
Having a named command set is very limiting when we want to do more
powerful things in the various modes. It is bad enough in copy mode.

I'll look at a format for mode name anyway.

It won't help you for the command prompt though.



On 7 May 2017 10:44 am, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

Or better a format like pane_mode_name (which would be useful for other
things too). But that would be a pain if you want to change multiple modes.

Ultimately choose mode _could_ use send -X too but I'm not sure it is worth
it, it uses like 10 keys.

**Comment by nicm** [comment]
You can try this [x.diff.txt](https://github.com/tmux/tmux/files/981975/x.diff.txt) which gives you two choices:

1) use the pane_mode format to bind a key in the root table that sends Down instead of n if the pane is in choose-mode:

tmux bind -n n if -F '#{==:#{pane_mode},choose-mode}' 'send Down' 'send n'

2) use the choose-mode table to replace n with Down:

tmux bind -Tchoose-mode n send Down

I am very likely to apply the pane_mode format for (1) because it is simple, but it is a pain to rebind a number of keys.

Not sure about (2) because it makes choose-mode table work differently from copy-mode. Still, it might be OK for a while until the new choose modes are done - when we see what they look like we can better decide if we need commands a la send -X for copy mode. I'm inclined not to add it though.

**Comment by morningpee** [comment]
For anyone piping to `xsel`, here is how my `tmux.conf` changed for 76d6d3641f:

    -bind -t vi-copy p copy-pipe 'xsel -ip'
    -bind -t vi-copy s copy-pipe 'xsel -is'
    -bind -t vi-copy o copy-pipe 'xsel -ib'
    +bind -T copy-mode-vi p send -X copy-pipe-and-cancel 'xsel -ip'
    +bind -T copy-mode-vi s send -X copy-pipe-and-cancel 'xsel -is'
    +bind -T copy-mode-vi o send -X copy-pipe-and-cancel 'xsel -ib'

**Comment by unlmtd** [comment]
> I am pretty sure I'm not going to do this

Like @ohjames , I have removed the qwerty handicap from my workflow, to the satisfaction of my body. I am totally convinced that more people are now realizing qwerty is an abomination living on momentum. Since momentum is not a source of energy, supporting more than the worst of all keyboard layouts sounds like a good idea. Not to say the problem could not be resolved more elegantly (system-wide), but that is out of this scope. I highly recommend taking 2-3 weeks to learn colemak; it's worth it imo.

**Comment by ohjames** [comment]
@unlmtd I coded my way around this by writing my own selector (which I open in a new tmux window) in rust. It's on github. Hope the author doesn't remove more customisability though, this isn't a good sign.

**Comment by barcher** [comment]
Just a piece of feedback: I don't think that a GH issue, or a commit is the best place to document a breaking change. You might consider an, "Updating to New Releases" section in the future to be proactive.

**Comment by vcavallo** [comment]
I'm on 10.11.6 and for me `begin-selection` doesn't actually begin the selection. However `<shift>-v` _does_ work to begin a line-wise selection (and copying / the clipboard works fine).
Sorta stumped on this one...

**Comment by arcseldon** [comment]
The following provided exactly what I wanted (combination of settings from above). Thanks for the contributions.

```

# vi like copy paste behaviour
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection
bind-key -Tcopy-mode-vi Escape send -X cancel
bind-key -Tcopy-mode-vi V send -X rectangle-toggle
```

**Comment by alphaCTzo7G** [comment]
Wonder if there is a good plugin that handles the differences between versions and provides good settings for vi-mode in tmux?

Otherwise, it seems people are manually setting this everywhere, in their tmux conf. It would be cleaner to just use a plugin
