### ISSUE TITLE
Strikethrough text seems not working.

### ISSUE THREAD

**Issue by everthis** [tmux/tmux#612]
For example, if I configure `git 2.10.0` like this:
```
git config --global color.diff.old "red strike"
```
what I get is
![abnormal](https://cloud.githubusercontent.com/assets/3142886/19766382/0cc4e7ba-9c80-11e6-8e3e-a441636ec830.PNG)
while what is expected is:
![normal](https://cloud.githubusercontent.com/assets/3142886/19766387/1af01968-9c80-11e6-87d6-eda8c15ef0ae.PNG)
(the latter screenshot was captured when I detached tmux.)

**Comment by nicm** [comment]
There is no standard support for strikethrough in most terminals and tmux does not support it either.

**Comment by untitaker** [comment]
@nicm 

>There is no standard support for strikethrough in most terminals

Could you tell me of a terminal emulator that *doesn't* support strikethrough text via escape codes? I haven't been able to find one.

If I understand the README correctly, the mailing list is preferred for discussion over GitHub issues. Do you think it makes sense to talk about this topic there (I'm thinking about writing a patch as well), or is there a reason why tmux explicitly does not support it?

**Comment by untitaker** [comment]
It appears that urxvt doesn't support strikethrough text, however with that the emulators without support are still in the minority.

**Comment by hobarrera** [comment]
FWIW, this is the escape sequence that works on most terminals: `echo -e "\e[9mstrikethrough\e[0m"`

**Comment by krader1961** [comment]
> Could you tell me of a terminal emulator that doesn't support strikethrough text via escape codes? 

Neither Terminal.app or iTerm2.app on macOS support it. You seem to be arguing that because a handful of terminals you've checked support it that it is therefore widely supported. That is not my experience.

**Comment by untitaker** [comment]
The majority of terminal emulators on Linux support it. That is definetly not a
handful and in any case I don't see why a feature should be excluded from tmux
on that basis.

**Comment by hobarrera** [comment]
So far, from my testing, the following terminals *do* support strikethrough (including the ones from major DE's):

* gnome-terminal (also tried the one from mint-cinnamon, but it's really the same thing)
* xterm
* termite
* st
* terminology
* konsole (that's the one from KDE)
* terminator

I've only found this one that doesn't:

* urxvt

Plus the two you mention. TBH, don't have macOS anywhere at hand to really try macOS terminals, nor am I familiar with the ecosystem. The same applies for windows, though, from some searching online, their terminal seems to support it too (*I can't confirm this!*).

That aside, I still don't see a reason to *not* support that on tmux; it creates a chicken-and-egg problem in which people keep refusing to support it because something else doesn't, and it's a perfectly sane feature (which actually follows the spec) that should present no downsides.

**Comment by untitaker** [comment]
Note that I offered to write a patch to this, but only if the feature request
itself gets accepted.

**Comment by nicm** [comment]
Adding this is fine but it will mean bumping the cell attributes to
uint16_t and using extended cells for any cells with this bit set.
Strikethough is very rare so I think using extended cells would be fine.

IIRC there are some other uncommon ISO attributes (hidden?), it is probably
worth adding them at the same time.

**Comment by nicm** [comment]
Note that there appears to be no existing terminfo entry for strikethrough, so you will need to negotiate what it should be called with upstream.

**Comment by nicm** [comment]
Also it looks like we already support hidden.

**Comment by untitaker** [comment]
I'm fairly new to terminal protocols at this level. For now I'm just trying to
get a hang of the tmux codebase. I have one question upfront:

I don't really understand what extended cells are, or why they're necessary
here. I also couldn't find any documentation about this concept.
  
As far as I understand they're used for e.g. storing rgb fg and bg if
necessary, but since cell attributes are now 16-bit for *all* grid cells and
strikethrough is just a single flag, why does the cell have to be extended?

**Comment by nicm** [comment]
struct grid_cell_entry is used for simple cells (not UTF-8, not RGB
colour), anything else goes in an array of extended cells (struct
grid_cell). When a cell is needed it is extracted into a struct
grid_cell, either from the struct grid_cell_entry or by copying it
directly from the extended cell array. There are already eight
attributes so the attr member of both structs is full. We don't want to
increase grid_cell_entry or we are making everybody's tmux use 120% of
the memory for something few will use. But we can increase grid_cell's
attr member to uint16_t and use extended cells for any cells with the
strikethrough attribute. If you make grid_cell.attr uint16_t then you
should only need to change:

grid_need_extended_cell
grid_store_cell
grid_get_cell
input_csi_dispatch_sgr
tty_attributes

**Comment by nicm** [comment]
This should work in master now, but you will need to add smxx with terminal-overrides:

set -as terminal-overrides ',xterm*:smxx=\E[9m'

**Comment by untitaker** [comment]
Sorry for not responding btw, I've been busy with other things!

**Comment by geier** [comment]
@nicm Thank you! (it's working over here)

**Comment by johnr14** [comment]
Ha ! had a hard time to find this ! This should be enabled by default !
Thanks, works great.
