### ISSUE TITLE
rename-pane ?

### ISSUE THREAD

**Issue by DavidGamba** [tmux/tmux#618]
Is there a way to manually label your panes inside tmux?

I am running tmux 2.3 on linux and have `set -g pane-border-status bottom` on my `~/.tmux.conf`.

**Comment by snehesht** [comment]
Try prefix + ,

**Comment by DavidGamba** [comment]
yes, I am taking about pane titles. Is there a way to manually override the title? I SSH into multiple QA servers that get rebuilt all the time and they have no bashrc settings and they all have localhost as their hostnames so they all look the same within tmux.

I end up working with them as windows instead, but with the new `pane-border-status` I was hoping for a better workflow that would allow me to use them in panes with sane identifiers just like windows.

**Comment by nicm** [comment]
You can change the title from within the terminal with the escape sequences, but tmux itself does not have a way to change it.

**Comment by DavidGamba** [comment]
Can this issue be used to track it as a feature request? or is this something you wouldn't consider adding to tmux?

**Comment by nicm** [comment]
Pane titles are not really tmux's to play with, they are for the
application inside tmux to set.

Can't you get whatever you would put in them into pane-border-format a
different way?

**Comment by vdun** [comment]
I use the command `tmux send-keys -t x ...` often in my scripts. Changing the target pane number `x` in my scripts is annoying.
An alternative name could be added to panes (like windows).

**Comment by micheal-w-wells** [comment]
2019 here, option to rename panes would still be appreciated.

**Comment by PiyushDeshmukh** [comment]
2020 here, option to rename panes would still be appreciated.

**Comment by nicm** [comment]
I don't mind having a pane name or label as well as the title, create a PR. It needs: a member in struct window_pane (like title and path); a command to change it, I would suggest select-pane -N like select-pane -T; a format like pane_name; and some code in cmd-find.c to allow it to be used as a target (-t :.mypane).

If you just want a quick label to view rather than all of that, then you can always set a pane user option (`set -p @mylabel foo`) and use that in pane-status-format or wherever with `#{@mylabel}`.
