### ISSUE TITLE
bind C-<letter> also binds C-<CAPITAL_LETTER>

### ISSUE THREAD

**Issue by tdivis** [tmux/tmux#627]
`bind C-<letter>` also binds `C-<CAPITAL_LETTER>`, while doing the same thing with ALT instead CONTROL works fine:
```
bind -n M-t new-window  # -> OK: Binds only ALT+t
bind -n M-T new-window  # -> OK: Binds only ALT+SHITFT+t
bind -n C-t new-window  # -> Error: Binds both, CONTROL+t and CONTROL+SHITFT+t
bind -n C-T new-window  # -> Error: Binds both, CONTROL+t and CONTROL+SHITFT+t
```

**Comment by nicm** [comment]
Yes terminals do not differentiate between C-x and C-S-x.

**Comment by tdivis** [comment]
Well, I don't understand internal stuff of terminal, are you saying it cannot be done at all?

This is quite counter-intuitive and also waste of lot of possibly very useful shortcuts.

**Comment by krader1961** [comment]
That is the expected behavior. The [ctrl] modifier key acts by taking the ASCII value of the key and masking it with 0x1F. That is, it causes the terminal to send just the low five bits of the value the modified key would normally send. If you look at an ASCII character table you'll see that the lowercase and uppercase letters have the same low five bits.

This is not a limitation of tmux. It is a historical artifact of how the [ctrl] key was defined to work. The [meta] key does something quite different.

**Comment by krader1961** [comment]
And, yes, it "cannot be done at all". Tmux has no way of knowing if you pressed [ctrl-a] or [ctrl-A]. Tmux gets the same value from the terminal for both.

**Comment by krader1961** [comment]
@nicm, This comes up often enough it probably warrants an entry in the FAQ.

**Comment by tdivis** [comment]
OK, now I see why some people want to create a new textual interface to replace terminal, as there are probably more historical artefacts as this one.

And yes, I think putting it to FAQ is a good idea. Maybe it could be mentioned even in the man page.
