### ISSUE TITLE
lack a whitespace between session name and window name

### ISSUE THREAD

**Issue by springmoonlight** [tmux/tmux#640]
as following.

tmux 1.8 
<img width="287" alt="qq20161111-1 2x" src="https://cloud.githubusercontent.com/assets/1595077/20235593/03830fc6-a8d1-11e6-8cf4-652bd175bce9.png">

tmux 2.4 (master branch)
<img width="251" alt="qq20161111-2 2x" src="https://cloud.githubusercontent.com/assets/1595077/20235594/0401b236-a8d1-11e6-91d3-0cfe14d23114.png">

**Comment by krader1961** [comment]
That is because tmux and your terminal have different ideas regarding the width of a Unicode character. You need to provide much more information such as your terminal (and its version) and the OS you're using when reporting a problem. Although, in this specific instance that is unlikely to matter.

@nicm, I'm a core contributor to the [fish shell](https://github.com/fish-shell/fish-shell) project. These types of issues occur there as well; albeit less often. It might be useful if our respective projects provided an easy way to ascertain what utf8proc, the OS native locale subsystem, and the user's terminal thought the width of a Unicode code point was. One of fish's other contributors has developed a way to determine the latter though I don't know how robust it is.

**Comment by nicm** [comment]
We removed the hardcoded space and you now need to include it in
status-left.

**Comment by nicm** [comment]
Kurtis I am open to any solution that does not mean adding complexity to
tmux, but this issue is not related to UTF-8 and not a good place to
discuss it, please open another issue with your suggestion.

**Comment by springmoonlight** [comment]
Thanks @nicm
