### ISSUE TITLE
man not working under tmux

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#66]
man clang
#prints something...
tmux
man clang
No manual entry for clang

**Comment by nicm** [comment]
What tmux version? What platform? Is it just clang or every man page? What's in MANPATH inside and outside tmux?

**Comment by timotheecour** [comment]
tmux 2.0
OSX
not every man page (man sudoers works)

tmux:
/opt/local/share/man:/local/man:/usr/share/man:/usr/local/share/man:/opt/X11/share/man:/opt/local/share/man:/local/man
outside tmux:
/opt/local/share/man:/local/man:

**Comment by nicm** [comment]
Are you sure you have listed the inside and outside MANPATH the right way round? Where is the clang manpage stored?

**Comment by timotheecour** [comment]
yes, i just verified.

man clang --path
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man/man1/clang.1

**Comment by nicm** [comment]
Well, it is not MANPATH then but something that man uses to determine where to look for manpages is different inside tmux from outside. This is not really an issue with tmux but with man.

**Comment by timotheecour** [comment]
how come does MANPATH changes inside vs outside tmux though?

**Comment by nicm** [comment]
Probably because tmux starts login shells and you set it up only for non-login shells. Or vice versa if you change default-shell.

-------- Original message --------

**Comment by michaelainsworth** [comment]
I'm having a similar problem.

Outside of a session:

    $ export A=1
    $ tmux

Inside of a session:

    $ echo $A
    1
    $ exit

Outside of a session again:

    $ export MANPATH=1
    $ tmux

Inside of a session again:

    $ echo $MANPATH
    
    $ # There is nothing above.
    $ exit

**Comment by krader1961** [comment]
@michaelainsworth You should, as a general rule, open a new issue rather than commenting on an issue closed more than a few days ago. Also, you don't seem to understand how environment variables work on UNIX like operating systems. Env vars are private to a process and cannot be modified by other processes. A new process either inherits its parent process env vars or the parent process gives it a unique set of env vars. The first time you start the tmux server by virtue of creating a tmux session it gets a set of env vars. When you then start a subsequent tmux session, by default, your current environment does not influence the tmux environment. See the section labeled "ENVIRONMENT" in the tmux man page.

**Comment by michaelainsworth** [comment]
Thanks for the note re currency of issues.

I do understand environment variables, and your point that environment variables are *inherited* by the child process from the parent process. Note that after the `export` bash built-ins in both of the above examples, a **new** instance of tmux is launched (i.e., not `tmux attach`) and hence tmux is a child of the shell.

Did you try the above examples? I think they highlight the issue clearly.

In the first, the variable `A` is `export`ed, meaning it will be available to child processes. `tmux` is launched, within which I echo `$A`, which is present. Process tree:

    bash (built-in export A=1)
    |-> tmux
        |-> bash (built-in echo $A, correctly producing a value of "1")

The second example is exactly the same as the first, albeit `MANPATH` is used instead of `A`, but the variable is empty. Process tree:

    bash (built-in export MANPATH=1)
    |-> tmux
        |-> bash (built-in echo $MANPATH, incorrectly producing an empty string)

**Comment by nicm** [comment]
Without -L or -S "tmux new" does not create a new server process.

**Comment by michaelainsworth** [comment]
I understand that. In both cases I exit `tmux`. Using `ps aux | grep tmux | grep -v grep` produces no output between invocations.

**Comment by nicm** [comment]
Then this seems like a problem with your shell. Do you see MANPATH if you run "env" instead of tmux?

**Comment by nicm** [comment]
Or run eg:
~~~~
tmux new "env;sleep 1000"

**Comment by michaelainsworth** [comment]
nicm, you're right, it IS a problem with my shell. I just installed `zsh`, and ran the following:

    export MANPATH=1
    tmux -c zsh
    echo $MANPATH
    1

I dug around and the last two lines of `/etc/profile` are as follows:

    # Man is much better than us at figuring this out
    unset MANPATH

I do wonder why such a silly line is included in the global configuration.

In any case, thanks for the assistance.
