### ISSUE TITLE
umask troubles

### ISSUE THREAD

**Issue by nachtgeist** [tmux/tmux#678]
Hi,

newly created sessions should inherit their umask from the process invoking `tmux new-session` instead of from a possibly already running "tmux server process."

This gave me a headache for the entire day today.

The day before yesterday I had fooled around in a ssh/bash session on a server doing some admin stuff and changed the umask to 077 therein. Later, from that very shell I startet a tmux session with no tmux processes previously existing.

Today I ssh'd into that server, started another tmux session (the old session still running) and was quite baffled to find my umask messed up all over the place when I was within any tmux'ed bash.

It took me a while to piece it all together: the second and all subsequently created tmux sessions had inherited the umask from the previously existing "tmux server". Just ssh'ing to the server showed a "clean" umask of 022 as I expected. As soon as I entered a tmux'ed bash, I'd gotten back the 077 mask.

Without knowing the code, I can only assume that `tmux new-session` looks for a pre-existing "server process" and - if found - tells it to create a new session - which inherits the "server's" umask. This is pretty counter-intuitive, as I expect the newly created session to inherit the umask from the shell it was called from.

Whats your opinion on this?

I'm using tmux 2.3 as it is provided by Debian jessie-backports.

Cheers
Daniel

**Comment by nicm** [comment]
So far we have chosen to be very limited in what we pick up from shells outside tmux, in favour of trying to keep panes created from inside tmux (from a key binding, for instance) as close as possible to panes created outside tmux. It is simpler, and inevitably there are some things we can't transfer, so it is more consistent - umask is possible, but groups or rlimits are not.

I'm not convinced we should break this policy for umask.

The only things we copy from the shell (if there is one) for new panes is PATH (because it is extremely useful to use a new PATH); and for new sessions is termios VERASE (for historical reasons) and anything that has been added to update-environment.

(I don't really like that things like umask and the initial global environment are picked up from the shell where tmux was initially started - I would prefer that it was a clean login environment - but that is how it is at the moment.)

I think it is just best to think of processes started in tmux as parented by the tmux server, wherever you happen to create them from (which is the truth, after all).

**Comment by nachtgeist** [comment]
> So far we have chosen to be very limited in what we pick up from shells outside tmux, in favour of trying to keep panes created from inside tmux (from a key binding, for instance) as close as possible to panes created outside tmux. It is simpler, and inevitably there are some things we can't transfer, so it is more consistent - umask is possible, but groups or rlimits are not.

In that, we agree. But we're talking across sessions here, not just new panes within the same session.

> I think it is just best to think of processes started in tmux as parented by the tmux server, wherever you happen to create them from (which is the truth, after all).

That's true with respect to tmux's architecture. So untrue with respect to traditional UNIX behavior (think `screen`). Again: across sessions. Tmux being a terminal multiplexer after all, I expect to be able to create separate and independent working environments:
- Admin Charly logs in to root@server, does some stuff - umask changes amongst them
- Admin Bob logs in to root@server as well and now suffers from Charlie's changes, most probably not even being aware of them, until sh*t hits the fan...



Possible solutions:

* create a new setting which switches between inheriting umask from a possibly existing server and inheriting the umask from the `tmux new-session` process
* create a new umask setting which - if set - forces any tmux process's umask
* If neither of these convince you, at the *very least* if and when the server's umask differs from the one of the tmux process which is invoking the new-session, the user needs to be made aware of that fact - and loudly - like e.g. is already the case when trying to nest tmux (→ "sessions should be nested with care")

**Comment by nicm** [comment]
I don't think we should do any of these things. It is better to be
consistent, panes created within tmux should look the same as panes created
outside tmux. It is impossible for a running tmux server to inherit the
environment fully from an existing shell.

If you want you can run tmux with -L or -S to create new servers instead of
new sessions.





On 8 Dec 2016 12:59 am, "nachtgeist" <notifications@github.com> wrote:

So far we have chosen to be very limited in what we pick up from shells
outside tmux, in favour of trying to keep panes created from inside tmux
(from a key binding, for instance) as close as possible to panes created
outside tmux. It is simpler, and inevitably there are some things we can't
transfer, so it is more consistent - umask is possible, but groups or
rlimits are not.

In that, we agree. But we're talking across sessions here, not just new
panes within the same session.

I think it is just best to think of processes started in tmux as parented
by the tmux server, wherever you happen to create them from (which is the
truth, after all).

That's true with respect to tmux's architecture. So untrue with respect to
traditional UNIX behavior (think screen). Again: across sessions. Tmux
being a terminal multiplexer after all, I expect to be able to create
separate and independent working environments:

   - Admin Charly logs in to root@server, does some stuff - umask changes
   amongst them
   - Admin Bob logs in to root@server as well and now suffers from
   Charlie's changes, most probably not even being aware of them, until sh*t
   hits the fan...

Possible solutions:

   - create a new setting which switches between inheriting umask from a
   possibly existing server and inheriting the umask from the tmux
   new-session process
   - create a new umask setting which - if set - forces any tmux process's
   umask
   - If neither of these convince you, at the *very least* if and when the
   server's umask differs from the one of the tmux process which is invoking
   the new-session, the user needs to be made aware of that fact - and loudly
   - like e.g. is already the case when trying to nest tmux (→ "sessions
   should be nested with care")

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/678#issuecomment-265622094>, or mute
the thread

**Comment by nachtgeist** [comment]
Sad story. Well, let's agree to disagree.

But what exactly is your rationale against my last suggestion to at least warn the user??

**Comment by nicm** [comment]
Almost all users do not care about this and a substantial number will not
know so I will be inundated by questions asking what the warning means and
what they should do. It would hurt more people than it helps. It would be
more appropriate to improve the ENVIRONMENT section in the man page to
better document how tmux works.

**Comment by nachtgeist** [comment]
If really only such a small user base were affected, you would hardly have to fear such an...inundation. Even so, *that* could be handled in the man page as well.

And about hurting: better safe than sorry. Or do you run your c-compiler with `-w` as well?

*headshaking*

**Comment by nachtgeist** [comment]
(the close was accidental)
