### ISSUE TITLE
vim lose colorscheme in tmux

### ISSUE THREAD

**Issue by sohnryang** [tmux/tmux#694]
I am using vim 8.0 in iTerm and tmux.

When excute vim in tmux, vim loses code highlighting but out of tmux, it is okay.

Is it a vim issue?

My .vimrc:

```vimrc
"Being improved
set nocompatible

"Syntax highlighting
if has("syntax")
	syntax on
endif

"Line numbers
set nu

"Tab size
set ts=4
set shiftwidth=4

"Status line
set laststatus=2
set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\

"Vundle conf 
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/vi_plugin')

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'Valloric/YouCompleteMe'
Plugin 'The-NERD-tree'
Plugin 'pangloss/vim-javascript'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'Raimondi/delimitMate'
Plugin 'scrooloose/syntastic'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'mattn/emmet-vim'
Plugin 'Chiel92/vim-autoformat'
Plugin 'shougo/vimshell.vim'

call vundle#end()
filetype plugin indent on

"ultisnips settings
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

"xterm-true-color
let &t_8f = "\[38:2:%lu:%lu:%lum"
let &t_8b = "\[48:2:%lu:%lu:%lum"

"colorscheme conf
set t_Co=256
set t_AB=[48;5;%dm
set t_AF=[38;5;%dm
colorscheme solarized8_dark

"termguicolors
set termguicolors
execute pathogen#infect()
call pathogen#helptags()

"YouCompleteMe settings
let g:ycm_min_num_of_chars_for_completion = 1
let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_add_preview_to_completeopt=0
let g:ycm_confirm_extra_conf=0
set completeopt-=preview

"syntastic settings
let g:syntastic_check_on_open=1
noremap <F4> :Errors<CR>

"vim-airline settings
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme='solarized'

"vim-autoformat settings
noremap <F3> :Autoformat<CR>

"indenting
set tabstop=4
set shiftwidth=4
set expandtab
```

vim --version:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 14 2016 22:05:32)
MacOS X (unix) version
Included patches: 1-134
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.3/lib
```

**Comment by sohnryang** [comment]
I set $TERM, .tmux.conf properly

**Comment by nicm** [comment]
What does "echo $TERM" show inside and outside tmux?

**Comment by nerdpad** [comment]
I have a similar issue, but in my case the colors do not match inside tmux.

I previously thought this may be happening because my tmux didn't have TrueColor support enabled properly. Thanks to @nicm I was able to resolve my TrueColor support issue https://github.com/tmux/tmux/issues/696, but my vim colors still do not match:

### Screenshot

**Left:** iTerm > tmux > nvim
**Right:** iTerm > nvim

**Noticeable Problems:**

- Background color doesn't match. Background color of nvim running within tmux has a darker tone
- Normally all colors look more contrasted (colors on left eg: pink, red, etc. are darker inside tmux

![screen shot 2016-12-21 at 6 06 12 pm 3](https://cloud.githubusercontent.com/assets/87896/21409452/5287aadc-c7a8-11e6-96fc-7cc2875e5f3d.png)

**Comment by nicm** [comment]
This program is probably assuming that tmux supports BCE, try tmux from Git
master.


On 21 Dec 2016 11:12 pm, "Zuhaib" <notifications@github.com> wrote:

I have a similar issue, but in my case the colors do not match inside tmux.

I previously thought this may be happening because my tmux didn't have
TrueColor support enabled properly. Thanks to @nicm
<https://github.com/nicm> I was able to resolve my TrueColor support issue
#696 <https://github.com/tmux/tmux/issues/696>, but my vim colors still do
not match:
Screenshot

*Left:* iTerm > tmux > nvim
*Right:* iTerm > nvim

*Noticeable Problems:*

   - Background color doesn't match. Background color of nvim running
   within tmux has a darker tone
   - Normally all colors look more contrasted (colors on left eg: pink,
   red, etc. are darker inside tmux

[image: screen shot 2016-12-21 at 6 06 12 pm 3]
<https://cloud.githubusercontent.com/assets/87896/21409452/5287aadc-c7a8-11e6-96fc-7cc2875e5f3d.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/694#issuecomment-268668775>, or mute
the thread

**Comment by nerdpad** [comment]
@nicm I have bce turned off in vim

```
if &term =~ '256color'
    " disable background color erase
    set t_ut=
endif
```

**Comment by nerdpad** [comment]
@nicm do not mind my issue. It was because ```set termguicolors``` wasn't being called inside tmux session

**Comment by sohnryang** [comment]
@nicm My $TERM is `xterm-256color`

**Comment by nicm** [comment]
Inside and outside tmux?

**Comment by sohnryang** [comment]
Inside tmux, $TERM is screen-256color

**Comment by sohnryang** [comment]
@nicm

**Comment by sohnryang** [comment]
Oh my mistake

**Comment by gapplef** [comment]
I have the same problem
I'm using tmux 2.2 + Gnome Terminal + vim 7.4 on Ubuntu Gnome 16.10 x64
My tmux and vim are all use the default config
$TERM outside tmux is 'xterm-256color', inside tmux is 'screen'.
the screenshot of vim used in and outside tmux show below:
![screenshot from 2016-12-23 17-02-44](https://cloud.githubusercontent.com/assets/5604665/21450596/7b05291c-c933-11e6-93e6-8330a68f5980.png)
![screenshot from 2016-12-23 17-03-29](https://cloud.githubusercontent.com/assets/5604665/21450595/7b021e5c-c933-11e6-91b3-f4eef3fa7a97.png)
I've tried the common said `set -g default-terminal "screen-256color"`in .tmux.conf ,  `tmux -2`, or  `set t_Co=256` in .vimrc.
All these method have no effect in my case.

**Comment by nicm** [comment]
xterm-256color is wrong TERM inside tmux, it needs to be screen-256color or tmux-256color.

**Comment by sohnryang** [comment]
But I added `set -g default-terminal "screen-256color"` in `.tmux.conf`, I see `xterm-256color` inside tmux.

**Comment by nicm** [comment]
You must be changing it in a shell profile file.

**Comment by sohnryang** [comment]
I added `set -g default-terminal "screen-256color"` in `.zshrc`, but still no highlighting.

**Comment by nicm** [comment]
No you need to make sure TERM is correct for your terminal (probably xterm-256color) outside tmux, and screen-256color inside tmux.

So best is not to change it in any shell profile files at all.
