### ISSUE TITLE
Feature request: command to move cursor outside of copy-mode

### ISSUE THREAD

**Issue by Iambecomeroot** [tmux/tmux#695]
Outside of tmux, in my terminal (termite), hitting `ctrl-right` or `ctrl-left` will move the cursor right/left by one word. Inside of tmux, hitting those bindings only moves the cursor by one character. I am trying to create a workaround for this, however, after much searching, I have not found a command that will move the cursor outside of copy mode. Please close this issue if this is incorrect.

`tmux -V':

    tmux 2.3

`uname -a`:

    Linux Hermes 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

## Edit: I didn't know I needed this for a feature request
`$TERM` inside tmux: screen
`$TERM` outside tmux: xterm-termite

**Comment by nicm** [comment]
If you run cat outside tmux then press C-Left, what do you see?

What is $TERM outside tmux?

**Comment by Iambecomeroot** [comment]
I don't understand what you want me to do with cat. I am talking about entering text as in when typing a command.

`$TERM` inside tmux: screen
`$TERM` outside tmux: xterm-termite

**Comment by nicm** [comment]
Run cat then press C-Left and tell me what you see. Outside tmux.

On 21 Dec 2016 10:54 pm, "Marcel Robitaille" <notifications@github.com>
wrote:

I don't understand what you want me to do with cat. I am talking about
entering text as in when typing a command.

$TERM inside tmux: screen
$TERM outside tmux: xterm-termite

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/695#issuecomment-268665319>, or mute
the thread

**Comment by Iambecomeroot** [comment]
Oh I thought you wanted me to cat a file. I get `^L`.

**Comment by nicm** [comment]
You get ^L when you press Ctrl+Left?



On 21 Dec 2016 11:13 pm, "Marcel Robitaille" <notifications@github.com>
wrote:

Oh I thought you wanted me to cat a file. I get ^L.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/695#issuecomment-268668929>, or mute
the thread

**Comment by Iambecomeroot** [comment]
Sorry I don't know what I was thinking. `^[[1;5D`

**Comment by nicm** [comment]
OK try turning xterm-keys option on in tmux.

**Comment by Iambecomeroot** [comment]
That works, thank you very much. The feature would still be nice to have though.
