### ISSUE TITLE
Unable to bind forward slash (C-/ or ^/) -- get "unknown key: C-/", etc.

### ISSUE THREAD

**Issue by dubaaron** [tmux/tmux#697]
When trying to bind C-/, I always get "unknown key: C-/":
```
$ tmux bind-key -n C-/ send-prefix
unknown key: C-/
$ tmux bind-key -n ^/ send-prefix
unknown key: ^/
```

I've tried everything I can think of -- including putting the "/" in quotes (bind-key C-"/") -- same result.

I can't find any documentation on this anywhere, nothing to say that I shouldn't be able to bind forward slash.

Binding a plain forward slash works, as does binding M-/. 

Attempted on tmux 2.2 on Mac OS X (10.11), as well as tmux 1.6 on CentOS.

I also compiled latest 2.4 from git master and result was the same. On Ubuntu 14.04.

Except for the Mac OS X version, I'm using PuTTY on windows to access the systems remotely.

**Comment by krader1961** [comment]
Try C-O since it's equivalent. Note that applying the control operator technically just masks out the three high order bits of a character. So since `/` has value 0x2F applying the control operator would turn it into 0x0F (the SI character). However, many programs (including most terminal emulators) don't allow applying the control operator to arbitrary characters. In this case `O` has value 0x4F so C-O also becomes 0x0F.

**Comment by dubaaron** [comment]
@krader1961 that's interesting; thanks for the tip.  It didn't seem to work for the `/` via either PuTTY or Terminal on OS X.  Interestingly, though, when setting C-O, it applies to both C-O and C-o ...

Using a `C-|` (pipe) for a binding doesn't seem to work either; gives the same "unknown key" message. I presume for the same reasons.

**Comment by krader1961** [comment]
> Interestingly, though, when setting C-O, it applies to both C-O and C-o 

Not really, "O" is 0x4F and "o" is 0x64, so doing `& 0x1F` (the control operator) results in 0x0F for both.

> Using a C-| (pipe) for a binding doesn't seem to work either; gives the same "unknown key" message. I presume for the same reasons.

Correct. "|" is 0x7C. Use C-\ ("\" is 0x3C). However note that on most UNIX systems that is mapped as the tty "quit" key which will result in the kernel sending SIGQUIT when you press it.

As you should have gleaned by now every character does not have a unique control representation. Meta, `M-`, works because it means something different: prefix each key with an escape character.

**Comment by nicm** [comment]
C-/ doesn't exist but in many terminals it is the same as C-_.
