### ISSUE TITLE
No way to figure out underlying TERM for original terminal

### ISSUE THREAD

**Issue by barrkel** [tmux/tmux#712]
Hello,

I use tmux on multiple platforms (Linux, Cygwin and OS X), and from multiple terminals (urxvt and minrtty (in xterm-256color mode)).

I'm having difficulty coming up with a value for TERM that works across all combinations of terminal and host system.

With screen (the application, not the value of TERM), everything just works; the value of TERM is either `screen.rxvt-unicode-256color` or `screen.xterm-256color`, and I can customize my applications (mostly emacs) accordingly.

Unfortunately with tmux, the value of TERM is just `screen`. There's no way to figure out which terminal emulator I'm running, so I can't configure applications to handle various extended keystrokes, like C-S-Left, C-M-Home etc. - things that are not exhaustively handled in OS terminfo files.

I can force the value of TERM using `set-option -g default-terminal screen.rxvt-unicode-256color` in .tmux.conf, but that only works when I'm using urxvt, but when I'm using xterm-compatible terminal and logging in over ssh, it doesn't.

Currently I'm considering writing a shell wrapper for tmux and swapping in and out different versions of .tmux.conf to change the value of TERM inside tmux based on the value outside, which seems unnecessarily awkward.

**Comment by nicm** [comment]
It is against the purpose of tmux to configure applications inside tmux
differently depending on the terminal outside and is not recommended.
Configure them for tmux itself.

For modified function keys, turn on xterm-keys (it will default to on in
the next release) and if the terminal is not xterm compatible make sure
TERM outside specifies the keys for your terminal (either by choosing the
correct terminfo entry or adding them using terminal-overrides).


On 7 Jan 2017 12:00 pm, "Barry Kelly" <notifications@github.com> wrote:

Hello,

I use tmux on multiple platforms (Linux, Cygwin and OS X), and from
multiple terminals (urxvt and minrtty (in xterm-256color mode)).

I'm having difficulty coming up with a value for TERM that works across all
combinations of terminal and host system.

With screen (the application, not the value of TERM), everything just
works; the value of TERM is either screen.rxvt-unicode-256color or
screen.xterm-256color, and I can customize my applications (mostly emacs)
accordingly.

Unfortunately with tmux, the value of TERM is just screen. There's no way
to figure out which terminal emulator I'm running, so I can't configure
applications to handle various extended keystrokes, like C-S-Left, C-M-Home
etc. - things that are not exhaustively handled in OS terminfo files.

I can force the value of TERM using set-option -g default-terminal
screen.rxvt-unicode-256color in .tmux.conf, but that only works when I'm
using urxvt, but when I'm using xterm-compatible terminal and logging in
over ssh, it doesn't.

Currently I'm considering writing a shell wrapper for tmux and swapping in
and out different versions of .tmux.conf to change the value of TERM inside
tmux based on the value outside, which seems unnecessarily awkward.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/712>, or mute the thread

**Comment by barrkel** [comment]
Indeed I had to enable xterm-keys to get functional S-Left.

If there were terminfo capabilities for C-Left, C-S-Left, C-M-S-Left, C-M-Left and so on I'd be able to fill them in. But AFAIK there's only `key_left` and `key_sleft` (capnames `kcub1` and `kLFT`). Emacs only works well in xterm compatible emulators because it ships with `term/xterm` that exhaustively binds all the other variants. To get decent emacs support inside screen, you need to know what the outside terminal is running; emacs assumes it's xterm-like and loads xterm, which works poorly for urxvt, and hence why having distinct values for TERM depending on the outer emulator is so important.

I've thought of a different workaround, though. I'll save the value of TERM in my rc, and also test the value of TERM in my rc, and switch it for a screen-prefixed version if it's equal to screen. 

I still think this is a bug in tmux's support. Full conversion of the outer terminal to the inner terminal is a fine idea in principle, but the terminfo database isn't rich enough to model the outer terminal.

**Comment by nicm** [comment]
You want kLFT, kLFT3, kLFT5 and so on.



On 7 Jan 2017 5:48 pm, "Barry Kelly" <notifications@github.com> wrote:

Indeed I had to enable xterm-keys to get functional S-Left.

If there were terminfo capabilities for C-Left, C-S-Left, C-M-S-Left,
C-M-Left and so on I'd be able to fill them in. But AFAIK there's only
key_left and key_sleft (capnames kcub1 and kLFT). Emacs only works well in
xterm compatible emulators because it ships with term/xterm that
exhaustively binds all the other variants. To get decent emacs support
inside screen, you need to know what the outside terminal is running; emacs
assumes it's xterm-like and loads xterm, which works poorly for urxvt, and
hence why having distinct values for TERM depending on the outer emulator
is so important.

I've thought of a different workaround, though. I'll save the value of TERM
in my rc, and also test the value of TERM in my rc, and switch it for a
screen-prefixed version if it's equal to screen.

I still think this is a bug in tmux's support. Full conversion of the outer
terminal to the inner terminal is a fine idea in principle, but the
terminfo database isn't rich enough to model the outer terminal.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/712#issuecomment-271098495>, or mute
the thread

**Comment by nicm** [comment]
Look at xterm+pcfkeys and the comment above above it in terminfo.src for
description.

Hopefully soon TERM=tmux should have xterm+pcfkeys but until then you could
build your own entry with something like:

cat <<EOF|tic -x - tmux|tmux terminal multiplexer, ritm=\E[23m,
rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@, use=xterm+pcfkeys, use=xterm+sl,
use=xterm+tmux, use=screen, tmux-256color|tmux with 256 colors,
use=xterm+256setaf, use=tmux, EOF

Although IIRC emacs doesn't look at the modified function keys anyway so
you will always need to configure it.

**Comment by barrkel** [comment]
That is interesting information - I wasn't aware of the extended definitions - they post-date my initiation into the world of terminfo and termcap. They're not in the [standard](http://pubs.opengroup.org/onlinepubs/7908799/xcurses/terminfo.html); nor are they documented in the [terminfo manual](http://man7.org/linux/man-pages/man5/terminfo.5.html). ncurses special, I guess.

Since emacs doesn't use the definitions, my workaround looks like the fastest path to success for me. Good luck changing the world!
