### ISSUE TITLE
Confusing lack of error message if stdin is not a terminal, in control mode

### ISSUE THREAD

**Issue by tejblum** [tmux/tmux#730]
tmux version 2.3

When I open my laptop and type
`$ ssh someserver tmux -CC attach`
tmux (on the 'someserver') just exits without any error message given (I missed the -t option to ssh). It is confusing. The following trivial patch cause tmux to print an error message, but I am not sure if it is right way:
[___.diff.txt](https://github.com/tmux/tmux/files/719250/___.diff.txt)

**Comment by nicm** [comment]
I have applied this but changed errx() to fprintf(stderr...) to match the others in the function. I think we don't use err() there because it prefixes "tmux: " which doesn't match with the error messages that come from the server... perhaps that is silly. Anyway it is changed, it should be in GitHub next time it syncs up. Thanks
