### ISSUE TITLE
Selecting more than one line with a mouse, while having more than one pane open, glitches out the others.

### ISSUE THREAD

**Issue by MrMino** [tmux/tmux#744]
After selecting more than one line with mouse when having two or more panes open, Tmux clutters up all the other panes, like this:

![screenshot from 2017-01-27 00-09-51](https://cloud.githubusercontent.com/assets/6691643/22354403/7e23116a-e425-11e6-9744-b554e6dda6d1.png)

Selecting less than one line, i.e. without going a single row below the start of the visual selection, or selecting rows where only a single one has any text, works fine,

Also, Tmux for some reason immediately jumps out of the selection, when mouse button is released, which seems like it's a bug rather than a feature (or am I missing something here?).

Steps to reproduce:
  - Have the following in `.tmux.conf`:
      `set-option -g mouse on`
  - Make one or more vertical split (horizontal splits don't share this behavior).
  - Select more than one line of text with a mouse

Tmux version as seen in `apt-cache policy`:
    `Installed: 2.1-3build1`

OS: Ubuntu Gnome 16.10

**Comment by nicm** [comment]
Turn off set-clipboard




On 26 Jan 2017 11:20 pm, "MrMino" <notifications@github.com> wrote:

After selecting more than one line with mouse (less than one, i.e. without
going a row below the start of the visual selection, or selecting another
row without any text, is fine), when having two or more panes open, tmux
clutters up all the other panes, like this:

[image: screenshot from 2017-01-27 00-09-51]
<https://cloud.githubusercontent.com/assets/6691643/22354403/7e23116a-e425-11e6-9744-b554e6dda6d1.png>

Also, Tmux for some reason immediately jumps out of the selection, when
mouse button is released.

Steps to reproduce:

   - Have the following in .tmux.conf:
   set-option -g mouse on
   - Make one or more vertical split (horizontal splits don't share this
   behavior).
   - Select more than one line of text with a mouse

Tmux version as seen in apt-cache policy:
Installed: 2.1-3build1

OS: Ubuntu Gnome 16.10

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/744>, or mute the thread

**Comment by MrMino** [comment]
Thank you, this seems to fix the problem.
