### ISSUE TITLE
Mode-key removal in master as of 2017-01-25

### ISSUE THREAD

**Issue by mathstuf** [tmux/tmux#753]
It looks like 0f9354eec211247fc83d1397d12c7e0708f70285 reverted much of bded7437064c76dd6cf4e76e558d826859adcc79. Was this intentional?

**Comment by nicm** [comment]
What did it revert?


On 31 Jan 2017 4:32 pm, "Ben Boeckel" <notifications@github.com> wrote:

It looks like 0f9354e
<https://github.com/tmux/tmux/commit/0f9354eec211247fc83d1397d12c7e0708f70285>
reverted much of bded743
<https://github.com/tmux/tmux/commit/bded7437064c76dd6cf4e76e558d826859adcc79>.
Was this intentional?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/753>, or mute the thread

**Comment by mathstuf** [comment]
It removes things like `-t $mode_table` flags to `bind-key`, `list-keys`, and `unbind-key` commands. I think that's all it removes, but I'm not that familiar with this part of the keybinding code.

**Comment by nicm** [comment]
Right but they weren't added in that previous commit, are you thinking of
-T? It was not removed.

**Comment by mathstuf** [comment]
Gah, grabbed the wrong commit. Looking again, is the `mode-table` stuff supposed to have been removed? In any case, if `master` looks like you intend, the commit message on the "Bad merge." commit was confusing me and feel free to close.

**Comment by nicm** [comment]
Yes all mode table code is gone.


On 31 Jan 2017 7:22 pm, "Ben Boeckel" <notifications@github.com> wrote:

Gah, grabbed the wrong commit. Looking again, is the mode-table stuff
supposed to have been removed? In any case, if master looks like you
intend, the commit message on the "Bad merge." commit was confusing me and
feel free to close.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/753#issuecomment-276463929>, or mute
the thread
