### ISSUE TITLE
Documentation for control mode

### ISSUE THREAD

**Issue by gnunn1** [tmux/tmux#763]
I'm the author of a tiling terminal emulator for Linux called Terminix (https://gnunn1.github.io/terminix-web). I'm interested in integrating Terminix with the tmux control mode however there doesn't seem to be much documentation around it beyond the brief description of it in the man page. 

Is there anywhere that describes the text protocol in more detail in terms of commands that can be sent, expected behaviors on notifications, etc?

**Comment by nicm** [comment]
Hi

Someone asked the same thing about a week ago:

George Nachman wrote a spec when he originally did the work, it is
probably on his site somewhere and will probably give you the basic
idea, although it is no doubt out of date in places.

Otherwise for anything beyond what is in the tmux manual, you will need
to look at the tmux and iterm2 code, but feel free to ask me questions
if you need to.

**Comment by gnunn1** [comment]
Thanks.
