### ISSUE TITLE
Loses truecolor switching windows

### ISSUE THREAD

**Issue by thejmazz** [tmux/tmux#775]
Running tmux 2.3 (`tmux-next=2.3~20170210~bzr3713+20-1ubuntu1~ppa0~ubuntu16.04.1` from [pi-rho](https://launchpad.net/~pi-rho/+archive/ubuntu/dev), `tmux -V` prints `tmux-next master`. Ubuntu 16.04 on Linux x86_64.

When switching windows, 24 bit colors/truecolor change:
![tmux-loses-color](https://cloud.githubusercontent.com/assets/1270998/22887240/4d377a52-f1cf-11e6-84ee-66ccc43bfba0.gif)

-  iTerm2 Build 3.0.20170210-nightly
- `$TERM` outside tmux is `xterm`
- `$TERM` inside tmux is `screen`
- `tmux` is aliased to `TERM=xterm-256color tmux-next`
- `set-option -ga terminal-overrides ",xterm-256color:Tc"` in `~/.tmux.conf`

I can switch windows on my local (client machine) tmux session without breaking colours, but the session inside ssh breaks on window switch (and with no local tmux as well).

I tried building from master but got:
```
./configure: line 4737: syntax error near unexpected token `newline'
./configure: line 4737: `PKG_CHECK_MODULES('
```

**Comment by nicm** [comment]
Try master please, you need to install pkg-config.




On 13 Feb 2017 2:33 pm, "Julian Mazzitelli" <notifications@github.com>
wrote:

Running tmux 2.3 (tmux-next=2.3~20170210~bzr3713+20-1ubuntu1~ppa0~
ubuntu16.04.1 from pi-rho
<https://launchpad.net/%7Epi-rho/+archive/ubuntu/dev>, tmux -V prints tmux-next
master. Ubuntu 16.04 on Linux x86_64.

When switching windows, 24 bit colors/truecolor change:
[image: tmux-loses-color]
<https://cloud.githubusercontent.com/assets/1270998/22887240/4d377a52-f1cf-11e6-84ee-66ccc43bfba0.gif>

   - iTerm2 Build 3.0.20170210-nightly
   - $TERM outside tmux is xterm
   - $TERM inside tmux is screen
   - tmux is aliased to TERM=xterm-256color tmux-next
   - set-option -ga terminal-overrides ",xterm-256color:Tc" in ~/.tmux.conf

I can switch windows on my local (client machine) tmux session without
breaking colours, but the session inside ssh breaks on window switch (and
with no local tmux as well).

I tried building from master but got:

./configure: line 4737: syntax error near unexpected token `newline'
./configure: line 4737: `PKG_CHECK_MODULES('

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/775>, or mute the thread

**Comment by thejmazz** [comment]
My bad, should not have given up on building so easily.

Problem persists on master.

**Comment by nicm** [comment]
Please run tmux from master with -vvvv, reproduce and show me the logs



On 13 Feb 2017 2:48 pm, "Julian Mazzitelli" <notifications@github.com>
wrote:

My bad, should not have given up on building so easily.

Problem persists on master.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/775#issuecomment-279412295>, or mute
the thread

**Comment by thejmazz** [comment]
Attached a session, ran 24-bit-color.sh, made a new window, went back to first window (colors wonky), exited:

```
1486997629.651099 client started (24927): version master, socket /tmp/tmux-1000/default, protocol 8
1486997629.651124 on Linux 2.6.32-042stab120.16 #1 SMP Tue Dec 13 20:58:28 MSK 2016; libevent 2.0.21-stable (poll)
1486997629.651159 socket is /tmp/tmux-1000/default
1486997629.651171 trying connect
1486997629.651238 add peer 0x25e53a0: 6 ((nil))
1486997629.651310 sending message 100 to peer 0x25e53a0 (4 bytes)
1486997629.651323 sending message 101 to peer 0x25e53a0 (15 bytes)
1486997629.651330 sending message 102 to peer 0x25e53a0 (11 bytes)
1486997629.651337 sending message 108 to peer 0x25e53a0 (21 bytes)
1486997629.651345 sending message 104 to peer 0x25e53a0 (0 bytes)
1486997629.651351 sending message 107 to peer 0x25e53a0 (4 bytes)
1486997629.651356 sending message 105 to peer 0x25e53a0 (20 bytes)
1486997629.651362 sending message 105 to peer 0x25e53a0 (108 bytes)
1486997629.651367 sending message 105 to peer 0x25e53a0 (23 bytes)
1486997629.651373 sending message 105 to peer 0x25e53a0 (14 bytes)
1486997629.651379 sending message 105 to peer 0x25e53a0 (16 bytes)
1486997629.651385 sending message 105 to peer 0x25e53a0 (22 bytes)
1486997629.651390 sending message 105 to peer 0x25e53a0 (35 bytes)
1486997629.651396 sending message 105 to peer 0x25e53a0 (23 bytes)
1486997629.651401 sending message 105 to peer 0x25e53a0 (19 bytes)
1486997629.651406 sending message 105 to peer 0x25e53a0 (26 bytes)
1486997629.651410 sending message 105 to peer 0x25e53a0 (12 bytes)
1486997629.651416 sending message 105 to peer 0x25e53a0 (1416 bytes)
1486997629.651425 sending message 105 to peer 0x25e53a0 (20 bytes)
1486997629.651431 sending message 105 to peer 0x25e53a0 (22 bytes)
1486997629.651436 sending message 105 to peer 0x25e53a0 (178 bytes)
1486997629.651441 sending message 105 to peer 0x25e53a0 (23 bytes)
1486997629.651447 sending message 105 to peer 0x25e53a0 (46 bytes)
1486997629.651453 sending message 105 to peer 0x25e53a0 (25 bytes)
1486997629.651458 sending message 105 to peer 0x25e53a0 (8 bytes)
1486997629.651464 sending message 105 to peer 0x25e53a0 (18 bytes)
1486997629.651470 sending message 105 to peer 0x25e53a0 (19 bytes)
1486997629.651475 sending message 105 to peer 0x25e53a0 (15 bytes)
1486997629.651481 sending message 105 to peer 0x25e53a0 (55 bytes)
1486997629.651486 sending message 105 to peer 0x25e53a0 (51 bytes)
1486997629.651492 sending message 105 to peer 0x25e53a0 (32 bytes)
1486997629.651497 sending message 105 to peer 0x25e53a0 (42 bytes)
1486997629.651502 sending message 105 to peer 0x25e53a0 (31 bytes)
1486997629.651507 sending message 105 to peer 0x25e53a0 (34 bytes)
1486997629.651512 sending message 105 to peer 0x25e53a0 (9 bytes)
1486997629.651517 sending message 105 to peer 0x25e53a0 (16 bytes)
1486997629.651522 sending message 106 to peer 0x25e53a0 (0 bytes)
1486997629.651530 sending message 200 to peer 0x25e53a0 (4 bytes)
1486997629.651535 client loop enter
1486997629.653334 peer 0x25e53a0 message 207
1486997629.653351 sending message 208 to peer 0x25e53a0 (0 bytes)
1486997653.069817 peer 0x25e53a0 message 201
1486997653.069843 sending message 205 to peer 0x25e53a0 (0 bytes)
1486997653.069998 peer 0x25e53a0 message 204
1486997653.070007 client loop exit
```

I think it has something to do with the way the screen is redrawn: for example, if I visually select over a bunch of lines in nvim those get "cleaned up".

**Comment by nicm** [comment]
You did not restart tmux entirely or you would have a server log file as
well. Make sure you stop tmux completely before testing.

**Comment by thejmazz** [comment]
From inside tmux repo:

1. `TERM=xterm-256color ./tmux -vvvv`
2.  `~/24-bit-colors.sh`
3. new window
4. back to first window (colors wonky)
5. detach
6. `./tmux kill-server`

- [tmux-server-26367.log](https://procedural.life/tmux-share/tmux-server-26367.log?raw=true)
- [tmux-client-26365.log](https://procedural.life/tmux-share/tmux-client-26365.log?raw=true)
- [tmux-out-26367.log](https://procedural.life/tmux-share/tmux-out-26367.log?raw=true)

I also managed to grab an out log with correct colors:
- [tmux-out-27542.log](https://procedural.life/tmux-share/tmux-out-27542.log?raw=true)

**Comment by nicm** [comment]
I have fixed this in OpenBSD now, it should be in GitHub in a few hours. You were never running tmux 2.3, this bug was only ever present in master. Please test when when the fix appears (look for "Collected cells may still need to be extended for RGB colours.") and let me know if there are still problems.
