### ISSUE TITLE
tmux should ignore Ctrl+Z ( bg ) command 

### ISSUE THREAD

**Issue by vmindru** [tmux/tmux#788]
While in TMUX session press Ctrl+B then Ctrl+Z tmux will move into background job, I  find this behavior undesired :( is it possible to somehow force tmux to ignore bg command?

**Comment by nicm** [comment]
Unbind the C-z key.




On 19 Feb 2017 8:50 pm, "Veaceslav Mindru" <notifications@github.com> wrote:

While in TMUX session press Ctrl+B then Ctrl+Z tmux will move into
background job, I find this behavior undesired :( is it possible to somehow
force tmux to ignore bg command?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/788>, or mute the thread

**Comment by vmindru** [comment]
that was easy, thanks !
