### ISSUE TITLE
characters for borders

### ISSUE THREAD

**Issue by fpusersuggest** [tmux/tmux#793]
Hi, I have a tmux on openbsd 6.0. Installed by pkg_add
tmux -V give me "unknown option" error.
then I don't know what version it is.
Platform: OpenBSD 6.0 amd64
Problem: In console tmux give me many ??? for horizontal and vertical splitted windows borders.
TERM=wsvt25 (outside tmux)
TERM=wsvt25 (inside tmux)
this is the default beahaviour without config.
I can't make a screenshot.

**Comment by nicm** [comment]
Unset LANG and LC_ALL and LC_CTYPE before running tmux in the console.


On 21 Feb 2017 6:03 pm, "fpusersuggest" <notifications@github.com> wrote:

Hi, I have a tmux on openbsd 6.0. Installed by pkg_add
tmux -V give me "unknown option" error.
then I don't know what version it is.
Platform: OpenBSD 6.0 amd64
Problem: In console tmux give me many ??? for horizontal and vertical
splitted windows borders.
TERM=wsvt25 (outside tmux)
TERM=wsvt25 (inside tmux)
this is the default beahaviour without config.
I can't make a screenshot.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/793>, or mute the thread

**Comment by fpusersuggest** [comment]
I have "unset LANG", "unset LC_ALL" and "unset LC_CTYPE"
but nothing was changed. Also something strange was happened... I mean I can't unset LC_CTYPE.. with locale command it continues to give me LC_CTYPE="C"

**Comment by nicm** [comment]
Are you running tmux with -u (don't)

**Comment by fpusersuggest** [comment]
ok... now LC_CTYPE was unsetted.
No, I don't run tmux -u

**Comment by fpusersuggest** [comment]
with tmux -u ti give me many â

**Comment by fpusersuggest** [comment]
ok, looks it works with
set-option -ga terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@'
in .tmux.conf

**Comment by nicm** [comment]
Hmm OK the problem is not what I thought, forget about LC_ALL and LC_CTYPE and LANG. Yes that was what I was going to suggest next, apparently wscons doesn't support ACS even though TERM says it does.

**Comment by nicm** [comment]
Which is weird cos the code says it should support it.

**Comment by nicm** [comment]
If you do this it would be better:

set-option -ga terminal-overrides ',wsvt*:enacs@:smacs@:rmacs@:acsc@'

Then other TERM settings will not be affected.

**Comment by fpusersuggest** [comment]
yes, Thank you :-)
