### ISSUE TITLE
Allow multi-line status bar or status bar padding

### ISSUE THREAD

**Issue by st3fan** [tmux/tmux#795]
It would be great if the status bar could be two lines. I am mostly asking because I would like to have a blank line of padding under (or above) the status bar.

**Comment by tardypad** [comment]
I assume you want a padding **below** your **top** status bar, or **above** you **bottom** status bar

I wanted to have such kind of feature as well, mainly to separate my bottom status bar from vim's command line just above.

What I did is use `setw -g pane-border-status bottom`
With this you don't exactly get what you asked (you get a regular pane border line, not an empty line) but it probably fulfill your need too.

And you can customize the pane text displayed in that line with `pane-border-format`
I use `setw -g pane-border-format ' #{pane_current_command} '` for example but you can trick it and use `setw -g pane-border-format '─'` if you just want a full line to be displayed

**Comment by nicm** [comment]
There was some discussion of this before, and I did have it working, but there wasn't really enough interest in it from anyone else and I'm not really convinced it is as useful as it sounds anyway.

**Comment by gmile** [comment]
@nicm I would really want to have 2 lines for status line component. But second line would ideally be able to contain any custom output, not be just blank decoration line.

This would elegantly solve the request I once posted on the [mailing list](https://groups.google.com/forum/#!topic/tmux-users/aj4Iiawo9Ts), where I proposed a way to always display a list of sessions.

Having a second line of output would make it possible to render a list of sessions into it, highlight currently selected session, etc. – all via some a 3rd party code / plugin.

**Comment by unphased** [comment]
Here is practical use case for this.  Say you want to run multiple tall tmux windows side by side. they don't leave much room, with only one line to work with in the status bar. Usually the main things that I end up using which are present in the status bar are the CWD of the active pane, and (funny enough) the current time.

the working directory is useful because you can just go in and copy it using the terminal to grab it. But what this often means is that it is a pretty lengthy segment. It is often truncated, and doubly so when the terminal isn't a fullscreen one.

It seems like being able to conditionally shuffle the layout into a two-liner or three-liner statusline depending on the host tty width would be ideal!


This much flexibility would be tricky, though, for sure.

**Comment by karakays** [comment]
Adding an empty status bar for each pane might help on this.

**Comment by sflip** [comment]
Tmux 2.9 now supports status bars with multiple lines, see [here](https://github.com/tmux/tmux/blob/master/CHANGES).

**Comment by charlietag** [comment]
This is how I I accomplish multiple status bars.
First line (status-format[0]) - window part
Second line (status-format[1]) - status-left / status-right part

https://github.com/charlietag/tmux-split-statusbar
