### ISSUE TITLE
Vim syntax generator

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#796]
I have a script I wrote for generating a Vim syntax file from the tmux source code: https://github.com/ericpruitt/static-unix-userland/blob/master/make-tmux-syntax.awk

Would you be willing to accept a pull request with a script similar to this one? The most significant change I would make if I were to submit a pull request would be to split out the template, shell and Awk code into separate files.

**Comment by nicm** [comment]
Hi

We are not carrying around miscellaneous scripts for various programs in
tmux anymore, you could see if Vim themselves want to include it, or if
not then host it yourself. We already point to a Vim syntax file in
README, I can change it to point to yours, but you will need to confirm
with the person who currently maintains it because I don't want to link
to two.

Thanks

**Comment by ericpruitt** [comment]
Alright, I will contact the author of the current syntax file currently linked in the README. If they agree to let the link to their syntax file be replaced, I will create a separate repository just for the syntax generation script and setup a cron job to automatically generate the *.vim file once a day.

**Comment by keith** [comment]
Fine with me!

**Comment by ericpruitt** [comment]
Thanks, Keith.

@nicm , these are the new URLs:

- https://github.com/ericpruitt/tmux.vim/
- https://raw.githubusercontent.com/ericpruitt/tmux.vim/master/vim/syntax/tmux.vim

**Comment by nicm** [comment]
Changed, thanks.
