### ISSUE TITLE
status-interval not working

### ISSUE THREAD

**Issue by rpellerin** [tmux/tmux#797]
Hello,

I just cloned the repo, from `master` and installed tmux, although I've been using it for a couple of years. I believe the version is 2.3 (or 2.4?).
I'm using Xubuntu 16.04 and gnome-terminal.

```bash
$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux master
tmux-256color
```

Here is an extract of my `.tmux.conf`:

```text
set -g default-terminal "tmux-256color"
set -g status-interval 60
tm_time='#[fg=colour255]%a %h-%d %H:%M:%S'
set -g status-right $tm_weather' '$tm_separator' '$tm_battery' '$tm_separator' '$tm_time
```

I restarted tmux. When I look at the status bar, it gets refreshed way more often than 60 seconds. `$tm_time` shows the seconds, that's how I know.

How come and how to fix this? It is kind of troublesome for me since `$tm_weather` makes API calls.

Thanks a lot!

**Comment by nicm** [comment]
status-interval is a maximum not a mininum. If you are using tmux and it needs to redraw the status line more often, it will. It won't run #() more than once a second though.

**Comment by rpellerin** [comment]
When does it need to redraw? What is it based on?

**Comment by nicm** [comment]
Depends what you are doing.

**Comment by nicm** [comment]
If you don't touch it at all, how often do the seconds change?

**Comment by rpellerin** [comment]
It's very variable, sometimes twice a minute, sometimes every second or so. Here is a gif of my screen (it last for about a minute, watch till the end to witness the weird behavior). Look at the bottom right corner.
![out](https://cloud.githubusercontent.com/assets/5323445/23344985/2bdafd36-fc3b-11e6-81ea-c0d3c0f6d673.gif)

**Comment by nicm** [comment]
If you take out your #() command does the problem go away if you do the
same (start tmux then not touch it)?



On 26 Feb 2017 11:49 pm, "Romain Pellerin" <notifications@github.com> wrote:

It's very variable, sometimes twice a minute, sometimes every second or so.
Here is a gif of my screen (it last for about a minute, watch till the end
to witness the weird behavior). Look at the bottom right corner.
[image: out]
<https://cloud.githubusercontent.com/assets/5323445/23344985/2bdafd36-fc3b-11e6-81ea-c0d3c0f6d673.gif>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/797#issuecomment-282599307>, or mute
the thread

**Comment by rpellerin** [comment]
Not as much, but the behavior is still very unpredictable.

**Comment by nicm** [comment]
Show me logs please from reproducing with a simple config.

**Comment by rpellerin** [comment]
`tmux-server-*.log`?
I investigated the problem. It seems that without my #() which makes API calls, there are no random updates. It occurs only when hitting `prefix` (C-b), even though I don't necessarily add panes/windows etc. Is this a normal behavior? Any ideas about why my #() triggers refresh?

**Comment by nicm** [comment]
tmux will update the status line when the command finishes in order to use
the latest output, but it should not run the command again unless it is
more than 1 second since the last update. Pressing C-b updates the status
line because people may have bits in the status line that depend on the
prefix state. It will only redraw it onto the screen if it has actually
changed though, you are getting a redraw because you have %S.

If your command routinely takes more than 1 second to run it is not  a good
idea to put it in the status line. Run it separately (in the background  or
from cron) and have tmux read the output from a file.



On 1 Mar 2017 7:42 am, "Romain Pellerin" <notifications@github.com> wrote:

tmux-server-*.log?
I investigated the problem. It seems that without my #() which makes API
calls, there are no random updates. It occurs only when hitting prefix
(C-b), even though I don't necessarily add panes/windows etc. Is this a
normal behavior? Any ideas about why my #() triggers refresh?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/797#issuecomment-283268081>, or mute
the thread

**Comment by rpellerin** [comment]
Got it, thanks for the additional information. The cron job sounds like a good idea.
Thanks again!
