### ISSUE TITLE
split-window does not draw active pane border when using "-b".

### ISSUE THREAD

**Issue by MadMaverick9** [tmux/tmux#798]
```
tmux -f /tmp/tmux.conf
```
Then do a "split-window -b -h".

The pane on the left should have an active border, but it does not.

Without the "-b", it works as expected (aka. the pane on the right has an active border)..

/tmp/tmux.conf:
```
#
set-option -g pane-border-style 'bg=blue,fg=colour226'
set-option -g pane-active-border-style 'bg=colour88,fg=colour226'
#
```
Other information:
```
bash $ uname -sp
Linux Intel(R) Pentium(R) Dual  CPU  E2160  @ 1.80GHz
bash $ ./tmux -V
tmux 2.3
bash $ echo $TERM
rxvt-unicode-256color
bash $
```
Inside a pane in tmux:
```
bash $ echo $TERM
screen
```
And I tested git master as well. Same problem.
```
bash $ ./tmux -V
tmux master
```
Thank you.

**Comment by nicm** [comment]
I can reproduce this; I think it is because we end up with the pane indexes in a different order (1 on the left, 0 on the right), which probably confuses the code that works out whether the x,y of the border is in the active or inactive cell. I think we should avoid getting the pane indexes this way round.

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/803068/x.diff.txt)

**Comment by MadMaverick9** [comment]
That worked. Thanks for your quick reply and fix.

**Comment by nicm** [comment]
Applied a similar change,thanks!
