### ISSUE TITLE
Select words on double-click

### ISSUE THREAD

**Issue by xordspar0** [tmux/tmux#802]
System details:
- Mac OS X & iterm2
- tmux 2.3
- $TERM: screen

With mouse mode on, you can copy text by dragging the mouse over the text you want to copy, however, normally in the terminal you can select whole words quickly by double-clicking. tmux overrides this behavior when in mouse mode. You should be able to select and copy words in tmux by double-clicking on them.

**Comment by nicm** [comment]
Certainly could. This is already in the TODO file.

**Comment by xordspar0** [comment]
Ok, thanks for pointing that out. If no one is already working on that and there's no plan for it, I can dive in and write a patch.

**Comment by nicm** [comment]
Actually I misread this - selecting by double clicking already works. It is selecting whole words by /dragging/ that is not supported.

**Comment by xordspar0** [comment]
Oh, great. What version was that added in? Is it released already? Is there a configuration option I have to turn on, or is there just a problem at my end?

**Comment by nicm** [comment]
It's in master, will be in next release

On 8 Mar 2017 10:04 pm, "Jordan Christiansen" <notifications@github.com>
wrote:

Oh, great. What version was that added in? Is it released already? Is there
a configuration option I have to turn on, or is there just a problem at my
end?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/802#issuecomment-285184740>, or mute
the thread
