### ISSUE TITLE
Feature Request: add "set-pane-title" command

### ISSUE THREAD

**Issue by mahescho** [tmux/tmux#807]
It would be nice to have a "rename-pane" command. The solution with using "send-keys" and a escape sequens is neither elegant nor straight forward nor institutive :-) This wold really help when scripting Tmux.

**Comment by nicm** [comment]
Panes don't have names.



On 5 Mar 2017 2:35 pm, "Matthias Henze" <notifications@github.com> wrote:

It would be nice to have a "rename-pane" command. The solution with using
"send-keys" and a escape sequens is neither elegant nor straight forward
nor institutive :-) This wold really help when scripting Tmux.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/807>, or mute the thread

**Comment by mahescho** [comment]
Ok .... set-pane-title .... better?

https://github.com/tmux/tmux/issues/680

**Comment by nicm** [comment]
Did you try the patch in the issue you linked to?
