### ISSUE TITLE
tmux -V returning "master" instead of version number

### ISSUE THREAD

**Issue by agrajag9** [tmux/tmux#810]
When compiling from source in github, `PACKAGE_VERSION='master'` and `PACKAGE_STRING='tmux master'`. This results in a compiled binary that returns `tmux master` to the command `tmux -V` instead of a useful version number. This in turn causes problems for other codebases that rely on determining tmux versions for integration (e.g. powerline).

**Comment by ThomasAdam** [comment]
Seems this changed in c0346701dfa2a4aa4c2ea6f05157406bcfb7a50b

**Comment by nicm** [comment]
This is intentional, programs should not rely on the format of tmux -V.



On 6 Mar 2017 10:48 pm, "agrajag9" <notifications@github.com> wrote:

When compiling from source in github, PACKAGE_VERSION='master' and
PACKAGE_STRING='tmux
master'. This results in a compiled binary that returns tmux master to the
command tmux -V instead of a useful version number. This in turn causes
problems for other codebases that rely on determining tmux versions for
integration (e.g. powerline).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/810>, or mute the thread

**Comment by agrajag9** [comment]
Feature request: version numbering.

**Comment by nicm** [comment]
Releases are versioned, master is not. There is no reason that "2.4" meaning one of 2.4-release or master is any better than "2.4" meaning 2.4-release and master meaning master, and there are advantages to the latter.

**Comment by ZyX-I** [comment]
> This is intentional, programs should not rely on the format of tmux -V.

If programs should not rely on this format how they are supposed to get tmux version? It is much more strong statement then refusing to output version number in git builds.

Also what are advantages of not showing version number on master? I think that best variant is something like `v0.2.0-827-gff6fa39`: this is Neovim version. Basically the output of `git describe`: contains last release version, number of commits since then and actually used hash. This, of course, does not work for non-VCS builds, but most of time it is good.

**Comment by nicm** [comment]
They should not rely on the format always being the same, if they break
because tomorrow we decide to call the next version tmux 'Randy Rabbit'
2017 instead of 2.4 then it is a bug.

I don't want Git to be a build time dependency, so 'x.y' or 'master' is the
most we can do without that.


On 6 Mar 2017 11:46 pm, "Nikolai Aleksandrovich Pavlov" <
notifications@github.com> wrote:

This is intentional, programs should not rely on the format of tmux -V.

If programs should not rely on this format how they are supposed to get
tmux version? It is much more strong statement then refusing to output
version number in git builds.

Also what are advantages of not showing version number on master? I think
that best variant is something like v0.2.0-827-gff6fa39: this is Neovim
version. Basically the output of git describe: contains last release
version, number of commits since then and actually used hash. This, of
course, does not work for non-VCS builds, but most of time it is good.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/810#issuecomment-284572523>, or mute
the thread

**Comment by nicm** [comment]
We could do '2.3-master' instead of plain 'master' I suppose, but I'm not
sure it is worth changing it again, it only matters if it is /some/ Git
build and not a specific release.


On 7 Mar 2017 6:11 am, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

They should not rely on the format always being the same, if they break
because tomorrow we decide to call the next version tmux 'Randy Rabbit'
2017 instead of 2.4 then it is a bug.

I don't want Git to be a build time dependency, so 'x.y' or 'master' is the
most we can do without that.



On 6 Mar 2017 11:46 pm, "Nikolai Aleksandrovich Pavlov" <
notifications@github.com> wrote:

This is intentional, programs should not rely on the format of tmux -V.

If programs should not rely on this format how they are supposed to get
tmux version? It is much more strong statement then refusing to output
version number in git builds.

Also what are advantages of not showing version number on master? I think
that best variant is something like v0.2.0-827-gff6fa39: this is Neovim
version. Basically the output of git describe: contains last release
version, number of commits since then and actually used hash. This, of
course, does not work for non-VCS builds, but most of time it is good.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/810#issuecomment-284572523>, or mute
the thread

**Comment by surmish** [comment]
How do I find out the version number of my tmux installed?

**Comment by seanspotatobusiness** [comment]
I installed tmux via some commands I found to compile from github and now my version says 'master' and I've no way of knowing what version that really is. I presume 2.7 or similar.

**Comment by AMV007** [comment]
Ok, looking like it's dead end, so I wrote simple script to compile tmux locally with correct version:
https://github.com/AMV007/tmux_install

**Comment by tomskopek** [comment]
I would like to see this re-opened, `tmux master` is not helpful.

For example - I was just installing tmuxinator and it says it does not work in tmux 2.5.
How is one to know that they are not running 2.5?

Out of interest, at the moment, what other results could `tmux -V` output? Other than `tmux master` I mean?

**Comment by chros73** [comment]
You can [easily modify](https://github.com/chros73/build-tmux/blob/master/build.sh#L338) it to display anything before compiling.
