### ISSUE TITLE
Inconsistent #{session_name} in after-switch-client hook

### ISSUE THREAD

**Issue by dmendel** [tmux/tmux#811]
```
$ uname -sp && tmux -V && echo $TERM                                         
Linux x86_64
tmux 2.3
xterm-256color
```

Initial setup is as below. The intent is to use the `after-switch-client` hook to capture both the *from* and the *to* session when the client switches between sessions.
```
tmux new-session -d -s s1
tmux new-session -d -s s2
tmux set-hook -g after-switch-client 'run-shell "echo Switch from #{client_last_session} to #{session_name} >> /tmp/tmux.log"'
```

We enter session *s1*.
```
tmux attach-session -t s1
```

and then switch to session *s2* and back to *s1*. The values of `client_last_session` and `session_name` are as expected.
```
tmux switch-client -t s2 ; tmux switch-client -t s1
cat /tmp/tmux.log ; rm /tmp/tmux.log
```

Output of `/tmp/tmux.log`
```
Switch from s1 to s2
Switch from s2 to s1
```

However, now executing `switch-client` with `-n` results in an unexpected value of `session_name`. We experience the same with `-p` or `-l`.

```
tmux switch-client -n
cat /tmp/tmux.log
```

Output of `/tmp/tmux.log`
```
Switch from s1 to s1
```

We expect the output to be `s1 to s2`, but is `s1 to s1`. ie. The value of `session_name` is not as expected.

To clarify, `switch-client -t target-session` sets the value of `session_name` (inside the `after-switch-client` hook) to  the target session as expected.

`switch-client` with `-l`, `-n` or `-p` doesn't set `session_name` to the session being switched *to*, but leaves it as the session being switched *from*.

**Comment by nicm** [comment]
What if you use hook_session or hook_session_name?




On 7 Mar 2017 4:11 am, "Dion Mendel" <notifications@github.com> wrote:

$ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.3
xterm-256color

Initial setup is as below. The intent is to use the after-switch-client
hook to capture both the *from* and the *to* session when the client
switches between sessions.

tmux new-session -d -s s1
tmux new-session -d -s s2
tmux set-hook -g after-switch-client 'run-shell "echo Switch from
#{client_last_session} to #{session_name} >> /tmp/tmux.log"'

We enter session *s1*.

tmux attach-session -t s1

and then switch to session *s2* and back to *s1*. The values of
client_last_session and session_name are as expected.

tmux switch-client -t s2 ; tmux switch-client -t s1
cat /tmp/tmux.log ; rm /tmp/tmux.log

Output of /tmp/tmux.log

Switch from s1 to s2
Switch from s2 to s1

However, now executing switch-client with -n results in an unexpected value
of session_name. We experience the same with -p or -l.

tmux switch-client -n
cat /tmp/tmux.log

Output of /tmp/tmux.log

Switch from s1 to s1

We expect the output to be s1 to s2, but is s1 to s1. ie. The value of
session_name is not as expected.

To clarify, switch-client -t target-session sets the value of session_name
(inside the after-switch-client hook) to the target session as expected.

switch-client with -l, -n or -p doesn't set session_name to the session
being switched *to*, but leaves it as the session being switched *from*.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/811>, or mute the thread

**Comment by dmendel** [comment]
Are `hook_session` or `hook_session_name` tmux variables? I can't find them in the manpage and when I try them they appear to be empty.

**Comment by nicm** [comment]
You will need to build tmux from Git master, hooks in 2.3 were early in
development and there have been substantial changes.


On 7 Mar 2017 6:22 am, "Dion Mendel" <notifications@github.com> wrote:

Are hook_session or hook_session_name tmux variables? I can't find them in
the manpage and when I try them they appear to be empty.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/811#issuecomment-284633226>, or mute
the thread

**Comment by nicm** [comment]
I am pretty sure in 2.3 hooks did not make any attempt to take account of
the session changing, so what you are seeing is expected. I can't guarantee
master will work any better but at least it is intended to do it.

On 7 Mar 2017 6:26 am, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

You will need to build tmux from Git master, hooks in 2.3 were early in
development and there have been substantial changes.


On 7 Mar 2017 6:22 am, "Dion Mendel" <notifications@github.com> wrote:

Are hook_session or hook_session_name tmux variables? I can't find them in
the manpage and when I try them they appear to be empty.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/811#issuecomment-284633226>, or mute
the thread

**Comment by dmendel** [comment]
Okay, thanks. I'll check again when 2.4 is released.
