### ISSUE TITLE
paste doesn't work correct when paste to a remote server

### ISSUE THREAD

**Issue by wqhhust** [tmux/tmux#812]
In my local ubuntu linux tmux, I ssh to a remote solaris, and then from that remote ssh to the target solaris target. When I paste "initLookup" (from system clipboard by using plugin of tmux-yank) to the target solaris shell, it show "iitLookupn", but the thing I want to past is "initLookup". What's the possible reason? 

If in the same tmux,  open a terminate by using ssh oracle@localhost, and then in that terminal, paste work. So it works for linux, but not on solaris.

**Comment by nicm** [comment]
Have you rebound your  n key in tmux?


On 7 Mar 2017 6:52 am, "wqhhust" <notifications@github.com> wrote:

In my local ubuntu linux tmux, I ssh to a remote solaris, and then from
that remote ssh to the target solaris target. When I paste "initLookup"
(from system clipboard by using plugin of tmux-yank) to the target solaris
shell, it show "iitLookupn", but the thing I want to past is "initLookup".
What's the possible reason?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/812>, or mute the thread

**Comment by wqhhust** [comment]
I did rebound. One thing forgot to mention is that I am using Ctrl+Shift+v to do the paste inside tmux, since I am in gnome-terminal, It's possible to use Ctrl+Shift+v.  And since the buffer I want to paste is from system clipboard, so I can't use tmux binding, because that buffer is not available to tmux.

**Comment by nicm** [comment]
What is your n key bound to without the prefix, look at tmux lsk

**Comment by wqhhust** [comment]
Is the following bounding what you said n key bound?

`bind-key    -T root   n                run-shell "tmux send-keys 'n'; /home/oracle/.tmux/plugins/tmux-copycat/scripts/copycat_jump.sh 'next'; true"
`

**Comment by nicm** [comment]
This is the problem, this binding will delay the n but not the other keys
so it will be out of order.

On 7 Mar 2017 7:55 am, "wqhhust" <notifications@github.com> wrote:

Is the following bounding what you said n key bound?

bind-key -T root n run-shell "tmux send-keys 'n';
/home/oracle/.tmux/plugins/tmux-copycat/scripts/copycat_jump.sh 'next';
true"

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/812#issuecomment-284648318>, or mute
the thread

**Comment by wqhhust** [comment]
Thanks a lot. But that binding comes from plugin of tmux-copycat. How to fix it? Weird thing is that if run on local terminal, it works, only on remote solaris it has such issue. Is because there are long latency to the remote solaris server?

**Comment by nicm** [comment]
You should talk to the people who wrote this plugin.


On 7 Mar 2017 8:11 am, "wqhhust" <notifications@github.com> wrote:

Thanks a lot. But that binding comes from plugin of tmux-copycat. How to
fix it? Weird thing is that if run on local terminal, it works, only on
remote solaris it has such issue. Is because there are long latency to the
remote solaris server?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/812#issuecomment-284651374>, or mute
the thread
