### ISSUE TITLE
Tmux doesn't work without utf-8 locale

### ISSUE THREAD

**Issue by DmitryHetman** [tmux/tmux#815]
Platform: Gentoo nomultilib experimental
Can't run tmux without utf-8 locale.
Also, seems like utf-8 symbols used for border. use | instead.

**Comment by DmitryHetman** [comment]
![wayland-screenshot](https://cloud.githubusercontent.com/assets/18743742/23696050/f849afde-03d9-11e7-93ef-c1801c0938f3.png)

**Comment by nicm** [comment]
tmux requires either en_US.UTF-8 to be available or a different UTF-8
locale to be specified in LC_ALL. If you install en_US.UTF-8 it should work.


On 8 Mar 2017 8:33 am, "Dmitry" <notifications@github.com> wrote:

Platform: Gentoo nomultilib experimental
Can't run tmux without utf-8 locale.
Also, seems like utf-8 symbols used for border. use | instead.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/815>, or mute the thread

**Comment by DmitryHetman** [comment]
Why install locale for tmux? Remove utf-8 from tmux impossible? Can you create separate 'make' option for including utf-8?

**Comment by nicm** [comment]
No, tmux only supports UTF-8 and depends on working UTF-8 in libc. You do
not have to use a UTF-8 terminal but tmux itself needs UTF-8.


On 8 Mar 2017 8:41 am, "Dmitry" <notifications@github.com> wrote:

Why install locale for tmux? Remove utf-8 from tmux impossible? Can you
create separate 'make' option for including utf-8?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/815#issuecomment-284980983>, or mute
the thread
