### ISSUE TITLE
tmux draws jibberish when I click-drag select text in nano with the mouse

### ISSUE THREAD

**Issue by dmalyuta** [tmux/tmux#816]
- Platform: Ubuntu 14.04
- Problem: with mouse mode turned on, tmux draws weird characters at the border of a split when I left mouse click and drag with the mouse over text in the `nano` editor:
![jibberish](http://i.imgur.com/nUwUkb9.png)
- tmux config:
```
# look good
set-option -g default-terminal "screen-256color"

# remap prefix to Ctrl+x (Emacs style)
set -g prefix C-x
# bind 'C-x C-x' to type 'C-x'
bind C-x send-prefix
unbind C-b

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Ctrl-arrow
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up select-pane -U
bind -n C-Down select-pane -D

# Resize pane splits quicker
bind-key -n M-Up resize-pane -U 1
bind-key -n M-Down resize-pane -D 1
bind-key -n M-Left resize-pane -L 1
bind-key -n M-Right resize-pane -R 1

# don't rename windows automatically
set-option -g allow-rename off

# window resizing
set-window-option -g aggressive-resize

# navigate using Emacs keys
setw -g mode-keys emacs

# Enable mouse support (works in iTerm)
set-option -g -q mouse on
#set -g mouse-utf8 off
# make mousewheel work when not in copy mode
bind-key -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"
bind-key -t vi-copy WheelUpPane halfpage-up
bind-key -t vi-copy WheelDownPane halfpage-down

# Allows for faster key repetition
set -s escape-time 0

# Highlight active window in tab-bar at bottom in red
set-window-option -g window-status-current-bg red

# move current window left and right in the tab list, respectively.
bind '<' swap-window -t -1
bind '>' swap-window -t +1
```
- Terminal: terminator 0.98 (also happens in regular Ubuntu GNOME terminal 3.6.2), $TERM=screen-256color inside tmux and $TERM=xterm outside tmux

```
~ $ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.3
xterm
```

This error is not reproducible with `tmux -vvvv -Ltest -f/dev/null new` since mouse mode is not enabled by default. Jibberish is only output when click-and-drag selecting text in nano with mouse mode enabled.  The same issue occurs with `vim`, but not with `emacs -nw`.

**Comment by nicm** [comment]
Probably you have set-clipboard on (the default) and are using TERM=xterm
outside tmux but in a terminal that is not xterm and doesn't support the
xterm clipboard escape sequences. Either turn set-clipboard off or use a
more suitable TERM for your terminal.



On 8 Mar 2017 9:07 am, "Danylo Malyuta" <notifications@github.com> wrote:


   - Platform: Ubuntu 14.04
   - Problem: with mouse mode turned on, tmux draws weird characters at the
   border of a split when I click and drag with the mouse over text in the
   nano editor:
   [image: jibberish]
   <https://camo.githubusercontent.com/41bff7022bc888db26436c233e664f0aa5d9cb3f/687474703a2f2f692e696d6775722e636f6d2f6e5577556b62392e706e67>
   - tmux config:

# look good
set-option -g default-terminal "screen-256color"

# remap prefix to Ctrl+x (Emacs style)
set -g prefix C-x
# bind 'C-x C-x' to type 'C-x'
bind C-x send-prefix
unbind C-b

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you
want to use)
bind r source-file ~/.tmux.conf

# switch panes using Ctrl-arrow
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up select-pane -U
bind -n C-Down select-pane -D

# Resize pane splits quicker
bind-key -n M-Up resize-pane -U 1
bind-key -n M-Down resize-pane -D 1
bind-key -n M-Left resize-pane -L 1
bind-key -n M-Right resize-pane -R 1

# don't rename windows automatically
set-option -g allow-rename off

# window resizing
set-window-option -g aggressive-resize

# navigate using Emacs keys
setw -g mode-keys emacs

# Enable mouse support (works in iTerm)
set-option -g -q mouse on
#set -g mouse-utf8 off
# make mousewheel work when not in copy mode
bind-key -T root WheelUpPane if-shell -F -t = "#{alternate_on}"
"send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -T root WheelDownPane if-shell -F -t = "#{alternate_on}"
"send-keys -M" "select-pane -t =; send-keys -M"
bind-key -t vi-copy WheelUpPane halfpage-up
bind-key -t vi-copy WheelDownPane halfpage-down

# Allows for faster key repetition
set -s escape-time 0

# Highlight active window in tab-bar at bottom in red
set-window-option -g window-status-current-bg red

# move current window left and right in the tab list, respectively.
bind '<' swap-window -t -1
bind '>' swap-window -t +1


   - Terminal: terminator 0.98 (also happens in regular Ubuntu GNOME
   terminal 3.6.2), $TERM=screen-256color inside tmux and $TERM=xterm outside
   tmux

~ $ uname -sp && tmux -V && echo $TERM
Linux x86_64
tmux 2.3
xterm

This error is not reproducible with tmux -vvvv -Ltest -f/dev/null new since
mouse mode is not enabled by default. Jibberish is only output when
click-and-drag selecting text in nano with mouse mode enabled. The same
issue occurs with vim, but not with emacs -nw.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/816>, or mute the thread

**Comment by dmalyuta** [comment]
> Either turn set-clipboard off
How?

>  use a more suitable TERM for your terminal.
Which one and how?

**Comment by nicm** [comment]
set-option -g set-clipboard off

**Comment by dmalyuta** [comment]
And the suitable TERM?

**Comment by nicm** [comment]
You can ask the people who wrote your terminal, or look at the terminfo
database for it. Gnome terminal you can try "gnome".
