### ISSUE TITLE
where is the help command?

### ISSUE THREAD

**Issue by nathantech2005** [tmux/tmux#838]
Why is there no standard linux convention --help or -h command for tmux?

**Comment by nicm** [comment]
It is not standard and we do not have it. Read the manual instead.

**Comment by krader1961** [comment]
FWIW, I mostly agree with @nicm. While many commands implement `-h`, `-?` and `--help` it is not a "standard". If you think these CLI flags should be supported by tmux you should open an issue proposing that they be implemented followed by a change to the code which implements that behavior.

Having said that I do think there is value is implementing such a change. A,nd @nicm should  be more open to such requests by leaving the issue open as a placeholder to remind people that here is a relatively simple way to improve tmux.

**Comment by nicm** [comment]
We are not going to add -h or --help, so please don't implement it. This has been covered before - tmux is an OpenBSD project, not a GNU project, and we don't have -h or --help. The documentation for tmux is in the tmux(1) manual page.

Please note that we don't use issues as placeholders. The reason is that I don't want feature requests cluttering up the issue list. So, realistic feature requests that nobody is going to work on right now are moved to the TODO file, and those which are not going to be implemented at all can be closed.

The same applies to all issues - this is the tmux issue tracker, so issues are not for other people, they are for tmux developers (so, most often for me). Issues remain open so long as I need to do something, or may in future need to do something. GitHub doesn't prevent people responding to closed issues, and if they do I will get an email and can reopen the issue if necessary.

You might say I could use labels, or projects, or another GitHub feature du jour to track this instead, but I don't, I close the issue - then it is gone from the list and I don't need to worry about it again unless I get another email about it.

I am always happy for people creating an issue to ask "how can I contribute" or "I saw this in the TODO file, how will it work", but there is no need for issues to sit open without any activity.
