### ISSUE TITLE
move cursor after search buffer, the highlight dispare

### ISSUE THREAD

**Issue by qendo** [tmux/tmux#841]
1. search something in buffer
2. move cursor
3. the highlight the search result disappare

**Comment by qendo** [comment]
how to keep high light search after move cursor

**Comment by nicm** [comment]
You can't, that's how it works, once you move the cursor the search is done.


On 25 Mar 2017 4:04 pm, "qendo" <notifications@github.com> wrote:

how to keep high light search after move cursor

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/841#issuecomment-289221088>, or mute
the thread

**Comment by qendo** [comment]
accroding the vim, while search is done, but the highlight is still on

**Comment by nicm** [comment]
tmux follows emacs and when you move the cursor the highlighting disappears

On 25 Mar 2017 4:21 pm, "qendo" <notifications@github.com> wrote:

accroding the vim, while search is done, but the highlight is still on

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/841#issuecomment-289222074>, or mute
the thread

**Comment by qendo** [comment]
can i configure it as vim

**Comment by nicm** [comment]
No, tmux works this way, you can change the keys to vim but the style of
search etc is staying like emacs.


On 25 Mar 2017 4:25 pm, "qendo" <notifications@github.com> wrote:

can i configure it as vim

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/841#issuecomment-289222336>, or mute
the thread

**Comment by qendo** [comment]
is there a plan to support search style like vim
if not, is there a patch that make the search style like vim?
thanks very much

**Comment by nicm** [comment]
No I think we only need one search style and I like emacs, sorry

**Comment by qendo** [comment]
no matter, thanks for you answering
