### ISSUE TITLE
pane_current_path seems to be the pwd of the current command, not bash

### ISSUE THREAD

**Issue by randomekek** [tmux/tmux#842]
- your platform: linux (ubuntu 14.04, tmux 2.3)

- a brief description of the problem with steps to reproduce:

      cd ~
      man tmux
      tmux new-window -c "#{pane_current_path}"
      pwd

   - expected: pwd = ~
   - actual: pwd = /usr/share/man

- config: none required

**Comment by nicm** [comment]
That is exactly what it is..



On 27 Mar 2017 8:54 am, "randomekek" <notifications@github.com> wrote:


   -

   your platform: linux (ubuntu 14.04, tmux 2.3)
   -

   a brief description of the problem with steps to reproduce:

   cd ~
   man tmux
   tmux new-window -c "#{pane_current_path}"
   pwd

   - expected: pwd = ~
      - actual: pwd = /usr/share/man
   -

   config: none required

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/842>, or mute the thread

**Comment by randomekek** [comment]
Ok fair enough. Is there a way to implement this in tmux config, or would it require source code changes?

**Comment by nicm** [comment]
You'd need to change the code.


On 28 Mar 2017 2:15 am, "randomekek" <notifications@github.com> wrote:

Ok fair enough. Is there a way to implement this in tmux config, or would
it require source code changes?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/842#issuecomment-289623799>, or mute
the thread

**Comment by pmnoxx** [comment]
In .bashrc you can add
'''
export BASH_PWD=$PWD
'''
Then in your script you can use 
'''
tmux new-window -c "$BASH_PWD"
'''
