### ISSUE TITLE
Sequence passthrough

### ISSUE THREAD

**Issue by disarmer** [tmux/tmux#846]
Hi!
I'm using tmux 2.3 locally as terminal tabs and same version remotely (nested tmux via ssh) on archlinux and ubuntu hosts. It's works perfectly, but i have problem with terminal sequence passthrough.

In plain terminal this sequence works (it's urxvt notification):
`printf %b '\033]777;notify;test;test\007\007'`

In one tmux passthrought sequence works too:
`printf %b   '\033Ptmux;\033'       '\033]777;notify;test;test\007\007'      '\033\\'`

By my assumption, double sequence should work in nested tmux, but it doesn't (i'm getting freezed pane instead, until i'll close connection):
`printf %b   '\033Ptmux;\033'       '\033Ptmux;\033'       '\033]777;notify;test;test\007\007'      '\033\\'     '\033\\'`
It there any way to pass sequence through two tmux?

========
TERM=tmux-256color inside, and TERM=rxvt-unicode-256color outside
% uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.3
tmux-256color

**Comment by nicm** [comment]
I don't think you are escaping \033 and \\ enough times in the second case.

\033]777;notify;test;test\007\007
\033Ptmux;\033\033]777;notify;test;test\007\007\033\\
\033Ptmux;\033\033Ptmux\033\033\033\033]777;notify;test;test\007\007\033\033\\\\\033\\

**Comment by disarmer** [comment]
Hm, last command still doesn't work, but not freezing terminal, just prints nothing.

If i start tmux server with -vvvvvv, running second sequence, i get this output in log:
```
1491259766.123269 input_parse: %0 ground, 34 bytes: \033Ptmux;\033\033]777;notify;test;test\a\a\033\\
1491259766.123280 input_dcs_dispatch: "tmux;\033]777;notify;test;test\a\a"
```
Looks fine, notification working.

Then i'll start nested tmux, run third sequence and get this in external tmux log:
```
1491260284.622434 input_parse: %0 ground, 50 bytes: \033Ptmux\033\033]777;notify;test;test\a\a\033\\\033[1;1H\033[1;49r\033[2B
1491260284.622452 input_dcs_dispatch: "tmux\033]777;notify;test;test\a\a"
```
Almost same, but notification not working.

**Comment by nicm** [comment]
Is the nested tmux in the active window in the outer tmux?


On 4 Apr 2017 12:03 am, "Александр Тихонов" <notifications@github.com>
wrote:

Hm, last command still doesn't work, but not freezing terminal, just prints
nothing.

If i start tmux server with -vvvvvv, running second sequence, i get this
output in log:

1491259766.123269 input_parse: %0 ground, 34 bytes:
\033Ptmux;\033\033]777;notify;test;test\a\a\033\\
1491259766.123280 input_dcs_dispatch: "tmux;\033]777;notify;test;test\a\a"

Looks fine, notification working.

Then i'll start nested tmux, run third sequence and get this in external
tmux log:

1491260284.622434 input_parse: %0 ground, 50 bytes:
\033Ptmux\033\033]777;notify;test;test\a\a\033\\\033[1;1H\033[1;49r\033[2B
1491260284.622452 input_dcs_dispatch: "tmux\033]777;notify;test;test\a\a"

Almost same, but notification not working.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/846#issuecomment-291303882>, or mute
the thread

**Comment by disarmer** [comment]
Yes, i tried with just one window in external and one window in nested tmux, so both are active

**Comment by nicm** [comment]
Build tmux from master please (it has more logging) then show me the logs
from inner and outer tmux.



On 4 Apr 2017 6:46 am, "Александр Тихонов" <notifications@github.com> wrote:

Yes, i tried with just one window in external and one window in nested
tmux, so both are active

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/846#issuecomment-291399550>, or mute
the thread

**Comment by disarmer** [comment]
Done:
outer tmux: https://dpaste.de/iLLG
inner tmux: https://dpaste.de/TuHL

**Comment by nicm** [comment]
This one is missing a semicolon after tmux, it should be 'tmux;':

1491285687.182638 input_dcs_dispatch: "tmux\033]777;notify;test;test\a\a"

**Comment by disarmer** [comment]
Ah, yes, it's working with semicolon:
`printf %b '\033Ptmux;\033\033Ptmux;\033\033\033\033]777;notify;test;test\007\007\033\033\\\033\'`
Thank you a lot!

**Comment by wilhelmy** [comment]
Where can I find documentation about this \033P escape sequence?
