### ISSUE TITLE
Italics and 24 bit color in tmux and vim

### ISSUE THREAD

**Issue by arturojosejr** [tmux/tmux#857]
I'm in Linux Mint 18.1 Cinnamon and I'm trying to have italics and true color when using vim inside tmux. My [tmux.conf](https://github.com/arturojosejr/dotfiles/tree/master/tmux), [vimrc](https://github.com/arturojosejr/dotfiles/blob/master/config/nvim/init.vim), [zshrc](https://github.com/arturojosejr/dotfiles/blob/master/zsh/zshrc.symlink) and [terminfo](https://github.com/arturojosejr/dotfiles/tree/master/resources).
```bash
uname -sp && tmux -V && echo $TERM && tic -V
Linux x86_64
tmux 2.3
tmux
ncurses 6.0.20160213
```
I've tried doing what appears in the FAQ.

> * I don't see italics! Or less and vim show italics and reverse the wrong way round!

But it says:
```bash
cat <<EOF|tic -x -                                                                                              ✗ master 
        tmux|tmux terminal multiplexer,
                ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
                use=xterm+tmux, use=screen,

        tmux-256color|tmux with 256 colors,
                use=xterm+256setaf, use=tmux,
EOF
"<stdin>", line 1, col 13: Illegal character - '|'
"<stdin>", line 1, col 13: Entry does not start with terminal names in column one
```
I don't know how to update ncurses or tic and the FAQ doesn't say anything.

I've then copied [this osx terminfo](https://github.com/pjcj/base/blob/b34a07bef49f7d6e91169d46b1fe0cab27367b47/utils/make_tmux_terminfo) and used tic to the file. With that I've achieved italics inside tmux but [I've lost the colors](https://github.com/tmux/tmux/issues/450).
There isn't an [easy to follow guide](https://bruinsslot.jp/post/how-to-enable-true-color-for-neovim-tmux-and-gnome-terminal/) on how to get italics and colors in vim and tmux using the terminfo from the FAQ?

**Comment by ThomasDickey** [comment]
On Mon, Apr 10, 2017 at 02:01:23PM -0700, Arturo wrote:
> I'm in Linux Mint 18.1 Cinnamon and I'm trying to have italics and true color when using vim inside tmux. My [tmux.conf](https://github.com/arturojosejr/dotfiles/tree/master/tmux), [vimrc](https://github.com/arturojosejr/dotfiles/blob/master/config/nvim/init.vim), [zshrc](https://github.com/arturojosejr/dotfiles/blob/master/zsh/zshrc.symlink) and [terminfo](https://github.com/arturojosejr/dotfiles/tree/master/resources).
...
> But it says:
> ```bash
> cat <<EOF|tic -x -                                                                                              ✗ master 
>         tmux|tmux terminal multiplexer,
>                 ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
>                 use=xterm+tmux, use=screen,
> 
>         tmux-256color|tmux with 256 colors,
>                 use=xterm+256setaf, use=tmux,
> EOF
> "<stdin>", line 1, col 13: Illegal character - '|'
> "<stdin>", line 1, col 13: Entry does not start with terminal names in column one
> ```

tic's feature for reading from the standard input was added in March 2012.
OSX bundles ncurses 5.7, released November 2008.

(That's not unusual - for OSX - since its command-line utilities don't
get updated as frequently, say, as Debian/stable).

> I don't know how to update ncurses or tic and the FAQ doesn't say anything.

MacPorts works well enough (some prefer "brew").  Those would build a
new terminfo database (probably necessary with Apple's changes to filesystem
permissions with El Capitan).
 
-- 
Thomas E. Dickey <dickey@invisible-island.net>
http://invisible-island.net
ftp://invisible-island.net

**Comment by nicm** [comment]
I don't think he is using OS X, just that he copied a script someone wrote for OS X because it suffers from the same problem as his platform (its tic is old).

The terminfo entries from the script should be fine. I don't know what exactly "lost the colours" means, but it probably means that vim needs to be configured to play nicely with TERM=tmux (it was probably making assumptions based on TERM=screen or TERM=xterm). I don't know exactly how to fix it and it depends what colours vim is using, you will need to use Google or ask the vim developers for help. t_Co and t_ut seem to be common issues, but I don't know how to make it do RGB colour.

**Comment by nicm** [comment]
You might want this:

set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
