### ISSUE TITLE
Readme file is not properly formatted

### ISSUE THREAD

**Issue by Roshanjossey** [tmux/tmux#858]
The current README is not formatted well. It'd be much better if we use markdown formatting to better present information

🐞 **Problem**
The current README file is not easily readable because it's not formatted well

🎯 **Goal**
A well formatted README where important details are very easy to find

I'd love to work on this and submit a PR if you're interested

**Comment by nicm** [comment]
No thanks I do not want it to be full of markup stuff.



On 14 Apr 2017 9:01 pm, "Roshan Jossey" <notifications@github.com> wrote:

The current README is not formatted well. It'd be much better if we use
markdown formatting to better present information

🐞 *Problem*
The current README file is not easily readable because it's not formatted
well

🎯 *Goal*
A well formatted README where important details are very easy to find

I'd love to work on this and submit a PR if you're interested

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/858>, or mute the thread

**Comment by Roshanjossey** [comment]
@nicm The current Readme link in http://tmux.github.io/ points to raw version of this readme. Hyperlinks doesn't work there.

Wouldn't it be better if we added another readme page in the site?
I didn't see any issue section in the repo for http://tmux.github.io/

**Comment by nicm** [comment]
I don't want to maintain two files.


On 14 Apr 2017 9:08 pm, "Roshan Jossey" <notifications@github.com> wrote:

@nicm <https://github.com/nicm> The current Readme link in
http://tmux.github.io/ points to raw version of this readme. Hyperlinks
doesn't work there.

Wouldn't it be better if we added another readme page in the site?
I didn't see any issue section in the repo for http://tmux.github.io/

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/858#issuecomment-294226660>, or mute
the thread

**Comment by Jesin** [comment]
@Roshanjossey @nicm I have suggested a minimal-effort compromise at tmux/tmux.github.io#5.

**Comment by kenden** [comment]
Link to other PRs about this.
https://github.com/tmux/tmux/pull/124
https://github.com/tmux/tmux/issues/858

I would argue that adding markdown formatting makes the file easier to read even in a text editor, Also, adding sections to the readme makes it 
- easier to browse/navigate 
- more likely to become more complete (install instructions for redhat/ubuntu/mac for example?).
Else, it looks like an abandoned file. 
Like it or not, github is the biggest open source repo on the web.
