### ISSUE TITLE
select-pane command doesn't work in binding

### ISSUE THREAD

**Issue by datanoise** [tmux/tmux#863]
Prior to version 2.4 the following command selected another pane in the current window and zoomed it:

```
bind q select-pane -U \; resize-pane -Z
```

With version 2.4 the `select-pane` command is ignored.

**Comment by nicm** [comment]
Works for me.

**Comment by nicm** [comment]
Oh wait, no it doesn't!

**Comment by nicm** [comment]
The problem is that we save the active pane as the current pane for this command sequence which means it is used by all commands, when really we want to work out the current pane again for the second command. I think this was only intended for mouse bindings, so please try this: [x.diff.txt](https://github.com/tmux/tmux/files/943350/x.diff.txt)

**Comment by datanoise** [comment]
yes, this patch fixes the issue for me. thanks
