### ISSUE TITLE
tmux 2.4, regression: 'tmux start' creates a new session if .tmux.conf exists

### ISSUE THREAD

**Issue by fjaell** [tmux/tmux#869]
as of tmux 2.4 it's no longer possible to start the tmux server without any session, if a configuration file exists. 'tmux start' immediately creates a new session.

**Comment by nicm** [comment]
No it doesn't:

$ touch foo
$ tmux -f./foo -Ltest start
$ tmux -Ltest ls
no server running on /tmp/tmux-1000/test
$

**Comment by fjaell** [comment]
Please add a 'new' command to your configuration file:

$ cat foo
new
$ tmux -f./foo -Ltest start

than, from inside the tmux session:
$ tmux -Ltest ls
0: 1 windows (created Fri Apr 21 14:04:08 2017) [158x87] (attached)
$ tmux kill-server

[server exited]
$

**Comment by fjaell** [comment]
For comparison, here's the same test with tmux 2.3

$ cat foo
new
$ tmux -Ltest ls
no server running on /tmp/tmux-500/test
$ tmux -ffoo -Ltest start
$ tmux -Ltest ls
0: 1 windows (created Fri Apr 21 14:19:23 2017) [80x23]
$

**Comment by nicm** [comment]
This is a change, but I think it is fine, you want new -d if you don't want to attach.

**Comment by fjaell** [comment]
well, guess we can live with the new behaviour, but IMO it should be documented in man-page accordingly.
I stumbled over the problem because I had a 'tmux start' first and a 'tmux attach' as a parameter for an xterm start later on in my .xinitrc which doesn't work anymore with 2.4.

**Comment by nicm** [comment]
We didn't document the old behaviour so I don't particularly see that we need to document the new but if you suggest some changes I'll look at them.

TBH I think either behaviour is fine but this is potentially more useful so I'm not sure I want to change it again.

**Comment by nicm** [comment]
Although it does just make tmux start the same as tmux attach...

**Comment by fjaell** [comment]
from the man-page:

start-server
Start the tmux server, if not already running, without creating any sessions

**Comment by nicm** [comment]
Right, and it doesn't create any sessions. Your config file creates the sessions with new-session.

**Comment by fjaell** [comment]
yeah, indeed, there's not really a difference between the two modes ;)

**Comment by fjaell** [comment]
ok, but it's a incompatible change and should be mentioned in CHANGES.

**Comment by nicm** [comment]
Not quite actually, with attach you can't avoid attaching.

So now with "new" in config file they are the same, but with "new -d" they are different.

I think this is still in the spirit of what start-server is meant to do (start up the server and let the config file do whatever it does). If this is how start-server had worked from the beginning it would have been fine, you only notice because it changed.

**Comment by nicm** [comment]
I think this changed because the config file is now loaded in the context of the starting client, when it would previously not have had one at all. This seems to revert back to the old behaviour, but there may be other consequences:


~~~~
Index: cfg.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/cfg.c,v
retrieving revision 1.55
diff -u -p -r1.55 cfg.c
--- cfg.c       5 Apr 2017 10:45:39 -0000       1.55
+++ cfg.c       21 Apr 2017 12:57:11 -0000
@@ -66,14 +66,14 @@ start_cfg(void)
        if (cfg_client != NULL)
                cfg_client->references++;

-       load_cfg(TMUX_CONF, cfg_client, NULL, 1);
+       load_cfg(TMUX_CONF, NULL, NULL, 1);

        if (cfg_file == NULL && (home = find_home()) != NULL) {
                xasprintf(&cfg_file, "%s/.tmux.conf", home);
                quiet = 1;
        }
        if (cfg_file != NULL)
-               load_cfg(cfg_file, cfg_client, NULL, quiet);
+               load_cfg(cfg_file, NULL, NULL, quiet);

        cmdq_append(cfg_client, cmdq_get_callback(cfg_done, NULL));
 }

**Comment by nicm** [comment]
Even if we did this you are stuck with it for 2.4, so basically just need to decide what it is actually better to do... I'll need to have a closer look.

**Comment by fjaell** [comment]
ok, many thanks for now, will wait for your decision :)

**Comment by nicm** [comment]
I'm going to change it actually - I think the config file should not run in the context of a client at all. If you want it to, you can do "tmux start\; source myfile" instead.

**Comment by nicm** [comment]
I have changed this now in master, please let me know if you see any other problems. Thanks!
