### ISSUE TITLE
tmux 2.4 pane clearing bug

### ISSUE THREAD

**Issue by trevordmiller** [tmux/tmux#876]
First of all, thank you for tmux, it is one of my most used tools ❤️

I upgraded to latest tmux from homebrew yesterday and now when I have multiple panes open and I open vim in one of them, the other panes clear until I move to them and hit Ctrl + C as shown in this gif:

![tmux-2 4-clear-bug](https://cloud.githubusercontent.com/assets/5497885/25307545/e5a5cecc-275f-11e7-9a98-98de1d7b7e1a.gif)

- Platform: macOS latest (10.12.4)
- a minimal tmux config, if you can't reproduce without a config: https://github.com/trevordmiller/settings/blob/master/dotfiles/.tmux.conf
![image](https://cloud.githubusercontent.com/assets/5497885/25307421/c435e83c-275d-11e7-8195-cb723780081c.png)
- I've reproduced this in multiple terminal emulators (mac terminal and Hyper)
- My $TERM is the same inside and outside of tmux:
![image](https://cloud.githubusercontent.com/assets/5497885/25307467/aaa01716-275e-11e7-852d-17f43330edef.png)

Logs:
[tmux-logs.zip](https://github.com/tmux/tmux/files/949221/tmux-logs.zip)

**Comment by nicm** [comment]
What if you use TERM=nsterm outside tmux?




On 22 Apr 2017 8:31 pm, "Trevor D. Miller" <notifications@github.com> wrote:

First of all, thank you for tmux, it is one of my most used tools ❤️

I upgraded to latest tmux from homebrew yesterday and now when I have
multiple panes open and I open vim in one of them, the other panes clear
until I move to them and hit Ctrl + C as shown in this gif:

[image: tmux-2 4-clear-bug]
<https://cloud.githubusercontent.com/assets/5497885/25307545/e5a5cecc-275f-11e7-9a98-98de1d7b7e1a.gif>

   - Platform: macOS latest (10.12.4)
   - a minimal tmux config, if you can't reproduce without a config:
   https://github.com/trevordmiller/settings/blob/master/dotfiles/.tmux.conf
   <https://github.com/trevordmiller/settings/blob/master/dotfiles/.tmux.conf>
   [image: image]
   <https://cloud.githubusercontent.com/assets/5497885/25307421/c435e83c-275d-11e7-8195-cb723780081c.png>
   - I've reproduced this in multiple terminal emulators (mac terminal and
   Hyper)
   - My $TERM is the same inside and outside of tmux:
   [image: image]
   <https://cloud.githubusercontent.com/assets/5497885/25307467/aaa01716-275e-11e7-852d-17f43330edef.png>

Logs:
tmux-logs.zip <https://github.com/tmux/tmux/files/949221/tmux-logs.zip>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/876>, or mute the thread

**Comment by nicm** [comment]
These logs only have one pane. What use are logs that don't show the problem?

**Comment by trevordmiller** [comment]
@nicm Using `TERM=nsterm` outside of tmux didn't seem to make a difference. I apologize for the incorrect logs, I've regenerated them here:

[pane-clearing-tmux-logs.zip](https://github.com/tmux/tmux/files/949303/pane-clearing-tmux-logs.zip)

I've confirmed this pane clearing is also a problem when running the CTRL L or `clear` in any pane as well, so it is not specific to starting vim:

![tmux-2 4-pane-clearing-2](https://cloud.githubusercontent.com/assets/5497885/25308494/945e6390-2772-11e7-8c2d-d8695469e673.gif)

**Comment by nicm** [comment]
You are just confusing things here, because these logs don't match the animation you are showing either. In the logs it looks like you had two panes and you run clear in the bottom one, but your animation shows you have two or four panes and you run clear the top one. Also you are obviously running something in the lower pane or panes in the animation, but none of that text appears in the logs.

**Comment by nicm** [comment]
Anyway, if you actually did see a problem after running clear in the logs you gave me this is almost certainly a bug in your terminal. tmux is doing nothing that would cause the terminal to clear and copying the same output from your logs and sending it to xterm causes it to draw correctly. Can you reproduce this in another terminal like xterm or iTerm2?

**Comment by nicm** [comment]
What does this show in your terminal, outside tmux. Show me a screenshot please:
~~~~
printf '\033[H\033[Jabc\r\ndef\r\nxyz\033[H\033[K\033[1B\033[K'; sleep 1000
~~~~

**Comment by trevordmiller** [comment]
@nicm Sorry for the confusion; the logs were from the minimal use case (start tmux, make a pane, type `clear`, hit enter), whereas my gifs were from my actual use with tools running in multiple panes; but the result is the same either way with the other panes being cleared when the current pane clears or enters vim. I have reproduced the problem in multiple terminals (mac terminal and Hyper). I've been using this setup for over a year and haven't had any problems until upgrading to the new 2.4 release so it seems to be something with that.

Here is the output of the `printf` command ^
![image](https://cloud.githubusercontent.com/assets/5497885/25310329/956b8448-279f-11e7-8e73-c88d20ba463b.png)

**Comment by trevordmiller** [comment]
But since you can't reproduce it, it must be something specific to my setup. I'll keep tinkering. Thanks.

**Comment by trevordmiller** [comment]
@nicm The problem only happens when I use my tmux config here:
https://github.com/trevordmiller/settings/blob/master/dotfiles/.tmux.conf

Do you see anything in here that would have been affected by the 2.4 update, or that I should change?

**Comment by nicm** [comment]
Please send me logs of this actually happening, if it only happens with your config, please send me logs using that config - there is no point in sending me logs of you running "clear" with no config if it actually works fine when you do that.

There is something your terminal doesn't like, either because tmux is sending it incorrectly or because the terminal has a bug. But if you don't send me a log of what tmux actually sends when the problem occurs then I can't even guess what that is.

**Comment by trevordmiller** [comment]
@nicm Ok, how do I generate logs that use my tmux config? I'm not sure how to modify these commands to do so
``` 
tmux -Ltest kill-server
tmux -vvvv -Ltest -f/dev/null new
```

**Comment by nicm** [comment]
Just remove the -f/dev/null and it will load .tmux.conf as normal:

tmux -Ltest kill-server
tmux -vvvv -Ltest new

**Comment by trevordmiller** [comment]
@nicm Thanks. Ok, here is a new gif with the logs from the gif using my config. I've confirmed this is only a problem when I run `clear` or open `vim` in the first pane; you can see how I make a split, then jump back to the first pane and type `clear` and the second pane (including the separator line) dissapears, and then even when I switch back to the pane that dissapeared it still doesn't show the pane's content:
[tmux-logs.zip](https://github.com/tmux/tmux/files/949891/tmux-logs.zip)
![tmux-pane-clear-issue-with-config](https://cloud.githubusercontent.com/assets/5497885/25315957/3e436ad8-281b-11e7-8cd5-e867b6a1784f.gif)

Here is my tmux config; it's pretty minimal so I'm not sure what would be causing this but it is new as of tmux 2.4:
https://github.com/trevordmiller/settings/blob/master/dotfiles/.tmux.conf

**Comment by nicm** [comment]
OK I see what is happening. This is a bug in tmux - we fixed it for clear-end-of-screen but not for clear-screen. The reason you are seeing it is because you have the status line turned off.

You can try this change:

~~~~
? tmux
Index: tty.c
===================================================================
RCS file: /cvs/src/usr.bin/tmux/tty.c,v
retrieving revision 1.266
diff -u -p -r1.266 tty.c
--- tty.c	19 Apr 2017 06:52:27 -0000	1.266
+++ tty.c	23 Apr 2017 18:06:45 -0000
@@ -1218,6 +1218,7 @@ tty_cmd_clearscreen(struct tty *tty, con
 	tty_margin_off(tty);
 
 	if (tty_pane_full_width(tty, ctx) &&
+	    ctx->yoff + wp->sy >= tty->sy - 1 &&
 	    status_at_line(tty->client) <= 0 &&
 	    tty_term_has(tty->term, TTYC_ED)) {
 		tty_cursor_pane(tty, ctx, 0, 0);

**Comment by nicm** [comment]
If you want a workaround, do this in .tmux.conf:

set -sa terminal-overrides ',*:ed@'

**Comment by nicm** [comment]
I have fixed this in Git master.

**Comment by trevordmiller** [comment]
Thank you for the fix @nicm, I appreciate it

**Comment by nicm** [comment]
No problem, thanks for the report.
