### ISSUE TITLE
Default to using incremental search in copy-mode-vi too

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#895]
In tmux 2.4, this is the default for copy-mode:

```
bind-key -T copy-mode C-r command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""
bind-key -T copy-mode C-s command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
```

Any reason why we wouldn't do the same (by default) for copy-mode-vi as well?

```
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""
```

I added this to my `~/.tmux.conf`, but it seems like a reasonable default given that copy-mode already does it.

**Comment by nicm** [comment]
I don't mind too much if we do this but I don't think vi has incremental
search.


On 28 Apr 2017 9:07 pm, "Greg Hurrell" <notifications@github.com> wrote:

In tmux 2.4, this is the default for copy-mode:

bind-key -T copy-mode C-r command-prompt -i -p "search up" "send -X
search-backward-incremental \"%%%\""
bind-key -T copy-mode C-s command-prompt -i -p "search down" "send -X
search-forward-incremental \"%%%\""

Any reason why we wouldn't do the same (by default) for copy-mode-vi as
well?

bind-key  -T copy-mode-vi / command-prompt -i -p "search down" "send
-X search-forward-incremental \"%%%\""
bind-key  -T copy-mode-vi ? command-prompt -i -p "search up" "send -X
search-backward-incremental \"%%%\""

I added this to my ~/.tmux.conf, but it seems like a reasonable default
given that copy-mode already does it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/895>, or mute the thread

**Comment by wincent** [comment]
True, it's a Vim thing.

**Comment by nicm** [comment]
If you are sure this is not going to make vi or vim users complain it doesn't work the right way, we can do this fine.

**Comment by wincent** [comment]
I'm sure you'll get complaints either way (can't keep all of the people happy all the time); my argument for changing the default is consistency (and consistency alone) with the emacs mode bindings, ignoring subjective judgments about what is better or whether users expect "vi mode" to be more like be or more like Vim etc. Up to you.

**Comment by nicm** [comment]
OK I'm just going to leave it for now.

**Comment by maximbaz** [comment]
Hey @nicm, can we please revisit this request to make incremental search default in copy-mode-vi too? 

Incremental search is extremely useful, the number of :+1: keeps growing, but this might not be very visible as the ticket is closed.

**Comment by wangsongiam** [comment]
I enjoy the thread, increment search is useful for sure. But Vim doesn't have incremental search as default, so, I'll argue that the consistency for vim user is to just leave it here in Tmux.

**Comment by SidOfc** [comment]
Hello!

Saw this thread and wanted to say that both Vim and Neovim have an `incsearch` option which enables incremental search highlighting (`:h incsearch`). In NeoVim it is enabled by default whereas in Vim it is disabled by default (probably backwards-compat thing).

I write a comment here because it is the first place one lands when searching how to enable "tmux incremental search". If it cannot be enabled by default for consistency because it may piss off some users, (can imagine If they are used to having it one way and now it suddenly works different) then maybe a section can be added to the [FAQ](https://github.com/tmux/tmux/wiki/FAQ) for those who want it instead? It could include the code snippet the OP posted since it works nicely 👍
