### ISSUE TITLE
Feature request: Zmodem sz/rz command support ?

### ISSUE THREAD

**Issue by lxj616** [tmux/tmux#906]
Hi, just for asking, is there any plans to support zmodem sz/rz commands like GNU screen ?

I have only some piped tty access to target machine,
So
I have to use GNU screen to transfer files,

Wondering if tmux can have a option like GNU screen: zmodem catch ?

related article: http://adammonsen.com/post/256

**Comment by nicm** [comment]
No way, this is not what tmux is for, sorry.

**Comment by jurajlutter** [comment]
There are situations where you need, for example, to send a file to, let's say, network device (router, switch, ...).

**Comment by krader1961** [comment]
Zmodem is thirty years old. Last time I used it was perhaps twenty years ago. If you really have devices which only support zmodem for transferring files you can do it without magic support by tmux. Strong thumbs down from me. Practically any other change to tmux would have greater value.

**Comment by Dema** [comment]
It may be useful if you are several ssh hops away. Like "Me" → Machine1 →Machine2. Other option is to set up several ssh tunnels prelimitary.

**Comment by therevoman** [comment]
When has anything been dismissed in Linux just because it's old? Linux itself is that old...

Anyhow, there are many environments where you have to pass through one or more jump boxes. If I have to retrieve a file or more, that's more than a few bytes, kicking off zmodem removes the pain of scp the file between each level, or setting up complex port forwards (which are often disabled by policy).

Practically not adding this valuable feature means users are forced into an outdated usage pattern.
