### ISSUE TITLE
https://github.com/hzeller/timg rendering garbled

### ISSUE THREAD

**Issue by octoploid** [tmux/tmux#912]
tmux master
tmux-256color

With:
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

https://github.com/hzeller/timg doesn't work on trunk anymore:

To reproduce just open two windows and render a picture with timg in one of them.
Then switch between the windows and you will get corrupt rendering
with no visible cursor.

![2017-05-05-075514_1080x1920_scrot](https://cloud.githubusercontent.com/assets/327746/25734999/5fac75b0-3168-11e7-9520-7a366076ae4d.png)

[log.tar.zip](https://github.com/tmux/tmux/files/978206/log.tar.zip)

**Comment by nicm** [comment]
Does it work if you use a much smaller, simpler image like this one? https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Venn_diagram_for_additive_RG_color.svg/2000px-Venn_diagram_for_additive_RG_color.svg.png

**Comment by octoploid** [comment]
Yes, with the smaller image it works fine.

**Comment by nicm** [comment]
Link me to the image you are having trouble with please.

**Comment by octoploid** [comment]
![petrus_christus _portrait_of_a_young_girl](https://cloud.githubusercontent.com/assets/327746/25736442/29c18d64-3172-11e7-98a7-14477dbcebd0.jpg)

**Comment by nicm** [comment]
Redrawing this generates so much data that it hits the "terminal can't keep up" check for the actual redraw - that is, for the data sent by tmux itself - and causes a loop of redrawing.

The best bet is probably to prevent this check for the data sent by tmux's own redraw (rather than by a program inside tmux). Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/986616/x.diff.txt)

**Comment by octoploid** [comment]
Your patch works fine. Thanks for the fix.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub soon. Thanks!
