### ISSUE TITLE
2.4 fails to compile because ncurses cannot be found but same options worked for 2.3

### ISSUE THREAD

**Issue by ericpruitt** [tmux/tmux#915]
I am unable to compile tmux 2.4 the same way I compiled 2.3, and it appears that the problem may be due to LIBNCURSES_CFLAGS and LIBNCURSES_LIBS not being used when compiling some terminal libraries:

    tmux-src [1]$ make -j1
    /home/ericpruitt/projects/static-unix-userland/musl-1.1.16/bin/musl-gcc -std=gnu99 -DPACKAGE_NAME=\"tmux\" -DPACKAGE_TARNAME=\"tmux\" -DPACKAGE_VERSION=\"2.4\" -DPACKAGE_STRING=\"tmux\ 2.4\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"tmux\" -DVERSION=\"2.4\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DIRENT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_PATHS_H=1 -DHAVE_PTY_H=1 -DHAVE_STDINT_H=1 -DHAVE_SYS_DIR_H=1 -DHAVE_DIRFD=1 -DHAVE_FLOCK=1 -DHAVE_PRCTL=1 -DHAVE_SYSCONF=1 -DHAVE_ASPRINTF=1 -DHAVE_CFMAKERAW=1 -DHAVE_FGETLN=1 -DHAVE_SETENV=1 -DHAVE_STRCASESTR=1 -DHAVE_STRLCAT=1 -DHAVE_STRLCPY=1 -DHAVE_STRNDUP=1 -DHAVE_STRSEP=1 -DHAVE_NCURSES_H=1 -DHAVE_PR_SET_NAME=1 -DHAVE_PROC_PID=1 -I.  -DTMUX_CONF="\"/etc/tmux.conf\""  -iquote.      -I/home/ericpruitt/projects/static-unix-userland/common/include  -std=gnu99 -O2   -I/home/ericpruitt/projects/static-unix-userland/common/include -O1 -c -o tty-term.o tty-term.c
    tty-term.c:24:21: fatal error: ncurses.h: No such file or directory
     #include <ncurses.h>
                         ^
    compilation terminated.
    Makefile:801: recipe for target 'tty-term.o' failed

When doing parallel builds, I see a similar error for tty.c:

    tty.c:24:20: fatal error: curses.h: No such file or directory
     #include <curses.h>
This is what the build rule looks like in my personal Makefile:

    $(TMUX)/tmux: $(LIBEVENT_BUILT) $(TMUX_FOLDER) $(NCURSES_BUILT)
        cd $(TMUX); \
        test -e configure || ./autogen.sh; \
        test -e Makefile || ./configure \
            CFLAGS="$(CFLAGS)" \
            LDFLAGS="$(LDFLAGS)" \
            LIBEVENT_CFLAGS="-I$(COMMON_PREFIX)/include" \
            LIBEVENT_LIBS="-levent" \
            LIBNCURSES_CFLAGS="-I$(COMMON_PREFIX)/include/ncurses" \
            LIBNCURSES_LIBS="-lncurses" \
            --disable-dependency-tracking \
            --enable-static \
            --sysconfdir=/etc \
        ; \
        $(MAKE) -S; \

I have attached [config.log](https://github.com/tmux/tmux/files/980611/config.log.txt).

**Comment by nicm** [comment]
I'll take a look when I get home but I'm not particularly inclined to change this again because we are already jumping through a load of hoops to find ncurses and make sure it works. I think NCURSES_LIBS etc are for pkg-config to set, you should either point configure to your ncurses .pc file, or use plain CPPFLAGS, CFLAGS, LDFLAGS etc.

**Comment by ericpruitt** [comment]
I tried moving the LIBEVENT_CFLAGS into CFLAGS, but the build still fails:

    # Makefile
    $(TMUX)/tmux: $(LIBEVENT_BUILT) $(TMUX_FOLDER) $(NCURSES_BUILT)
        cd $(TMUX); \
        test -e configure || ./autogen.sh; \
        test -e Makefile || ./configure \
            CFLAGS="$(CFLAGS) -I$(COMMON_PREFIX)/include/ncurses" \
            LDFLAGS="$(LDFLAGS)" \
            LIBEVENT_CFLAGS="-I$(COMMON_PREFIX)/include" \
            LIBEVENT_LIBS="-levent" \
            LIBNCURSES_LIBS="-lncurses" \
            --disable-dependency-tracking \
            --enable-static \
            --sysconfdir=/etc \
        ; \
        $(MAKE) -S; \

    # Build
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: executing depfiles commands
    make[2]: *** No rule to make target 'compat/forkpty-linux.c', needed by 'compat/forkpty-linux.o'.  Stop.

[config.log](https://github.com/tmux/tmux/files/981856/config.log.txt)

**Comment by nicm** [comment]
tmux will only use LIBNCURSES_* and LIBEVENT_* if PKG_CHECK_MODULES succeeds.

I'm guessing that macro will use those ones you give it. It isn't documented that it will as far as I can see but if it didn't it would never work. But anyway, it _does_ succeed on your system because you do have a working pkg-config.

I'd expect it to be failing much later though, because now we look for libtinfo first, you will try to link against against both the system libtinfo and your libncurses. Did you try setting LIBTINFO_* instead of LIBNCURSES_*?

I wouldn't recommend you try to do it like this, however. The best way would be to either point PKG_CONFIG_PATH to the *.pc files for your custom built libncurses and libevent, or to build entirely without pkg-config (PKG_CONFIG= ./configure) and use only CPPFLAGS/CFLAGS/LDFLAGS (of course you can construct them however you like).

**Comment by ericpruitt** [comment]
Thanks, I was able to get it to compile by setting LIBTINFO_* instead of LIBNCURSES_* and also adding "-I$(COMMON_PREFIX)/include/ncurses" to CFLAGS. I haven't created any pkg-config definitions before, so I will look into that when I have more time later.

**Comment by nicm** [comment]
Both ncurses and libevent should have a way to generate appropriate *.pc
files when you build and install them.
