### ISSUE TITLE
tmux close when using :new

### ISSUE THREAD

**Issue by dannywillems** [tmux/tmux#926]
When I want to create a new session in tmux with C-b :new session_name, tmux is closed and the session is not created. It's the master branch.

Linux x86_64
tmux master
xterm-256color
Ubuntu 16.04

No screenshot can be provided.

**Comment by nicm** [comment]
Maybe if you used -s

**Comment by dannywillems** [comment]
My bad... With -s it's working. But strange tmux close no?

**Comment by nicm** [comment]
Not strange unless you really have a command called session_name you want
it to run

On 13 May 2017 10:44 am, "Danny Willems" <notifications@github.com> wrote:

My bad... With -s it's working. But strange tmux close no?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/926#issuecomment-301237358>, or mute
the thread

**Comment by nicm** [comment]
Does it really exit completely or does it just detach because your new
session closed (because there is no command)?

**Comment by dannywillems** [comment]
Yes it really exit e.g. with `:new hello`.

**Comment by nicm** [comment]
And you can't attach your previous session anymore?

**Comment by dannywillems** [comment]
Yes I can attach to previous session by re-executing `tmux a`.

**Comment by nicm** [comment]
OK that is expected then, you make a new session and tmux switches to it,
then when it closes the client detaches as normal

**Comment by dannywillems** [comment]
@nicm As it's normal, I close the issue.
Thanks for these very fast answers.
