### ISSUE TITLE
session size in control master mode is 80x23 and cannot be changed to 80x24

### ISSUE THREAD

**Issue by cgull** [tmux/tmux#947]
Recently, Mosh's build tests failed on OpenBSD-current (http://mailman.mit.edu/pipermail/mosh-devel/2017-May/001490.html).  I see this issue with tmux-portable from Git on macOS 10.12.5 as well. tmux-portable 2.5 does not have this problem.

Mosh uses tmux in control master mode to drive its testing, and expects the session window to be 80x24, without setting the size explicitly.  tmux from git at d1497527c6b4771c9d4bc0e9f9956f38322545d2 creates an 80x23 window, which breaks some of our tests that require the window to be the correct height.  I wouldn't call this a bug, since the default size of the window in control mode has never been documented.  But there is an associated bug:  `refresh-client -C 80,24` does not change the window size; apparently tmux internally believes that the window is 80x24.  (Changing it to any other size *does* work.)  The following test script and typescript illuminate the problem.

Reverting d1497527c6b4771c9d4bc0e9f9956f38322545d2 clears both these issues.  It looks to me like there is some confusion within tmux about the window height, and this was previously hidden, because the client always reset the session window size.

```shell
#!/bin/sh
commands()
{
    while read x; do
	printf '%s\n' "$x"
	sleep 1
    done <</EOF
send-keys 'stty -a' C-m
refresh-client -C 80,24
send-keys 'stty -a' C-m
refresh-client -C 80,23
send-keys 'stty -a' C-m
refresh-client -C 80,24
send-keys 'stty -a' C-m
kill-session
/EOF
}

commands | ./tmux -C
```

```
%begin 1495990490 231 0
%end 1495990490 231 0
%window-pane-changed @0 %0
%window-add @0
%session-window-changed $0 @0
%sessions-changed
%session-changed $0 0
%begin 1495990490 238 1
%end 1495990490 238 1
%output %0 stty -a\015
%output %0 \012
%window-renamed @0 tmux
%output %0 -bash: p
%output %0 om: comm
%output %0 and not
%output %0 found\015\012
%output %0 -bash: f
%output %0 ortune:
%output %0 command
%output %0 not foun
%output %0 d\015\012
%output %0 cgull@m
%output %0 inipixel:/Users/cgull/src/tmux 0 $ stty -a\015\012
%output %0 speed 9600 baud; 23 rows; 80 columns;\015\012lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr -igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint -inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr -onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard = <undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012\011min = 1; quit = ^\134; reprint = ^R; start = ^Q; status = ^T;\015\012\011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%window-renamed @0 bash
%begin 1495990491 241 1
%end 1495990491 241 1
%begin 1495990492 242 1
%end 1495990492 242 1
%output %0 stt
%output %0 y -a\015\012
%output %0 speed 9600 baud; 23 rows; 80 columns;\015\012lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr -igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint -inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr -onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard = <undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012\011min = 1; quit = ^\134; reprint = ^R; start = ^Q; status = ^T;\015\012\011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990493 243 1
%end 1495990493 243 1
%begin 1495990494 244 1
%end 1495990494 244 1
%output %0 s
%output %0 tty -a\015\012
%output %0 speed 9600 baud; 23 rows; 80 columns;\015\012lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr -igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint -inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr -onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard = <undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012
%output %0 \011min = 1; quit = ^\134; reprint = ^R; start = ^Q; status = ^T;\015\012\011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990495 245 1
%end 1495990495 245 1
%layout-change @0 b25d,80x24,0,0,0 b25d,80x24,0,0,0 *
%output %0 \015\033[Kcgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990496 247 1
%end 1495990496 247 1
%output %0 st
%output %0 ty -a\015\012
%output %0 speed 9600 baud; 24 rows; 80 columns;\015\012lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr -igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint -inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr -onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard = <undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012\011min = 1; quit = ^\134; reprint = ^R; start = ^Q; status = ^T;\015\012
%output %0 \011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990497 248 1
%end 1495990497 248 1
%sessions-changed```

**Comment by nicm** [comment]
Does it change to 80x24 if you do set status off for the session?



On 28 May 2017 6:12 pm, "cgull" <notifications@github.com> wrote:

Recently, Mosh's build tests failed on OpenBSD-current (
http://mailman.mit.edu/pipermail/mosh-devel/2017-May/001490.html). I see
this issue with tmux-portable from Git on macOS 10.12.5 as well.
tmux-portable 2.5 does not have this problem.

Mosh uses tmux in control master mode to drive its testing, and expects the
session window to be 80x24, without setting the size explicitly. tmux from
git at d149752
<https://github.com/tmux/tmux/commit/d1497527c6b4771c9d4bc0e9f9956f38322545d2>
creates an 80x23 window, which breaks some of our tests that require the
window to be the correct height. I wouldn't call this a bug, since the
default size of the window in control mode has never been documented. But
there is an associated bug: refresh-client -C 80,24 does not change the
window size; apparently tmux internally believes that the window is 80x24.
(Changing it to any other size *does* work.) The following test script and
typescript illuminate the problem.

Reverting d149752
<https://github.com/tmux/tmux/commit/d1497527c6b4771c9d4bc0e9f9956f38322545d2>
clears both these issues. It looks to me like there is some confusion
within tmux about the window height, and this was previously hidden,
because the client always reset the session window size.

#!/bin/shcommands()
{
    while read x; do
	printf '%s\n' "$x"
	sleep 1
    done <</EOF
send-keys 'stty -a' C-m
refresh-client -C 80,24
send-keys 'stty -a' C-m
refresh-client -C 80,23
send-keys 'stty -a' C-m
refresh-client -C 80,24
send-keys 'stty -a' C-m
kill-session
/EOF
}

commands | ./tmux -C

%begin 1495990490 231 0
%end 1495990490 231 0
%window-pane-changed @0 %0
%window-add @0
%session-window-changed $0 @0
%sessions-changed
%session-changed $0 0
%begin 1495990490 238 1
%end 1495990490 238 1
%output %0 stty -a\015
%output %0 \012
%window-renamed @0 tmux
%output %0 -bash: p
%output %0 om: comm
%output %0 and not
%output %0 found\015\012
%output %0 -bash: f
%output %0 ortune:
%output %0 command
%output %0 not foun
%output %0 d\015\012
%output %0 cgull@m
%output %0 inipixel:/Users/cgull/src/tmux 0 $ stty -a\015\012
%output %0 speed 9600 baud; 23 rows; 80 columns;\015\012lflags: icanon
isig iexten echo echoe echok echoke -echonl
echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin
-nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr
-igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint
-inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr
-onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb
-crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard =
<undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 =
<undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012\011min
= 1; quit = ^\134; reprint = ^R; start = ^Q; status =
^T;\015\012\011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%window-renamed @0 bash
%begin 1495990491 241 1
%end 1495990491 241 1
%begin 1495990492 242 1
%end 1495990492 242 1
%output %0 stt
%output %0 y -a\015\012
%output %0 speed 9600 baud; 23 rows; 80 columns;\015\012lflags: icanon
isig iexten echo echoe echok echoke -echonl
echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin
-nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr
-igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint
-inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr
-onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb
-crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard =
<undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 =
<undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012\011min
= 1; quit = ^\134; reprint = ^R; start = ^Q; status =
^T;\015\012\011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990493 243 1
%end 1495990493 243 1
%begin 1495990494 244 1
%end 1495990494 244 1
%output %0 s
%output %0 tty -a\015\012
%output %0 speed 9600 baud; 23 rows; 80 columns;\015\012lflags: icanon
isig iexten echo echoe echok echoke -echonl
echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin
-nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr
-igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint
-inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr
-onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb
-crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard =
<undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 =
<undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012
%output %0 \011min = 1; quit = ^\134; reprint = ^R; start = ^Q; status
= ^T;\015\012\011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990495 245 1
%end 1495990495 245 1
%layout-change @0 b25d,80x24,0,0,0 b25d,80x24,0,0,0 *
%output %0 \015\033[Kcgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990496 247 1
%end 1495990496 247 1
%output %0 st
%output %0 ty -a\015\012
%output %0 speed 9600 baud; 24 rows; 80 columns;\015\012lflags: icanon
isig iexten echo echoe echok echoke -echonl
echoctl\015\012\011-echoprt -altwerase -noflsh -tostop -flusho -pendin
-nokerninfo\015\012\011-extproc\015\012iflags: -istrip icrnl -inlcr
-igncr ixon ixoff -ixany imaxbel iutf8\015\012\011-ignbrk brkint
-inpck -ignpar -parmrk\015\012oflags: opost onlcr -oxtabs -onocr
-onlret\015\012cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb
-crtscts -dsrflow\015\012\011-dtrflow -mdmbuf\015\012cchars: discard =
<undef>; dsusp = ^Y; eof = ^D; eol = <undef>;\015\012\011eol2 =
<undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;\015\012\011min
= 1; quit = ^\134; reprint = ^R; start = ^Q; status = ^T;\015\012
%output %0 \011stop = ^S; susp = ^Z; time = 0; werase = ^W;\015\012
%output %0 cgull@minipixel:/Users/cgull/src/tmux 0 $
%begin 1495990497 248 1
%end 1495990497 248 1
%sessions-changed```

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/947>, or mute the thread

**Comment by cgull** [comment]
No, that doesn't work, not in the above test script, nor in using tmux -C interactively.

**Comment by nicm** [comment]
The problem here is that the client is already 80x24, so we don't recalculate the session size when you set it to 80x24 again.

If we did recalculate, the session would change to 80x24 because we don't include the status line for control clients. It starts off as 80x23 because we _do_ include the status line for new sessions, even if there is no client.

I think we should recalculate the size always when control clients set it.

I'm not convinced we should include the status line when creating detached sessions. The idea was that a detached session would eventually need to be attached, and there is less chance of having to resize if we have the status line included up front. But maybe it would be better not to include it.

Please try this: [x.diff.txt](https://github.com/tmux/tmux/files/1034362/x.diff.txt)

**Comment by nicm** [comment]
If we are going to use 80x24 by default should probably do it for all detached clients, like this: [y.diff.txt](https://github.com/tmux/tmux/files/1034384/y.diff.txt)

In any case the refresh-client bit should fix your problem.

**Comment by cgull** [comment]
Of course, I'll agree that the server should default to 80x24, since I need that for my tests :)

One way to look at this is to say that the server should default to an 80x24 tty for applications, and clients should modify that as they see fit (status line, control mode, etc).

With x.diff.txt, the repro script above gets an initial 80x23 window, but is then able to set it to 80x24 on the first try.  Getting refresh-client working for the Mosh test scripts will take a little more work, I think I'm having some race conditions between my scripts and tmux client and tmux server.

I'm actually getting the same behavior with y.diff.txt, stty shows a 23-row pty initially.

**Comment by nicm** [comment]
This will mean control clients start with 80x24: [z.diff.txt](https://github.com/tmux/tmux/files/1034408/z.diff.txt)

I think it would be better for you to now use -x and -y rather than relying on the defaults or on refresh -C.

**Comment by cgull** [comment]
I forgot to mention earlier that `tmux -C new-session -x 80 -y 24` (or any other size for y) also does not work with tmux master.  It doesn't seem to work with your latest diff either.  If that worked, it would be a better solution than `refresh-client`.

**Comment by cgull** [comment]
Argh, getting myself mixed up here, forgot that it would have to be `tmux -C new-session -d -x 90 -y 30`.  But that followed by `tmux -C attach-session` does work with your latest patch.

**Comment by nicm** [comment]
Try this to allow new -x -y to work for control clients without -d: [xx.diff.txt](https://github.com/tmux/tmux/files/1034431/xx.diff.txt)

**Comment by cgull** [comment]
That works for me in Mosh tests, and also seems to work backward-compatibly with older versions of tmux, so I don't have to change tmux's command lines based on tmux version.  Thanks!

**Comment by nicm** [comment]
Good stuff, applied to OpenBSD now, thanks.

**Comment by cgull** [comment]
Thanks.  I'm waiting for the changes to percolate out to OpenBSD CVSWeb and/or here for final verification, since I'm not 100% sure which changes you're applying.  Also, I don't see any man page updates yet, I can supply those if you want.
