### ISSUE TITLE
rmam / smam terminal sequences

### ISSUE THREAD

**Issue by arcanis** [tmux/tmux#969]
Environment:

```
Archlinux
tmux 2.5
screen-256color
```

Test command:

```
tput rmam; printf "=%.0s" {0..1000}; echo; tput smam
```

Running the command above should yield a single line on the terminal, that takes the full terminal width, and that doesn't get wrapped even when the terminal is resized (instead, the line is expanded or shrinked as necessary to always take the full terminal width). Unfortunately, when ran inside tmux, the line wraps on multiple lines instead.

**Comment by nicm** [comment]
tmux does not support automatic margins and I'm not sure I really see a compelling reason to do so. Do you have an application that requires it?

We should probably drop them from the terminfo entry.

**Comment by arcanis** [comment]
Not an application per se, but I use this technique in my shell prompt to print a line between my command lines and their output:

![image](https://user-images.githubusercontent.com/1037931/27013658-dc50c7ee-4edf-11e7-8bf6-88958acf613f.png)

**Comment by nicm** [comment]
In fact neither terminfo supported inside tmux (tmux or screen) has these capabilities anyway. So you would have to send the actual escape sequences. But don't, because they won't work :-).

**Comment by arcanis** [comment]
:'(

**Comment by nicm** [comment]
Er wait, I was looking at the wrong function, sorry. These escape sequences should already work:
~~~~
printf "\033[?7l$(perl -e 'print "x"x1000')\033[?7h\n"
~~~~
I don't know where you get your idea about how it should behave on resize because neither not wrapping when made smaller or expanded when made bigger seem to be a requirement and no terminal I have here behaves like that. It must be an extension in your terminal.

**Comment by arcanis** [comment]
Oooh, I use mintty, maybe that's why :o

Damn, it was a nice feature ...
