### ISSUE TITLE
how to navigate while in incremental search mode?

### ISSUE THREAD

**Issue by timotheecour** [tmux/tmux#972]
```
Linux unknown
tmux 2.5
screen
```

```
^b + [ + ?
#stat typing a search query
#do page up or home  => doesn't work
```

~/.tmux.conf:
```
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""

bind-key -T copy-mode-vi Home send-keys -X history-top
```

I'd like to be able to navigate while still seeing all the search matches: eg, `home` should go to top and still highlight the search term

EDIT: partial workaround: control+C will at least allow to use `n` to search next term; but not previous term nor page up/down or other navigation

**Comment by nicm** [comment]
I think it is better all the editing keys work in the prompt. You can use
C-r and C-s to move through the found search terms.



On 12 Jun 2017 8:16 pm, "Timothee Cour" <notifications@github.com> wrote:

Linux unknown
tmux 2.5
screen

^b + [ + ?
#stat typing a search query
#do page up or home  => doesn't work

~/.tmux.conf:

bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X
search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X
search-backward-incremental \"%%%\""

bind-key -T copy-mode-vi Home send-keys -X history-top

I'd like to be able to navigate while still seeing all the search matches:
eg, home should go to top and still highlight the search term

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/972>, or mute the thread

**Comment by timotheecour** [comment]
what do i need to enable `C-r` and `C-s` ? I'm in vi-mode as shown above.

Typing `control+r` or `control+s` doesn't do anything

**Comment by timotheecour** [comment]
EDIT: ssh-ing from mac to ubuntu, and using iterm2

**Comment by nicm** [comment]
We don't have them in vi mode at the moment, you can try this [x.diff.txt](https://github.com/tmux/tmux/files/1069494/x.diff.txt)

**Comment by timotheecour** [comment]
thanks; will that be in git master?

**Comment by nicm** [comment]
Does it work?
