### ISSUE TITLE
Hardware tabs support? Or why are tabs replaced with whitespaces

### ISSUE THREAD

**Issue by gharry-bsd** [tmux/tmux#978]
Dear tmux coders, thanks for your ongoing improvements and congratulation to your 2.5 release!

I haven't found a quick answer to this one question, which is a quiet severe issue for me.  I have to admit that I never really spent much effort finding out why tmux(1) replaces tab stops with whitespaces, but I'm aware that screen(1) has the identical issue listed in the bugs section as "hardware tabs not supported yet".

Ist that true also for tmux(1)? Did I miss a simple config tweak? Or is this a known limitation which is planned to be addressed at some time?

Thanks,
-harry

**Comment by nicm** [comment]
What tabs? A tab (that is a \011 character) is just an instruction to move
the cursor to the next tab stop position, it doesn't write any whitespace.

**Comment by gharry-bsd** [comment]
Sorry for beeing unclear.  Indeed, \011 (or 0x9), the ascii control character for horizontal tab stop was meant.
tmux(1) seems to not pass it to the terminal, but replaces it with white spaces (\040 or 0x20).
At least with urxvt(1)/xterm(1),cons25(1) or anything else I ever used together with tmux(1) during the last years.
Steps to reproduce:
»echo -e "HTw/tmux\ttest"«, if echo does support -e (which some external do not, sh internal does).
You'll get single (whitespace) characters drawn within a tmux(1) session and xterm(1).
If you do the same without tmux(1) in place, but the same terminal, there won't be multiple whitespace characters, but a real horizontal cursor shift.
To check that the command does the right thing, just check with »echo -e "HT w/tmux\ttest" | hd« – You'll see 09 in both cases, but different draw.

-harry

**Comment by nicm** [comment]
I don't know where you are seeing this because this is not how tmux works.
When you send a tab it moves its internal cursor position but it does not
move the external cursor until further characters are written at the new
position. And it will not use spaces, because they would destroy the
characters that the tab has moved past - it will move the cursor with
whatever cursor movement escape sequence seems best.


On 15 Jun 2017 10:27 pm, "gharry-bsd" <notifications@github.com> wrote:

Sorry for beeing unclear. Indeed, \011 (or 0x9), the ascii control
character for horizontal tab stop was meant.
tmux(1) seems to not pass it to the terminal, but replaces it with white
spaces (\040 or 0x20).
At least with urxvt(1)/xterm(1),cons25(1) or anything else I ever used
together with tmux(1) during the last years.
Steps to reproduce:
»echo -e "HTw/tmux\ttest"«, if echo does support -e (which some external do
not, sh internal does).
You'll get single (whitespace) characters drawn within a tmux(1) session
and xterm(1).
If you do the same without tmux(1) in place, but the same terminal, there
won't be multiple whitespace characters, but a real horizontal cursor shift.
To check that the command does the right thing, just check with »echo -e
"HT w/tmux\ttest" | hd« – You'll see 09 in both cases, but different draw.

-harry

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/978#issuecomment-308870627>, or mute
the thread

**Comment by krader1961** [comment]
I don't know what your `echo` command is supposed to demonstrate, @gharry-bsd. However, if you do the following you should see that the `#` characters between the two words are not overwritten by spaces when executed inside tmux:

```
echo -e "#############\rtmux\ttest"
```

That produces identical results for me with iTerm2 whether or not I'm inside a tmux session within the terminal.

**Comment by gharry-bsd** [comment]
krader, thanks for your attention!

You are right, the printed character's aren't overwrtitten.

Could you please look at my example: Simply copy the output from it into the clipboard.
Then ' hd << EOF', and paste the clipboard, (followed by EOF in case anyone else wants to try who needs that info).
With tmux(1) in place, there's : 48 54 77 2f 74 6d 75 78  20 20 20 20 20 20 20 20
Without tmux(1), it's "48 54 77 2f 74 6d 75 78  74.." in my case, since I can't paste the horizontal tab stop character. This doesn't matter, it demonstrates the difference.

Looking forward to know if I'm the only one with that problem?!

Thanks,

-harry

**Comment by gharry-bsd** [comment]
nicm, thanks for the explanation.
Quote: »it will move the cursor with whatever cursor movement escape sequence seems best«

This is proven by krader's example.
But why isn't cursor moved by \011 here? Is there a workarround? Had a quick look at ascii control sequences, but haven't found what character might be used instead...

Thanks,

-harry

**Comment by nicm** [comment]
Ah you didn't mention you were looking at the clipboard.

It is probably impractical for tmux to use tabs for cursor positioning,
they are too complicated and there is too much variance among terminals.
The problems would outweigh the small benefit.

tmux could (and probably should) preserve tabs internally so that copying
from copy mode can keep them. It doesn't at the moment though. Copy mode is
the recommended way to copy from tmux.



On 16 Jun 2017 9:41 am, "gharry-bsd" <notifications@github.com> wrote:

nicm, thanks for the explanation.
Quote: »it will move the cursor with whatever cursor movement escape
sequence seems best«

This is proven by krader's example.
But why isn't cursor moved by \011 here? Is there a workarround? Had a
quick look at ascii control sequences, but haven't found what character
might be used instead...

Thanks,

-harry

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/978#issuecomment-308969194>, or mute
the thread

**Comment by gharry-bsd** [comment]
nicm, thank you for this clarification.
Unfortunately with 2.5, I have additional problems feeding the clipboard.
Copying output via mouse somehow mutilates line breaks, but I have to admit that I currently don't know how tmux is designed to work and if it's a desired feature. The way I'm using tmux (completely transparent), I have to revert. Will have a look at the documentation/code to get the idea why/how to use "copy-mode" but due to extreme time limitations that won't happen soon and I need to be able to simply copy'n'paste like I do with all other X clients and have done with tmux before.

Thanks,

-harry

**Comment by christianpbrink** [comment]
Am I right to conclude from this thread that there's no way to preserve tab chars when copying buffer output to tmux's clipboard?
