### ISSUE TITLE
tmux clobbers env variables when setting status

### ISSUE THREAD

**Issue by mikeecb** [tmux/tmux#988]
I'm running macOS Sierra 10.12.5.
```
$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.5
screen
```

To reproduce:
```
tmux -Ltest kill-server
tmux -vv -Ltest -f/dev/null new

C-b:
set -g status-right "#(echo $(TZ=':US/Pacific' date '+%Z %H:%M:%S')) #(echo $(TZ=':Europe/London' date '+%Z %H:%M:%S'))"
```

The right status text is "PDT 07:29:34 PDT 07:29:34" but it should be "PDT 07:29:34 BST 15:29:34".

I reproduced this with a tmux build from Git master.

tmux-server-*.log file: https://pastebin.com/51Xkg6nw

**Comment by nicm** [comment]
This command doesn't do what you want because the date % formats are
expanded by tmux, it has nothing to do with environment variables. You need
to escape them, or set TZ appropriately before starting tmux.



On 29 Jun 2017 3:36 pm, "Michael Cypher" <notifications@github.com> wrote:

I'm running macOS Sierra 10.12.5.

$ uname -sp && tmux -V && echo $TERM
Darwin i386
tmux 2.5
screen

To reproduce:

tmux -Ltest kill-server
tmux -vv -Ltest -f/dev/null new

C-b:
set -g status-right "#(echo $(TZ=':US/Pacific' date '+%Z %H:%M:%S'))
#(echo $(TZ=':Europe/London' date '+%Z %H:%M:%S'))"

The right status text is "PDT 07:29:34 PDT 07:29:34" but it should be "PDT
07:29:34 BST 15:29:34".

I reproduced this with a tmux build from Git master.

tmux-server-*.log file: https://pastebin.com/51Xkg6nw

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/988>, or mute the thread

**Comment by mikeecb** [comment]
@nicm escaping the % results in the time in the status not updating (apart from when you type C-b) and both times are still using the PDT time zone. I don't know how setting `TZ` before starting tmux would help as I need `TZ` to be different for both calls to `date`. 

One solution I found is to have tmux call another script (see below) that sets the `TZ` env variable. However, I'm still unsure why this won't work from within tmux.

```
#!/bin/bash
echo `TZ=":$1" date "+%Z %H:%M:%S"
```

**Comment by nicm** [comment]
It will update every status-interval


On 29 Jun 2017 3:49 pm, "Michael Cypher" <notifications@github.com> wrote:

@nicm <https://github.com/nicm> escaping the % results in the time in the
status not updating (apart from when you type C-b) and both times are still
using the PDT time zone. I don't know how setting TZ before starting tmux
would help as I need TZ to be different for both calls to date.

One solution I found is to have tmux call another script (see below) that
sets the TZ env variable. However, I'm still unsure why this won't work
from within tmux.

#!/bin/bash
echo `TZ=":$1" date "+%Z %H:%M:%S"

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/988#issuecomment-311990371>, or mute
the thread

**Comment by mikeecb** [comment]
@nicm apologies, I mistakenly escaped the %. It works as expected now:

`set -g status-right "#(echo $(TZ=':US/Pacific' date '+%%Z %%H:%%M:%%S')) #(echo $(TZ=':Europe/London' date '+%%Z %%H:%%M:%%S'))"` works!

`set -g status-right "#(echo $(TZ=':US/Pacific' date '+\%Z \%H:\%M:\%S')) #(echo $(TZ=':Europe/London' date '+\%Z \%H:\%M:\%S'))"` does not!

**Comment by nicm** [comment]
Yeah sorry I meant escape them with %% as for strftime because tmux also
passes it through strftime
