### ISSUE TITLE
switch-client regression in 2.5

### ISSUE THREAD

**Issue by majutsushi** [tmux/tmux#995]
I'm using Tmux 2.5 on Debian, and I noticed a change in behaviour between 2.5 and 2.3 when using the `switch-client` command, which I use in a `precmd` hook in zsh to refresh the environment before every command.

The problem is that the command seems to incorrectly determine the current client in some cases.

I can reproduce it with these steps (order is important):

1. Open two terminals.
2. Start a fresh tmux server and session in the first one:
```
$ tmux -L foo -f /dev/null
```
3. Run this command in the newly opened tmux:
```
$ sleep 10; tmux -L foo -f /dev/null switch-client
```
4. Switch to the second terminal and start a new session there as well:
```
$ tmux -L foo -f /dev/null
```
5. Wait until the sleep returns.

The client in the second terminal should now have switched to the session from the first terminal. This didn't happen in version 2.3.

Note that if I change the command in step 3 to this, it works as expected:
```
$ sleep 10; tmux -L foo -f /dev/null switch-client -t $(tmux display-message -p -F '#{client_name}')
```

**Comment by nicm** [comment]
Sounds vaguely familiar, does this still happen in master?

**Comment by nicm** [comment]
Since you aren't specifying any target client it is up to tmux to decide
what the best client is, but it isn't ideal that it is choosing the second
(probably because that is MRU). It should be able to choose the first
because there is only one choice of session for the pane it is running in
and that session is only attached to one client. I'll take a look when I
get home.


But all the same you are safest to specify exactly what you want when
scripting, we have always tried to be very clear that without -t choice of
target will be best effort.

**Comment by majutsushi** [comment]
It isn't actually explicitly specified in the man page what is supposed to happen if you don't use the -t argument, but my understanding was that it would reuse he current client, so it would essentially be a no-op except for the refreshing of the environment. And before the introduction of the client_name format in 2.4 scripting this more explicitly would have been a bit more complicated.

I can try master tomorrow if you haven't had time to look for it before then, but a quick look at the history doesn't turn up anything that looks relevant.

**Comment by nicm** [comment]
It will be a best guess and the definition of best is not guaranteed to
always stay the same. There is sometimes no way for tmux to know exactly
what you mean.


On 6 Jul 2017 10:35 am, "Jan Larres" <notifications@github.com> wrote:

It isn't actually explicitly specified in the man page what is supposed to
happen if you don't use the -t argument, but my understanding was that it
would reuse he current client, so it would essentially be a no-op except
for the refreshing of the environment. And before the introduction of the
client_name format in 2.4 scripting this more explicitly would have been a
bit more complicated.

I can try master tomorrow if you haven't had time to look for it before
then, but a quick look at the history doesn't turn up anything that looks
relevant.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/995#issuecomment-313346954>, or mute
the thread

**Comment by nicm** [comment]
However in this case if display-message can figure it out (since you don't
give it -t either), switch-client should use the same. So probably it needs
to be changed.



On 6 Jul 2017 10:37 am, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

It will be a best guess and the definition of best is not guaranteed to
always stay the same. There is sometimes no way for tmux to know exactly
what you mean.


On 6 Jul 2017 10:35 am, "Jan Larres" <notifications@github.com> wrote:

It isn't actually explicitly specified in the man page what is supposed to
happen if you don't use the -t argument, but my understanding was that it
would reuse he current client, so it would essentially be a no-op except
for the refreshing of the environment. And before the introduction of the
client_name format in 2.4 scripting this more explicitly would have been a
bit more complicated.

I can try master tomorrow if you haven't had time to look for it before
then, but a quick look at the history doesn't turn up anything that looks
relevant.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/995#issuecomment-313346954>, or mute
the thread

**Comment by nicm** [comment]
Try this please: [x.diff.txt](https://github.com/tmux/tmux/files/1129484/x.diff.txt)

**Comment by majutsushi** [comment]
That fixes it for me, thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!
