### ISSUE TITLE
shortcut of splitting window

### ISSUE THREAD

**Issue by jingpengw** [tmux/tmux#998]
ubuntu 14.04

```
│~: uname -sp && tmux -V && echo $TERM     
│Linux x86_64
│tmux master
│screen-256color
```
the splitting window key binding should be switched as documented?
```
bind-key    -T prefix       "                 split-window                                  
bind-key    -T prefix       %                 split-window -h                               
```

**Comment by nicm** [comment]
No... why?


On 7 Jul 2017 7:04 pm, "Jingpeng Wu" <notifications@github.com> wrote:

ubuntu 14.04

│~: uname -sp && tmux -V && echo $TERM
│Linux x86_64
│tmux master
│screen-256color

the splitting window key binding should be switched as documented?

bind-key    -T prefix       "                 split-window
bind-key    -T prefix       %                 split-window -h

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/issues/998>, or mute the thread
